### ISSUE TITLE
Create new lightbulb artwork

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#118]
The light bulbs in scenery do not meet the criteria for what we need for a CCK bulb. The artwork should have the following properties.
* Side/bottom connections obvious
* Clear path for the electron motion
* Silhouette of Faraday's Law bulb is preferred

**Comment by arouinfar** [comment]
Preliminary design:
![image](https://cloud.githubusercontent.com/assets/8419308/15691061/fb72e658-2743-11e6-9d1c-c325da41d946.png)


The filament is a 5pt stroke with a color picked from the existing wire artwork. The bulb will also be a bit smaller than what's currently implemented.

![image](https://cloud.githubusercontent.com/assets/8419308/15689334/beeacac8-273b-11e6-9cc9-a07cc60da1b7.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15689350/cfaa77dc-273b-11e6-8745-b0609435b256.png)

We will probably need to split into two images, because the electrons will be obscured when they go behind the socket.
![image](https://cloud.githubusercontent.com/assets/8419308/15691004/8f3cd4ee-2743-11e6-98f1-ce750184267d.png)

**Comment by arouinfar** [comment]
This is probably a better pair of front/back images. Both images are on identically sized artboards (trimmed to the size of the full bulb). This way the exported .png (or .svg) files can be layered directly on top of one another without needing to shift anything. The back image has been made more complete so that a single image can be used while working on the electron's path, if desired.

![image](https://cloud.githubusercontent.com/assets/8419308/15726754/d7574742-280f-11e6-8103-e274876f220d.png)

Tagging this for design meeting, so we can decide if this is the desired look before @samreid implements a new bulb. Stanford has indicated that the scenery bulb (as currently implemented in the sim) is acceptable for the Black Box study.

**Comment by samreid** [comment]
On Thursday, we requested @arouinfar to make the base a bit wider to separate the vertices.  Also, consider putting the vertices at a 45 degree angle--it may have a nice symmetry for looks and dragging.

**Comment by samreid** [comment]
@arouinfar: @kathy-phet said it would be good to spend time working on this now.  She said even  using the new battery image without having the electrons traverse the new wire paths would be an improvement--possibly good enough for the study.

@arouinfar can you provide AI files for the new artwork, accounting for the changes in the preceding comment https://github.com/phetsims/circuit-construction-kit-common/issues/118#issuecomment-225641160 ?

**Comment by samreid** [comment]
On Friday, @kathy-phet said this should be reasonably high priority, so I'll label this issue as such.

**Comment by arouinfar** [comment]
@samreid I've emailed you the latest asset I have (see below). When we discussed the artwork in design meeting, we decided that the wire could be completely hidden by the socket, and there was no need for wire stubs to be visible on the side and bottom.


![image](https://cloud.githubusercontent.com/assets/8419308/16896325/5b66e410-4b4d-11e6-9bf4-e8e30caacd31.png)

**Comment by samreid** [comment]
I added the new light bulb image in the above commit, it looks like this in context:

![image](https://cloud.githubusercontent.com/assets/679486/16929520/64ce6808-4cf5-11e6-9c6a-abe2c7647da6.png)

@kathy-phet were you imagining we would show the internal light bulb wire while still showing the electrons flowing straight from vertex to vertex for now?

@arouinfar and @kathy-phet anything else to do for this revision other than the brightness lines?

**Comment by samreid** [comment]
@arouinfar have you considered making the bulb glass fully transparent when the bulb is turned off?

**Comment by arouinfar** [comment]
> @arouinfar have you considered making the bulb glass fully transparent when the bulb is turned off?

I modeled this bulb after the Faraday's Law bulb, as I'd like to keep our bulbs as stylistically similar/consistent as possible. While I think the transparency would look nice from an artistic perspective, I think it would diverge from the current bulb style. I also think the visual difference between off/on is pretty obvious, so I'm not sure transparency would add much here.

> @arouinfar and @kathy-phet anything else to do for this revision other than the brightness lines?

Looks good to me! I think brightness lines are all that's missing.

**Comment by samreid** [comment]
@arouinfar can you evaluate the light bulb in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.20/circuit-construction-kit-black-box-study_en.html

**Comment by arouinfar** [comment]
Looks great @samreid! Closing.
