### ISSUE TITLE
PhET Black Box: In the black box screen, reset all doesn't reset the selected black box

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#123]
Typically the reset all button should reset the entire screen.  In #122 I noticed that reset all doesn't go back to the "warm up" black box, but I realized this may not be desirable in this case.  @arouinfar can you please advise?

**Comment by arouinfar** [comment]
@samreid I took a look at dev.14. It looks like Reset All only affects the active black box. The state of the other black boxes is still saved. I could see this being a useful feature in an interview setting. A student may build something particularly messy, and want to clear it without losing their work on other black boxes.

For Stanford's purposes, I think we should leave the behavior like it is, and tell them that a browser refresh will be necessary to completely reset the sim.

**Comment by arouinfar** [comment]
When the time comes to develop a Black Box sim for the PhET site, we may want to rethink this behavior. I'm going to leave this issue open, but on hold for future discussion at a design meeting.

On second thought, probably best to leave this one assigned to me.

**Comment by samreid** [comment]
Moved to black box repo, closing.
