### ISSUE TITLE
Rename circuit-construction-kit-black-box repo to circuit-construction-kit-black-box-study repo

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#139]
I realized we should probably rename circuit-construction-kit-black-box repo to circuit-construction-kit-black-box-study repo because we may eventually publish a Black Box version that is substantially different than the study version.

Or... is the black box version going to be a screen within a sim?

@arouinfar @ariel-phet @kathy-phet can you remind me about the plans regarding PhET Black Box (on our site), particularly whether it will be a standalone sim or a screen within another sim?

**Comment by arouinfar** [comment]
@samreid it's still unclear at this point whether or not Black Box will be a screen within CCK: DC or a standalone sim. It may take some time before we determine how/if a Black Box would fit into CCK: DC. 

At this point, it's fine to to leave the repo name as is, and then rename it to circuit-construction-kit-black-box-study if we decide to make a standalone CCK: Black Box sim.

**Comment by samreid** [comment]
I've already renamed this (a) for future-proofing and (b) so it is clear to other developers that this is for a study, not a production simulation.
