### ISSUE TITLE
Vertices don't connect in build screen

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/circuit-construction-kit-common#141]
For phetsims/tasks#617 and #140 
Test device: Bates

Operating System: Windows 7

Browser: Chrome

Problem description: Component vertices in build mode will not connect to each other under certain circumstances. It seems to only happen when there is something connected to the box's vertex from investigate mode. Then when you connect a component to the box vertex and then try to connect it to something else, more than likely, it will not connect and deflect away. New components dragged in seem to be able to connect normally, but trying to connect to anything that was already in the box does not work. 
Possible this is related to something fixed from #128 or #136. 

Steps to reproduce: In Investigate, connect anything to the box vertices. Then in Build, connect components to the vertices and try to connect them to other components or box vertices.

Severity: high

Screenshots:
![cck](https://cloud.githubusercontent.com/assets/11947677/16210013/1b43fd06-36f7-11e6-9b7f-21fb0a9ff77a.gif)

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Black Box‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.17/circuit-construction-kit-black-box_en.html
Version: 1.0.0-dev.17 2016-06-20 19:15:41 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1366x623
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"047295f6","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"e044eccd","branch":"master"},"circuit-construction-kit":{"sha":"34780a85","branch":"master"},"circuit-construction-kit-black-box":{"sha":"88cbfaf4","branch":"master"},"dot":{"sha":"551f726f","branch":"master"},"joist":{"sha":"a42bced7","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"52b783d9","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by brroberts1231** [comment]
I'll be posting a few more examples as I record them.

Here you can see that it will not allow connecting components that have investigate components on their vertices to a component whose box vertex has nothing else connected, but it will allow the reverse. Works the same way with components that aren't connected to any box vertex.
![cck-1](https://cloud.githubusercontent.com/assets/11947677/16211219/7b1b0624-36fd-11e6-97a8-7e9462ee5fb3.gif)

**Comment by brroberts1231** [comment]
However fixed length components connected to a free vertex will not be able to connect, when a wire would.
![cck-2](https://cloud.githubusercontent.com/assets/11947677/16211489/029c683a-36ff-11e6-99b9-09fa43910579.gif)

**Comment by phet-steele** [comment]
@samreid this is certainly a consequence of the rule you stated in https://github.com/phetsims/circuit-construction-kit/issues/128#issuecomment-226837685. In all of these videos, if the wires that are placed in Investigate are instead rotated to be "inside" the black box, then all connections work correctly. To demonstrate:

![cckbb07](https://cloud.githubusercontent.com/assets/5863899/16237925/b9a8e46c-379b-11e6-8451-d43b22e87198.gif)

**Comment by samreid** [comment]
The problem was introduced in #136, which says that a vertex may not connect to another vertex if it has any connected vertices outside of the black box.  Perhaps this should be refined to say that it is OK for a vertex to be outside of the black box if it is not attachable.

**Comment by samreid** [comment]
Fixed as described in the preceding comment, ready for testing in next version.

**Comment by samreid** [comment]
Testing issue linked above.

**Comment by phet-steele** [comment]
@samreid not quite. If two components placed in "Build" have one vertex outside of the box, no more connects can be made:

![cckbb09](https://cloud.githubusercontent.com/assets/5863899/16632735/c37f00a0-4382-11e6-87c2-1c938bb00487.gif)

**Comment by samreid** [comment]
@arouinfar can I get your guidance on this issue?  The rule is that in "Build Circuit" mode, a connection cannot be made while any connected vertices are outside of the black box.  For instance:

![connect](https://cloud.githubusercontent.com/assets/679486/16710693/2229ce36-45f5-11e6-9277-974d68354002.gif)

Can you please advise how to proceed?

**Comment by samreid** [comment]
Upon reflection, perhaps we should restrict the search to "translating vertices" instead of "connected vertices", that may address this sufficiently.  I'll reassign to myself for investigation.

**Comment by samreid** [comment]
The preceding comment seems like a good compromise:

![connect2](https://cloud.githubusercontent.com/assets/679486/16711426/8015697a-4617-11e6-8f33-1c989d9e2f72.gif)

@arouinfar and @phet-steele sound OK?

**Comment by brroberts1231** [comment]
Looks good to me. I won't close just yet in case @phet-steele or @arouinfar have anything else to add.

**Comment by arouinfar** [comment]
Looks good to me @samreid.

**Comment by phet-steele** [comment]
Yup, this is good, Nice idea @samreid!
