### ISSUE TITLE
Back layer is prioritized when measuring overlapping wires

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/circuit-construction-kit-common#143]
This one is probably a bit lower priority than most of the vertex connection problems.
If two or more wires overlap, and you measure current or voltage at the point where they cross, the value read will be for the wire displayed on the furthest back layer. I feel like this could be confusing and it should read the front-most wire. 

I made this setup with two batteries of different voltage with some crossing wires, so I would expect that if I put the probes on the vertical wire at the intersection, it would read 10V and 1A because it is the wire that's visible on top.
![cckoverlap1](https://cloud.githubusercontent.com/assets/11947677/16243832/5d599592-37b6-11e6-947d-0ba131424d57.JPG)
But the voltmeter and ammeter both measure the horizontal wire that's behind.
![cckoverlap2](https://cloud.githubusercontent.com/assets/11947677/16243939/e4cb9c28-37b6-11e6-80a7-5bbc3f8816fe.JPG)
![cckoverlap3](https://cloud.githubusercontent.com/assets/11947677/16243996/1a7813c4-37b7-11e6-8950-7d3a7167e837.JPG)

For phetsims/tasks#617 and #140 
Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Black Box‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.17/circuit-construction-kit-black-box_en.html
Version: 1.0.0-dev.17 2016-06-20 19:15:41 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"047295f6","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"e044eccd","branch":"master"},"circuit-construction-kit":{"sha":"34780a85","branch":"master"},"circuit-construction-kit-black-box":{"sha":"88cbfaf4","branch":"master"},"dot":{"sha":"551f726f","branch":"master"},"joist":{"sha":"a42bced7","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"52b783d9","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by samreid** [comment]
Fixed above and ready for testing in next version.

**Comment by samreid** [comment]
Testing issue linked above.

**Comment by brroberts1231** [comment]
Fixed, closing
