### ISSUE TITLE
Add electron speed throttling message

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#152]
Now that electrons speed is throttled properly, we should show a message about the throttling amount.

**Comment by samreid** [comment]
Here's what it looks like in the Java one:
![image](https://cloud.githubusercontent.com/assets/679486/16546460/1a623cca-4108-11e6-8677-1406255c4bfe.png)

**Comment by samreid** [comment]
Fixed above, closing.

**Comment by phet-steele** [comment]
@arouinfar has suggested only showing this message when "Show Electrons" is checked, and hiding it when not checked.

**Comment by samreid** [comment]
Great idea, thanks @arouinfar, will do.

**Comment by samreid** [comment]
I'll create a separate issue for the preceding comment.
