### ISSUE TITLE
Numbers on voltmeter and ammeter are not vertically centered

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/circuit-construction-kit-common#157]
For phetsims/tasks#636
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Chrome

Problem Description: Numbers on voltmeter and ammeter are not horizontally centered. This is seen on the explore and the black box screens. 

![image](https://cloud.githubusercontent.com/assets/19288972/16629597/940535ba-4373-11e6-98a7-c147d029dc57.png)

In the Capacitor Lab: Basics sim, the numbers look centered

![image](https://cloud.githubusercontent.com/assets/19288972/16629633/b488b37a-4373-11e6-89d2-d0a1db812209.png)

Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.18/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.18 2016-07-05 23:04:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1386x718
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"452ce1dc","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"531f9047","branch":"master"},"circuit-construction-kit":{"sha":"6c44e1b0","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"85860b42","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"d2906d78","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"c5dbf7cd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by samreid** [comment]
It appears the text is horizontally centered, but not vertically centered.  I'll update the labels (but correct me if I'm wrong).

**Comment by samreid** [comment]
We chose to have the text right-aligned so that the decimal place will always be in the same place, for instance:

```
   0.00 V
  10.00 V
 100.00 V
```

I'll commit shortly to center it vertically.

**Comment by samreid** [comment]
Vertically centered above, closing.
