### ISSUE TITLE
Much slower performance than dev.17

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/circuit-construction-kit-common#158]
For phetsims/tasks#636
Test device: Bates

Operating System: Windows 7

Browser: Chrome, Firefox, IE

Problem description: Dev.18's performance can become noticeably slow when dragging around components if there are around 5 or 6 components on the screen, and gets very bad once there are more than 10. Mainly only affects components that move 2 or more wires when you drag them.
(Probably a result of the addition of the Show Electrons feature, but still happens even when unchecked.)

Screenshots:
![cck](https://cloud.githubusercontent.com/assets/11947677/16634265/1d02a6ca-438a-11e6-8bb6-dffb70b143eb.gif)

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.18/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.18 2016-07-05 23:04:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"452ce1dc","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"531f9047","branch":"master"},"circuit-construction-kit":{"sha":"6c44e1b0","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"85860b42","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"d2906d78","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"c5dbf7cd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}**

**Comment by phet-steele** [comment]
This is the behaviour being reflected in #71.

**Comment by samreid** [comment]
I tried boundsMethod = none for ElectronNode, but it doesn't seem to help at all.

**Comment by samreid** [comment]
> (Probably a result of the addition of the Show Electrons feature, but still happens even when unchecked.)

Electrons are still being updated when invisible so the performance of "Show Electrons" will match the performance of "Hide Electrons", so we can focus on performance optimizing both cases.

**Comment by samreid** [comment]
A few more fixes above, I'll run the next version past @brroberts1231 to see what he thinks.

**Comment by phet-steele** [comment]
Performance is now significantly better, nice one.
