### ISSUE TITLE
An electron gets stuck on the lightbulb

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/circuit-construction-kit-common#160]
For phetsims/tasks#636
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Chrome

Problem Description: An electron gets stuck on the lightbulb when only one point on the lightbulb is attached to the circuit. This is happening in the Java version of the sim as well.

Steps to Reproduce:
1. Create any complete circuit
2. Select the option to show electrons
3. Attach only one point of a lightbulb to the circuit

Screenshots:

![image](https://cloud.githubusercontent.com/assets/19288972/16664302/a7c02712-443c-11e6-84f6-1a6d21ab4be3.png)

Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.18/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.18 2016-07-05 23:04:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1386x717
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"452ce1dc","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"531f9047","branch":"master"},"circuit-construction-kit":{"sha":"6c44e1b0","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"85860b42","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"d2906d78","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"c5dbf7cd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by samreid** [comment]
I think this behavior is correct, it is showing that there is no current between the beginning and end of the light bulb. I'll reassign to @arouinfar to confirm.  If you agree, then please close the issue.

**Comment by samreid** [comment]
This behavior is indeed correct, but I'm wondering if it could be confusing for students who think it is broken instead of that there is no current flowing through a component.  Though I don't think any concerns have been raised for the Java CCK, so perhaps we should just close this.  @arouinfar reopen if you have other thoughts.
