### ISSUE TITLE
Revealing or switching between investigate and build brings all solder to the top layer

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#164]
From #48, revealing or switching between investigate and build brings all solder to the top layer (except any solder in investigate mode apparently).

**Comment by samreid** [comment]
@phet-steele is this fixed in RC.3?

**Comment by phet-steele** [comment]
> @phet-steele is this fixed in RC.3?

No, before reveal:
<img width="695" alt="screen shot 2017-02-15 at 2 26 18 pm" src="https://cloud.githubusercontent.com/assets/5863899/22996135/f1e08028-f38a-11e6-843c-6004a382cb74.png">

After reveal:
<img width="727" alt="screen shot 2017-02-15 at 2 27 09 pm" src="https://cloud.githubusercontent.com/assets/5863899/22996146/f93d5d96-f38a-11e6-81e5-facae1689965.png">

**Comment by samreid** [comment]
Unassigning because it is not part of DC milestone.

**Comment by phet-steele** [comment]
Moved to https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/63. We lost some labels, if that's okay.
