### ISSUE TITLE
Solder should be in front of wires

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#165]
In #48 we decided the solder should be in front of the wires.  However, @phet-steele identified a case where this is failing:

A wire will appear above the solder in the following scenario, seen in the #126 version. Before trying to reproduce, note it is VERY important to watch the order of events. The order in which wires/components are taken from the toolbox and placed into the play area is the whole reason this procedure works:
1. Place any number of objects into the play area. Doesn't matter what they are.
2. Take a wire and place it in the play area. Do NOT let it attach to anything, just place it by its lonesome.
3. Now, connections MUST be made by dragging objects _from_ step 1 _towards_ wires from step 2. Reversing this order will not yield incorrect solder layering.

![cckbb05](https://cloud.githubusercontent.com/assets/5863899/15872885/07a7158c-2cb9-11e6-98ec-3a05052a0e88.gif)

**Comment by samreid** [comment]
@phet-steele was this addressed in https://github.com/phetsims/circuit-construction-kit-common/issues/255 ?

**Comment by phet-steele** [comment]
> @phet-steele was this addressed in #255 ?

No. This procedure can still be followed in rc.3. It is still very order-dependent.

1. Drag out a bulb
2. Drag out a wire and DROP IT (don't connect it to anything)!
3. Drag the bulb to the wire. The wire is in front of the solder

<img width="423" alt="screen shot 2017-02-15 at 2 13 26 pm" src="https://cloud.githubusercontent.com/assets/5863899/22995661/fabcf3c2-f388-11e6-8da9-195a1b699aa9.png">

**Comment by samreid** [comment]
I think we will need to add a phase that moves the wires behind the solder.

**Comment by Denz1994** [comment]
The wire now is set behind all other connected circuit elements. There is a dev version you can use for review.

 http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.56/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
This looks great, except for https://github.com/phetsims/circuit-construction-kit-common/issues/319. Discussion will continue there.

**Comment by phet-steele** [comment]
@samreid, maybe this was re-introduced? While looking at master I tried this:

1. Drag out a wire
2. Drag out and attach another wire to the first wire, don't drop it in the play area first. I HAVE to attach the left vertex of the new wire to the right vertex of the first wire. So in the screenshot below, the right wire is the wire from step 2.

<img width="393" alt="screen shot 2017-07-28 at 1 40 12 pm" src="https://user-images.githubusercontent.com/5863899/28733653-629af23c-739a-11e7-8c73-ab258d06b8da.png">

**Comment by samreid** [comment]
Since we were able to simplify the layering in https://github.com/phetsims/circuit-construction-kit-dc/issues/106 I would like to apply a similar strategy here.  Instead of throwing wires, vertices and circuit elements into the same list and trying to keep their order correct, we will use separate layers for each.  This should solve the problem at hand, simplify the code significantly, and perhaps address as-yet undiscovered bugs.  Tagging @arouinfar about this proposed work, please notify me if you think it will not work to have the layers split up like that.

**Comment by samreid** [comment]
Here's the I can delete if we move toward organizing the layers described in the preceding comment:

```js
          // Insert the circuit element node behind the vertex nodes.
          // Search backwards starting at the end until we find the last 2 vertex nodes
          // var index = layer.getChildrenCount() - 1;
          // var vertexNodeCount = 0;
          // while ( index >= 0 ) {
          //   if ( layer.getChildAt( index ) ) {
          //     vertexNodeCount++;
          //     if ( vertexNodeCount >= 2 ) {
          //       break;
          //     }
          //   }
          //   index--;
          // }
          // assert && assert( index >= 0, 'missing vertex nodes' );
          // layer.insertChild( index - 1, circuitElementNode );

// ...

      // make sure the vertex didn't already get removed (like in fuzz testing)
      // if ( this.mainLayer.indexOfChild( vertex ) >= 0 ) {
      //   var self = this;
      //
      //   var solderNode = this.getSolderNode( vertex );
      //   var adjacentCircuitElements = this.circuit.getNeighborCircuitElements( vertex );
      //   var adjacentWires = adjacentCircuitElements.filter( function( component ) {return component instanceof Wire;} );
      //   var adjacentFixedLengthComponents = adjacentCircuitElements.filter( function( component ) {
      //     return component instanceof FixedLengthCircuitElement;
      //   } );
      //
      //   // This method is called for all vertices when viewProperty value changes
      //   if ( this.viewProperty.get() === CircuitConstructionKitCommonConstants.LIFELIKE ) {
      //     if ( adjacentFixedLengthComponents.length > 0 ) {
      //
      //       // move before the first fixed length component
      //       var nodes = adjacentFixedLengthComponents.map( function( c ) {return self.getCircuitElementNode( c );} );
      //       var lowestNode = _.minBy( nodes, function( node ) {return self.mainLayer.indexOfChild( node );} );
      //       var lowestIndex = self.mainLayer.indexOfChild( lowestNode );
      //       var solderIndex = self.mainLayer.indexOfChild( solderNode );
      //       if ( solderIndex >= lowestIndex ) {
      //         self.mainLayer.removeChild( solderNode );
      //         self.mainLayer.insertChild( lowestIndex, solderNode );
      //       }
      //     }
      //     else if ( adjacentWires.length > 0 ) {
      //
      //       // move after the last wire
      //       var wireNodes = adjacentWires.map( function( c ) {return self.getCircuitElementNode( c );} );
      //       var topWireNode = _.maxBy( wireNodes, function( node ) {return self.mainLayer.indexOfChild( node );} );
      //       var topIndex = self.mainLayer.indexOfChild( topWireNode );
      //       var mySolderIndex = self.mainLayer.indexOfChild( solderNode );
      //       if ( mySolderIndex <= topIndex ) {
      //         self.mainLayer.removeChild( solderNode );
      //         self.mainLayer.insertChild( topIndex, solderNode );
      //       }
      //     }
      //
      //     // Make sure black box vertices are behind the black box
      //     // TODO (black-box-study): This is duplicated below, factor it out.
      //     if ( self.blackBoxNode ) {
      //       var blackBoxNodeIndex = self.mainLayer.children.indexOf( self.blackBoxNode );
      //       if ( vertex.blackBoxInterfaceProperty.get() ) {
      //         self.mainLayer.removeChild( solderNode );
      //         self.mainLayer.insertChild( blackBoxNodeIndex, solderNode );
      //       }
      //     }
      //   }
      //   else {
      //
      //     // in schematic mode, solder should be on top of every component, including wires
      //     self.mainLayer.removeChild( solderNode );
      //     self.mainLayer.addChild( solderNode );
      //   }
      // }

// ...

      // Schedule a step to make sure the solder is layered correctly.  This is necessary because vertices are added
      // before CircuitElements, but solder should be in front of Wires, see
      // https://github.com/phetsims/circuit-construction-kit-common/issues/386
      self.stepListeners.push( function() {
        self.fixSolderLayeringForVertex( vertex );
      } );

// ...

    this.viewProperty.link( function() {
      circuitConstructionKitScreenView.circuitConstructionKitModel.circuit.vertices.forEach( function( vertex ) {
        self.fixSolderLayeringForVertex( vertex );
      } );
    } );

// ...

    var relayerListener = function() {
      circuitLayerNode.fixSolderLayeringForVertex( vertex );
    };
    vertex.relayerEmitter.addListener( relayerListener );
```

**Comment by samreid** [comment]
The proposed fix is implemented above.  It should address https://github.com/phetsims/circuit-construction-kit-common/issues/165#issuecomment-318744912 and it removed nearly 100 lines of complex layering code by making the layers separate instead of interleaved.

@phet-steele and @arouinfar can you please test the https://github.com/phetsims/circuit-construction-kit-common/issues/165#issuecomment-318744912 and generally make sure play area layering is good for schematic and lifelike?  Here's a dev version:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.120/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks good to me too!
