### ISSUE TITLE
Should the black box study code be in this repo?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#170]
The Concentration sim appears as a screen in Beer's Law Lab, hence it makes sense for concentration code to appear in the beers-law-lab repo.  However, the Black Box Study will not appear in "circuit construction kit common", which indeed is not a sim.  For this situation, should the black-box specific code be developed in the black box repo, or is it simpler/better to keep all of the code in one repo and just use the black-box repo for selecting the screens?

**Comment by samreid** [comment]
I should also mention that numerous "black box" features are going to be coded in "circuit construction kit common" code.  For instance, a circuit Vertex has an attribute "isBlackBoxInterfaceVertex".  Rather than subclassing Vertex to create BlackBoxVertex and having factory functions that decide which kind of vertex to create, it is just centralized in Vertex for simplicity.  So there won't be a clear line between black box and non-black box features, though there will be files that are only used in "black box".

**Comment by pixelzoom** [comment]
Top-level stuff (Screen, ScreenView, Model,...) should be in circuit-construction-kit-black-box-study.

**Comment by samreid** [comment]
Consensus from meeting: move code to specific repos as much as possible.

**Comment by samreid** [comment]
Finished in above commits, closing.
