### ISSUE TITLE
What is the name of the DC version?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#171]
In Java it was "Circuit Construction Kit (DC Only)"  The Google Drive document for the HTML5 one is called: "Circuit Construction Kit: DC".  @arouinfar @kathy-phet @ariel-phet can you confirm the latter?

**Comment by arouinfar** [comment]
@samreid CCK: DC will replace both "Circuit Construction Kit (DC Only)" and "Circuit Construction Kit (DC Only), Virtual Lab", so I don't think its name should be an exact match of either.

I personally like "Circuit Construction Kit: DC", and I think it is a clean-looking (but still interpretable) name. @kathy-phet or @ariel-phet please feel free to chime in.

I'll also make a note of this in the design doc to discuss at our next meeting.

**Comment by samreid** [comment]
@arouinfar that sounds good to me too.

**Comment by kathy-phet** [comment]
I like Circuit Construction Kit: DC too. 
Kathy

**Comment by ariel-phet** [comment]
Works for me

**Comment by samreid** [comment]
Perfect, thanks, closing.
