### ISSUE TITLE
Vertex becomes dislocated when joining after an auto-move

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#173]
@phet-steele reported:

> @samreid I believe https://github.com/phetsims/circuit-construction-kit-common/issues/128#issuecomment-226837158 is still present.

@samreid I ran into another instance of vertex pushing. If a fixed-length component is in the path of a wire that snaps into the box, such that their vertices are within the snap-to-connect distance, it's possible for the vertex of the fixed-length component to be dislocated.
![vertexpushing2](https://cloud.githubusercontent.com/assets/8419308/16159718/8bcc2bde-3481-11e6-9d27-14b3be2f5d69.gif)

**Comment by samreid** [comment]
In the above commit, I delay the wire movement until after the drop action is complete.  What was happening was that the wire was getting bumped into the black box before the drag action was complete, so it thought the user dropped the wire inside the box.  Hence that triggered the code that looked for a nearby connection.  I solved this problem by delaying the bump code until after the drop has been fully processed.  However, it is unclear whether other behavior was relying on the bump code happening before the drop was processed.

**Comment by samreid** [comment]
I did not see any other detrimental effects from delaying the move, so I'll mark this a fixed-pending testing and the QA team can take a closer look in the next version.

**Comment by phet-steele** [comment]
Looks good.
