### ISSUE TITLE
Incorrect background colors when switching between challenges

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#177]
@samreid, we nailed two different procedures to have the sim show an incorrect background color (@andrea-phet and I):

1. After sim load, go to Black Box screen
2. Start on a black box challenge of your choosing
3. Enter Build mode
4. Switch to a different challenge
5. Switch back to your original challenge in step 2

You will still be in Build mode on your original challenge, but the background outside of the black box will not be the "pale" blue, just the normal blue.
![buildblue](https://cloud.githubusercontent.com/assets/5863899/16811745/137d4666-48e7-11e6-815b-b345956e8f8d.PNG)

1. After sim load, go to Black Box screen
2. Start on a black box challenge of your choosing
3. Switch to a different challenge
4. Enter Build mode
5. Switch back to your original challenge in step 2

We've just switched steps 3 & 4, but now you will be on your original challenge in Investigate mode with the "pale" blue background.
![investpale](https://cloud.githubusercontent.com/assets/5863899/16811752/19c15e68-48e7-11e6-993e-168a3eb66443.PNG)

Seen on Win 7 & 10 Chrome. For phetsims/tasks#643.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.19/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.19 2016-07-12 22:00:54 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"5b1f70f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"8825397d","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"0496b8ff","branch":"master"},"circuit-construction-kit-common":{"sha":"9c38befc","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"b4a2dc38","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by samreid** [comment]
Fixed above, ready for review in next version.

**Comment by samreid** [comment]
The test issue is https://github.com/phetsims/circuit-construction-kit-common/issues/203

**Comment by samreid** [comment]
@phet-steele can you please test whether this is resolved in the version linked above?

**Comment by phet-steele** [comment]
Looks resolved @samreid.
