### ISSUE TITLE
Build Screen vertices remain red when something is connected

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/circuit-construction-kit-common#178]
On the build screen, the vertices will stay red after a component is connected. They'll only turn black if two or more components are connected. Seen on Win 7, Chrome, FF, IE. For phetsims/tasks#643
![cckredvert1](https://cloud.githubusercontent.com/assets/11947677/16817161/a1e42796-48fe-11e6-8ec4-ab504600fc5e.JPG)
![cckredvert2](https://cloud.githubusercontent.com/assets/11947677/16817181/b73c4b14-48fe-11e6-9446-c5e599bd9397.JPG)

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.19/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.19 2016-07-12 22:00:54 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"5b1f70f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"8825397d","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"0496b8ff","branch":"master"},"circuit-construction-kit-common":{"sha":"9c38befc","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"b4a2dc38","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by phet-steele** [comment]
@samreid @brroberts1231 I checked with @arouinfar and this is the desired behaviour.
