### ISSUE TITLE
Warm-up Build Circuit text layered over things

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#179]
On the Warm-up challenge, the text in Build mode covers other UI elements. @arouinfar @samreid should this be moved behind?

<img width="659" alt="screen shot 2016-07-14 at 11 19 22 am" src="https://cloud.githubusercontent.com/assets/5863899/16848823/e154bf60-49b4-11e6-8c60-6fab7d17ce43.png">

Seen on Win 10 & OSX 10.11.5 Chrome. For phetsims/tasks#643.

**Comment by arouinfar** [comment]
Good catch @phet-steele. Please move the text behind the UI elements @samreid.

**Comment by samreid** [comment]
It looks like the moveToFront is no longer necessary to get the text in front of the transparency overlay (if we still have one?):

![image](https://cloud.githubusercontent.com/assets/679486/17523967/c681694e-5e19-11e6-986d-b14c5665ba10.png)

Committing shortly.

**Comment by samreid** [comment]
Fixed above and will be ready for @phet-steele to confirm in the next version.

**Comment by samreid** [comment]
Ready for testing in https://github.com/phetsims/circuit-construction-kit-common/issues/197

**Comment by arouinfar** [comment]
Looks good to me @samreid! 

![image](https://cloud.githubusercontent.com/assets/8419308/17533973/60d83d9a-5e44-11e6-82d9-adaf0c6615ee.png)
![image](https://cloud.githubusercontent.com/assets/8419308/17533987/68a57498-5e44-11e6-92ea-fbfa341fad18.png)
![image](https://cloud.githubusercontent.com/assets/8419308/17534014/7d13e536-5e44-11e6-8ea0-65c626697e25.png)
