### ISSUE TITLE
Internal black vertex

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#180]
This is the opposite of #176, where now a black vertex is shown inside of Build mode where it shouldn't. The connection on the right shows two wires in Build that disconnect and leave behind a red vertex (correctly). The left shows one wire in Investigate and one wire in Build, that when disconnected leave behind a black vertex. My clue as to why this is wrong is because switching between view modes changes the vertex back to red.
![cckbb12](https://cloud.githubusercontent.com/assets/5863899/16848152/9eb7f526-49b1-11e6-9b77-ae15fb505156.gif)

Seen on Win 10 & OSX 10.11.5 Chrome. For phetsims/tasks#643.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.19/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.19 2016-07-12 22:00:54 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"5b1f70f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"8825397d","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"0496b8ff","branch":"master"},"circuit-construction-kit-common":{"sha":"9c38befc","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"b4a2dc38","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by samreid** [comment]
Putting updateStroke in a timeout(0) works around this problem.

**Comment by samreid** [comment]
Fixed above, closing.
