### ISSUE TITLE
Only show edit hint on components from the tool box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#181]
Currently, in each Black Box challenge with a component in Reveal, the screen displays a "Tap circuit element to edit." hint. This is true for all challenges *except* challenge Black Box 2, which doesn't display a hint since Reveal only contains a wire. This could be a dead giveaway to some students; after I showed @arouinfar this, she proposed that the "Tap circuit element to edit." hint only appears/applies to components dragged from the tool box. This would effectively change each challenge to never display the hint without a user dropping their own component in the play area. The hint would go away when all user-placed components are removed.

Seen on Win 10 & OSX 10.11.5 Chrome. For phetsims/tasks#643.

**Comment by arouinfar** [comment]
@samreid can you address this before we deliver a new version to Stanford? I wouldn't be surprised if a few students figure out this unintentional hint.

**Comment by samreid** [comment]
Fixed above and ready for review in next version.

**Comment by samreid** [comment]
Testable version in https://github.com/phetsims/circuit-construction-kit-common/issues/197

**Comment by phet-steele** [comment]
Looks good in 1.0.0-dev.22

**Comment by arouinfar** [comment]
Actually, something's not quite right here...

![edit_component_text](https://cloud.githubusercontent.com/assets/8419308/17534830/61aa223e-5e48-11e6-8ba1-569241414996.gif)

* In Investigate, drag editable component into play area, and the edit hint appears (as it should).
* Switch to Build, the edit hint remains, despite there being no editable components that are clickable. (I think the edit hint should disappear here.)
* Drag wire into box, edit hint disappears. (Edit hint should have disappeared as soon as switching to Build.)
* Switch back to Investigate, edit hint should be visible, but is not.

**Comment by phet-steele** [comment]
Thanks @arouinfar!

**Comment by samreid** [comment]
In the preceding commit, the hint updates when the mode changes, and it seems to have the correct behavior for the scenario @arouinfar described above.  Note that the hint does not appear for wires because they cannot be edited (though they can be deleted).  Ready for review in next version.

**Comment by samreid** [comment]
The test issue is https://github.com/phetsims/circuit-construction-kit-common/issues/203

**Comment by samreid** [comment]
@arouinfar can you please test this in the version linked above?

**Comment by arouinfar** [comment]
Looks good!
