### ISSUE TITLE
"Tap circuit element to edit." hint is sticky

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#182]
The hint "Tap circuit element to edit." remains on the screen when there are no components left to edit (lightbulbs, resistors, and batteries). It doesn't matter if a component is returned to the tool box, deleted, or Reset All is pressed, the hint will remain until a **wire** is manipulated.
![cckbb11](https://cloud.githubusercontent.com/assets/5863899/16846875/68147680-49ab-11e6-9360-b25a3165d141.gif)

Seen on Win 10 & OSX 10.11.5 Chrome. For phetsims/tasks#643.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.19/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.19 2016-07-12 22:00:54 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"5b1f70f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"8825397d","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"0496b8ff","branch":"master"},"circuit-construction-kit-common":{"sha":"9c38befc","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"b4a2dc38","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by phet-steele** [comment]
@samreid I believe this has been addressed by something?

**Comment by samreid** [comment]
In ecb28fc47e260f0cdfcd3d8ed1e95db99ce2b3af we update the text when vertices are removed, so this is ready to close.
