### ISSUE TITLE
The "Show Electrons" checkbox should have a query parameter that disables it.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#183]
The "Show Electrons" checkbox should have a query parameter that disables it.  It's unclear whether we should do this with existing phet-io machinery or creation of a new query parameter.

**Comment by arouinfar** [comment]
@samreid unless Stanford has requested this feature from you, this is not necessary for their study, as far as I know. I'm leaving the study tag for now, but please remove it if you haven't heard anything from Stanford/KP about this.

**Comment by samreid** [comment]
@kathy-phet mentioned that Stanford would need this feature.

**Comment by samreid** [comment]
The tandems we need are:
```
circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel
circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel
```

**Comment by samreid** [comment]
This query parameter does the trick (must be phet-io version):

```
phet-io.expressions=[["circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel","setVisible",[false]],["circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel","setVisible",[false]]]
```

**Comment by samreid** [comment]
Test version available in https://github.com/phetsims/circuit-construction-kit-common/issues/197

**Comment by arouinfar** [comment]
@samreid I'm not sure how to test this in dev.22, since the query parameter is an iO feature. I'll leave this one to @phet-steele or @samreid to confirm.

**Comment by samreid** [comment]
You are correct, I will need to publish a phet-io version before you can test this.  Assigned to me.

**Comment by samreid** [comment]
Here's a version that can be tested.  @arouinfar and/or @phet-steele can you test it on a few platforms?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.24/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&phet-io.expressions=[[%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,[false]]]

**Comment by arouinfar** [comment]
Everything seems in order for OSX 10.11.5 with the latest Chrome/Firefox/Safari.

My only request would be for the toolbox panel to top-align with the component panel if show electrons is suppressed. It looks a little unbalanced to me.
![image](https://cloud.githubusercontent.com/assets/8419308/17681303/2eb768e6-6302-11e6-8b8d-0f7a884e2077.png)

If this is a quick change, please take care of it for Stanford @samreid. Otherwise, don't worry about it.

**Comment by samreid** [comment]
I'd be interested in discussing with @andrewadare and possibly @jonathanolson how to address layouts where items can be removed.  It seems like for PhET-iO versions we need the ability to remove components and add them back in (possibly not dynamically).

Until now, PhET-iO has only "removing" components by making them invisible.  Perhaps we should use another pattern where the "removed" components are never created and never enter the layout?

Should we move to a dynamic layout which updates when the contents change, perhaps using HBox or VBox?  I suspect this will introduce difficulty for Circuit Construction Kit, which makes assumptions about the coordinate frame of the toolbox items are dragged out of.

**Comment by samreid** [comment]
@arouinfar PhET-iO doesn't currently support the behavior you described, I'll discuss it with @andrewadare and possibly @jonathanolson for adding support in the future, but I think this version will need to ship with the shifted toolbox.

**Comment by arouinfar** [comment]
Sounds reasonable to me @samreid!

**Comment by samreid** [comment]
I created a general issue and cck issues for fixing this kind of layout hole, closing.
