### ISSUE TITLE
What else needs to be done before sharing the next version?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#185]
@arouinfar can you please review open issues and decide what else should be completed before we share the next version with our collaborators?

**Comment by arouinfar** [comment]
@samreid I've finished my review, and have tagged issues that should be addressed for Stanford. 
https://github.com/phetsims/circuit-construction-kit-common/labels/circuit-construction-kit:black-box-study

Given the memory leak issue, @phet-steele and I should do another (final?) round of testing before sharing with Stanford.

**Comment by samreid** [comment]
Thanks @arouinfar, I'll continue in the marked issues.
