### ISSUE TITLE
Initial review of light bulb electrons

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#191]
I've published a dev version of initial support for light bulb electrons here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.20/circuit-construction-kit-black-box-study_en.html

Some of the code is prototype-ish and this has performance implications that need to be solved. That being said, I'm ready for design team feedback on the overall look and behavior.  @arouinfar can you take a look and let me know what you recommend?

**Comment by arouinfar** [comment]
The light bulb electrons look good for Stanford @samreid.

However, it looks like electrons may occasionally overlap one another, so we should work a bit more on the design. Tagging for design meeting.

<img width="266" alt="e_overlap_2" src="https://cloud.githubusercontent.com/assets/8419308/17203100/add36258-545a-11e6-8c49-e940f603daf2.png">  <img width="283" alt="e_overlap_1" src="https://cloud.githubusercontent.com/assets/8419308/17203101/ade11cd6-545a-11e6-9c38-3528fe3d74ff.png">

**Comment by samreid** [comment]
I'm not too concerned about the overlap, to me it seems like they are "going behind" each other instead of touching each other.  If we do need to solve this, we could make the electrons smaller (easy) or change the geometry of the light bulb (more difficult).

**Comment by arouinfar** [comment]
Temporarily unassigning myself from all issues in this repo tagged for design meeting. When we resume design meetings, we can come back to these issues.

**Comment by arouinfar** [comment]
@samreid I think we touched a little bit on this during yesterday's meeting when reviewing the light bulb. I think we're all okay with the way the electrons are moving through the light bulb, but will discuss further tweaks to the bulb itself in #238.

I think this issue can be closed. Do you agree @samreid?

**Comment by samreid** [comment]
Sounds good, thanks.  Closing.
