### ISSUE TITLE
Fine tune touch interface

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#194]
@kathy-phet said there is an event in September which would benefit from a touch-friendly CCK.  This includes:

a) swipe to snag in the touch area
b) testing and refinement

I mentioned that swipe to snag wasn't trivial for the toolbox, and @kathy-phet said it may not be essential with those increased touch areas.

**Comment by samreid** [comment]
@pixelzoom said:

FYI, In case your upcoming touchSnag work involves any situations where events need to be marked as “handled”:
https://github.com/phetsims/scenery/issues/547

Chris

**Comment by samreid** [comment]
I'm seeing other touch issues like #196 which could take some time, so perhaps we should move forward with a Stanford version before working on the touch issues too much.

**Comment by samreid** [comment]
I added `allowTouchSnag` for play area components above and it is working nicely on iPad3.

**Comment by samreid** [comment]
I also fixed #196 and after testing for a few minutes on an iPad3, I did not see any other touch issues.  It would be good for @phet-steele to see if he sees any trouble in the next testing version.

**Comment by samreid** [comment]
Test version available in https://github.com/phetsims/circuit-construction-kit-common/issues/197

**Comment by arouinfar** [comment]
Touch feels good on the iPad Air @samreid. 

I was able to swipe items out of the toolboxes and within the play area, and everything seems to be working nicely.
