### ISSUE TITLE
Layer the scissors/cut button above electrons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#198]
Found as part of #197. 

The scissors button should be layered on top of everything, but it's currently behind the electrons.
![image](https://cloud.githubusercontent.com/assets/8419308/17535663/3966a84c-5e4d-11e6-8f3e-43fcc29e252d.png)

**Comment by samreid** [comment]
The scissors node is currently layered with the vertex node and would be a significant amount of work to move to an independent layer.  My recommendation is to deliver to Stanford before working on this.  @arouinfar can you comment?

**Comment by arouinfar** [comment]
Oh, then please don't worry about the layering for Stanford @samreid.

However, I think we'll still want to make this change for CCK: DC.

**Comment by samreid** [comment]
Proposed fix is above and published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.18/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Looks great!
