### ISSUE TITLE
In Build mode, remove node outlines for components unavailable for connection

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#199]
For #197.

Red nodes are used to indicate which are empty and available for connection.
![image](https://cloud.githubusercontent.com/assets/8419308/17536846/585d9a5a-5e55-11e6-95bc-13b4e06041f7.png)

This can be a bit confusing when switching to Build mode. There are visible nodes which a user cannot connect anything to.
![image](https://cloud.githubusercontent.com/assets/8419308/17536858/66ecb330-5e55-11e6-87c4-eeec2dcb6659.png)

I believe @phet-steele and I may have discussed this before, and we agreed that it would be preferable to remove the dotted lines around ALL unavailable nodes.

In this situation, the dotted lines would only be visible on the black box nodes. The dotted lines around the other five vertices would disappear, leaving behind only the solder joint where applicable. This would help cue to the users which nodes are available for connection.
![image](https://cloud.githubusercontent.com/assets/8419308/17537026/95c48e52-5e56-11e6-9105-84c14812c73c.png)

**Comment by samreid** [comment]
In the preceding commit, the vertex dotted lines have been hidden for unattachable vertices.  My limited testing checks out, but it would be good for @arouinfar to check in the next version.

**Comment by samreid** [comment]
The test issue is https://github.com/phetsims/circuit-construction-kit-common/issues/203

**Comment by samreid** [comment]
Here's the new pic of the above case.  @arouinfar can you please review in the version linked above?

![image](https://cloud.githubusercontent.com/assets/679486/17673309/c34e40a8-62dd-11e6-8002-e2f9c33d1dd4.png)

**Comment by arouinfar** [comment]
👍
