### ISSUE TITLE
Able to edit the BB circuit after Reset All

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#200]
1. Finger A holds down the reveal button
2. Finger B hits Reset All
3. Switch to Investigate Circuit to edit the circuit

![cckbb03](https://cloud.githubusercontent.com/assets/5863899/17598252/d8447ace-5fb6-11e6-9e5a-f31e97aeffac.gif)

Produces this error:

```
Uncaught Error: duplicates are not allowed
push @ circuit-construction-kit-black-box-study_en.html:626
add @ circuit-construction-kit-black-box-study_en.html:626
f @ circuit-construction-kit-black-box-study_en.html:652
(anonymous function) @ circuit-construction-kit-black-box-study_en.html:652
emit2 @ circuit-construction-kit-black-box-study_en.html:626
_notifyObservers @ circuit-construction-kit-black-box-study_en.html:626
_setAndNotifyObservers @ circuit-construction-kit-black-box-study_en.html:626
set @ circuit-construction-kit-black-box-study_en.html:626
fire @ circuit-construction-kit-black-box-study_en.html:651
(anonymous function) @ circuit-construction-kit-black-box-study_en.html:651
n @ circuit-construction-kit-black-box-study_en.html:626
emit2 @ circuit-construction-kit-black-box-study_en.html:626
_notifyObservers @ circuit-construction-kit-black-box-study_en.html:626
_setAndNotifyObservers @ circuit-construction-kit-black-box-study_en.html:626
set @ circuit-construction-kit-black-box-study_en.html:626
set @ circuit-construction-kit-black-box-study_en.html:626
up @ circuit-construction-kit-black-box-study_en.html:646
buttonUp @ circuit-construction-kit-black-box-study_en.html:643
up @ circuit-construction-kit-black-box-study_en.html:643
dispatchToPointer @ circuit-construction-kit-black-box-study_en.html:641
dispatchEvent @ circuit-construction-kit-black-box-study_en.html:640
upEvent @ circuit-construction-kit-black-box-study_en.html:640
mouseUp @ circuit-construction-kit-black-box-study_en.html:640
run @ circuit-construction-kit-black-box-study_en.html:640
fireBatchedEvents @ circuit-construction-kit-black-box-study_en.html:640
batchEvent @ circuit-construction-kit-black-box-study_en.html:640
onmouseup @ circuit-construction-kit-black-box-study_en.html:640
```

Seen on iOS 9.3.3 and Win 10 Chrome (with a touch screen). For phetsims/tasks/issues/668.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.22/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.22 2016-08-02 19:40:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON:
{"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1fd91832","branch":"master"},"babel":{"sha":"98628f5a","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"2616d1cf","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"2ee1d54a","branch":"master"},"circuit-construction-kit-common":{"sha":"4facd999","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"e8a38a2c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"0318877f","branch":"master"},"scenery-phet":{"sha":"70dd84b7","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"df2905e6","branch":"master"},"tandem":{"sha":"bd7d63a1","branch":"master"}}

**Comment by samreid** [comment]
Moved to the issue noted above, closing.
