### ISSUE TITLE
Disembodied vertices after deleting a controlled object

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#202]
1. Finger A will tap on an element, then hold down the element
2. Finger B will tap the delete button while finger A is still controlling the element
   ![cckbb01](https://cloud.githubusercontent.com/assets/5863899/17596985/1655e77c-5fb1-11e6-8231-e9936a8cd5ef.gif)

Gives the following error:

```
Uncaught TypeError: Cannot read property 'pointer' of undefined
maybeSelect @ circuit-construction-kit-black-box-study_en.html:647
end @ circuit-construction-kit-black-box-study_en.html:648
endDrag @ circuit-construction-kit-black-box-study_en.html:646
disposeFixedLengthCircuitElementNode @ circuit-construction-kit-black-box-study_en.html:648
dispose @ circuit-construction-kit-black-box-study_en.html:648
(anonymous function) @ circuit-construction-kit-black-box-study_en.html:649
_fireItemRemoved @ circuit-construction-kit-black-box-study_en.html:626
remove @ circuit-construction-kit-black-box-study_en.html:626
remove @ circuit-construction-kit-black-box-study_en.html:629
listener @ circuit-construction-kit-black-box-study_en.html:647
(anonymous function) @ circuit-construction-kit-black-box-study_en.html:646
fire @ circuit-construction-kit-black-box-study_en.html:646
(anonymous function) @ circuit-construction-kit-black-box-study_en.html:646
n @ circuit-construction-kit-black-box-study_en.html:626
emit2 @ circuit-construction-kit-black-box-study_en.html:626
_notifyObservers @ circuit-construction-kit-black-box-study_en.html:626
_setAndNotifyObservers @ circuit-construction-kit-black-box-study_en.html:626
set @ circuit-construction-kit-black-box-study_en.html:626
set @ circuit-construction-kit-black-box-study_en.html:626
up @ circuit-construction-kit-black-box-study_en.html:646
buttonUp @ circuit-construction-kit-black-box-study_en.html:643
up @ circuit-construction-kit-black-box-study_en.html:643
dispatchToPointer @ circuit-construction-kit-black-box-study_en.html:641
dispatchEvent @ circuit-construction-kit-black-box-study_en.html:640
upEvent @ circuit-construction-kit-black-box-study_en.html:640
touchEnd @ circuit-construction-kit-black-box-study_en.html:640
run @ circuit-construction-kit-black-box-study_en.html:640
fireBatchedEvents @ circuit-construction-kit-black-box-study_en.html:640
batchEvent @ circuit-construction-kit-black-box-study_en.html:640
ontouchend @ circuit-construction-kit-black-box-study_en.html:640
```

Seen on iOS 9.3.3 and Win 10 Chrome (with a touch screen). For phetsims/tasks/issues/668.
Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.22/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.22 2016-08-02 19:40:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON:
{"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1fd91832","branch":"master"},"babel":{"sha":"98628f5a","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"2616d1cf","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"2ee1d54a","branch":"master"},"circuit-construction-kit-common":{"sha":"4facd999","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"e8a38a2c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"0318877f","branch":"master"},"scenery-phet":{"sha":"70dd84b7","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"df2905e6","branch":"master"},"tandem":{"sha":"bd7d63a1","branch":"master"}}

**Comment by phet-steele** [comment]
This leads to some fun consequences when showing electrons and deleting an object in the circuit:
![cckbb04](https://cloud.githubusercontent.com/assets/5863899/17598843/975799a8-5fb9-11e6-983f-2d0a9aefcd1a.gif)

**Comment by phet-steele** [comment]
There's also a very similar procedure by just pressing Reset All when controlling an object.

**Comment by Denz1994** [comment]
@samreid and I tried to reproduce this on an iPhone 5 and iPhone 6 (iOS 10.3.2), also on the iPad named  "Pauling" with no success. Can you reproduce this bug @phet-steele with the latest dev version? 

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.56/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Testing dev.56 on an iPhone 5s running iOS 10.2.1 doesn't leave straggling vertices when deleted while dragging.

**Comment by phet-steele** [comment]
Unable to reproduce these days.
