### ISSUE TITLE
Fix the layout hole in the top right when showElectrons checkbox is hidden

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#204]
As described in https://github.com/phetsims/circuit-construction-kit-common/issues/183#issuecomment-239944313, after https://github.com/phetsims/phet-io/issues/544 is solved, we would like the sensor toolbox to move to the top of the screen when the display options panel is not shown.  I could hack around this now with a workaround but it would really be best to think about general solutions first.

**Comment by samreid** [comment]
@jonathanolson provided a new module for synchronizing layouts between panels, perhaps it would work here?

**Comment by jonathanolson** [comment]
That, or VBox? Couldn't fully understand the required changes.

**Comment by samreid** [comment]
The given behavior seems acceptable for this version of CCK study.  In the future, if we have dynamic layouts, we can revisit.  Closing.
