### ISSUE TITLE
Missing draggingTogetherProperty model event

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#205]
@samreid this feels incorrect to me. It looks like the `***.model.***.draggingTogetherProperty` for the voltmeter and ammeter are set to "true" at sim start up and after a Reset All. This means the first occurrence of a drag of these tools can be missed in the model. An example after Reset All:

<img width="568" alt="screen shot 2016-08-16 at 1 20 44 pm" src="https://cloud.githubusercontent.com/assets/5863899/17712715/732e5482-63b4-11e6-873a-97ad3648125a.png">

Starting a drag will not show this property becoming true (since it already is) until dropped first, then starting another drag. For #138. Tested on OSX 10.11.6 Chrome.

**Comment by phet-steele** [comment]
@samreid I think I misinterpreted this property. This must be true when dragging the tool's body will also drag its probes, and false when dragging the tool's body only drags the body. If that's the case, I guess this issue can be closed.

**Comment by samreid** [comment]
> This must be true when dragging the tool's body will also drag its probes, and false when dragging the tool's body only drags the body.

Yes that is correct, can you help me think of a better name for that variable, so that other's won't have the same misconception?

**Comment by phet-steele** [comment]
> help me think of a better name for that variable, so that other's won't have the same misconception?

Discussed over Skype, and the decision is moved to #207. Closing.
