### ISSUE TITLE
Missing user interaction message

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#206]
@samreid the only thing I can see missing from the PhET-iO data stream is anything saying I clicked on a circuit element. For example, after just dragging a battery out, I clicked it and got just these three messages:
![screen shot 2016-08-16 at 12 48 16 pm](https://cloud.githubusercontent.com/assets/5863899/17711628/c6ad01b2-63af-11e6-964b-85983f974c3b.png)

For #138. Tested on OSX 10.11.6 Chrome.

**Comment by samreid** [comment]
Good catch @phet-steele, I think we should instrument the property that indicates which circuit element is selected.

**Comment by samreid** [comment]
I added a new message that outputs when an element is selected:

![image](https://cloud.githubusercontent.com/assets/679486/25570282/e8672fd4-2de0-11e7-90b8-c795761ac4d7.png)

@phet-steele does that seem OK?

**Comment by phet-steele** [comment]
@samreid I love it! Works great after a quick look. Thank you.
