### ISSUE TITLE
Deliver versions to Stanford

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#208]
In https://github.com/phetsims/circuit-construction-kit-common/issues/203 we completed testing a candidate for Stanford, and determined that version is ready to share.  @arouinfar can you deliver the links to them and ask them to try everything out?  Please include the following links:

* the standard version
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.23/circuit-construction-kit-black-box-study_en.html

* one with ?showPlayPauseButton
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.23/circuit-construction-kit-black-box-study_en.html?showPlayPauseButton

* the phet-io version with the data stream enabled using ?phet-io.log=console (which includes full JSON) and another for ?phet-io.log=lines (colorized and human-readable for Chrome and Firefox)
  * http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.25/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=console
  * http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.25/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines
* A link to the version that hides the "show electrons" button.
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.24/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&phet-io.expressions=[[%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,[false]]]

Also, @arouinfar what are next steps for us for this project?  Are we helping them to collect/analyze data, customize the simulation, etc?

**Comment by arouinfar** [comment]
Great news @samreid! I'll draft an email to Stanford, but I also have questions about what's next. Do we need to schedule a Zoom call like we did previously?

> what are next steps for us for this project? Are we helping them to collect/analyze data, customize the simulation, etc?

These are better questions for @kathy-phet, so I'll assign her.

**Comment by samreid** [comment]
A zoom call sounds very nice, perhaps after they have had a few days to investigate things on their own and think of questions?  Or we could have a zoom meeting for delivery then a relatively soon follow-up.  @kathy-phet what do you recommend?

**Comment by kathy-phet** [comment]
It would be good to do a short zoom meeting with Shima hopefully soon, to give her a tour and check in on her anticipated plans. Then do a follow-up meeting after that. 

Next steps for us for the time being:  
Build a simple wrapper (e.g. a blank wrapper with a fixed iframe size for the time being, except for entering 1-2 identifiers of sorts so Shima can associate with students ... we will need to know what they want here). 
Finish testing for metacog data recording, and make sure that playback through the sims works well so that there is a way to review the data (like a video). 
Have Engin examine the data log so it works for him. 
Set a sub-account up so Engin and Shima have access to their data.

**Comment by samreid** [comment]
I moved the next steps from the previous comment to a new issue.

**Comment by arouinfar** [comment]
After meeting with Stanford this morning, I sent a follow-up email with these links for testing. Closing.
