### ISSUE TITLE
Next steps for Stanford

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#209]
From @kathy-phet in #208 
- Build a simple wrapper (e.g. a blank wrapper with a fixed iframe size for the time being, except for entering 1-2 identifiers of sorts so Shima can associate with students ... we will need to know what they want here). 
- Finish testing for metacog data recording, and make sure that playback through the sims works well so that there is a way to review the data (like a video). 
- Have Engin examine the data log so it works for him. 
- Set a sub-account up so Engin and Shima have access to their data.

**Comment by ariel-phet** [comment]
@samreid @arouinfar can this issue be closed?

**Comment by arouinfar** [comment]
Possibly, @ariel-phet, but @samreid should confirm. Shima's change requests have all been logged in the CCK:BB Study repo:
https://github.com/phetsims/circuit-construction-kit-black-box-study/issues

**Comment by samreid** [comment]
I don't recall building a data collection wrapper for Shima yet, perhaps this still needs to be done.

**Comment by samreid** [comment]
Here is the last email sent to Shima and Carl,

 Hello Shima & Carl,

It was nice getting to chat with you this morning!  We’re looking forward to hearing what additional feedback you have for us.

Sam has logged two issues to address so far — one to change the background color to gray when in pause mode (while finding visually distinct colors from investigate/build), and the other to fix the bug related to the animation speed warning string. These changes aren’t reflected in the links below.


Standard version
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.23/circuit-construction-kit-black-box-study_en.html

PhET-io version with full JSON data stream (in Chrome go to View > Developer > JavaScript Console to see the messages)
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.25/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=console

PhET-io version with colorized and human-readable (in Firefox/Chrome) data stream 
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.25/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines

PhET-io version with electrons disabled and colorized/human-readable data stream
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.24/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&phet-io.expressions=%5B%5B%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D,%5B%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D%5D


The Play/Pause button can be accessed using the ?showPlayPauseButton query parameter. For the standard version, the link would be
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.23/circuit-construction-kit-black-box-study_en.html?showPlayPauseButton

To add the Play/Pause button to any of the PhET-io versions, add &showPlayPauseButton to the end of the URL, like so:

PhET-io version with full JSON data stream and Play/Pause button
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.25/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=console&showPlayPauseButton

PhET-io version with colorized and human-readable data stream and Play/Pause button
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.25/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&showPlayPauseButton

PhET-io version with electrons disabled and Play/Pause button
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.24/phet-io/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone&phet-io.log=lines&phet-io.expressions=%5B%5B%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D,%5B%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D%5D&showPlayPauseButton


Happy testing!

Best,
Amy

**Comment by samreid** [comment]
Based on the last sent email (above), it seems like we did not yet deliver a wrapper that collects data in Metacog.  @kathy-phet and @amyh-phet are we still doing so?  What is the priority/schedule?  Should I communicate with Shima, Carl and Engin directly?

**Comment by samreid** [comment]
Thanks, you are right!

**Comment by arouinfar** [comment]
Frankly, I don't know the timeline for Stanford @samreid. After delivering the links to Shima, she had some change requests, which I logged in the CCK:BB Study repo:
https://github.com/phetsims/circuit-construction-kit-black-box-study/issues

@samreid have you started to refactor the CCK code? In our last meeting with Stanford, we told them that change requests would have a quicker turn-around if they came in before refactoring started.  We did not directly discuss the wrapper. I also don't know if we figured out who would be handling the data stream, as Carl informed us that Engin would not be working on the CCK: BB study.

**Comment by samreid** [comment]
I have not yet started on the change requests or the refactoring.

**Comment by samreid** [comment]
@kathy-phet can you please review this issue and help us prioritize/schedule?

**Comment by kathy-phet** [comment]
Sent email off to shima

Sent from my iPhone

On Oct 30, 2016, at 11:11 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


@kathy-phet<https://github.com/kathy-phet> can you please review this issue and help us prioritize/schedule?

-

**Comment by samreid** [comment]
I'm moving this issue to https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/12 with the pertinent information.

@kathy-phet did you hear back from Shima?

**Comment by kathy-phet** [comment]
Yes, I heard back from Shima. That is what I mentioned in status. She plans to do interviews mid-November, so we'd like to address her bugs/requests today (if possible) or devlote more time this week if a day is not enough.

**Comment by samreid** [comment]
Thanks @kathy-phet, I'll be working on CCK today in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/11 and the other cck-black-box-study issues.  Closing.
