### ISSUE TITLE
buggy usage of NumberControl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#210]
Noted while working on https://github.com/phetsims/scenery-phet/issues/254...

CreateBlackBoxControlPanel, line 19:

```js
Panel.call( this, new NumberControl( 'Black Box Width' ), new Property() );
```

The constructor signature of NumberControl is:

```js
function NumberControl( title, numberProperty, numberRange, options )
```

I'm guessing that this is unused code, otherwise it would be failing.  In any case, it should be fixed.

**Comment by samreid** [comment]
This was indeed unused code, and it has been removed.  Thanks @pixelzoom.
