### ISSUE TITLE
Background should be gray when paused

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#213]
When running with ?showPlayPauseButton the background should be a different color (gray was suggested) to indicate the simulation is paused.  If we go with gray, we will need to choose a shade that doesn't blend too much with the junction colors.

**Comment by samreid** [comment]
Carl also suggested a "running" or "paused" text near the play/pause button, but it is unclear whether we still need that if the background color is changing.  @arouinfar can you comment?

**Comment by arouinfar** [comment]
@samreid I believe Carl suggested that text _could_ go above the play/pause button, but I'm not sure if we need to add this text just yet. Let's make the background color change, and then see what Stanford has to say.

**Comment by samreid** [comment]
Tracking in the above issue, closing.
