### ISSUE TITLE
parseInt missing radix argument

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#214]
`MNACircuit` contains 4 calls to `parseInt` with no radix argument. 

[Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) for `parseInt` says:

>  Different implementations produce different results when a radix is not specified, usually defaulting the value to 10.

**Comment by pixelzoom** [comment]
Fixed, but not confident that I exercised the sim (or the proper sim) in a way that verified this. @samreid please verify.

**Comment by samreid** [comment]
The change set seems good, closing.
