### ISSUE TITLE
Replace getQueryParameter with QueryStringMachine

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#216]
Factored out of https://github.com/phetsims/query-string-machine/issues/15

**Comment by pixelzoom** [comment]
I took care of this, but was unable to lint because this sim fails lint, or test because it's the sims that I tried that use this repo fail on startup.  Assigned to @samreid to verify.

**Comment by samreid** [comment]
Lint and launch working properly, code review of the changes doesn't show any red flags. Thanks!
