### ISSUE TITLE
Add an option to show node voltages to the user

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#22]
In #21 we are going to move the node voltages to the user, however I realized this could be a powerful representation for users to understand circuits.  @arouinfar and @ariel-phet we should discuss this at an upcoming meeting.

**Comment by arouinfar** [comment]
@samreid this is an undesirable feature for Stanford's MVP, but we can discuss the possibility of including it the sim that we eventually publish to the PhET site.

**Comment by samreid** [comment]
I'll assign this to @arouinfar since it is a design question.

**Comment by samreid** [comment]
For debugging, I added a query parameter to show the node voltages.  You can see this feature with ?vertexDisplay=voltage

Here's an example:
![image](https://cloud.githubusercontent.com/assets/679486/16695736/ad6b285c-44fe-11e6-8594-7a9f9d49a9e3.png)

**Comment by arouinfar** [comment]
Good idea @samreid!

Next design meeting, let's go through the myriad open issues we have tagged for discussion.

**Comment by samreid** [comment]
At today's design meeting, we decided that @kathy-phet's feedback will be crucial before we can proceed (if we decide to proceed).

**Comment by samreid** [comment]
To me this seems like a pedagogically useful feature for learning about how circuits work, and I have seen illustrations like this in textbooks.  That being said, I'd be happy to leave this for a 1.1 or future version in order to keep focused on getting 1.0 ready.  Would be good to discuss at tomorrow's design meeting.

**Comment by samreid** [comment]
I haven't implemented the "show values" feature yet, this could be implemented as a part of that (or a sub-option).

**Comment by arouinfar** [comment]
@samreid I'll add this to today's agenda.

**Comment by arouinfar** [comment]
Discussed in 4/20/17 meeting. Showing node voltages is not a desired featured for CCK, though handy to keep query parameter for QA testing.

* Zero point is arbitrary, and we would need to show a ground
* Doesn't require students to do measure -- gives away too much
* Voltage meter measures voltage drops -- not raw value. Students often don't think of Ohm's law in terms of deltaV=IR.
