### ISSUE TITLE
Default values for batteries and resistors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#221]
Moving this email chain over to GitHub.

@kathy-phet:
> Amy,
I was playing with CCK and noticed that the default resistor is 4.5 ohms, but that once you move away from that value you can never get back to it because the slider and the tweakers just let you change to whole number values.
Similarly, voltage is only whole number values but 1 decimal is displayed.
I am just sending this because I cannot recall if we discussed this constraint to just whole numbers? But it seems problematic for the default resistor to have a decimal, but you cannot get back to that value.
Kathy

@arouinfar:
>Hi Kathy,
I don’t recall having a specific discussion about this. Perhaps the default resistance is 4.5 ohms because it works nicely with the default voltage is 9 V? I definitely find it problematic that the default value cannot be recreated. However, I would think that increments of 1 ohm are sufficient. So perhaps the default would instead be 5 ohms/10V?
Best,
Amy

@samreid:
> 5 ohms * 2 amps = 10 volts sounds good to me.  Should we ask Ariel? What was the Java sim like? What do you recommend, Kathy?
Best Regards,
Sam

@kathy-phet :
> The default was 9 volts because that is the batteries you can actually buy in the store.
We could also make it 3 ohms and 9 volts. That avoids the voltmeter reading 5 volts across a 5 ohm resistor --- might cause some confusion. This would be 4.5 volts across a 3 ohm resistor. ... although it would be 3 amps current.
Kathy

@samreid:
>3 Ohm corresponding to 3 Amps also seems confusing, too bad 9 isn't divisible by anything else!  I'm not sure what's best.
Sam

@kathy-phet:
> I agree. I do think it is less confusing than the 5 ohms and 5 volts though.
Kathy

**Comment by arouinfar** [comment]
Based on the discussion above, here are three options for the default values:

1. Keep the same default values, 4.5 ohms and 9V, but change the resistance tweakers to 0.5 ohm step size so default resistance can be restored.
2. 5 ohms, 10 V. Allows us to keep tweakers as is, but 10V isn't a standard battery size.
3. 3 ohms, 9 V. Keeps the standard 9V battery, but resistance and current will both be a "3" which could cause confusion.

@kathy-phet @samreid @ariel-phet I'm leaning towards the first option.

**Comment by kathy-phet** [comment]
I like option #1 too!

**Comment by ariel-phet** [comment]
I agree with the first option

**Comment by arouinfar** [comment]
Thanks @kathy-phet and @ariel-phet! Reassigning to @samreid.

**Comment by samreid** [comment]
The place to make this change is in circuit-construction-kit-common/js/common/view/CircuitElementEditPanel.js

However, before I make this change I want to discuss a potential pedagogical problem.  If we make the resistance slider go by 0.5 and leave the voltage slider at increments of 1.0, then a student may come to the mistaken conclusion that voltage "matters more" than resistance in driving current (if they are counting button presses and not paying attention to the readout.)  Therefore, I recommend to make both the resistor and battery sliders go by 0.5.

@arouinfar @kathy-phet @ariel-phet what do you think?

**Comment by kathy-phet** [comment]
I agree - both having the same increment makes sense to me.
K

Sent from my iPhone

On Dec 23, 2016, at 2:04 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #221<https://github.com/phetsims/circuit-construction-kit-common/issues/221> to @kathy-phet<https://github.com/kathy-phet>.

-

**Comment by samreid** [comment]
Fixed above, will be ready in the next version.  Closing.
