### ISSUE TITLE
What should happen if you click and release on an object in a toolbox?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#224]
In our simulations with toolboxes, typically a "click" (down then immediate up) leads to this behavior: The object flickers large for a second.  This is probably not what the user intended to happen.

I asked @arouinfar in https://github.com/phetsims/circuit-construction-kit-common/issues/63 what the behavior should be, and she replied:

> the object is grabbed (full size) but can immediately be dropped back into the toolbox -- like the tools in Bending Light.

I wanted to discuss this more thoroughly and understand our reasoning for this behavior and discuss whether it should be changed.  Is this current behavior the behavior because it is easy to implement?  Because it is rare for students to click and release on those objects?  Because we want them to learn that they are supposed to drag it?  (does a flicker accomplish this?)  What if a click and release made the object appear in the play area (adjacent to the toolbox)?  Or what if a click and release just did nothing?  (that is, didn't show the flicker).  There are more possibilities as well, my main point is to start a discussion about what we want the ideal user experience to be.

**Comment by arouinfar** [comment]
@samreid these are excellent questions, and it sounds like we should have a more global conversation about the desired behavior. Whatever we decide, we'll want to keep things consistent across all sims. The same goes for the highlight in #63.

Perhaps we could have a general discussion about this behavior in the next design meeting where both AP and KP will be around... perhaps Jan 12? I think we may also want to invite other designers to the discussion. 

@samreid does that sound reasonable? This doesn't sound like extremely time-sensitive issue, but I also don't want to hold back your progress.

**Comment by samreid** [comment]
> @samreid does that sound reasonable? This doesn't sound like extremely time-sensitive issue, but I also don't want to hold back your progress.

Within the next month or two will be fine.

**Comment by arouinfar** [comment]
@samreid I've requested at this (or possibly next) week's design meeting to discuss general toolbox behavior. I want to open an issue in one of the common repos to track the discussion. I'm not sure which repo would be the most appropriate, though. @samreid can you make a suggestion?

**Comment by samreid** [comment]
scenery-phet is most likely the repo where we would implement toolboxes (if we added a common code implementation for them), so that's my best bet for where to discuss it.

**Comment by arouinfar** [comment]
Thanks @samreid! I'll open a general toolbox issue in scenery-phet.

**Comment by arouinfar** [comment]
@samreid during last week's design meeting, we discussed the possibility of having a slightly longer flicker (~0.5 s) on release. Otherwise, we decided the current toolbox behavior should remain as-is.

**Comment by arouinfar** [comment]
I've created a new issue to track the longer flicker (#244) , so I'll go ahead and close this one @samreid.
