### ISSUE TITLE
Voltmeter not working

### ISSUE THREAD

**Issue by FelixINX** [phetsims/circuit-construction-kit-common#231]
Hi,

The voltmeter is not currently working. It alway's show "?". The console output an error as soon you move the voltmeter :
```
BatchedDOMEvent.js?bust=1485113247161:71 Uncaught TypeError: Cannot read property 'call' of null(…)
run	@	BatchedDOMEvent.js?bust=1485113247161:71
fireBatchedEvents	@	Input.js?bust=1485113247161:137
batchEvent	@	Input.js?bust=1485113247161:107
onmouseout	@	Input.js?bust=1485113247161:92
```

Test it here : [http://phet-circuits.felixinx.me/circuit-construction-kit-dc_en.html](http://phet-circuits.felixinx.me/circuit-construction-kit-dc_en.html)

_Note : the test is based on the DC version, but it look's like a general problem._

Thanks :+1:

**Comment by ariel-phet** [comment]
@FelixINX - although we appreciate you looking at this code and understand why you have published a version, you are using an unfinished version with KNOWN issues. 

Unfortunately, our priorities at the moment cannot be driven by bug reports on an unfinished product. We would appreciate if you hold off submitting any bug reports until we have actually published this sim.

**Comment by FelixINX** [comment]
@ariel-phet I understand this, but I didn't find any issue for this specific problem, and I thought it would have been a good idea to mention it, before the final release!

**Comment by ariel-phet** [comment]
@FelixINX you did not find a specific issue because this sim is not even yet at the testing phase. We have a rigorous process to identify bugs. Once the sim gets to the testing phase you will see we have done an "RC" branch, until that time, the main developer is continuing to work to get the sim feature complete.

**Comment by FelixINX** [comment]
@ariel-phet Thank you for the answer. Having said that, can we help? We are many students who practice programming, and if we can help students in our school, and around the world, we would be delighted!

Sorry to disturb you on this sunday!

**Comment by ariel-phet** [comment]
@FelixINX if you wish to help with testing when the sim is ready, we would be more than happy to have your assistance.

**Comment by FelixINX** [comment]
@ariel-phet I'm talking about development, with code!

**Comment by ariel-phet** [comment]
@FelixINX possibly, if that is of interest, please send me a good email contact, and I will get in touch there!

**Comment by FelixINX** [comment]
@ariel-phet Perfect!
