### ISSUE TITLE
Add query parameter for "virtual lab" version

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#233]
How do we minimize the number of CCK flavors while maintaining flexibility?

For example, some teachers do not want to use the non-contact ammeter in their classrooms. Others may only want their students to play with the intro screen.

We can build a customization tool that lives on the sim page that would allow teachers to check off the options they want, and then generate the URL with the appropriate query parameters. For example:
* Show/Hide non-contact ammeter
* Show/Hide conventional ammeter
* Launch screen 1 only
* Launch screen 2 only

To address this, we will create customization tool for the sim page with checkboxes tied to query parameters.

**Comment by samreid** [comment]
@arouinfar can we postpone this until 1.1+ ?

**Comment by arouinfar** [comment]
@samreid I think that would be reasonable, but we should confirm with @kathy-phet.

**Comment by ariel-phet** [comment]
@samreid @arouinfar yes, definitely should be postponed.

**Comment by samreid** [comment]
@arouinfar we published virtual-lab as a separate simulation.  Can this issue be closed?

**Comment by arouinfar** [comment]
Yes, let's close.
