### ISSUE TITLE
Add a Grab Bag items to main toolbox/carousel

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#234]
@arouinfar said she would mock up a grab bag carousel.

**Comment by samreid** [comment]
Doesn’t always need to be open. May encourage students to interact with it earlier in the flow than we’d like. We could have a checkbox, accordion menu, or later in the carousel.

Keeping it in the carousel is more challenging. Users should always have access to wires. Carousel not an ideal option.

**Try accordion menu + Balancing Act carousel style**

**Comment by samreid** [comment]
Infinite carousel would be nice here. May be hard to track where we are without the dots.
Infinite carousel + tracking dots

**Comment by arouinfar** [comment]
@samreid here's an example of Accordion menu + Balancing Act-style Carousel. I think we'd want the Grab Bag closed by default on the Intro screen, and possibly open on the Lab screen.

![image](https://cloud.githubusercontent.com/assets/8419308/23480215/67be62b6-fe84-11e6-8516-b7a3f23b97fe.png)

The Balancing Act-style carousel does not have tracking dots, nor is it infinite. In BA, there's a definite scaffolding of items, but I think that's less true for the CCK Grab Bag. An infinite carousel would be nice, though I don't know if tracking dots would  be necessary. 

Tagging for review in design meeting.

**Comment by arouinfar** [comment]
I read through the meeting notes again, and in the 7/7/16 notes, we said
> Infinite carousel would be nice here. May be hard to track where we are without the dots.

Here's what it would look like with the tracking dots. There are 7 items in the Grab Bag, so 4 dots would be needed.
![image](https://cloud.githubusercontent.com/assets/8419308/23483658/146a456e-fe91-11e6-98f5-608b4edbd54a.png)

**Comment by arouinfar** [comment]
Discussed during the 3/2/17 design meeting.

Grab bag is not necessary on Intro screen. We could possibly add another screen "More" (2nd screen) that would be the Intro Screen + Grab Bag.

There could be one big carousel that includes the circuit components and grab bag items. The wire (and possibly the battery) would always be at the top of the carousel.

Leaving self-assigned to mock this up.

**Comment by arouinfar** [comment]
Here's a mockup with the updated carousel.
![image](https://cloud.githubusercontent.com/assets/8419308/23812569/4a54b0d4-0598-11e7-9939-78f50f557b92.png)

![image](https://cloud.githubusercontent.com/assets/8419308/23812499/0f70dcc2-0598-11e7-93a4-f9c1988e2d9c.png)

**Comment by arouinfar** [comment]
The carousel on the lab screen will need to (eventually) include the fuse, LED, and non-Ohmic bulb. I think these items would show up between the standard circuit components and the grab bag items.

**Comment by samreid** [comment]
@arouinfar how did you decide to use battery for the lifelike/schematic radio buttons?  I think it looks good, but wonder if more people might be familiar with resistor schematic icon (not sure if that even matters though).

**Comment by arouinfar** [comment]
@samreid I think I first mocked them up that way during a design meeting. I think resistors and batteries have the opposite problem -- schematic resistors are more recognizable than the lifelike version. I think we'd want to go with either a battery or resistor, but I don't have a strong opinion on this issue. We can bring it up during design meeting.

**Comment by arouinfar** [comment]
Lifelike battery is more recognizable, so we'll stick with that. The function of the schematic button will become immediately obvious to users.

**Comment by samreid** [comment]
I have split this issue into two steps, noted above and will proceed in those, closing.
