### ISSUE TITLE
Add magnifying glasses in the bottom left for zoom

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#235]
Want to preserve Medium and Small options from original CCK. Can function like radio button, no need to dynamically zoom.

Try magnifying glass icons in the bottom left

**Comment by samreid** [comment]
Only 2 zoom levels.  Default and "zoom out".

**Comment by samreid** [comment]
From recent meeting:

Two levels: Medium and Small from Java version.

Dynamic slider doesn’t directly support learning goals and could have animation performance costs, so a radio option may be better.

If circuit is built on the edge when zoomed out, that circuit should stay where it is when zoomed in. Don’t scoot it into the new zoom level. Leave it outside.

**Comment by samreid** [comment]
@arouinfar where did we decide to put these controls at the end of the latest design meeting?

**Comment by samreid** [comment]
I'm rolling with bottom-left for now.

**Comment by arouinfar** [comment]
@samreid, when we tried having two separate carousels on the left side of the screen, we moved the zoom buttons to the lower right, near the reset all button. However, I think now that we've decided to combine the circuit components and grab bag into one carousel, we can keep the zoom buttons in the lower left corner.

**Comment by samreid** [comment]
Currently the circuit element toolbox is in the same layer as the circuit itself.  Here's a note from Black Box about why that is done:

> Has to be interleaved in the circuit layering to support the black box, so that the toolbox can be behind circuit elements but in front of the transparency overlay

The effect is that the circuit toolbox zooms out too:

![image](https://cloud.githubusercontent.com/assets/679486/23716243/c198a34c-03ec-11e7-87f3-c0e15f89b464.png)

This does not seem desirable.

**Comment by samreid** [comment]
Zoom is mostly working, I'll create side issues for the remaining work.
