### ISSUE TITLE
Should the light bulb have wires coming off of it?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#238]
At a June 2016 design meeting, it was suggested that we add wire stubs to the light bulb, like so:

![image](https://cloud.githubusercontent.com/assets/679486/22311453/c0439b98-e310-11e6-8d68-437e4ac4322e.png)

Notes: Widen socket so there’s more room for electrons. May or may not need to keep one wire on the edge. Center wire doesn’t need to be perfectly centered. Something like this:

![image](https://cloud.githubusercontent.com/assets/679486/22311468/cf0a2f2a-e310-11e6-8c2f-03f532e1cefd.png)

@arouinfar said she would update the artwork.

Keep in mind issue https://github.com/phetsims/circuit-construction-kit-common/issues/73 which I will link below:

**Comment by arouinfar** [comment]
@samreid I'm happy with the light bulb used CCK:BB and CCK:Prototype. We can re-review the behavior during the next design meeting to see if there is anything we'd like fine-tuned. Light bulb discussion would also need to include #73 and #259.

**Comment by arouinfar** [comment]
3/9/17 discussion:

Widen the socket.
Preferable to keep vertices in the same location on schematic and lifelike views.

**Comment by arouinfar** [comment]
I widened the socket by 10% and was able to move the right vertex a few pixels to the right.

New bulb (left) vs. current bulb (right)
![image](https://cloud.githubusercontent.com/assets/8419308/23810699/d49445e2-058f-11e7-8cd6-d0fb6a752f03.png)

Any thoughts @samreid @ariel-phet?

**Comment by arouinfar** [comment]
The bulb does not need wires coming off of it. We're happy with the design in the comment above. I will open a new issue to track the new bulb.
