### ISSUE TITLE
What should the battery internal resistance be?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#242]
In https://github.com/phetsims/circuit-construction-kit-common/issues/72#issuecomment-277076184 we saw that Java has the internal battery resistance at 1E-4 and the HTML one looks like 0.  I should confirm these suspicions and see if it is causing any trouble, or if it should be changed in HTML5.

**Comment by samreid** [comment]
If I recall correctly, I added the battery internal resistance in Java to prevent numeric instability in the solutions.  Thus far, we have not observed any numerical problems in the circuits with the battery internal resistance being 0 (ideal battery).  My recommendation: leave this issue open but "on hold" as a thing to double check before publishing in case numerical issues arise.

**Comment by samreid** [comment]
One point: it is impossible to create a circuit without wires, and all wires have at least 1E-8 ohms resistance, so the circuits algebra doesn't have any problems.  @arouinfar can this issue be closed?

**Comment by arouinfar** [comment]
@samreid sounds good. I think we can go ahead and close this issue.
