### ISSUE TITLE
Increase flicker time when item in toolbox is clicked and released

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#244]
In https://github.com/phetsims/scenery-phet/issues/289 @ariel-phet wrote:
> @arouinfar I think make an issue for increasing the time delay of increased component size, but make this issue in CCK. @samreid can try it out in that sim, and then if all looks good we can consider generalizing. In the issue probably mention the idea of generalizing, and @samreid can decide where and how that should be done if all looks good (since we have several sims that use this enlargement strategy like FAMB Bending Light and such)

When at item in the toolbox is clicked (down then immediate up), the object flickers large. In the Toolbox design meeting, the consensus was that this "flicker" time could be made a bit longer (~0.5s). 

@samreid can you try this out in CCK? If we like the behavior, it could retroactively apply to several other sims, so please keep generalization in mind.

**Comment by samreid** [comment]
Fixed above, will need review in next version.

**Comment by samreid** [comment]
@arouinfar can you test this in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.7/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
@samreid, in general the flicker time seems good. However, the bulb doesn't return to the toolbox after clicking. It gets stuck like this:
![image](https://cloud.githubusercontent.com/assets/8419308/25241039/d3776ec2-25b1-11e7-9d99-ec326e4d35f3.png)

I'm using the latest Mac OS/Chrome.

**Comment by samreid** [comment]
Thanks, that will be tracked in https://github.com/phetsims/circuit-construction-kit-common/issues/278, closing.
