### ISSUE TITLE
Dealing with 0 resistance light bulbs and resistors

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#248]
It is odd to show a resistor or light bulb that has 0 resistance, since these don't exist in real life (unless they are broken).  Some possibilities:

* Graphically depict a 0 resistance resistor (or bulb) as a wire
* Prevent the user from turning the resistance to 0.  (I'm not a fan of this idea since it limits the ability of the user to explore).

@arouinfar and @ariel-phet thoughts?

**Comment by ariel-phet** [comment]
@samreid they do actually exist...they are called superconductors :). So it is not outside the realm of real life.

I do not think we should necessarily prevent this situation, but it does have consequences.

**Comment by arouinfar** [comment]
@samreid @ariel-phet I don't think it's necessarily harmful to keep the 0 resistance bulbs and resistors. In some situations, it may actually be a bit handy. For example, a teacher may set up a somewhat complicated circuit, and then decide to "turn off" various resistors or bulbs by setting R = 0.

**Comment by kathy-phet** [comment]
I think we do want to Keep 0 resistance or make it nearly zero equivalent. I see lots of cases where this is useful for parallel and series circuits.

Sent from my iPhone

On Feb 8, 2017, at 5:05 PM, Amy Rouinfar <notifications@github.com<mailto:notifications@github.com>> wrote:


@samreid<https://github.com/samreid> @ariel-phet<https://github.com/ariel-phet> I don't think it's necessarily harmful to keep the 0 resistance bulbs and resistors. In some situations, it may actually be a bit handy. For example, a teacher may set up a somewhat complicated circuit, and then decide to "turn off" various resistors or bulbs by setting R = 0.

**Comment by samreid** [comment]
We are in agreement that we should be able to set resistor and light bulb resistances to 0.  Should a 0 resistance light bulb look exactly the same as a 10 Ohm light bulb?

**Comment by arouinfar** [comment]
@samreid I think they should look the same, with the exception that a 0 ohm bulb won't light up.

**Comment by samreid** [comment]
It sounds like we are in agreement that 0-resistance bulbs should look like regular bulbs, 0-voltage batteries should look like regular batteries, etc.  I'll close for now.
