### ISSUE TITLE
Label text should not be camel case

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#249]
@arouinfar noticed that these labels should probably not be camel case. Title case (with a space between "light" and "bulb") would probably be better.

<img width="152" alt="screen shot 2017-02-08 at 3 27 58 pm" src="https://cloud.githubusercontent.com/assets/5863899/22760314/3564f252-ee13-11e6-98b8-79c998148ac6.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/781.

**Comment by samreid** [comment]
Agreed, good catch!

**Comment by samreid** [comment]
Fixed above, will be ready for verification in rc.2.

**Comment by samreid** [comment]
Ready for verification in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

**Comment by arouinfar** [comment]
It's not title case, but I actually prefer the way the lower case labels look. Thanks @samreid.

**Comment by samreid** [comment]
I tried Title case (with upper case first letter), but it looked odd to me and lower seemed much better.

**Comment by arouinfar** [comment]
Good call @samreid. Thanks!
