### ISSUE TITLE
Remove the toolbox highlight

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#250]
Based on https://github.com/phetsims/circuit-construction-kit-common/issues/63#issuecomment-277782953, the outline on the toolbox should be removed in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.1/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
Fixed above, will leave open until confirmed in rc.2.

**Comment by samreid** [comment]
Ready for verification in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

**Comment by phet-steele** [comment]
Removed in rc.2, thanks!
