### ISSUE TITLE
Odd yellow square when a light bulb is selected

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#252]
I've got this little yellow square towards the upper left of the light bulb when I select it for edit. It doesn't look like it does anything.

<img width="264" alt="screen shot 2017-02-09 at 10 35 27 am" src="https://cloud.githubusercontent.com/assets/5863899/22795888/8556e624-eeb5-11e6-8617-20d3957f8703.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/781.

**Comment by samreid** [comment]
Fixed in preceding commit, will leave open until confirmed in rc.3.

**Comment by phet-steele** [comment]
Fixed here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.3/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone
