### ISSUE TITLE
Slider resizes when thumbs at min/max

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#253]
It looks like the thumb on each slider will reposition the tweakers if the thumb has extended further  than the right or left of the track. The reposition/resize only happens after disabling then re-enabling the slider. I used a wire to align to the left edge of a tweaker so it was more obvious when it moved.

1. Click on a component to enable the slider.
2. Move the thumb all the way left or right.
3. Click away from the slider to hide it.
4. Click on the same component in step 1. The tweakers will have moved outward

![cckbbio05](https://cloud.githubusercontent.com/assets/5863899/22796968/cda1b4a0-eeb9-11e6-8006-ed7e2ee69e56.gif)

Seems eerily familiar to phetsims/rutherford-scattering/issues/97.

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
It seems the best way to address the root cause of this problem would be to add struts or bounds to the slider itself that will account for the half width of the slider.

**Comment by samreid** [comment]
We will pursue a solution to this problem in https://github.com/phetsims/sun/issues/282

**Comment by samreid** [comment]
Note: when this is fixed in common code, we will need new SHAs or a common code branch for RC.3.

**Comment by samreid** [comment]
Fixed in the sun issue/pending testing/requires new SHA.

**Comment by phet-steele** [comment]
Looks good in rc.3 @samreid.

**Comment by samreid** [comment]
@phet-steele can this be closed?

**Comment by phet-steele** [comment]
> can this be closed?

Indeed it can! Left it open in case you would use it as a reminder for the sun issue.

**Comment by samreid** [comment]
I got the new sun sha, so we are good to go.  Thanks!
