### ISSUE TITLE
Vertex....Pulling?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#254]
Using fixed length components, you can detach vertices from their body while controlling the opposite vertex you are attaching.

In this video, I am controlling vertex 26 and "pushing" vertex 27 and 24 together. Once I release 26, the battery is pulled away from vertex 25:

![cckbbio07](https://cloud.githubusercontent.com/assets/5863899/22837836/8ecf825e-ef7f-11e6-87da-9c67b9a2fdc9.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
I have reproduced the problem, thanks @phet-steele!

**Comment by samreid** [comment]
Proposed fix is above, ready for testing with RC.3 is ready.

**Comment by phet-steele** [comment]
@samreid your fix works for single component manipulation, but not if I am moving a vertex atached to a different circuit element (I'm pushing vertex 26):

![cckbbio08](https://cloud.githubusercontent.com/assets/5863899/22991118/84f037fe-f378-11e6-9fbb-0a76641b4062.gif)

**Comment by samreid** [comment]
Good catch @phet-steele.  @arouinfar and @phet-steele what behavior do you recommend for that case?  I believe there is already code to bump vertices away from each other, or we could try letting them be close without connecting.  I guess I'm leaning toward bumping them away so we don't end up with a situation where two elements look connected but aren't connected.  Sound OK to try?

**Comment by arouinfar** [comment]
@samreid is it not possible for the right-most battery in https://github.com/phetsims/circuit-construction-kit-common/issues/254#issuecomment-280109283 to remain attached to vertex 23 when it scoots left? If not, I think it would be reasonable to try bumping the right-most battery away instead.

**Comment by phet-steele** [comment]
@samreid a bump would not solve the case where the component you are pushing towards is fixed in place:

![cckbbio09](https://cloud.githubusercontent.com/assets/5863899/22992340/a91bc5a4-f37c-11e6-8cda-e9c9005acbc9.gif)

**Comment by phet-steele** [comment]
Actually, I didn't need the battery:
<img width="1058" alt="screen shot 2017-02-15 at 12 48 44 pm" src="https://cloud.githubusercontent.com/assets/5863899/22992510/22c8e5f8-f37d-11e6-9cc6-0197dfd6af50.png">

**Comment by samreid** [comment]
@arouinfar is the behavior in rc.3 acceptable for our February deadline?

**Comment by samreid** [comment]
> @samreid is it not possible for the right-most battery in https://github.com/phetsims/circuit-construction-kit-common/issues/254#issuecomment-280109283 to remain attached to vertex 23 when it scoots left? If not, I think it would be reasonable to try bumping the right-most battery away instead.

We could do that, but we must consider the more general case where the battery on the right is also connected to a larger circuit (or a black box vertex).

**Comment by arouinfar** [comment]
> We could do that, but we must consider the more general case where the battery on the right is also connected to a larger circuit (or a black box vertex).

Excellent point @samreid. I haven't been able to reproduce any of the examples described in this issue in rc.4. The behavior is definitely acceptable for Stanford's study, but I would like @phet-steele to take another look to make sure this is good enough for a publishable sim.

**Comment by arouinfar** [comment]
So after consulting with @phet-steele I realized that I didn't fully understand the procedure to cause vertex pulling. In rc.3 I was able to get vertices to pull without releasing the component. 

I can still cause vertex pulling in rc.4, but I think it's a little tricky to do. I do not think this is a blocking issue for Stanford, but we'll need to address this before sim publication.

**Comment by samreid** [comment]
Since the remaining issue looks like it only affects the BBS version, I'll move this issue to that repo.

**Comment by phet-steele** [comment]
This issue, specifically https://github.com/phetsims/circuit-construction-kit-common/issues/254#issuecomment-280109283, is not fixed in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.135/circuit-construction-kit-dc_en.html. Reopening. It looks like discussion on how to handle ended at https://github.com/phetsims/circuit-construction-kit-common/issues/254#issuecomment-280691501?

For phetsims/QA/issues/33.

**Comment by arouinfar** [comment]
@samreid can you treat the situation in https://github.com/phetsims/circuit-construction-kit-common/issues/254#issuecomment-280109283 like this?

![vertex_pulling](https://user-images.githubusercontent.com/8419308/29097371-b9298e32-7c56-11e7-8492-156934d3835a.gif)

The group of objects being dragged gets sucked into the component on the far right.

**Comment by samreid** [comment]
In the preceding commit I changed the rule from "the dragged vertex and its neighbor can connect" to "the dragged vertex and any other vertex that is connected by fixed length circuit elements to that group can connect."  The proposed fix is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.146/circuit-construction-kit-dc_en.html

@phet-steele and @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Seems okay to me @samreid, but I think @phet-steele should definitely take a look.

**Comment by phet-steele** [comment]
Also is working for me, thanks @samreid.
