### ISSUE TITLE
Fire is seen when the sim is paused

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#256]
This seems not ideal, especially when coupled with the static electrons. A quick discussion with @arouinfar yielded that, for the purposes of this particular play/pause button, the effects of a circuit should only be seen when the sim is playing. This does mean that fire will "flicker" on and off when the sim is toggled between play/pause.

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
Fixed above and ready for testing in rc.3+

**Comment by phet-steele** [comment]
Bel lavoro!
