### ISSUE TITLE
Cut buttons can be lost off screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#257]
@samreid I would recommend not letting the scissors get lost off the screen when vertices are along the edges of the sim.

<img width="253" alt="screen shot 2017-02-15 at 2 00 54 pm" src="https://cloud.githubusercontent.com/assets/5863899/22995209/362f9286-f387-11e6-811e-02da20b12fd8.png">

**Comment by samreid** [comment]
We'll also need to handle the situation where the scissors are onscreen and then the screen is resized (though I think in other sims the popup controls just disappear when the window is resized).

**Comment by samreid** [comment]
Proposed fix is above, @phet-steele would you like to test it?

**Comment by phet-steele** [comment]
@samreid I like this fix! Although, I think it would be slightly more aesthetically pleasing if the button was layered over the yellow ring, no?

<img width="167" alt="screen shot 2017-03-22 at 10 26 10 am" src="https://cloud.githubusercontent.com/assets/5863899/24208795/24727710-0eea-11e7-9a1f-b04fc7046c6d.png">

**Comment by samreid** [comment]
If I understand correctly, the default implementation for accessibility has the focus regions on top of everything else.  We have the opportunity to override this on a case-by-case-basis, but I'm not sure whether it will be worth the effort.  I may know more after finishing #114

**Comment by samreid** [comment]
I moved the remaining work to a new issue, closing.
