### ISSUE TITLE
Reset All does not reset the Labels checkbox

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#258]
Seen in rc.3 on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
Good catch, fixed above.

**Comment by samreid** [comment]
Ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.4/wrappers/index/

**Comment by phet-steele** [comment]
Bien fait, @samreid.
