### ISSUE TITLE
Light bulb should become transparent at power=0

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#259]
@kathy-phet said in https://github.com/phetsims/circuit-construction-kit-dc/issues/16

> Also, in looking at the original CCK, I really like how the bulb is a clear glass bulb there so it goes completely "dark" (transparent) when the power is 0 and it itself glows with the light going on. It makes it super clear that it is not on at all. I know we worked on getting the wire shape and electron path correct, but can we discuss the transparency issue at some point down the road. No rush on that, but I just wanted to note it since (to me) the original seems clearer pedagogically.

**Comment by samreid** [comment]
@arouinfar can you please provide artwork for the light bulb that will help with this?  All the images I have right now show as opaque even for power=0.

![image](https://cloud.githubusercontent.com/assets/679486/23474140/f1323280-fe6f-11e6-97f8-ea1639722e45.png)

Please see https://github.com/phetsims/circuit-construction-kit-common/tree/a1d7c54dd6267bc26b750f0e891e8f2a4dac0cfc/images for a reminder of how the image layers work for the light bulb.

**Comment by arouinfar** [comment]
@samreid I've split the current lightbulb asset into three layers. The back (left) layer would only be visible when P>0.
![image](https://cloud.githubusercontent.com/assets/8419308/23478154/9eb63476-fe7d-11e6-8661-4f3f7d4d11d6.png)

I'll email you the updated assets.

**Comment by samreid** [comment]
Fixed in #274 and the above commit.  Posted dev version here http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.25/circuit-construction-kit-dc_en.html .  @arouinfar can you please see if this transparency issue is OK?

I also noticed a tiny yellow flake on the unlit bulb, not sure what it is.  Should we make an issue for it?

![image](https://cloud.githubusercontent.com/assets/679486/26328853/e60175e2-3f01-11e7-91f2-1c580a324512.png)

**Comment by samreid** [comment]
Fix for the yellow flakes is on the way

**Comment by samreid** [comment]
OK Yellow flakes should be gone after the above commit.

**Comment by arouinfar** [comment]
:+1:
