### ISSUE TITLE
Instead of a sudden max for light bulb brightness, use a logistic function or other asymptote

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#260]
From https://github.com/phetsims/circuit-construction-kit-dc/issues/16

@arouinfar would you like to recommend a max power?  Or should we try to implement a gradual (instead of sudden) cutoff, like a logistic function, so that we can depict different powers over a wider range?

![image](https://cloud.githubusercontent.com/assets/679486/23290198/400a5486-fa0c-11e6-9fcf-f50512d7368d.png)

**Comment by samreid** [comment]
@kathy-phet said:

> @samreid, @arouinfar  - I think we could use this sort of shaped curve on the upper end, but the behavior on the bottom end seems good.

**Comment by samreid** [comment]
@kathy-phet said:

> @samreid , @arouinfar - I think the logistic function would be good to try,

**Comment by samreid** [comment]
@arouinfar said:

>  I think the logistic function would be a good long-term solution, but not necessary for Stanford.

**Comment by samreid** [comment]
@arouinfar can you please think about how we should depict brightness as a function of power, and make a recommendation for this issue?  You could provide (a) a function or (b) a clear description of how it should behave then we can work together to make it a function.

**Comment by arouinfar** [comment]
@samreid I've been playing with sigmoid functions, and I think I've found a function that will allow for reasonable range of brightnesses up to 100 W: 
![image](https://cloud.githubusercontent.com/assets/8419308/26693711/5f639984-46c2-11e7-93e0-4d09f7eb6b55.png)


![screen shot 2017-06-01 at 11 50 22 am](https://cloud.githubusercontent.com/assets/8419308/26693285/e214f992-46c0-11e7-871a-655cb31f6fad.png)

For a circuit with a single battery and bulb
* Default battery + variable bulb, max power is 81 W
* Default bulb + variable battery, max power is 1000 W. 100 W would correspond to ~32 V, but up to 40 V (160 W)  would be decent:
![image](https://cloud.githubusercontent.com/assets/8419308/26693637/17b6aa90-46c2-11e7-91fa-73c925bd5415.png)

Any thoughts @samreid?

**Comment by samreid** [comment]
@arouinfar to clarify, should I subtract 0.5 from the sigmoid so that 0 power => 0 brightness?

**Comment by samreid** [comment]
I tried

```js
var brightness = (1 / (1 + Math.exp( -0.05 * power )) - 0.5) * 2;
```

And saw that for a default 10 ohm bulb, the brightness lines saturate at 93.02130662342283 watts, for a 35V battery.  I'll try to stretch out the sigmoid a bit more.

**Comment by samreid** [comment]
Wolfram Alpha said it got the same answer:

plot (1 / (1 + e^( -0.05 * x )) - 0.5) * 2 from x = 0 to 100

![image](https://user-images.githubusercontent.com/679486/26959201-222c86dc-4c8c-11e7-8a4d-b015f4247e39.png)

Here's one that has a broader range:
plot (1 / (1 + e^( -0.0035 * x )) - 0.5) * 2 from x = 0 to 1000

![image](https://user-images.githubusercontent.com/679486/26959255-72f6753c-4c8c-11e7-85ab-751dbdfaf6d7.png)

I'll see how it looks in the sim...

**Comment by samreid** [comment]
The preceding function with 0.0035 has a great dynamic range up to 1000W, but the default brightness (default bulb + default battery) is kind of wimpy and very different than what we've done until now:

![image](https://user-images.githubusercontent.com/679486/26959296-bf8ced04-4c8c-11e7-8523-7c4996f4f504.png)

**Comment by kathy-phet** [comment]
I had recently looked at the prior brightness and I thought it was in a good place because you could do the whole 0-100v without it maxing out on the default resistance. It seemed like it was a nice improvement over the Java and you hit the main issue with that.
K

Sent from my iPhone

On Jun 8, 2017, at 8:55 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


The preceding function with 0.0035 has a great dynamic range up to 1000W, but the default brightness (default bulb + default battery) is kind of wimpy and very different than what we've done until now:

[image]<https://user-images.githubusercontent.com/679486/26959296-bf8ced04-4c8c-11e7-8523-7c4996f4f504.png>

**Comment by samreid** [comment]
I agreed it is working great for 0-100v in the current version.  If we want to extend the range (to handle values beyond 100v) while keeping this behavior mostly the same, we could choose piecewise linear segments like this:

![image](https://user-images.githubusercontent.com/679486/26960420-4520e9e6-4c94-11e7-9bf7-13581190a998.png)

This doesn't seem perfect because it is too sharp of a curve around 100 W but I bet @jonathanolson could create a continuous function that's a good match.

**Comment by kathy-phet** [comment]
Sam, Note I said 0-100v on battery. In watts that is at v^2/r which is 1000watts for the 100v setting.

Sent from my iPhone

On Jun 8, 2017, at 9:51 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


I agreed it is working great for 0-100v in the current version. If we want to extend the range (to handle values beyond 100v) while keeping this behavior mostly the same, we could choose piecewise linear segments like this:

[image]<https://user-images.githubusercontent.com/679486/26960420-4520e9e6-4c94-11e7-9bf7-13581190a998.png>

This doesn't seem perfect because it is too sharp of a curve around 100 W but I bet @jonathanolson<https://github.com/jonathanolson> could create a continuous function that's a good match.

**Comment by samreid** [comment]
I agree the main part was fixed for 0-100V and it is working much better than the Java version.  I think it is still desirable to show the brightness changing as the power changes, even beyond 1000 volts.  Not sure how we will want to handle this for the high-voltage high-resistance components, but we may need some flexibility.

@jonathanolson recommended looking into a logarithm to keep the desired behavior up to 1000 watts but still showing a dynamic range beyond it.  In the preceding commit, we added a logarithm that has a good dynamic range up to 2000W and matches behavior nicely up to 1000W.  We can also adjust it further as we decide how to depict brightness for the high-resistance/high-voltage case.

**Comment by samreid** [comment]
Here is the function @jonathanolson and I developed yesterday:

```js
  /**
   * Determine the brightness for a given power
   * @param {number} multiplier - steepness of the function
   * @param {number} power - the power through the light bulb
   * @returns {number}
   */
  function toBrightness( multiplier, power ) {
    var maximumBrightness = 1;

    // power at which the the brightness becomes 1
    var maximumPower = 2000;
    return Math.log( 1 + power * multiplier ) * maximumBrightness / Math.log( 1 + maximumPower * multiplier );
  }
```

The free parameters are the `maximumPower` which sets the overall scale factor and the `multiplier` which determines the steepness of the logarithm.  I'll publish a dev version and we can discuss it further.

**Comment by samreid** [comment]
Here's a dev version with the logarithm:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.58/circuit-construction-kit-dc_en.html

Also, here's a pic of the logarithm (using multiplier 0.35), note that after the logarithm, the brightness is clamped to 1.0 (so it isn't a true asymptote in the y-dimension)

![image](https://user-images.githubusercontent.com/679486/26979030-b4153fe0-4cea-11e7-9bcd-529d3f11087b.png)

@arouinfar can you take a look?

**Comment by arouinfar** [comment]
@samreid I think the brightness on the standard bulb looks really good! I think it would be good to discuss how to handle brightness above 2000 W in the next design meeting.

**Comment by samreid** [comment]
@arouinfar are we having another design meeting for this?  If not, should we make any adjustments?  Is the logarithm "good enough" for 1.0?

**Comment by arouinfar** [comment]
@samreid we'll have a design meeting this week, and we should discuss high power circuits. I suspect the logarithm will be "good enough" for 1.0, as the brightness variation may not be as important for the high V/R components.

**Comment by samreid** [comment]
@arouinfar did we decide this is fine for 1.0?

**Comment by arouinfar** [comment]
@samreid we decided to defer further work on the brightness until 1.1+, but I'm not sure what adjustments we would make in a future version. I'm going to go ahead and close this issue, but we can revisit the brightness if we get a lot of pushback/requests from users.
