### ISSUE TITLE
Default resistivity

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#261]
In the CCK:DC (java), wires and lowest-resistence bulbs have a small amount of resistance. We should look closely at this behavior as we work on the DC HTML version - as I recall we spent a lot of time honing these types of choices in the original.

**Comment by arouinfar** [comment]
Discussed in 3/23/17 design meeting. 

Default resistance for bulbs and resistors will be 10 ohms. This will make the calculation for R in parallel easier (adding/inverting factors of 1/10 instead of 1/4.5), and the voltage can be maxed out without the fire appearing.

**Comment by arouinfar** [comment]
@samreid I think this issue overlaps a bit with https://github.com/phetsims/circuit-construction-kit-dc/issues/17. Perhaps one of them can be closed?

**Comment by samreid** [comment]
I changed the default resistance for bulbs and resistors to be 10 ohms.  @arouinfar and @kathy-phet anything else to do for this issue?  I'm asking because the title is about resistivity but the comment https://github.com/phetsims/circuit-construction-kit-common/issues/261#issuecomment-288871727 doesn't mention resistivity.

**Comment by arouinfar** [comment]
From the original https://github.com/phetsims/circuit-construction-kit-common/issues/261#issue-210151368, I'm fairly certain @kathy-phet was referring to the resistance, not resistivity, as the title suggests. I don't think there's anything else that needs to be done here.

@kathy-phet can you please review? If everything looks good, please close.

**Comment by kathy-phet** [comment]
Does the resistance per length of the wires currently match the Java version?

**Comment by samreid** [comment]
In the Java CCK at the default value of "almost none", the default wire at its default length has resistance of 1.5E-4 Ohms.  When stretched diagonally across the screen, it has 0.0015796715030564601 Ohms.

At "lots", it has:
1.5 (short)
15.65 across the screen

For the HTML5 one, I see:
0.00015273409966500692 (short)
0.0016947679254338806 (across the screen)
"lots"
0.76 (short)
8.9 (across the screen).

Hence it seems if we make the HTML5 resistivity slider "lots" twice as large, it would match up much more closely with the java one.

**Comment by samreid** [comment]
After doubling "lots", I see 1.5273409966500693 (short) and 18.1 (diagonal).  I'll commit this then check with @arouinfar and @kathy-phet if this is good enough.

**Comment by samreid** [comment]
@arouinfar and @kathy-phet does that sound good enough to you?

**Comment by arouinfar** [comment]
Sounds good to me @samreid. Thanks!

**Comment by samreid** [comment]
Changes are published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.7/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
@kathy-phet can you please review?

**Comment by samreid** [comment]
Tagging for upcoming design meeting in case @kathy-phet hasn't had a chance to review before then.q

**Comment by arouinfar** [comment]
Discussed 6/15/17 and we can go ahead and close this issue.
