### ISSUE TITLE
User reported issue: batteries in parallel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#266]
A user reported to phethelp:
> When mounting a circuit with batteries in parallel, the electric current should increase.
![bug](https://cloud.githubusercontent.com/assets/8419308/23683983/38bb48c4-0359-11e7-8c98-781b90d75224.png)

I think the user may be conflating current and mAh. Consider a 9V battery connected to a 4.5 ohm resistor. The current through the resistor is 2 amps. If a 2nd 9V battery is connected in parallel to the 1st battery, the voltage across the resistor is still 9V, so the current remains 2 amps. However, the batteries are now working together to supply those 2 amps, so their lifetime (mAh) is effectively doubled. 

However, I was troubled by the user's screenshot that shows a current of 0 amps through the lower part of the circuit. Playing more with CCK: Prototype, I discovered that two semantically identical circuits behaved very differently. (This bug is not present in the Java sim.)

![parallel_batteries](https://cloud.githubusercontent.com/assets/8419308/23684154/16afd258-035a-11e7-9ddf-b7673b9a0529.gif)

The circuit on the left exhibits the behavior in the user's original screenshot. Both batteries should be supplying 1/2 of the current that is delivered to the resistor. However, it seems the lower battery is not considered a part of the circuit unless there's an extra wire stub coming out of the upper battery (like in the right circuit).

Something else that's bothered me a little bit is that the current in the two battery branches is vastly different. This screenshot is from Java, but the same behavior is in HTML5. I would think they should both be roughly equal (~0.45 amps in the screenshot below). I suspect this could be related to the resistance in the wire, but even when trying to keep the wire segments a similar length, the current supplied by the two batteries was quite different.
![image](https://cloud.githubusercontent.com/assets/8419308/23684223/96e0d92c-035a-11e7-92a4-7b078fdc9731.png)

**Comment by arouinfar** [comment]
As discussed in 4/13/17 design meeting, the Java sim contains the bug... not the HTML5 sim. 

This situation is still okay, because the inline current meters act as wires. 
![image](https://cloud.githubusercontent.com/assets/8419308/25024060/b60ab7f2-2059-11e7-8b87-9fd857c59b9c.png)

**Comment by phet-steele** [comment]
The issue linked immediately above is the reason for this corner case. Wires in this sim have some resistance, causing a voltage drop and current. Without including wires (the left), you do not promote current. Including wires (the right) adds resistance and a voltage drop to promote current. 

![parallel_batteries](https://cloud.githubusercontent.com/assets/8419308/23684154/16afd258-035a-11e7-9ddf-b7673b9a0529.gif)
