### ISSUE TITLE
User suggestion: Recalibrate electron speed for ampere

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#271]
Unfuddle Ticket [#3549](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3549?cycle=true)

>I use this simulation a lot. It really is a great one to learn about the difference between Voltage and current. When I explain the kids what an Ampere is I usually take a chronograph and point in a spot anywhere in the wire, let one of my pupils count 10 second and count the number of balls passing the point that I point at. It really happens to be so, that when I should count 1 Ampere then about 10 balls pass the point that I'm pointing at. It's a pity that it is not quite true.  I smuggle a bit and tell them that one ball represents 1 Coulomb of charge and so 6.24 x 10^(18) electrons. But it would really be great if it would fit perfectly.
Is it possible to do so in a next update of this simulation? I would greatly appreciate it.

The ampere is equivalent to 1 C/s. The user has made the assumption that each electron represents 1 C of charge. It sounds like the user builds a circuit that has a current of 1 amp, and then counts the number of electrons that pass a given point in 10 s. If each electron represents 1 C, then 10 electrons should pass in that time frame. I timed this in CCK: Prototype, and it takes ~8.5 seconds for 10 electrons to pass a given point in a circuit that has a current of 1 amp. 

I don't think the teacher has made a particularly bad assumption here. I would imagine other teachers may also want to use the sim to demonstrate the definition of an ampere. I certainly don't see it as a primary learning goal of the sim, but perhaps this is something we could accommodate.

**Comment by samreid** [comment]
Does it seem like speeding up all electrons by a factor of 10/8.5 would work?  That would be an easy change but we would want to make sure we test for it in RCs too to make sure it remains good.

If we really want to support this as an explicit learning goal, we may also want to introduce a stopwatch and play/pause/step buttons (perhaps in the lab screen?).  I think we will need some of these time controls in the AC CCK too.

**Comment by arouinfar** [comment]
> Does it seem like speeding up all electrons by a factor of 10/8.5 would work? That would be an easy change but we would want to make sure we test for it in RCs too to make sure it remains good.

Yes, I think so @samreid. I think this change is worth trying out. 

> If we really want to support this as an explicit learning goal, we may also want to introduce a stopwatch and play/pause/step buttons (perhaps in the lab screen?). I think we will need some of these time controls in the AC CCK too.

I'm not sure that its an explicit learning goal, but it might be nice to add a stopwatch to the lab screen. I don't think it's critical for 1.0, but perhaps this is something we can add in later on?

**Comment by samreid** [comment]
In the above comment, I revised the speed and am now reading 10 electrons in 10 seconds in a 1 amp circuit.  I'll post a new dev version for @arouinfar to test.

**Comment by samreid** [comment]
A new test shows about 11ish electrons in around 10 seconds.  @arouinfar here is a recent dev version:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.28/circuit-construction-kit-dc_en.html

Can you review and let me know your thoughts?

**Comment by arouinfar** [comment]
@samreid I find it much easier to time 10 electrons, than count the the number of electrons that pass in 10 seconds. I tested dev.37 and consistently timed 10 electrons in ~9.5 seconds. I think that's close enough, but if you wish to further tweak the electron timing, go for it.

**Comment by samreid** [comment]
That seems close enough to me, thanks!
