### ISSUE TITLE
Should electrons have a minus sign?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#272]
When discussing the conventional current with Mike, he noticed that the electrons have a minus sign on them. He was enthusiastic about the addition, but pointed out it deviates from the Java version.

Personally, I also like the minus sign. However, I imagine there's probably a good reason why the electrons in Java are plain blue spheres, but I don't believe we've ever had a discussion about the issue.

Any thoughts @ariel-phet @samreid @kathy-phet?

**Comment by samreid** [comment]
I am pro minus sign and don't recall any discussion about why it was specifically omitted previously.

**Comment by ariel-phet** [comment]
I am generally for the minus sign as well (seem consistent with other sims), but definitely we should leave the current arrows as just arrows.

**Comment by arouinfar** [comment]
Discussed 3/16/17. Everyone likes the minus sign, so we'll keep it.
