### ISSUE TITLE
Create schematic bulb

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#273]
In https://github.com/phetsims/circuit-construction-kit-dc/issues/18, we decided that a schematic bulb is desired for 1.0.

Design specs
* The schematic bulb will use the illuminating lamp symbol with two schematic wire leads. 
* In the toolbox, only the symbol will be shown (no wire leads). 
* The vertices and electron path will remain the same as the lifelike bulb. Once implemented, we will review the electron path to decide if it is "close enough" to keep as-is. If not, we may consider adjusting the path or removing the ability to view the current altogether.

Here's a mockup of the schematic bulb and a comparison with the updated bulb from #274. The schematic bulb wire leads are shifted slightly off-center from the vertices to maximize the overlap between the wire leads and the bulb's filament.
![image](https://cloud.githubusercontent.com/assets/8419308/24056468/74bbd7d2-0b09-11e7-919d-fdf53ed3ab62.png)

**Comment by samreid** [comment]
It would be good to touch base on this again before implementation work starts.  Is it really desirable that the wires not be centered in the vertices?  There will be a sizable gap between wires in that case.  What about keeping the same path as the filament of the light bulb, but drawing the circle across the top?  That way we could keep the path geometry the same.

**Comment by arouinfar** [comment]
For now, we'll keep the schematic bulb as-is. With the solder being layered on top, things should look fine, but we can make adjustments as necessary once implemented.

**Comment by samreid** [comment]
Would be best to do #274 first.

**Comment by samreid** [comment]
Perhaps it wouldn't be so bad to redo the circuit path, we could trigger a relayout of electrons on schematic/lifelike change and use the new path.  Then code both paths in LightBulb.js

**Comment by samreid** [comment]
I published a dev version: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.27/circuit-construction-kit-dc_en.html

This shows the schematic icon in the toolbox with no leads and shows a rough draft of the schematic light bulb in the play area, with the leads overlapping the electron paths.  The main question for this dev version is: should we spend time to update the electron paths?  It could take a half a day for initial implementation, then more time to refine, pass QA, etc.

**Comment by samreid** [comment]
After fixing #328 the code for this got simpler and the layout may have changed a bit.  I'll post a new version.

**Comment by samreid** [comment]
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.29/circuit-construction-kit-dc_en.html

@arouinfar can you take a look?

**Comment by samreid** [comment]
It looks like the height deviated, I'll post a fix for this.

**Comment by samreid** [comment]
Height is much better in this revision:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.36/circuit-construction-kit-dc_en.html

Also, after seeing this, I'm less concerned about the electron path because it kind of matches the curve of the schematic bulb.

**Comment by arouinfar** [comment]
@samreid looks good! I am not bothered by the electron path, so I don't think it's worth spending the time to adjust. That said, I think it'd be good to briefly review in the next design meeting to see what @ariel-phet and @kathy-phet think.

**Comment by samreid** [comment]
Today we decided the schematic light bulb view looks good enough.  I informed the team that it is a 4 hour estimate to change the path and we decided to leave it as-is since it seems good enough.

**Comment by phet-steele** [comment]
@samreid I'm going to reopen this issue for phetsims/QA/issues/33, and here is why:

In phetsims/circuit-construction-kit-dc/issues/104, we reduced the diameter of electrons. In a schematic lightbulb, here is a before and after for the size difference:

BEFORE
<img width="213" alt="screen shot 2017-07-28 at 2 04 48 pm" src="https://user-images.githubusercontent.com/5863899/29085415-796461c0-7c2c-11e7-9387-5881f9215434.png">

AFTER
<img width="174" alt="screen shot 2017-07-28 at 2 02 23 pm" src="https://user-images.githubusercontent.com/5863899/29085428-8420cd88-7c2c-11e7-9fab-9b81da03adb6.png">

You can see that after the change, the electron is now quite visibly not in contact with the bulb. Isn't this cause for concern? I remember a similar discussion where the paperclip artwork had to be changed since electrons were not always in contact along their path. To me, this is similar, and it certainly looks quite odd to have the electron floating outside of a component. A different path, while providing technical challenges I'm sure, would fix this bad representation.

> I informed the team that it is a 4 hour estimate to change the path and we decided to leave it as-is since it seems good enough.

@samreid is this time estimate still accurate? @ariel-phet @arouinfar @kathy-phet what do you think about the AFTER image? Is it worth changing?

**Comment by kathy-phet** [comment]
Wanting to hear from Sam on updated time estimate.

**Comment by arouinfar** [comment]
@samreid I'd also be curious for an updated time estimate. 

I'll point out that the conventional current looks a bit worse than the electrons:
![screen shot 2017-08-08 at 1 39 32 pm 2](https://user-images.githubusercontent.com/8419308/29091542-9019829c-7c40-11e7-90f5-0fd0d105ce4e.png)

**Comment by samreid** [comment]
Still probably around 4 hours, I'll take a closer look...

**Comment by samreid** [comment]
Rough draft is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.145/circuit-construction-kit-dc_en.html

It seems OK to me except for the fact that we chose the left leg of the schematic light bulb to be offset from the vertex, and the conventional current doesn't line up on it:

![image](https://user-images.githubusercontent.com/679486/29105232-bed9f560-7c88-11e7-9421-d4fdb2b17be4.png)

@phet-steele @arouinfar @kathy-phet can you please review and advise?

**Comment by kathy-phet** [comment]
I think that was just to help the alignment with electrons originally. I think we could alter the graphic now.

Kathy

Sent from my iPhone

On Aug 8, 2017, at 10:31 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Rough draft is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.145/circuit-construction-kit-dc_en.html

It seems OK to me except for the fact that we chose the left leg of the schematic light bulb to be offset from the vertex, and the conventional current doesn't line up on it:

[image]<https://user-images.githubusercontent.com/679486/29105232-bed9f560-7c88-11e7-9421-d4fdb2b17be4.png>

@phet-steele<https://github.com/phet-steele> @arouinfar<https://github.com/arouinfar> @kathy-phet<https://github.com/kathy-phet> can you please review and advise?

**Comment by arouinfar** [comment]
@samreid the updated path looks nice! 

The purpose of the schematic bulb's offset was to maximize the overlap with the lifelike bulb's current path, but now that the schematic bulb has its own current path, perhaps we could revert the offset.

**Comment by samreid** [comment]
After the commit above:
![image](https://user-images.githubusercontent.com/679486/29127699-10385414-7cdf-11e7-8ae2-fd39312dbbc0.png)

Dev version is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.148/circuit-construction-kit-dc_en.html

@arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks great @samreid!
