### ISSUE TITLE
Update bulb

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#274]
In https://github.com/phetsims/circuit-construction-kit-common/issues/238 we tweaked the bulb's design. The socket and glass are slightly wider, and the bottom vertex has been shifted a few pixels to the left to provide more padding between the vertices.

Updated design:
![image](https://cloud.githubusercontent.com/assets/8419308/24056619/217fa796-0b0a-11e7-930e-79503ae857e5.png)

I will email the updated asset files to @samreid.

**Comment by samreid** [comment]
I added the new artwork in the above commits.  Still need to move the vertices apart.

**Comment by samreid** [comment]
I'm going to work on the vertices issue in #326.  @arouinfar can you review the artwork in this dev version?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.25/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
