### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#276]
At times, the light rays do not contrast well against the light blue background. Java CCK does not suffer this same issue, so we should find a darker alternative.

Argenta reported:
> We had a question in our worksheet asking students to compare the brightness of the bulbs in the various circuits they'd built. Some students were confused about how they could compare brightness with the sim. That might because our activity before that had them measuring voltage and current, so they may have expected to be able to measure a numerical value for brightness, but I also noticed that it was a bit difficult to see the bulb rays on the computer screens they were using. So (for future iterations of the sim, Not for this study) could you make the background color a touch darker so the rays coming out of the bulbs are a little more obvious? On a related note, on the black box "test" screen, the bulb brightness becomes very difficult to see because of the lighter background. 

@kathy-phet replied
> I had noticed that the original sim had a much better contrast of background color to bulb brightness, and was going to suggest looking at that closely as we focus on details of the redesign. I thought it could be challenging on a projector. Looks like it is also a bit challenging on the regular screen. So we should add it to the list for closer examination. 

I've found a few alternative blues to try out for the background. It'd probably be easiest if @samreid could change the background color during a design meeting so we could review in realtime.

| Swatch | Hexcode |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/8419308/24114851/3872a52a-0d67-11e7-9594-9c3232036403.png) | 5b9aff |
| ![image](https://cloud.githubusercontent.com/assets/8419308/24114879/497bcd10-0d67-11e7-906b-de3980e247d0.png) | 7cafff |
| ![image](https://cloud.githubusercontent.com/assets/8419308/24114886/50cb3dda-0d67-11e7-993a-8cfc936fffc3.png) | 99c1ff |
| ![image](https://cloud.githubusercontent.com/assets/8419308/24114897/5814a676-0d67-11e7-8a93-0958be3baa9d.png) | b0cfff |

**Comment by arouinfar** [comment]
@samreid can you please publish a dev version with the background color of: 99c1ff

If we'd still like to play with the color, we can pursue the use of colorpicker.

**Comment by samreid** [comment]
@Denz1994 can you please investigate this one?  Are you set up for publishing dev versions?

**Comment by Denz1994** [comment]
Dev version released with "99c1ff" background color. Thanks for the help with the dev set up @samreid. Leaving open for review.
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.11/

**Comment by arouinfar** [comment]
👍
