### ISSUE TITLE
Putting wire resistance to 0 seemed to behave nicely, why???

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#282]
![image](https://cloud.githubusercontent.com/assets/679486/25024265/68e7de54-205a-11e7-8210-75212b2392db.png)

**Comment by samreid** [comment]
@Denz1994 looked into this and when the matrix system has more unknowns than independent equations, the QRDecomposition basically gives you garbage.  In this case, maybe we got lucky so that it seems somewhat correct but we cannot rely on this as a solution.

One day it would be nice to investigate how to deal with zeroes in the solution.  Maybe this would be a great thing for our new Electrical Engineer to consult on?  @ariel-phet can you put us in contact with him?

**Comment by ariel-phet** [comment]
@samreid - will do once I have a CLA from him and add to the team

**Comment by samreid** [comment]
One proposed solution for dealing with 0-resistance loops was proposed in #284, but it is unclear whether we want to implement it.  Marking as priority deferred.

**Comment by samreid** [comment]
Since we decided to always have some wire resistance, this issue is moot. Closing.
