### ISSUE TITLE
How to make room for battery resistance panel?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#286]
In https://github.com/phetsims/circuit-construction-kit-dc/issues/36#issuecomment-294631817 @Denz1994 noticed that with our pre-existing panel sizes there is not enough room for the battery resistance panel (it overlaps with the reset all button).  I'm not sure whether we are adding other controls to the right-side of the screen or not.

@arouinfar can you please advise on whether more controls are on the way, and recommend a solution for getting everything to fit in the layout?

**Comment by samreid** [comment]
It looks like the mock-up was updated 4 days ago, it will probably work.  @Denz1994 can you use it as a guide for adjusting the sizes of things?  The work of making sure all the panels have the same width is a different problem and will be handled separately, but you could work on getting the basic dimensions correct (especially for height).

![image](https://cloud.githubusercontent.com/assets/679486/25141406/b10c0182-2420-11e7-8e91-3e4dbff1e389.png)

**Comment by arouinfar** [comment]
Thanks @samreid, looks like you beat me to it! Here's a mockup with the panels open:

![image](https://cloud.githubusercontent.com/assets/8419308/25141422/bfff5d42-2420-11e7-95a4-6bc1be6cad6c.png)

**Comment by Denz1994** [comment]
This looks good. I will begin working on this.

**Comment by arouinfar** [comment]
@Denz1994 the toolbox is a bit narrower now, which also frees up space for the other panels. Here's the latest mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/26129107/265a50a6-3a4c-11e7-9f41-9cab610a380e.png)

During the last design meeting, we also decided to use 'ohms' rather than the omega symbol in the battery resistance readout.

**Comment by samreid** [comment]
@Denz1994 can you please put the word "ohms" (internationalized) in the battery resistance control instead of the ohm symbol?

**Comment by Denz1994** [comment]
Layout adjustments were made as suggested such as reducing the padding margins to make room for the resetAllButton. A dev version was published for review @arouinfar. http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.19/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
@Denz1994 the panel spacing looks great! I think the scene selection buttons should be moved below the Battery Resistance panel, but perhaps that should be tracked elsewhere?

**Comment by samreid** [comment]
Thanks @arouinfar, we'll close this issue and move your preceding comment to a new or pre-existing issue.
