### ISSUE TITLE
Implement "show values"

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#289]
From the design doc, it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/25197509/922d638c-2501-11e7-87d3-6e113c0d1df4.png)

**Comment by samreid** [comment]
@arouinfar do you want this text always upside-up (recommended) or to rotate with the component?  Should the text always be the same distance from the center of the component, and always directly above it?

**Comment by arouinfar** [comment]
@samreid the text should always be upside-up. As for the label location, I'm not sure. The Java approach seems to work well. What would you recommend @samreid?
![image](https://cloud.githubusercontent.com/assets/8419308/25352542/9e3a24e4-28e9-11e7-98c3-c8a672ace8d8.png)

**Comment by samreid** [comment]
I'm also wondering about the z-ordering. Should these be in front of all components, in front of the light bulb brightness lines, in front of control panels, behind the focus rectangle?

**Comment by samreid** [comment]
Maybe for future design docs it would be good for the design team to create a "z-order" document?

**Comment by samreid** [comment]
Should the values zoom in and out?  With current implementation, they will be in the circuit layer between circuit elements and highlights, and will zoom in and out.

**Comment by samreid** [comment]
Rough draft is published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.16/circuit-construction-kit-dc_en.html

I chose to have these zoom in and out with the zoom level so they don't move or scale relative to the circuit elements (and obscure elements on zoom on). I tried to choose a size that will look good at either zoom level.  I'm applying a rule that always has it over the "north" of the circuit element, so if the circuit element is upside down, the label would be beneath.  For the light bulb, this is nice so the label is always closest to top of the light bulb.  There are opportunities for the labels to overlap, but perhaps users will position the components so it is not too problematic?

@arouinfar can you please take a look and let me know your thoughts?

**Comment by samreid** [comment]
I also suppressed the internal resistance readout of the battery if it is 0, so it won't be confusing on the first 2 screens where it is always 0.

**Comment by arouinfar** [comment]
We discussed the label appearance in the meeting notes from [5/11/17](https://docs.google.com/document/d/1l9ABgqq4zgsU0f3nW4naylJ9fXGkX4RhBcLNrg0lsLE/edit#heading=h.xzy9uukwh9fl) and @samreid did some real-time pixel polishing. I've reviewed the labels in dev.18, and I think they look great! However, the label should be centered over the light bulb.
![image](https://cloud.githubusercontent.com/assets/8419308/26129378/3003bee8-3a4d-11e7-9b24-cc080cc4dc34.png)

**Comment by samreid** [comment]
Thanks @arouinfar, I'll close this issue and create a new issue for centering the label over the bulb.
