### ISSUE TITLE
Show more precision in ammeter readout?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#290]
From https://github.com/phetsims/circuit-construction-kit-dc/issues/27#issuecomment-287448467

Another user has requested we add an additional decimal place to the current meter readout.

Unfuddle ticket [#3728](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3728?cycle=true)
> I want to use “Circuit contraction kit AC / DC” as a formal program for the lab But I find two problems before satisfying that
we using a little voltage as 12 v to avoid electric shock .. then the current will be in mill amp . The Ammeter is not sufficient sensitive for this, for example the current is 0.012 amp -> 12 m A the ammeter read 0.01 amp .

**Comment by arouinfar** [comment]
@samreid I think a 3rd decimal place would be a reasonable addition to the current meters.

**Comment by samreid** [comment]
We decided to go for it.

**Comment by samreid** [comment]
@arouinfar let's discuss this further before making a change.  In the present version of CCK DC, with a 12 volt battery the lowest current you can get is 0.12 amps, which doesn't require a 3rd digit.  Later when we add higher resistance components in https://github.com/phetsims/circuit-construction-kit-dc/issues/29 or the grab bag, this could become an issue, but perhaps we should wait until we have developed those higher resistance components before changing the ammeter readout (so we can make sure it behaves as desired).

**Comment by arouinfar** [comment]
@samreid let's defer the third decimal until we have high R components. I imagine that 3 decimals will give us enough precision, but  we can look at it more carefully when the time comes.

**Comment by samreid** [comment]
On hold until we have high R components.

**Comment by arouinfar** [comment]
@samreid I'm sure this is already on your radar, but we'll definitely need to add a third decimal to both ammeters, otherwise it's pretty easy to run into situations where the ammeter reads 0.00 A, but the light bulb is lit. Even after adding a 3rd digit, it will be possible to have a lit bulb with 0.000 A displayed, but this will only occur for V<5 (which seems more reasonable).

![image](https://user-images.githubusercontent.com/8419308/26940138-d05d1e5c-4c36-11e7-9d21-c2591abb0f26.png)

**Comment by samreid** [comment]
Thanks @arouinfar, I'll look into it.

**Comment by samreid** [comment]
I've added another decimal place for both ammeters (but not the voltmeter), it will look like this after commit:

![image](https://user-images.githubusercontent.com/679486/27057040-99fcf28e-4f87-11e7-938f-6d57e305231b.png)

**Comment by samreid** [comment]
Commit is above and dev version is here for review:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.65/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
