### ISSUE TITLE
In schematic mode, solder should always be on top

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#291]
Easier to imagine the connections and helps in visually segmenting different components.  Discussed in https://github.com/phetsims/circuit-construction-kit-common/issues/273

**Comment by samreid** [comment]
Proposed implementation is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.41/circuit-construction-kit-dc_en.html

@arouinfar can you take it for a test drive?

**Comment by arouinfar** [comment]
@samreid something's not quite right. In dev.37, the solder laying is the same in the lifelike and schematic views.
![image](https://cloud.githubusercontent.com/assets/8419308/26436938/fc521b98-40ce-11e7-871d-7613a35a5704.png)

**Comment by samreid** [comment]
Did you test dev.37?  The proposed fix for this is in dev.41, linked above.

![image](https://cloud.githubusercontent.com/assets/679486/26437090/3ea2febe-40d8-11e7-95dc-2980fcd20aff.png)

**Comment by arouinfar** [comment]
Ah, my bad @samreid. For some reason I was thinking dev.37 was the latest. Things look good in dev.41!
