### ISSUE TITLE
Button should be over the focus highlight maybe?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#292]
In #257 @phet-steele said:

> Although, I think it would be slightly more aesthetically pleasing if the button was layered over the yellow ring, no?

<img width="167" alt="screen shot 2017-03-22 at 10 26 10 am" src="https://cloud.githubusercontent.com/assets/5863899/24208795/24727710-0eea-11e7-9a1f-b04fc7046c6d.png">

I replied:

> If I understand correctly, the default implementation for accessibility has the focus regions on top of everything else.  We have the opportunity to override this on a case-by-case-basis, but I'm not sure whether it will be worth the effort.  I may know more after finishing #114

**Comment by jessegreenberg** [comment]
Does the button need to be so close to the connection point?  Could it be totally outside the radius of the focus highlight?

**Comment by samreid** [comment]
Normally it is much further away:
![image](https://cloud.githubusercontent.com/assets/679486/25763478/95e74b7c-31a0-11e7-93c1-c5849cdf7b92.png)

There is only an overlap when close to the edge of the screen (since the button is constrained to lie in the visible bounds)

![image](https://cloud.githubusercontent.com/assets/679486/25763506/b2fb9f74-31a0-11e7-8828-943ad7e09aec.png)

@arouinfar is this behavior OK for 1.0?

**Comment by arouinfar** [comment]
Seems reasonable to me @samreid.
