### ISSUE TITLE
test performance for opacity on iPad

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#293]
@ariel-phet pointed out that having transparent electrons/arrows may have a performance impact.  I'll take a look.

**Comment by samreid** [comment]
dragging a single battery with transparency: 19fps
dragging a single battery fully opaque: 19fps
dragging a single battery charge opaque: 19fps

battery+wire+resistor with transparency: 20fps
battery+wire+resistor full opaque: 30fps
battery+wire+resistor charge opaque: 29fps

So it seems for animating the charges, it costs us 10 frames per second.  This will need further investigation.

**Comment by samreid** [comment]
@jonathanolson suggested to try `setImageOpacity`.  That showed 19fps dragging and 29fps animating.  Just as good as the opaque solution.  (This will eliminate opacity for conventional current, but at yesterday's meeting that seemed it would be fine.) I'll commit that.

**Comment by samreid** [comment]
Published a dev version here as described above.  @arouinfar can you check that the electron and arrow opacity are good to go?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.15/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks good @samreid!
