### ISSUE TITLE
Voltmeter probes read when not touching

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#294]
Since the voltmeter reads out values when the probes are in the dotted circle, you can create cases like this where the probes are too far away from the terminals to conduct, yet still show a value:

![image](https://cloud.githubusercontent.com/assets/679486/25548502/eccfe3a8-2c29-11e7-96f0-c536405c92a5.png)

Is this acceptable?  If not, how should we change it?

**Comment by arouinfar** [comment]
@samreid I do not think this is desirable behavior, as the probe tips are clearly not touching anything conductive. Perhaps the logic could be more like this:
* When a component is disconnected, the probe tips must be in the half of the vertex closest to the component. These would both be acceptable:
![image](https://cloud.githubusercontent.com/assets/8419308/25589359/88266822-2e69-11e7-8d94-f200fb31d9b4.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/25589459/f3a5e9d8-2e69-11e7-9c76-0c2e2feb77cd.png)
* When connected to another component, the probe tips can read anywhere within the vertex.
<img width="357" alt="screen shot 2017-05-01 at 12 34 40 pm" src="https://cloud.githubusercontent.com/assets/8419308/25589638/9a433732-2e6a-11e7-98e2-c81ae9e5ea12.png">

I realize that the probe locations in these screenshots would not produce readings in real life, but for usability, I think we'll need to allow a bit of wiggle room.

**Comment by samreid** [comment]
Do you want to "snap" the probes to the conductive areas?  Do you think it is likely that a student will get a misreading by being outside of the conductive area?

**Comment by arouinfar** [comment]
Discussed in 5/4/17 design meeting. In Java, the probes read anywhere within the vertex, so the HTML5 behavior is consistent. We have not received complaints about this over the years, so we've decided to keep things as they are. I will make a note of this behavior in the Teacher Tips.

A "snap" feature may be something we consider in the future, but it is not necessary for 1.0.

**Comment by arouinfar** [comment]
Tracking the teacher tips in https://github.com/phetsims/circuit-construction-kit-dc/issues/41, so unassigning myself.

**Comment by samreid** [comment]
According to the above discussion, there is nothing left to do for this issue.  I'll open a side issue for "snap" in case we want to pursue that.
