### ISSUE TITLE
voltmeter probes should read 0.0 when touching each other

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#296]
Cross-assigned to @arouinfar to double check that this is worth spending time on.

**Comment by arouinfar** [comment]
@samreid, technically the probes should read 0 V when touching, but I'm not sure if it's worth sinking a lot of time into. We can talk about it at design meeting.

**Comment by arouinfar** [comment]
@samreid do you have a rough estimate of how much time this would take?

**Comment by samreid** [comment]
I'm guessing the up-front work to detect collisions between the probes would be 2-4 hours.  Then there would be the (small) recurring cost of this as a feature to maintain and support.

**Comment by samreid** [comment]
At design meeting today, we decided this is not necessary for 1.0 and we can consider it for future versions.

**Comment by phet-steele** [comment]
Feel I should point out that https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.1/capacitor-lab-basics_en.html has this behaviour, and it's not even to RC yet! 😝

**Comment by arouinfar** [comment]
@samreid is this something that can be cherry-picked from CLB relatively easily, or does your estimate of 2-4 hours up-front still hold?

**Comment by phet-steele** [comment]
@samreid this is in [Voltmeter.js](https://github.com/phetsims/capacitor-lab-basics/blob/master/js/common/model/meter/Voltmeter.js)

```js
/**
     * Probes are touching if their tips intersect.
     * @public
     *
     * @returns {boolean}
     */
    probesAreTouching: function() {
      var posShape = this.shapeCreator.getPositiveProbeTipShape();
      var negShape = this.shapeCreator.getNegativeProbeTipShape();

      return posShape.bounds.intersectsBounds( negShape.bounds ) &&
             posShape.shapeIntersection( negShape ).getNonoverlappingArea() > 0;
    },
```

**Comment by samreid** [comment]
Fixed and I'll push it to rc.3

**Comment by samreid** [comment]
Published at https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.3/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks great!
