### ISSUE TITLE
Meters shouldn't move on zoom in

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#302]
@Denz1994 showed that during zoom in the meter locations change. It could be confusing to automatically change the position without the user directing it.  We should make the probe keep the location independent of zoom.  If the user loses a meter, they would have to zoom back out to get it.

**Comment by samreid** [comment]
@arouinfar if you zoom out then place a voltmeter at the edge of the screen then zoom in, the voltmeter translates along the visible edge of the sim.  @Denz1994 and I think this is problematic because it could mess up user readings and change the "physical" state by just changing the zoom level.  It makes sense that the user would have to zoom back out to get back the voltmeter. 
 However, if you rotate an iPad or change a browser window size, you could lose the voltmeter.  Would the user have to rotate the iPad back (or resize the browser) to get the voltmeter back?  Should we put an icon or button "return voltmeter" if we detect it is out of range?  Should we do the same for circuit elements?  We don't want the user to be able to drag the voltmeter out of bounds (or do we/especially if there is a return voltmeter button), but right now that is tangled up with the behavior of automatically keeping it onscreen during zoom or browser reshape.  Can you please advise?

**Comment by arouinfar** [comment]
@samreid it seems like there are two cases of losing things off-screen.

1) The circuit is built outside of dev, and window is resized. The circuit jumps back into the play area (this could use some polishing), and the meter scoots with the edge of the window. I think portrait > landscape iPad rotation would likely behave the same.
<img width="353" alt="screen shot 2017-06-01 at 10 24 52 am" src="https://cloud.githubusercontent.com/assets/8419308/26689922/ad471c24-46b4-11e7-984e-55021b9c5896.png">
<img src="https://cloud.githubusercontent.com/assets/8419308/26689924/b0cc25b0-46b4-11e7-85cf-04b4dfa4e212.png">

2) The play area is zoomed out, and a circuit is built in the corner of screen. After zooming back in, the circuit is off-screen, but the meter has moved to the edge of the play area.
<img width="244" alt="screen shot 2017-06-01 at 10 47 06 am" src="https://cloud.githubusercontent.com/assets/8419308/26690751/baacfa84-46b7-11e7-903d-d15033f23c46.png"> <img width="271" alt="screen shot 2017-06-01 at 10 46 52 am" src="https://cloud.githubusercontent.com/assets/8419308/26690752/baad3c88-46b7-11e7-83f0-ba4c071a9a3e.png">

I think we can continue to handle these cases separately, but it would make sense for the meters to remain with the circuit in case 2.  We may want to consider a Return button for the meter(s), but it may not be necessary.

**Comment by samreid** [comment]
I moved (1) to #365 and we can continue (2) in this issue.

**Comment by samreid** [comment]
This seems more closely related to #365 than I thought (due to zoom), let's discuss #365 and this at an upcoming design meeting.

**Comment by arouinfar** [comment]
Discussed in 6/15/17 design meeting. It should not be possible to lose circuit components off-screen. When zooming in, the circuit should move into the play area. The meter behavior is fine as is.

**Comment by samreid** [comment]
It sounds like meters are behaving nicely.  We'll address other objects in https://github.com/phetsims/circuit-construction-kit-common/issues/365
