### ISSUE TITLE
Use Panel for the text background in Battery Resistance Control

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#305]
In https://github.com/phetsims/circuit-construction-kit-dc/issues/36 @Denz1994 has been developing the battery resistance control.  I noticed that the panel dimensions are hard-coded and do not update when the text gets longer.  To solve these problems, it would be best to use sun.Panel instead of a Rectangle.  The component looks like this at the moment (notice ohms runs off the side):

![image](https://cloud.githubusercontent.com/assets/679486/25769911/6d147dc6-31e3-11e7-8579-cded2389b023.png)

The code is:

```js
      // background for displaying the value
      var backgroundNode = new Rectangle( 0, 0, 60, 20, 2, 2, {
        fill: 'white',
        stroke: 'black',
        lineWidth: 1,
        tandem: backgroundNodesGroupTandem.createNextTandem()
      } );
      numberNode.center = backgroundNode.center;
      var valueParent = new Node( {
        children: [ backgroundNode, numberNode ],
        tandem: valueParentsGroupTandem.createNextTandem()
      } );
```

And instead of valueParent and backgroundNode, one Panel should suffice (leaving resize: true as the default will allow it to update size when necessary)

**Comment by Denz1994** [comment]
Reassigning for review.

**Comment by samreid** [comment]
I made a few aesthetic improvements in the preceding commit, everything else looks great! I moved a new issue to #316 and this one is good to close, thanks @Denz1994
