### ISSUE TITLE
Implement battery internal resistance

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#306]
We need to model the battery as having a series resistor for its internal resistance.

**Comment by samreid** [comment]
Implemented above, tested simple cases and it is working well.

**Comment by samreid** [comment]
@arouinfar can you test this in the latest dev version and make sure all is well?

**Comment by arouinfar** [comment]
@samreid things seems to be working nicely in dev.18. My only suggestion would be to make the slider snap to the tick marks. I believe we had discussed allowing the battery resistance to be whole numbers [0, 10], as there doesn't seem to be much pedagogical advantage to allow a resistance such as 6.2 ohms, for example.

**Comment by samreid** [comment]
@Denz1994 can you make the battery resistance slider snap to the tick marks?

**Comment by Denz1994** [comment]
Assigning to @samreid for review. The snapping action was added to the slider.

**Comment by samreid** [comment]
Looks great, nice work @Denz1994, closing.
