### ISSUE TITLE
Hit regions are wrong for schematic

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#310]
Mouse areas seem wrong, like they only go halfway.

**Comment by samreid** [comment]
Here's a pic:

![image](https://cloud.githubusercontent.com/assets/679486/26022167/f3c0d0d2-375a-11e7-8772-91c820300a9b.png)

**Comment by samreid** [comment]
Fixed above.  As I described in the comments I am not sure why using the shape bounds worked but the path bounds did not.  @jonathanolson can you take a look?

**Comment by samreid** [comment]
Here is a pic of using the shape (instead of path) for the bounds:

![image](https://cloud.githubusercontent.com/assets/679486/26022198/9c1bcbd8-375b-11e7-9d9a-d05839b0b24f.png)

**Comment by jonathanolson** [comment]
This looks like it's caused because node.bounds gives you a reference to the Bounds2 that Node mutates when its bounds change (which shouldn't get passed directly to mouseArea/touchArea).

It doesn't look like we discussed adding defensive copies to bounds getters in https://github.com/phetsims/scenery/issues/117, maybe that should be brought up. Thoughts?

**Comment by jonathanolson** [comment]
(I've been writing code assuming that a node's bounds access is immutable, so I have a preference for a potential defensive copy).

**Comment by samreid** [comment]
From a API & maintainability standpoint, it seems like a copy of the bounds is what clients probably expect.  However, I'm not sure how damaging that would be to performance or garbage collection.  So I'm not sure how to proceed, given that there are currently no known problems caused by this.  (I wonder if adding defensive copying would lead to double copies in some places like https://github.com/phetsims/circuit-construction-kit-common/commit/2ad4903c378a23ce0d7884ee6315b895ae84cba7 ?)

**Comment by samreid** [comment]
In any case, CCK is all set and I'll move this issue to scenery.

**Comment by samreid** [comment]
New issue is above, closing.
