### ISSUE TITLE
Factor out accordion box for battery and wire resistivity

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#312]
It may be useful to factor out options for the accordion box for these two panels. A parent class would be ideal for both ``` WireResistivityControl.js and BatteryResistanceControl.js```.

**Comment by Denz1994** [comment]
Parent class created and both controls are inheriting from this new class. Assigning to @samreid for review.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
