### ISSUE TITLE
SwitchNode should have curves and overlap in lifelike mode

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#313]
From https://github.com/phetsims/circuit-construction-kit-common/issues/88#issuecomment-302258137

The switch node should have curved edges and overlap like this:

![image](https://cloud.githubusercontent.com/assets/679486/26180229/7e3d3b10-3b25-11e7-93e8-81bbfa37e5f5.png)

The 2nd and 3rd segments of the switch should be created with Shape.lineTo, and something like ellipticalArcPoint, etc.  The schematic and lifelike will probably need to be separated (currently rendered with same function).

@Denz1994 is this something you can tackle?  Should take a couple of hours and only requires work in 1-2 files.

**Comment by samreid** [comment]
I'm thinking of looking into this, @Denz1994 please make a comment if you start on it so we don't collide.

**Comment by samreid** [comment]
Implemented and deployed here for testing:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.21/circuit-construction-kit-dc_en.html

Note that I adjusted some of the dimensions so that the electrons wouldn't appear over the notches and to look better in context (in my opinion).  @arouinfar can you please review the notches?

**Comment by arouinfar** [comment]
Love the lock-and-key mechanism! Thanks @samreid.

> Note that I adjusted some of the dimensions so that the electrons wouldn't appear over the notches and to look better in context (in my opinion). 

Good call @samreid. The electron spacing looks great!
