### ISSUE TITLE
Battery resistance control should say "1 ohm" instead of "1 ohms"

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#316]
In #305, we worked on the battery resistance control but not it shows "1 ohm" which is incorrect.  Can you change it so when there is only 1 ohm, it says "1 ohm" instead of "1 ohms".  @Denz1994 can you take a look?

![image](https://cloud.githubusercontent.com/assets/679486/26181434/42dc7c86-3b2d-11e7-90bb-1c69c28ad731.png)

**Comment by Denz1994** [comment]
The label is pluralized depending on resistance values. Assigning to @samreid for review.

**Comment by samreid** [comment]
Looks great, thanks! Closing.

**Comment by samreid** [comment]
From @jonathanolson review:

> This looks like it's trying to i18nize values. Note that languages like Slovenian have a special case for the quantity of 2. I'd either recommend NOT doing the separation here in two strings, OR handle all of the cases needed (looking up all cases for all common languages). May be worth an issue to track discussion.

My understanding is that English seems to be one of the most common languages for PhET launches at the moment, and it personally bothers me to see any software with bad plurals (like 1 ohms or 1 volts).  This could also be confusing to students who are seeing the word "ohm" for the first time.  So my recommendation is to fix this for English and defer fixing other languages until we have >=1 report from that language user.

@arouinfar, @ariel-phet or @kathy-phet can you please review @jonathanolson and my discussion in this comment and make a recommendation?

**Comment by jonathanolson** [comment]
@pixelzoom also has a lot of i18n experience, I'd like his opinion too.

**Comment by pixelzoom** [comment]
More annoying than "bad plurals" is software that trys the solve the problem and creates other problems. Like the way the value field in the Battery Resistance control resizes for "1 ohms".  And the way it's now inconsistent with the resistance control on the first screen, which still shows "1.0 ohms".  That said...

I don't have a problem with "1 ohms".   If it really bothers you, avoid the issue entirely and use the symbol, i.e. "1 Ω".   And I certainly don't think we should be attempting to address languages that have special cases for other plural values (e.g. Slovenia's '2' that @jonathanolson mentioned above).

**Comment by pixelzoom** [comment]
Here's more information on the can of worms that your opening here: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

Even '0' may treated differently depending on locale.  So while '0 ohms' is what you'd prefer for English, it's not what's appropriate for the French user.

**Comment by arouinfar** [comment]
I tried finding examples of spelled-out units in sims to see how singular/plural was handled, and couldn't find an example of a string that changed with the value.

When most values are > 1, the string is always plural, as with the Force slider in FAMB or Rate spinners in Unit Rates.
![image](https://user-images.githubusercontent.com/8419308/29843364-f612e776-8cc8-11e7-877b-c8dfc8e1011f.png) ![image](https://user-images.githubusercontent.com/8419308/29843746-382d99de-8cca-11e7-924e-b411cd1a38bc.png)

In Resistance in a Wire, the resistance readout always uses the singular "ohm", but many of the possible values are < 1. Decimals are a bit strange, though. I could say "point five ohms" or "half an ohm" so I suppose either would work.

![image](https://user-images.githubusercontent.com/8419308/29843633-cdae9360-8cc9-11e7-9b7b-9ea0f2edb087.png)

Given the issues described by @pixelzoom, I'm not in favor of keeping both "ohm" and "ohms".  The sim abbreviates the units elsewhere, so I'd be favor of ditching "ohm"/"ohms" for "Ω" for consistency. I know we try to spell units out for younger students, when possible,  but Battery Resistance is a more advanced feature so "Ω" seems perfectly reasonable to me.  Plus, it eliminates the issue of "bad plurals" entirely.
![image](https://user-images.githubusercontent.com/8419308/29844205-b6ad62f2-8ccb-11e7-976f-1679a3119aeb.png)

**Comment by ariel-phet** [comment]
@samreid strongly agree with @arouinfar 

1. Battery resistance is an advanced concept, no need to speed it out
2. We use the ohm symbol in the sim already
3. avoids plurals
4. in many readouts (like projectile motion) we use the abbreviations

Lets just use the symbol `Ω`

**Comment by kathy-phet** [comment]
I agree with just using the abbreviation in the battery resistance if it bothers people. But it is a trade off with consistency of controls in the first screen. 

I do want to keep ohms spelled out on the first screen ... e.g. on the bulb control. I think for that control just using "ohms" and not worrying about the special case of 1.0 is fine .... doesn't bother me. 

![image](https://user-images.githubusercontent.com/5096804/29845269-68287ef6-8ccf-11e7-9ed1-aac94d58d8d6.png)

**Comment by samreid** [comment]
> More annoying than "bad plurals" is software that tries to solve the problem and creates other problems. Like the way the value field in the Battery Resistance control resizes for "1 ohms". And the way it's now inconsistent with the resistance control on the first screen, which still shows "1.0 ohms". 

I agree, I'd only want to solve this problem in a consistent way and without creating worse problems.

> I don't have a problem with "1 ohms".

Do you mean that you don't think it's a pedagogical problem for students learning how to use the term "ohms" properly?

> avoid the issue entirely and use the symbol, i.e. "1 Ω".

What if one of the learning goals is to learn how to pronounce Ω?  Also, can we use this same strategy for "1 volts", so it would become "1 V"?  But what if we want students to learn the word volt?

> Here's more information on the can of worms that you're opening here: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

That's pretty intense and I can tell it would be a lot of work to do this right.

> I tried finding examples of spelled-out units in sims to see how singular/plural was handled, and couldn't find an example of a string that changed with the value.

I agree, this is an issue across our sims.

Based on @kathy-phet remarks I'll switch it to "1 ohms" and "1 volts" but I'm not convinced that it's not a pedagogical problem for students.

**Comment by ariel-phet** [comment]
@samreid @kathy-phet frankly in this sim I would go for all symbols for those quantities, that is my personal opinion. Especially for something like for the resistance of an object we label the slider "Resistance"

To me it is not a learning goal in general of most sims to teach vocabulary, but concepts. The key thing is that the student can change the resistance slider and see how resistance changes the circuit. The symbol used is somewhat irrelevant in that a young student can likely accept it is some sort of unit, even if they don't know it is called "ohms"

Again, especially because things are clearly labeled. The volt meter says "voltage" the ammeter is labelled "current" etc, I just don't think the units are problematic all being symbolic abbreviations.

**Comment by ariel-phet** [comment]
And...I would point out we often refer to a "9 volt battery" we don't say a "9 volts battery" 

So yet another strange case....

**Comment by kathy-phet** [comment]
While we do label voltage and current. It's the only place we use the term ohms.

I personally think it makes it a more flexible sim to use the term, and we know it is used with much younger grades.

I don't have any issue with using the symbol in the battery resistance control which looks a bit different anyways.
K


Sent from my iPhone

On Aug 29, 2017, at 5:07 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@samreid<https://github.com/samreid> @kathy-phet<https://github.com/kathy-phet> frankly in this sim I would go for all symbols for those quantities, that is my personal opinion. Especially for something like for the resistance of an object we label the slider "Resistance"

To me it is not a learning goal in general of most sims to teach vocabulary, but concepts. The key thing is that the student can change the resistance slider and see how resistance changes the circuit. The symbol used is somewhat irrelevant in that a young student can likely accept it is some sort of unit, even if they don't know it is called "ohms"

Again, especially because things are clearly labeled. The volt meter says "voltage" the ammeter is labelled "current" etc, I just don't think the units are problematic all being symbolic abbreviations.

**Comment by samreid** [comment]
It was unclear if we had a consensus.  In the preceding commit, I removed the switching between "ohm" and "ohms" in the battery internal resistance slider--now it always says "ohms".  I started with this to keep consistency between this resistance and the play area resistances like so:

![image](https://user-images.githubusercontent.com/679486/29854135-40cd076e-8d01-11e7-8116-f3a36805c697.png)

Some options to proceed:
1. Leave it as it is now (ohms for resistors and ohms in the battery resistance)
2. Add a decimal point (tenths place) to the battery resistance readout--this would unify it with the resistor readout and I think it makes 1.0 ohms linguistically correct.  (Googling for "1.0 singular or plural" seems to confirm this).
3. Any of the other options suggested in this thread.

**Comment by samreid** [comment]
I decided to proceed with (2) from the preceding comment, now it looks like so:
![image](https://user-images.githubusercontent.com/679486/29854337-8829aa26-8d02-11e7-9fd6-47dee800794a.png)

I know this doesn't answer the general case in other sims where we may omit the ".0" but it seems reasonable for this sim.  I'm flexible if changes are desired, I just wanted to jot down my "best guess" for now, reassigned to members of the CCK design team for feedback.

**Comment by kathy-phet** [comment]
I like this solution. @arouinfar @ariel-phet ?

**Comment by ariel-phet** [comment]
That works for me as we would probably say "one point zero ohms"

**Comment by arouinfar** [comment]
Works for me too @samreid! I think you'll need to widen the Battery Resistance readout a bit so it doesn't resize at 10.0 ohms, but otherwise looks good.

**Comment by samreid** [comment]
Thanks, I'll address the widening issue in #396
