### ISSUE TITLE
The switch should have a gradient

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#318]
From https://github.com/phetsims/circuit-construction-kit-common/issues/88#issuecomment-302496175

@arouinfar said:

> I find that the flat appearance of the switch looks a bit odd compared to the other components. @samreid can you apply a slight gradient to the switch?

@arouinfar are you thinking something similar to the wires?

**Comment by samreid** [comment]
I implemented a subtle gradient like this:

![image](https://cloud.githubusercontent.com/assets/679486/26289350/9171a970-3e5c-11e7-8b81-1b0ce5ca1001.png)

@arouinfar does this look OK?

**Comment by arouinfar** [comment]
@samreid the gradient looks great!
