### ISSUE TITLE
z-ordering for the switch

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#319]
In https://github.com/phetsims/circuit-construction-kit-common/issues/88#issuecomment-302496175

@arouinfar said:

> I'm also not sure if the switch should be layered above or below the solder. I think it would look better if layered below, but I know the current logic is that fixed-width components are layered above the solder.

Here's how it currently looks:
![image](https://cloud.githubusercontent.com/assets/679486/26221182/dbb16cb4-3bd2-11e7-8a6e-86c4e588171f.png)

I'm not sure how difficult it would be to change the layering for this, and also not sure what would look best.  Want to create a mock-up and we can take a look?

**Comment by arouinfar** [comment]
@samreid here's what it would look like if the switch is layered beneath the solder:
![image](https://cloud.githubusercontent.com/assets/8419308/26436691/1b54e310-40cd-11e7-879b-1c25d5aa88dc.png)

Personally, I prefer this layering. Any thoughts @samreid?

**Comment by samreid** [comment]
It seems OK to me (I don't feel too strongly one way or the other) but am concerned that the layering code is getting complicated.  @Denz1994 and I can surely give it a try though!

**Comment by arouinfar** [comment]
@samreid @Denz1994 please look into re-ordering the solder layering, but if things look like they'll be unnecessarily complicated, please feel free to shoot down this request.

**Comment by samreid** [comment]
If the solder is always in front of switches, I'm concerned that cases like this may look odd or asymmetrical:

![image](https://cloud.githubusercontent.com/assets/679486/26467804/5622c83e-4151-11e7-84af-54870a15e609.png)

Just wanted to check before @Denz1994 and I investigate further.  @arouinfar what do you think?

**Comment by samreid** [comment]
@Denz1994 said it may look better if the switch edges were rounded out instead of square.

**Comment by arouinfar** [comment]
> If the solder is always in front of switches, I'm concerned that cases like this may look odd or asymmetrical:

Good point @samreid.  For now, let's not worry about re-layering the solder.

I like @Denz1994 suggestion to round the corners on the switch edge. Can you try that, and then I can review again?

**Comment by samreid** [comment]
OK I created a new issue "Round the corners of the switch" and will close this one.

**Comment by phet-steele** [comment]
@arouinfar @samreid I'm confused about the argument in https://github.com/phetsims/circuit-construction-kit-common/issues/319#issuecomment-304106489 and how that would not look good if the solder were layered on top. Frankly, the mock-ups in https://github.com/phetsims/circuit-construction-kit-common/issues/319#issuecomment-303923661 look amaaaaaazing! We should do this!

**Comment by arouinfar** [comment]
I made a rough mockup of what it would look like to stagger the solder in @samreid's screenshot in https://github.com/phetsims/circuit-construction-kit-common/issues/319#issuecomment-304106489

![image](https://user-images.githubusercontent.com/8419308/28434663-5e9a9b04-6d4d-11e7-8569-c96839a7fa11.png)

Now that I see the solder sandwiched between the switch and battery, I don't think it actually looks that strange. I'll tag this for further discussion at design meeting.

**Comment by samreid** [comment]
At today's meeting we concluded this should be priority deferred, I'll mark it for 1.1+

**Comment by samreid** [comment]
@arouinfar anything else to do for this issue?

**Comment by arouinfar** [comment]
The solder is always layered below non-wire components, so the current z-ordering of the switch is consistent. Let's leave things the way they are @samreid.

![image](https://user-images.githubusercontent.com/8419308/64982829-567ba980-d87c-11e9-85d8-ae0d0102a281.png)
