### ISSUE TITLE
Move the scene selection buttons above the reset all button.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#321]
From https://github.com/phetsims/circuit-construction-kit-common/issues/286#issuecomment-302500760 @arouinfar requested that the scene selection buttons be at the bottom of all other controls.  

The current behavior is for the wire resistivity control and battery resistance controls to be appended below the scene selection button, so the scene selection button remains in the same place in the layout for all screens.

We noticed you had the wire resistivity control and battery resistance controls inserted between the display control and the scene selection control in the mockup, but wanted to double check before changing the code for the layout.

The code will be a little more complex to insert the controls instead of append them, and I'm wondering if it would necessarily be better for the user (because the scene selections will be in different spots on different screens).

Let us know your thoughts.

**Comment by arouinfar** [comment]
@samreid I thought I had seen a sim where the scene selection buttons are kept at the bottom. After reviewing the published HTML5 sims, the closest I could find is ESPB. However, in that case, the friction slider is appended to the top panel, so it's a bit different.
<img src="https://cloud.githubusercontent.com/assets/8419308/26664014/e226a0ae-464b-11e7-9cde-06c80b374b4b.png" width=250> <img src="https://cloud.githubusercontent.com/assets/8419308/26664024/ee4e2028-464b-11e7-87db-36f1e5487e38.png" width=250>

I still think the controls will look a bit more balanced if the scene selection buttons are kept below the panels, but it seems that would be a break from convention. That said, I would like to touch base on this during a design meeting, but for now leave things as they are @samreid.
<img src="https://cloud.githubusercontent.com/assets/8419308/26664398/977d7368-464e-11e7-8ba8-6239aa26a9e0.png" width =250> <img src="https://cloud.githubusercontent.com/assets/8419308/26664422/c7ce43e4-464e-11e7-9873-19e75c6421c7.png" width=250>

**Comment by samreid** [comment]
If I recall correctly, we decided to put the scene selection buttons right above the reset all button.  That way they will be in the same spot on every screen and always at the bottom.

**Comment by samreid** [comment]
Not sure if I am just used to the old way--this looks unbalanced to me:

![image](https://cloud.githubusercontent.com/assets/679486/26747921/80f48802-47b6-11e7-9f26-515304b274de.png)

Perhaps the sizes need to be adjusted.

**Comment by samreid** [comment]
@arouinfar here's a live one if you want to take it for a test drive:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.50/circuit-construction-kit-dc_en.html

Not sure if sizes/layouts are tracked elsewhere, but let me know if you have recommendations for this issue.

**Comment by arouinfar** [comment]
@samreid thanks for relocating the view selection buttons. I agree it looks a bit unbalanced. The view selection buttons seem way too large, so I reduced the width to 50px in all of the mockups below.

I've tried two options -- lower right corner and below the carousel. Originally we had the view selection buttons below the carousel (better proximity), but had moved them during a design meeting (unfortunately, I couldn't find any specific notes about this).  I'm not sure which option I prefer.

Keeping the buttons in the lower right doesn't look to bad with both accordion boxes open, but the buttons look a bit like they're floating on the first two screens.
![image](https://cloud.githubusercontent.com/assets/8419308/26799585/71b879d6-49f3-11e7-8d0f-8590d47b9f40.png)
![image](https://cloud.githubusercontent.com/assets/8419308/26799599/7b9e8756-49f3-11e7-8656-0f1c35694576.png)


Moving the buttons below the carousel would improve the proximity, but also suffers from odd spacing.
![image](https://cloud.githubusercontent.com/assets/8419308/26799684/cbb172b2-49f3-11e7-89dd-c1f5f228f581.png)
![image](https://cloud.githubusercontent.com/assets/8419308/26799691/d2b43cf2-49f3-11e7-9672-2eaea32a5a02.png)

**Comment by samreid** [comment]
@arouinfar would you be OK with having the view buttons be the same width as the sensor toolbox and showing up below all of the controls on the right?

**Comment by arouinfar** [comment]
@samreid I made the buttons wider to match the panel width. They're 90 px wide in these mockups. The alignment looks a bit cleaner, but I think the buttons are far too big and command more attention than necessary. I could with it, though.
 
![image](https://cloud.githubusercontent.com/assets/8419308/26802542/0c9d9a12-49fe-11e7-871c-86c0a2926a50.png)
![image](https://cloud.githubusercontent.com/assets/8419308/26802554/16de5e58-49fe-11e7-97ca-9bb9e4c7d7a5.png)

However, based on the screenshot in https://github.com/phetsims/circuit-construction-kit-common/issues/321#issuecomment-305929153, I don't know if this button size will work given the very small amount of padding between the view selection buttons and reset all. Perhaps some vertical space will be freed up once https://github.com/phetsims/circuit-construction-kit-dc/issues/9 is addressed.

**Comment by samreid** [comment]
Sorry, I meant the buttons would be immediately below the control panels, like this:

![image](https://cloud.githubusercontent.com/assets/679486/26804150/37e9b376-4a04-11e7-8178-1fef5b3fa895.png)

![image](https://cloud.githubusercontent.com/assets/679486/26804155/3dd9195c-4a04-11e7-931a-b031b4fe8233.png)

OK to give this a try?

**Comment by arouinfar** [comment]
Thanks for the clarification @samreid. Yes, let's give your suggestion a try!

**Comment by samreid** [comment]
The view radio buttons now appear below the bottom-most component on the right hand side, please test here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.51/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
