### ISSUE TITLE
Add icons for electrons and conventional current

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#322]
See https://github.com/phetsims/circuit-construction-kit-dc/issues/9

We need to add icons for electrons and conventional current like this: 

![image](https://cloud.githubusercontent.com/assets/679486/26231736/63818940-3c0e-11e7-8bc3-02572fd931d1.png)

@Denz1994 can you take a look at this?

**Comment by samreid** [comment]
@jonathanolson would I use AlignBox/AlignGroup to work on the "electrons" and "conventional" icons?

**Comment by jonathanolson** [comment]
Sounds like an easy way to handle aligning the right part of the labels (put both of the Text instances in an AlignBox with a group?)

**Comment by samreid** [comment]
Added new icons in the preceding commit, I'll create a separate issue for using AlignBox.
