### ISSUE TITLE
Implement current type icon alignment with AlignBox/AlignGroup

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#323]
In https://github.com/phetsims/circuit-construction-kit-common/issues/322 we added icons for the current types.  @jonathanolson suggested checking out AlignBox/AlignGroup for doing the alignment (currently hard-coded).

@jonathanolson said:

> Sounds like an easy way to handle aligning the right part of the labels (put both of the Text instances in an AlignBox with a group?)

@Denz1994 can you look through prior usages of AlignBox/AlignGroup and read the docs and see if it will help here?

**Comment by Denz1994** [comment]
I replaced the hStruts used in the ```DisplayOptionsPanel``` with an ```AlignBox```.  Is there more that can be done so that this isn't considered "hard-coded"? Assigning to @samreid for review. 

*Note: This pattern will be useful for https://github.com/phetsims/masses-and-springs/issues/81

**Comment by samreid** [comment]
Thanks, that seems better.  Can you also use the AlignBox/AlignGroup to position these icons?

![image](https://cloud.githubusercontent.com/assets/679486/26318309/fe3dee26-3ed7-11e7-815a-3b3576a6d909.png)

The problematic layout code is:

```js
    var electronsText = new Text( electronsString, TEXT_OPTIONS );
    var conventionalText = new Text( conventionalString, TEXT_OPTIONS );
    var largerTextWidth = Math.max( electronsText.width, conventionalText.width );
    var electronsBox = new HBox( {
      spacing: largerTextWidth - electronsText.width + textIconSpacing,
      children: [ electronsText, new ElectronChargeNode() ]
    } );

    var conventionalBox = new HBox( {
      spacing: largerTextWidth - conventionalText.width + textIconSpacing,
```

**Comment by Denz1994** [comment]
I've spent some time trying to use AlignBoxes to remove the spacing option in the layout code and reduce the about of HBoxes needed. Despite a lack of success, I was able to implement an align box for the radio buttons, but I feel like it doesn't get us much in regards to reducing code or readability.

It would be helpful to collab on this for maybe 10 min if these changes aren't ideal.

**Comment by samreid** [comment]
I agree, the commit you made does not solve the problem in the layout code.  I think AlignBox/AlignGroup is supposed to automatically handle the spacing, but I don't know how to use it.  Perhaps we can collaborate on this on Tuesday and get it figured out.

**Comment by Denz1994** [comment]
Okay sounds good. I found it hard to manage the spacing as well. Postponing until next collaboration.

**Comment by jonathanolson** [comment]
Since I was tagged:
```js
var group = new AlignGroup();
var electronsBox = new HBox( {
  children: [
    new AlignBox( new Text( electronsString, TEXT_OPTIONS ), { group: group } ),
    new ElectronChargeNode()
  ],
  spacing: textIconSpacing
} );
var conventionalBox = new HBox( {
  children: [
    new AlignBox( new Text( conventionalString, TEXT_OPTIONS ), { group: group } ),
    // the ArrowNode
  ],
  spacing: textIconSpacing
} );
```

**Comment by samreid** [comment]
Thanks @jonathanolson, I used the code above and now it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/26361715/1006d53e-3f99-11e7-9cde-54343f3ae54c.png)

Is there an option to left-align the "electrons" and "conventional" text?

**Comment by samreid** [comment]
Looks like AlignBox has leftAlign.  Not sure if I can specify this through the AlignGroup.  Checking...

**Comment by samreid** [comment]
Fixed above, thanks @jonathanolson!
