### ISSUE TITLE
The show values label should be centered over the light bulb

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#325]
From https://github.com/phetsims/circuit-construction-kit-common/issues/289

> the label should be centered over the light bulb.
![image](https://cloud.githubusercontent.com/assets/8419308/26129378/3003bee8-3a4d-11e7-9b24-cc080cc4dc34.png)

**Comment by samreid** [comment]
I used the charge path length to center it over the correct part of the filament:
![image](https://cloud.githubusercontent.com/assets/679486/26326815/1658746e-3efa-11e7-8ff2-812dacc8c510.png)

**Comment by samreid** [comment]
Fixed above, but the solution depends on the filament geometry.  May need to be re-tested after working on the other light bulb issues.

**Comment by samreid** [comment]
I published a version here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.24/circuit-construction-kit-dc_en.html

@arouinfar can you test this version and help me remember to test this again after other light bulb changes?

**Comment by arouinfar** [comment]
Looks good @samreid, thanks!
