### ISSUE TITLE
Move the light bulb vertices apart

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#326]
See #274, we need to move the vertices apart so they aren't touching.

![image](https://cloud.githubusercontent.com/assets/679486/26329518/da4c7546-3f04-11e7-83a6-08a7080399e0.png)

When I tried separating the vertices, it came out like this:

![image](https://cloud.githubusercontent.com/assets/679486/26329532/ec6304de-3f04-11e7-8026-d9ff3533dd48.png)

**Comment by samreid** [comment]
It was recommended to move the bottom vertex, but it turned out to be much simpler to move the right hand vertex.  The current version looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/26329764/f8c4a164-3f05-11e7-911e-361d58efc061.png)

**Comment by samreid** [comment]
I published http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.26/circuit-construction-kit-dc_en.html with this proposed fix.  The code is currently anchored about the bottom socket point.  It could be changed to adjust the position of the left vertex but it would take more work.  @arouinfar can you please review it and let me know your recommendation?

**Comment by arouinfar** [comment]
I reviewed the bulb in dev.37, and everything looks good to me. I don't think you need to make any further changes @samreid.
