### ISSUE TITLE
On screen 2-3, the circuit element toolbox should be a carousel

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#330]
From https://github.com/phetsims/circuit-construction-kit-common/issues/234

It should look like this

![image](https://cloud.githubusercontent.com/assets/8419308/23812569/4a54b0d4-0598-11e7-9939-78f50f557b92.png)

![image](https://cloud.githubusercontent.com/assets/8419308/23812499/0f70dcc2-0598-11e7-93a4-f9c1988e2d9c.png)

**Comment by samreid** [comment]
@jbphet @jonathanolson Can I use a carousel with only one page for the first screen, or will I need to use a different component?

**Comment by jonathanolson** [comment]
> Can I use a carousel with only one page for the first screen, or will I need to use a different component?

No clue, does it not work?

**Comment by samreid** [comment]
I didn't want to show the carousel buttons when there is only one page.  The default behavior is to show grayed out carousel buttons.  I worked around this with an if statement that creates a carousel if there are >1 pages, otherwise creates a sun panel.

**Comment by samreid** [comment]
I'm considering putting the dots on the right-hand-side of the carousel--it seems like it would impinge less on the amount of play area.

**Comment by samreid** [comment]
@Denz1994 and I added the page control dots in the preceding commit.  We tried them on the left side, but it trapped a lot of space and looked odd.

**Comment by samreid** [comment]
The carousel has an odd layout because the light bulb is so tall.  We tried to make the labels equally spaced using AlignBox, but it's still problematic.

![image](https://cloud.githubusercontent.com/assets/679486/26424593/03d0017c-408f-11e7-87ac-38a7157a790d.png)

**Comment by samreid** [comment]
Here's a pic with the light bulb at the bottom.  Looks better in my opinion but there is still a problem near the light bulb:

![image](https://cloud.githubusercontent.com/assets/679486/26424681/522e40ae-408f-11e7-9b40-0a43ad7800a3.png)

**Comment by samreid** [comment]
Removing the "bottom alignment" gives the switch much more room and looks much better:

![image](https://cloud.githubusercontent.com/assets/679486/26424730/715ce5de-408f-11e7-8327-1bb91b358c2c.png)

**Comment by samreid** [comment]
@Denz1994 and I posted a dev version for design team feedback:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.37/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
@samreid overall, it's looking good! I have a few suggestions:

* I'd prefer to keep the light bulb in its original location, as students tend to navigate top-down.
* We could make the light bulb icon 10-20% smaller so its alignment would look less odd. This would also allow us to make the carousel a bit shorter.
* I'm not a huge fan of having the navigation dots to the right of the carousel -- usually they are not inside the play area.

We should probably review this as a group in the next design meeting.

**Comment by samreid** [comment]
I moved the light bulb back to its original location.  80% seemed a bit too small, so I went with 85% which seemed good.

I published versions here with carousel page controls on the left or right so we can easily compare them.  I see that having the carousel buttons on the right impinges on the play area, but putting them on the left traps a lot of space.  Let's take a look and chat:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.45/circuit-construction-kit-dc_en.html?carouselPageControlSide=left

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.45/circuit-construction-kit-dc_en.html?carouselPageControlSide=right

**Comment by arouinfar** [comment]
Thanks @samreid! I really like the updated light bulb size. I still prefer the tracking dots to the left, but we can get the team's feedback during the next design meeting.

**Comment by samreid** [comment]
We decided to keep the dots on the left, but adjust the zoom buttons so they align with the left side of the carousel.  Indent the toolbox on screen 1.  On the right hand side make all the margins match.

**Comment by samreid** [comment]
The dots are on the left, and horizontal margins were updated to match.
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.49/circuit-construction-kit-dc_en.html

@arouinfar can you please check it out?

**Comment by arouinfar** [comment]
Looks great! Thanks @samreid.
