### ISSUE TITLE
Segregating DC strings from Common

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#332]
Before we publish we will need to think carefully about what strings should be "common" strings and what strings should be only in the "dc" repo.  It is difficult to change strings after the sim is published.  Some strings like "voltmeter" clearly belong in the common repo because they will be used in many CCK variants.  Will grab bag items be used in other CCK sims?  Also, can you take a look through here and see if you see anything that strikes you as "dc only"?

https://github.com/phetsims/circuit-construction-kit-common/blob/e3b1a4e787b21eec917e9bd2eb49bf4b74dce0b4/circuit-construction-kit-common-strings_en.json

**Comment by arouinfar** [comment]
@samreid if a string is "common" would it need to appear in all CCK flavors? For example, I could see grab bag items appearing in CCK: DC, CCK: AC, and possibly CCK: Basics, but they probably won't appear in CCK: Black Box.

Comparing the AC and DC flavors of Java, all DC strings also appear in AC, so I don't think there would need to be any CCK: DC-specific strings.

**Comment by samreid** [comment]
> @samreid if a string is "common" would it need to appear in all CCK flavors?

The main heuristic is that if a string should be identical in 2 or more flavors then it should be in common.  Good to know that the grab bag items will be the same in AC.  At some point it will be nice to discuss the design for AC CCK, since it may pertain to how things are built for DC CCK.
