### ISSUE TITLE
After dropping a selected circuit element, it should become deselected

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#333]
When dropping a selected vertex, it becomes deselected.  We should do the same for circuit elements.  See #201

**Comment by samreid** [comment]
Fixed above, closing.

**Comment by samreid** [comment]
On second thought, would be good to get this tested:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.42/circuit-construction-kit-dc_en.html

@phet-steele can you take a look?

**Comment by phet-steele** [comment]
Great!
