### ISSUE TITLE
Unchecking "Labels" should hide the labels in the sensor toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#337]
Currently unchecking "labels" removes the labels from the circuit element toolbox, but not the sensor toolbox:

![image](https://cloud.githubusercontent.com/assets/679486/26471565/637f5a2a-415f-11e7-9e0e-d095ed766e75.png)

@arouinfar should the labels in the toolbox be hidden in this case?  Am I getting Deja Vu?  If we want to hide the labels in the sensor toolbox, please reassign to @Denz1994.

**Comment by arouinfar** [comment]
@samreid not sure if we explicitly talked about the behavior, but I think the toolbox labels should behave like the carousel labels and be hidden when "Labels" is unchecked. Reassigning to @Denz1994.

**Comment by Denz1994** [comment]
I have added logic to make sure the labels in the sensor toolbox respond to the labels checkbox in the display options. Assigning to @samreid for review.

Also, this also took care of an i18n TODO for the strings in the sensor toolbox.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
