### ISSUE TITLE
Round the corners of the switch

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#338]
In https://github.com/phetsims/circuit-construction-kit-common/issues/319 @Denz1994 and @arouinfar recommended to round the corners of the switch.  @Denz1994 can you give this a try?  For the leftmost component, it may be as easy as passing radii to the rectangle constructor (if it is indeed a Rectangle).  For the component on the right, you will probably have to lineTo() a point before the corner, then arc() around the corner.  All code should be in SwitchNode.js

**Comment by Denz1994** [comment]
The right and left most edges have been rounded as suggested. Assigning to @arouinfar for review of dev version:  http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.46/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks great! Thanks @Denz1994.
