### ISSUE TITLE
Generate more unit tests for the resistor color bands

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#340]
The QUnit tests can be run at: http://localhost/circuit-construction-kit-common/tests/qunit/unit-tests.html

Here are the current tests for the resistor colors:
```js
  QUnit.test( 'test resistor colors', function( assert ) {
    assert.deepEqual( ResistorColors.getColorNames( 0 ), [ 'black' ], '0 resistance should have one black band' );
    assert.deepEqual( ResistorColors.getColorNames( 4700 ), [ 'yellow', 'violet', 'red', 'gold' ], '4700 ohm resistor' );
    assert.deepEqual( ResistorColors.getColorNames( 10 ), [ 'brown', 'black', 'black', 'gold' ], '10 ohm resistor' );
    assert.deepEqual( ResistorColors.getColorNames( 99.5 ), [ 'brown', 'black', 'brown', 'gold' ], '99.5 ohm resistor' );

    // TODO: use https://www.allaboutcircuits.com/tools/resistor-color-code-calculator/ to generate more tests
  } );
```

Can you please use https://www.allaboutcircuits.com/tools/resistor-color-code-calculator/ or something like it to generate more color bands tests, to make sure our algorithm is correct?

**Comment by Denz1994** [comment]
Let's add 10 more of these test.

Pick a resistance, give it the correct color bands following the provided link, and check for errors.

**Comment by Denz1994** [comment]
10 more unit test were added. Assigning to @samreid for review.

**Comment by samreid** [comment]
Looks great, thanks!  We'll discuss decimal bands in #346, closing this one.
