### ISSUE TITLE
Vertex moves too far

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#344]
From https://github.com/phetsims/circuit-construction-kit-common/issues/131

@phet-steele said: 
I've discussed with @arouinfar and we feel the pushing has the potential of being incredibly large. For example with this two wire setup, moving the upper left vertex only slightly produces a reasonable jump, but moving far creates a huge jump:
![cckdc03](https://cloud.githubusercontent.com/assets/5863899/26644340/9f8db6ce-45f1-11e7-9664-87e7bb7d5ef3.gif)

What causes the large pushing, and can it be standardized?

**Comment by samreid** [comment]
It looks like the pushing is caused by a rotation.  The angle is the same, but for the longer wire the translation is much further.

**Comment by samreid** [comment]
I chose to do a rotation because any number of fixed length circuit elements maybe attached to the offending vertex.  Rotation guarantees that none of the lengths will change.  @arouinfar can you recommend a better strategy?  Should I retain rotation as a general strategy but add special cases for situations like this?

**Comment by arouinfar** [comment]
@samreid perhaps you could continue to rotate away by some angle, but only if the resulting arc length is less than 100 px (or whatever you think is reasonable). In most situations, the component would rotate away as it does now. When dealing with long wires, the rotation would be limited by arc length, resulting in a much smaller angle of rotation.

Here's a rough sketch recreating the situation in https://github.com/phetsims/circuit-construction-kit-common/issues/344#issue-232742570, but limiting the arc of rotation. In the right-most image, the top vertex of the left wire was dragged close to the zoom buttons, resulting in the other vertex being rotated away.
<img src="https://user-images.githubusercontent.com/8419308/27094694-38152ab8-5028-11e7-859a-01b57f1ec814.png" width=200>  <img src="https://user-images.githubusercontent.com/8419308/27094707-43e3ea8c-5028-11e7-9c22-3cfd650ca25e.png" width=200>  <img src="https://user-images.githubusercontent.com/8419308/27094741-5cbbd934-5028-11e7-8d03-ef301dc0ee6d.png" width=200>

**Comment by samreid** [comment]
Proposed fix committed above and published for testing here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.72/circuit-construction-kit-dc_en.html

@arouinfar or @phet-steele can you please test it out?

**Comment by arouinfar** [comment]
@samreid I couldn't reproduce the situation in https://github.com/phetsims/circuit-construction-kit-common/issues/344#issuecomment-308185781, but I think it would be good if @phet-steele could also review.

**Comment by phet-steele** [comment]
I'm ok with this, thanks @samreid!
