### ISSUE TITLE
5-Band Resistors added to sim?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#346]
While creating some unit tests for the checking the color bands accuracy to its resistance values, I noticed that the colors of the bands were behaving as if the resistance values were being rounded up for decimal values. For example, a 33.5 ohm resistor is producing color bands for a 34 ohm resistor.

There is a %5 tolerance for our resistors due to the gold band, but the thought was raised after discussion with @samreid, should we have 5 band resistors. It was mentioned that it may be useful as students may come across this in real life and it would help represent our resistance without less ambiguity.

Tagging for design meeting for further discussion.

**Comment by Denz1994** [comment]
@samreid mentioned that using a 5 band resistor to represent resistance with decimal values will cause the resistor to switch between a 5 band and 4 band representation if the user is constantly incrementing the resistor values.

**Comment by arouinfar** [comment]
Drawing bands is performance heavy, so avoid adding 5th band. @Denz1994 have you found any resistors outside of the stated tolerance? If so, we can change the tolerance band color. If not, please go ahead and close this issue.

**Comment by samreid** [comment]
> Drawing bands is performance heavy, so avoid adding 5th band

To clarify, performance is not the issue, it is more of a design issue.

**Comment by Denz1994** [comment]
After some further investigation, it turns out that our %5 tolerance is accurate for our current ohm readings.

For example, 34.5 ohms corresponding to a 35.0 ohm resistor with %5 tolerance gives us a possible range of (36.75>x>33.5). We are within the bounds or tolerance.

At this point, I don't think we need 5 bands.

Closing this issue.

**Comment by arouinfar** [comment]
Thanks for looking into things @Denz1994!
