### ISSUE TITLE
Limit string widths

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#348]
![image](https://cloud.githubusercontent.com/assets/679486/26700577/17af0cf4-46db-11e7-95d8-8dccf374a08c.png)

**Comment by samreid** [comment]
@Denz1994 can you please measure the current english strings using console.log(textNode.width), then use that to set the maxWidth of those texts?  You can test it by ?stringTest=double

**Comment by Denz1994** [comment]
I added maxWidth options to strings that weren't scaled. I tested using &stringTest=long. From what I can see the texts now scale with a limited maxWidth. I followed the suggestion given in the last comment but added a bit more space (10-15 pixels) to the strings' maxWidth.

**Comment by samreid** [comment]
This looks very nice, the only 2 recommendations I have are that the tick mark labels and battery resistance text box are limited to be too small.

![image](https://user-images.githubusercontent.com/679486/27466166-d601b696-5795-11e7-91e8-2448edb907ac.png)

![image](https://user-images.githubusercontent.com/679486/27466180-ec370eb6-5795-11e7-85d3-5c98cad7f92e.png)

@Denz1994 can you please investigating allowing those to be larger?  (But not so large they cause problems when other strings and hence the panels are small?)

**Comment by samreid** [comment]
After the above commits:
![image](https://user-images.githubusercontent.com/679486/27767295-317930c8-5eb0-11e7-835b-19b5677aaa38.png)

Closing.
