### ISSUE TITLE
Internationalize the "animation speed limit reached" message

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#350]
Use a placeholder for the percentage of speed reduced.

**Comment by Denz1994** [comment]
Used StringUtils for formatting. Tested using stringTest=double and stringTest=x.

**Comment by samreid** [comment]
StringUtils.format is documented like so:

```NOTE: Please use StringUtils.fillIn instead of this function.```

Can you please write this using StringUtils.fillIn?

**Comment by samreid** [comment]
@Denz1994 and I changed it to use `fillIn` above.  @arouinfar we are wondering if we should internationalize the "<" sign that appears here:
![image](https://user-images.githubusercontent.com/679486/27103101-c4b9644a-5044-11e7-985c-9d7db4d065dd.png)

It is currently hard coded to be `< 1` for this case, but we are wondering if RTL or other languages will need the flexibility to change this.

**Comment by arouinfar** [comment]
@samreid I don't think we need to internationalize "<" as it is a mathematical symbol.

**Comment by samreid** [comment]
Do you think RTL languages may need to do 1 < ?

**Comment by arouinfar** [comment]
@samreid Arabic and Persian both read numbers LTR... not sure about other RTL languages, though.  Given that the number itself is not translatable, I don't think `< 1` is likely to be misinterpreted.

**Comment by samreid** [comment]
Thanks for clarifying, sounds good, closing.
