### ISSUE TITLE
Series ammeter pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#352]
* Body 10% larger
* "Current" as small as possible
* Widen top orange rectangle
* Made readout a bit bigger

Self-assigning to work on some mockups.

**Comment by arouinfar** [comment]
Here's a comparison of the current series ammeter (top) and the proposed change (bottom). Both ammeters have the same height, but the updated ammeter has been made 10% longer. "Current" is 10 pt and the value is 14 pt. 
![image](https://cloud.githubusercontent.com/assets/8419308/26743804/7c302530-47a0-11e7-84e8-f7ed8d604d75.png)

@samreid is this enough to get started with the changes? Anything else I need to specify?

**Comment by samreid** [comment]
That should be good for now, thanks!

**Comment by samreid** [comment]
After refining, its looking like this:

![image](https://user-images.githubusercontent.com/679486/26861102-e3dab8ba-4afe-11e7-88b4-daee8f4bce06.png)

I'll commit and create a dev version for review.

**Comment by samreid** [comment]
Ready for testing here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.52/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look?

**Comment by samreid** [comment]
I have a few other changes on the way.  Best to hold off testing for now.

**Comment by samreid** [comment]
OK ready for testing after other changes:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.53/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Love it!
