### ISSUE TITLE
Customize geometry for grab bag items

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#354]
> SR will investigate customizing vertex locations on grab bag items

**Comment by samreid** [comment]
And so they can be different lengths

**Comment by samreid** [comment]
Dog vertices are OK in #364.  @arouinfar do any other grab bag items need custom (non-centered) vertex coordinates?

**Comment by arouinfar** [comment]
Everything looks good to me!

**Comment by samreid** [comment]
I also adjusted the vertices for the hand, will be available in next version. and should look like this:

![image](https://user-images.githubusercontent.com/679486/27057480-9e6eb08a-4f89-11e7-91d8-738699e02307.png)
