### ISSUE TITLE
What to name CircuitNode.js?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#355]
CircuitNode.js shows the circuit elements, wires, electrons, vertices, solder.  Now it also shows the voltmeter.  Should I still call it CircuitNode even though the voltmeter is not technically part of the circuit (or is it?)

**Comment by samreid** [comment]
@jonathanolson said:

> ElectricalNode? Node?

@jbphet said:

> In response to Sam's CCK-related question, in EE terminology, a "node" in a circuit is the point where two or more elements meet, so there is a bit of an overloading of the term "node".  This should probably at least be acknowledged in the comment header, but IMO a name like "CircuitNode" would definitely be confusing to someone with a background in circuit design, and I would suggest avoiding it.  An ideal voltmeter doesn't draw any current, so is technically is not part of the circuit.  Some ideas: ElectricalElementNode maybe?  CompositeElectricalElementNode? (reference: https://en.wikipedia.org/wiki/Node_(circuits))

**Comment by samreid** [comment]
Here's the JSDoc:

```js
/**
 * The Node that represents a Circuit, including all Wires and FixedLengthCircuitElements, Charge, Solder, etc.  It also
 * renders the voltmeter and ammeter. It can be zoomed in and out.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Denzell Barnett (PhET Interactive Simulations)
 */
```

How about CircuitLayerNode, indicating that it shows everything that must be in the same layer as the circuit?

**Comment by jonathanolson** [comment]
Sounds great. Sorry was confused earlier, recommended `{ElectricalNode}` as a supertype for circuit elements or the meter.

**Comment by samreid** [comment]
Renamed to CircuitLayerNode, closing.
