### ISSUE TITLE
Address i18n TODO SeriesAmmeterNode

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#358]
Please reference `seriesAmmeterNode.js` line 66 for TODO.

 `var currentText = ( current < 1E-10 ) ? '' : Util.toFixed( current, 2 ) + ' A'; // TODO i18n and fillIn`

Also check ammeterNode to factor out this duplicate code (line 81)
`StringUtils.fillIn( currentAmpsString, { current: Util.toFixed( Math.abs( current ), 2 ) } );`

**Comment by Denz1994** [comment]
> Also check ammeterNode to factor out this duplicate code (line 81)
StringUtils.fillIn( currentAmpsString, { current: Util.toFixed( Math.abs( current ), 2 ) } );

Because `ammeter.js` and `seriesAmmeterNode.js` don't inherit from the same file (outside of Node.js in common code) I don't know where to factor out the code. 

I was thinking of having a function that just takes the current returns the duplicated line:

```js
createAmpReadout= function(currentAmpsString, current){
return StringUtils.fillIn( currentAmpsString, { current: Util.toFixed( Math.abs( current ), 2 ) } );
}
```
I think this would work but where would I put it? I thought in the ```CircuitConstructionKitConstants.js``` file. However after talking to @jbphet we found that it may go better in a Util file. Perhaps changing the name of ```CCKMathUtil.js``` to ```CCKUtil.js``` and dropping the function in this file.

Thoughts @samreid?

**Comment by Denz1994** [comment]
I have used a util file for creating arrows in Masses-And-Springs as well.

**Comment by samreid** [comment]
> Perhaps changing the name of ```CCKMathUtil.js``` to ```CCKUtil.js``` and dropping the function in this file.

That sounds like it will work great.  Or you could put the code in SeriesAmmeterNode or AmmeterNode.js as a static function and let one call the other.  Not sure what's best.

**Comment by Denz1994** [comment]
After toiling with both approaches, I think using the utility function would work better.

Main Reasons:
- There may be more utility functions needed besides this one.
- This function creates a formatted readout, which is not specific for an ammeter. It can be refactored to produce any readout with a unit.

I went a bit further than suggested @samreid. All of the sensors follow a similar means of producing a readout. I generalized the utility function to be able to accommodate for all of the sensors. It may be useful in case CCK-DC 2.0 introduces new sensor tools with readouts.

Do you find this useful? If not I can retract my changes to only use stringUtil.fill() as needed on a case by case basis. 

I would ask to please review the documentation of the method, to assure its clarity.

**Comment by samreid** [comment]
This looks pretty good but I would recommend taking one step back in the abstraction.  Can you please divide up createMeasurementReadout into CCKUtil.createVoltageReadout and CCKUtil.createCurrentReadout?  That will eliminate the need for the strings and object keys to be passed in from all client sites.

**Comment by Denz1994** [comment]
Understood. I will work on that.

**Comment by Denz1994** [comment]
The voltage and ampere readouts are now using two separate util functions. There are multiple commits because I had some issues merging conflicts, but it is now resolved.

**Comment by samreid** [comment]
@Denz1994 and I looked at this together, everything is looking great, thanks!
