### ISSUE TITLE
Objects should move to front (z-order) when dragging

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#362]
For instance, CircuitElements layer in the order they are created and the voltmeter is always behind the ammeter.  When something is dragged, it should normally be moved to the front.

**Comment by samreid** [comment]
@arouinfar can you comment on priority and confirm whether is essential for 1.0?

**Comment by arouinfar** [comment]
@samreid I haven't noticed any issues with the layering, so I think you can probably hold off on this. However, I think it may be good to keep an eye for this in QA testing to make sure there aren't any blocking issues that crop up.

**Comment by samreid** [comment]
@arouinfar want to spend any time on this for publishing AC?

**Comment by arouinfar** [comment]
@samreid, yes let's address this is AC 1.0.

**Comment by samreid** [comment]
In the preceding commits, I made ammeters, voltmeters, charts and circuit elements move to the front when pressed.  Note that the circuit defines specific layering, such as wires are always in the back and light bulbs are always in the front--this change only arranges elements within their layer (wires won't move in front of resistors).  Also, for circuit elements, this is only wired up when dragging the circuit element itself rather than dragging a connected vertex.  I was concerned that the general case for dragging a connected vertex is more complex.  For instance, N circuit elements can be connected to a vertex--should they all be moved to the front when the vertex is grabbed?  What about their neighbors?

@arouinfar can you please test the current implementation in phettest?  And can you please comment on what should happen to circuit element layering when vertices are pressed?

**Comment by arouinfar** [comment]
@samreid looks good in master.
