### ISSUE TITLE
Grab bag items are too big

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#363]
In #264 @arouinfar said:

I also find that the Grab Bag items are overly large. Do you need to address #354 before tweaking the size?
![image](https://user-images.githubusercontent.com/8419308/26890686-a4b72206-4b6f-11e7-932d-7381c842ea84.png)

**Comment by samreid** [comment]
In the preceding commits, I reduced the sizes and now it looks like this:

![image](https://user-images.githubusercontent.com/679486/26985356-6dbcb77e-4d00-11e7-9a7e-eda6d54bf94a.png)

The new sizes are:

```js
    // Length of grab bag items in view coordinates
    COIN_LENGTH: 85,
    ERASER_LENGTH: 90,
    PENCIL_LENGTH: 130,
    HAND_LENGTH: 140,
    DOG_LENGTH: 170,
    DOLLAR_BILL_LENGTH: 140,
    PAPER_CLIP_LENGTH: 75,
```

I published a dev version here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.59/circuit-construction-kit-dc_en.html

@arouinfar can you please review and recommend numbers for the grab bag item lengths?

**Comment by arouinfar** [comment]
The sizes look much better now, thanks @samreid!
