### ISSUE TITLE
Offset the dog vertices

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#364]
In #264 @arouinfar said:

For the dog, I think you'll want to off-set the vertices a bit, otherwise things may look a bit odd. In the carousel, the dog should be upright, but when pulled out, it could remain upright with the vertices offset (middle) or the dog could be rotated a bit so that the vertices are level with one another (bottom).

![image](https://user-images.githubusercontent.com/8419308/26891029-cf11d3ec-4b70-11e7-97ef-aca6caacb515.png)

**Comment by samreid** [comment]
I may need to implement #354 to implement this.

**Comment by samreid** [comment]
For reference, here is the dog before working on this issue:

![image](https://user-images.githubusercontent.com/679486/27041898-99298046-4f52-11e7-9b51-bfc31d411457.png)

**Comment by samreid** [comment]
If I vertically adjust the dog node, it looks like this:

![image](https://user-images.githubusercontent.com/679486/27042263-a50cee4c-4f53-11e7-81f5-456369bd4cfb.png)

This seems good to me, I think I'll commit it.

**Comment by samreid** [comment]
Dog is ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.62/circuit-construction-kit-dc_en.html

@arouinfar can you please test?

**Comment by arouinfar** [comment]
Now that I see the dog in context, I think it's pretty good. I don't think you need to adjust the vertices any further @samreid.
