### ISSUE TITLE
Objects move when the window is reshaped

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#365]
Perhaps related to https://github.com/phetsims/circuit-construction-kit-common/issues/302 but the vertices move when the window is reshaped, usually to a buggy position.

**Comment by samreid** [comment]
Fixed above.  To clarify, vertex groups are translated onscreen when a window resize or tablet rotation could move them off the screen.  This was buggy before because the bounds check was in the wrong coordinate frame.

**Comment by samreid** [comment]
@arouinfar commented:

1) The circuit is built outside of dev, and window is resized. The circuit jumps back into the play area (this could use some polishing), and the meter scoots with the edge of the window. I think portrait > landscape iPad rotation would likely behave the same.
<img width="353" alt="screen shot 2017-06-01 at 10 24 52 am" src="https://cloud.githubusercontent.com/assets/8419308/26689922/ad471c24-46b4-11e7-984e-55021b9c5896.png">
<img src="https://cloud.githubusercontent.com/assets/8419308/26689924/b0cc25b0-46b4-11e7-85cf-04b4dfa4e212.png">

**Comment by samreid** [comment]
This also relates to zoom.  If you zoom out so that a circuit is out of visible area then reshape the window, the circuit moves.  We should discuss what is desirable here.

**Comment by samreid** [comment]
The simplest implementation would be to allow objects to be dragged out of bounds and let window reshaping/tablet rotation move them out of bounds.  I was hoping we could come up with an elegant solution that kept objects always within reach but it's getting complicated.

**Comment by samreid** [comment]
Another possibility (more complex to implement): translate vertex groups together (including all wire vertices).  Not sure how to keep probes in the same relative locations though.

**Comment by arouinfar** [comment]
Discussed in 6/15/17 design meeting. Circuits built outside of dev should get pushed back into dev when the window is resized. @samreid will look into the solution he proposed in https://github.com/phetsims/circuit-construction-kit-common/issues/365#issuecomment-307989010.

**Comment by samreid** [comment]
Notes from previous meeting:

translate the entire group, make sure everything remains in view all the time
meter should always stay in bounds
	meters are good as is (regarding zoom and boundaries)
when zooming trigger the code that moves circuit things inside
make it so the geometry is preserved.

**Comment by samreid** [comment]
Committed in 33bcc7aa39467d87bc47873f80effba96fef0f0d preserving geometry

**Comment by samreid** [comment]
In the 2 preceding commits, geometry is preserved and objects are moved into view during zoom as well as screen reshape.  If the geometry is too large to fit on the screen, the algorithm will "try its best" without disturbing the geometry, but parts will be offscreen and need to be adjusted by the user.

**Comment by samreid** [comment]
I published a version for testing here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.75/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Looks good @samreid! Most cases work beautifully, but to test an edge case, I made an unrealistically large circuit while zoomed out. When zooming in, some elements were lost off screen, but part of the circuit was still retrievable. I think in this situation it's acceptable to require the user zoom back out to retrieve missing parts.

<img width="1124" alt="screen shot 2017-06-28 at 11 13 05 am" src="https://user-images.githubusercontent.com/8419308/27650673-ccaddffa-5bf2-11e7-857d-9f7ba3b38c78.png">

![image](https://user-images.githubusercontent.com/8419308/27650692-df67483e-5bf2-11e7-992e-15144c22eb3b.png)
