### ISSUE TITLE
Using Delete/Backspace to remove a circuit element, doesn't allow for second click.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#368]
1. Go to explore or lab screen.
2. Drag a circuit element out of the carousel.
3. Drop the circuit element in the play area.
4. Click on the circuit element (it should be highlighted).
5. Press delete or backspace.
6. Now click on a circuit element within the carousel. 

At this point, you should have to click twice for you to retrieve an element from the carousel

**Comment by samreid** [comment]
I was able to reproduce this problem.

**Comment by samreid** [comment]
CircuitElementNode has a clickToDismissListener which is correlated with this problem.

**Comment by samreid** [comment]
The proposed fix is in the preceding commit.  @Denz1994 can you please review and test?

**Comment by Denz1994** [comment]
I wasn't able to replicate this problem after trying following the above steps. I have even tried modifying my approach and still cannot reproduce the bug. I would consider it fixed after testing on MacBook Pro iOS 10.12.5

Closing. Thanks for the work @samreid.
