### ISSUE TITLE
Speed up performance when dragging an object out of the toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#369]

**Comment by samreid** [comment]
Here's our starting spot:
![image](https://user-images.githubusercontent.com/679486/27203154-ba0e89be-51e1-11e7-8508-52be1800e964.png)

**Comment by samreid** [comment]
After the above commit and commenting out VertexNode buttons and ValueNodes, it looks like this:
![image](https://user-images.githubusercontent.com/679486/27203565-a73f8174-51e3-11e7-9524-a82e63ccdd9c.png)

**Comment by samreid** [comment]
I'm deciding between these two approaches:

1. Preallocate all or many model and view objects.  Then dragging out of the toolbox just makes it visible.  This is guaranteed to be the fastest approach but will be more invasive.
2. Speed up individual steps that are taking up time when model and view objects are allocated.  There is no way this can ever be as fast as (1) and may take a long time to implement but would leave the typical dynamic allocation strategy intact.

@arouinfar and @ariel-phet I am leaning toward (1) but wanted to run it past you first.

**Comment by arouinfar** [comment]
@samreid option (1) sounds good to me, but I think this is more a question for you and @ariel-phet.

**Comment by ariel-phet** [comment]
@samreid, what is the cost of (1) in terms of "more invasive". I assume this step will cause a longer start up time of the sim (which I think is acceptable), but what other penalties will we pay?

I would also think there are some "slick" ways to perform (1) that we discussed the other day, such as for instance preallocating only one of each circuit element, but preallocate another once the first element is dragged out of the carousel. So for instance, preallocate a battery, and then if that battery is dragged out of the carousel, preallocate another when that battery is released.

**Comment by samreid** [comment]
> but what other penalties will we pay?

This is mostly speculative--we would know better after trying to build it.  It seems it would mainly be an issue of rewriting parts of the code that assume objects are created dynamically to a pre-allocation strategy.  I would need to add a `visible` or `active` or `unallocated` sort of attribute to circuit elements so the circuit knows whether they are alive or just waiting to be alive.

If a "preallocate everything" strategy turns out to be simplest, we would need to make sure the model performance is still acceptable.

"Preallocate everything and avoid dynamic allocations" is a typical strategy for getting good game performance.

**Comment by samreid** [comment]
I asked on Skype:

> I need a model term to indicate “preallocated for performance reasons but shouldn’t participate in model computations and the corresponding view shouldn’t be visible in the scene graph”

**Comment by ariel-phet** [comment]
@samreid sounds good

**Comment by samreid** [comment]
I'm noticing that rendering things with WebGL speeds this up significantly.  I think I should look into rendering with webgl before spending too much more time on the preallocation strategy.

**Comment by samreid** [comment]
Dragging out the first object is very slow even with webgl, but 2nd and later is fine even with no preallocation.  Perhaps we need to (a) exercise that code path or (b) make sure the webgl layer is all ready to go.

**Comment by samreid** [comment]
@jonathanolson identified that an important step is to prepopulate the sprite sheet.  This is done for the battery and working nicely.  Still needs to be done for all other circuit element types as well as schematic mode.

**Comment by samreid** [comment]
This is working much better (for WebGL as well as SVG), I'm closing this issue and we can continue in #377
