### ISSUE TITLE
Bump away vertices after cut?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#372]
In #344 we showed how cutting a vertex can create vertices that are very close to each other.  Perhaps we should run the "bump" away code when a cut occurs?

@arouinfar can you think of any problems this may cause?  Should I go for it?

**Comment by arouinfar** [comment]
@samreid I like this idea, but my worry is that the "bump" code will push the vertices too far apart, causing things to look odd. Ideally, the cut vertices would bump away enough so that there vertices are still close, but not overlapping.

**Comment by arouinfar** [comment]
After reviewing #344, perhaps the bump wouldn't be too far. 

Before cutting:
<img width="198" alt="screen shot 2017-06-23 at 11 31 23 am" src="https://user-images.githubusercontent.com/8419308/27493613-93314666-5807-11e7-9208-bd447232c50c.png"> 

Current behavior:
<img width="178" alt="screen shot 2017-06-23 at 11 31 30 am" src="https://user-images.githubusercontent.com/8419308/27493612-932ef8ac-5807-11e7-9257-711d07c5d1b0.png"> 

Proposed "bump":
<img width="159" alt="screen shot 2017-06-23 at 11 31 38 am" src="https://user-images.githubusercontent.com/8419308/27493611-93216eda-5807-11e7-994e-8587e370f937.png">

Perhaps if both vertices moved an equal distance away from one another it would look a bit more balanced, but I don't know how hard it would be to do. Either way, I'd say go for it @samreid.

**Comment by samreid** [comment]
It looks like the problem is is that the vertices move away from the old vertex toward the opposite vertex (which is still connected).  If two components are in the same direction this can cause an overlap:

![image](https://user-images.githubusercontent.com/679486/27498098-bcd358b6-581a-11e7-9c17-5c2f0d6eeed4.png)

**Comment by samreid** [comment]
Here's a 2-point cutVertex that seems to have much better behavior:

```js
    /**
     * Split the Vertex into two separate vertices.
     * @param {Vertex} vertex - the vertex to be cut.
     * @public
     */
    cutVertex: function( vertex ) {
      var neighborCircuitElements = this.getNeighborCircuitElements( vertex );
      if ( neighborCircuitElements.length === 0 ) {

        // No need to cut a solo vertex
        return;
      }

      var translations = [];
      var vertexGroups = [];
      for ( var i = 0; i < neighborCircuitElements.length; i++ ) {
        var circuitElement = neighborCircuitElements[ i ];
        if ( circuitElement.interactiveProperty.get() ) {
          var options = {
            draggable: true,
            interactive: true,
            attachable: true,
            blackBoxInterface: false,
            insideTrueBlackBox: false,
            tandem: this.vertexGroupTandem.createNextTandem()
          };
          var newVertex = new Vertex( vertex.positionProperty.get().x, vertex.positionProperty.get().y, options );

          // Add the new vertex to the model first so that it can be updated in subsequent calls
          this.vertices.add( newVertex );

          circuitElement.replaceVertex( vertex, newVertex );

          // Bump the vertices away from the original vertex
          var vertexGroup = this.findAllFixedVertices( newVertex );
          vertexGroups.push( vertexGroup );
          var oppositeVertex = circuitElement.getOppositeVertex( newVertex );
          var translation = oppositeVertex.positionProperty.get().minus( vertex.positionProperty.get() ).normalized().timesScalar( 30 );
          translations.push( translation );
        }
      }

      var angles = translations.map( function( t ) {return t.angle();} );
      var separation = Math.PI * 2 / angles.length;

      if ( translations.length === 2 ) {

        var center = (angles[ 0 ] + angles[ 1 ]) / 2;
        var a = center - separation / 2;
        var b = center + separation / 2;
        var ax = Vector2.createPolar( 30, a ).plus( vertex.positionProperty.value );
        var bx = Vector2.createPolar( 30, b ).plus( vertex.positionProperty.value );

        var da = angles[ 0 ] - center;

        var results = da < 0 ? [ ax, bx ] : [ bx, ax ];
      }

      for ( i = 0; i < neighborCircuitElements.length; i++ ) {

        vertexGroup = vertexGroups[ i ];

        for ( var j = 0; j < vertexGroup.length; j++ ) {
          var v = vertexGroup[ j ];

          // Only translate vertices that are movable and not connected to the black box interface by fixed length elements
          if ( v.draggableProperty.get() && !this.hasFixedConnectionToBlackBoxInterfaceVertex( v ) ) {
            v.setPosition( results[ i ] );
          }
        }
      }

      if ( !vertex.blackBoxInterfaceProperty.get() ) {
        this.vertices.remove( vertex );
      }

      // Update the physics
      this.solve();
    }
```

**Comment by samreid** [comment]
New algorithm puts cut vertices equidistant on a circle

![image](https://user-images.githubusercontent.com/679486/27502112-faf903d4-582e-11e7-9d5e-164a564d807f.png)

![image](https://user-images.githubusercontent.com/679486/27502118-0f7c109e-582f-11e7-9941-75878b9edf74.png)

**Comment by samreid** [comment]
I've published a fixed version here for review:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.73/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Love it @samreid!
