### ISSUE TITLE
multiple declarations of circuitElement

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#378]
Noted while looking at CircuitElementToolNode for https://github.com/phetsims/scenery-phet/issues/214.  

IDEA is flagging line 64 with "variable might not have been initialized".  The `var circuitElement` inside the `down` function (line 69) is shadowing the `var circuitElement` declared outside that function (line 48).  So  if line 64 is executed, `circuitElement` will be `undefined`.  

```js
    if ( preallocate ) {
      // Preallocate the CircuitElement
48    var circuitElement = createElement( new Vector2() );

      // Add the CircuitElement to the Circuit so that everything is ready to display when the tool is dragged
      circuit.circuitElements.add( circuitElement );
    }

    this.addInputListener( {
        down: function( event ) {

          // Don't try to start drags with a right mouse button or an attached pointer.
          if ( !event.canStartPress() ) { return; }

          // initial position of the pointer in the coordinate frame of the CircuitLayerNode
          var viewPosition = circuitLayerNode.globalToLocalPoint( event.pointer.point );

          if ( preallocate ) {
64          circuitElement.setMidpoint( viewPosition );
          }
          else {

            // Create the new CircuitElement at the correct location
69          var circuitElement = createElement( viewPosition );

            // Add the CircuitElement to the Circuit
            circuit.circuitElements.add( circuitElement );

          }
```

**Comment by samreid** [comment]
It seems the preallocation strategy will no longer be necessary due to other fixes in https://github.com/phetsims/circuit-construction-kit-common/issues/369 so I removed it in the preceding commit.  @pixelzoom did that fix the IDEA warnings?

**Comment by pixelzoom** [comment]
Appears to have been fixed in https://github.com/phetsims/circuit-construction-kit-common/commit/ef16dad49099b2ec2f17aaed7545790173b7e153, where there is now only 1 declaration of `circuitElement`.  

Closing.
