### ISSUE TITLE
i18n strings need help

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#380]
During code review https://github.com/phetsims/circuit-construction-kit-dc/issues/53 I noticed these strings:

```json
  "valueUnitsPattern": {
    "value": "{0} {{units}}"
  },
  "voltageUnits": {
    "value": "{{voltage}} V"
  },
  "ampereUnits": {
    "value": "{{ampere}} A"
  },
```

for the top one, it seems like it would be better to expand it out (and also use double curlies everywhere).  For the others, there is probably a better name for the keys.

**Comment by samreid** [comment]
@pixelzoom does NumberControl require the `{0}` pattern?  Is that a good long term solution?  Can/should I publish a sim with a string key like the one in the top of the issue description?

**Comment by pixelzoom** [comment]
You're asking if we can convert NumberControl options.valueFormat to the new "named placeholders" patterns.  You'll need to inspect all client usages of that pattern, and make sure that the "{0}" appears in code, and not in a translated string.  If that is the case, then you should be able to (1) replace "{0}" with "{{value}}" in NumberControl _and_ at all client sites, and (2) replace `StringUtils.format` with `StringUtils.fillIn` in NumberControl, but _not_ at client sites.

**Comment by samreid** [comment]
But we would have to change all translations, right?  Are we painted into a corner?

**Comment by pixelzoom** [comment]
This is going to result combined use of both placeholder formats, which feels a little weird/wrong.

Example...

projectile-motion-strings_en.json:

```js
  "pattern0Value1UnitsWithSpace": {
    "value": "{0} {1}"
  },
```

projectile-motion.LabProjectilePanel delta:

```js
- valuePattern: StringUtils.format( pattern0Value1UnitsWithSpaceString, '{0)', kgString ),
+ valuePattern: StringUtils.format( pattern0Value1UnitsWithSpaceString, '{{value}}', kgString ),
```

... which results in "{{values}} kg".

NumberDisplay delta:

```js
- self.valueNode.text = StringUtils.format( options.valuePattern, Util.toFixed( value, options.decimalPlaces ) );
+ self.valueNode.text = StringUtils.fillin( options.valuePattern, {
+   value: Util.toFixed( value, options.decimalPlaces ) 
+ } );
```

**Comment by pixelzoom** [comment]
> But we would have to change all translations, right? Are we painted into a corner?

We don't necessarily need to change translated strings.  We currently replace '{0}' with '{0}' in translated strings. We would replace '{0}' with '{{value}}'.   Which (again) feels a little weird/clever/wrong.

**Comment by samreid** [comment]
I'm not clear what your recommendation is for this CCK string.  Should I keep:

```js
  "valueUnitsPattern": {
    "value": "{0} {{units}}"
  },
```
or change it to something else?

**Comment by pixelzoom** [comment]
Until we decide what to do, and apply the same approach to all affected sims (eg projectile-motion), I would stick with old-style (numbered) placeholders.  I.e.:

```
  "valueUnitsPattern": {
    "value": "{0} {1}"
  },
```

**Comment by pixelzoom** [comment]
This probably deserves a more general issue, perhaps in scenery-phet.

The general issue is how (or whether) to change UI components that use numbered placeholders as part of their public API.  NumberControl and NumberDisplay do this through `options.valuePattern`.  Are their other common-code APIs that do something similar?  Should/can we change these APIs to use named placeholders?  What is the affect on client code? 

Note that the following clients would be affected by changes to NumberControl: cck, projectile-motion, gravity-force-lab, hookes-law, unit-rates.

**Comment by samreid** [comment]
In the preceding commit, I separated the strings so as not to mix the placeholder types and to give translators full control over those cases.  Closing.

**Comment by pixelzoom** [comment]
Reopening. circuit-construction-kit-common-strings_en.json now contains a mixture of numbered and named placeholders, and for things that are similar/identical.   For example:

```js
  "voltageUnits": {
    "value": "{{voltage}} V"
  },
  "voltageVoltsValuePattern": {
    "value": "{0} volts"
  },
```

Two issues with this:
(1) It's liable to be confusing to translators.
(2) It mixes different type of placeholders in new sim code.

So I think this issue should be left open until we reach a general consensus on how to address this in https://github.com/phetsims/scenery-phet/issues/317.

**Comment by samreid** [comment]
We decided to only use `{{named}}` in sim code and use an adapter to `{0}` where necessary.

**Comment by samreid** [comment]
@pixelzoom I switched to use named placeholders in the sim strings with an adapter for NumberControl, can you please review?

**Comment by pixelzoom** [comment]
👍 Closing.
