### ISSUE TITLE
Should this repo be MIT or GPL?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#383]
Our rule of thumb says common code is MIT and sim code is GPL.  Most of the CCK DC code is in CCK-common repo.  Should it be MIT?

**Comment by samreid** [comment]
@pixelzoom said scenery and sun (and their dependencies) should be MIT, and other things like shred and circuit-construction-kit-common should be GPL.  It looks like vibe should be MIT as well.

@pixelzoom says even if we do not change our overall policy regarding common code sim repos (like shred), cck-common should still be GPL since it is *only* used by CCK sims.

**Comment by samreid** [comment]
This seems like worth bringing up at developer meeting so we can decide if we want to change license or policy with repos like shred.

**Comment by samreid** [comment]
@jonathanolson says it is basically sim code so it would be GPL.  @ariel-phet recalls that a funder recommended a particular license like GPL-- @kathy-phet would know for sure.

@ariel-phet says circuit-construction-kit-common is basically "sim code" and should be GPL.

**Comment by samreid** [comment]
@jbphet and @samreid are wondering why everything can't be MIT?

**Comment by samreid** [comment]
It is already GPL, so we'll leave this as is, and leave the question in https://github.com/phetsims/circuit-construction-kit-common/issues/383#issuecomment-312071551 for future.

**Comment by pixelzoom** [comment]
6/29/17 dev meeting notes:

• circuit-construction-kit-common, inverse-square-law-common and shred should all be GPL
• why can't everything be MIT?
• if everything can't be MIT, why not make all PhET-specific common code GPL, and use MIT only for common code (and dependencies) that is useful outside of PhET?

**Comment by kathy-phet** [comment]
The basic thought was that common code like scenery could be available under MIT if some 3rd party wanted to build a proprietary software on top of it. 

For our sim-specific code, if someone wants to build a specialized version of it, we want that version available for use to anyone -- so we make the sim code GPL. If they want to build something proprietary using our sim-specific code as a base, they can always license the sim code from us directly and do that.

**Comment by samreid** [comment]
Thanks @kathy-phet, I've moved the discussion to https://github.com/phetsims/tasks/issues/875
