### ISSUE TITLE
Removing a circuit element causes an error.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#385]
After removing an item from the carousel, I get an error messge:
```throw new Error( 'Tried to set ' + key + ' after disposing a Node' );```

This isn't a problem in the latest [dev](http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.77/circuit-construction-kit-dc_en.html) version so this may be a new issue. Are you aware of this @samreid?

**Comment by Denz1994** [comment]
Pressing the trash can button and a drag/drop into the carousel will trigger this error as well.

**Comment by samreid** [comment]
Thanks @Denz1994, I think the recent node disposal scuttling revealed issues.  I'll investigate.

**Comment by Denz1994** [comment]
I'm actually getting the same error by just connecting elements together. For example, dragging out a battery and a wire, then connecting them raises an error.

**Comment by Denz1994** [comment]
Also using the backspace button produces the same error.

**Comment by samreid** [comment]
Proposed fix is above, @Denz1994 can you please test?

**Comment by Denz1994** [comment]
After testing, I can only replicate the issue with resistors and grab bag items. Could this have something to do with my commits in https://github.com/phetsims/circuit-construction-kit-common/commit/acd2e7dc279bc7d4eee30554ce7ec10ee96b2980

**Comment by samreid** [comment]
I fixed the dispose order in the above commit, can you please test?

**Comment by Denz1994** [comment]
After testing, I cannot reproduce the error. I am going to close this. Thank you for the fix.
