### ISSUE TITLE
Wire solders jump in Z-layering when connected to resistors.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#386]
Steps to reproduce:

1. drag out a resistor/grab bag item and drop it in play area
2. drag out a wire and connect it to the resistor in the play area
       - Note: the solder is behind the circuit items
3. drag out a resistor/grab bag item and connect it to the other vertex of the wire
4. at this point both solders on the vertex of the wire will jump forward in the z-layer ordering.

This is minor, but I don't know if this was intentional or not. Thoughts @samreid.

**Comment by samreid** [comment]
I think we want the solder to always be in front of the wires, so there is already a problem at step 2

![image](https://user-images.githubusercontent.com/679486/28378593-ebcb37b2-6c6d-11e7-8da8-87bd4cc356fc.png)

I think this will solve the problem.

**Comment by samreid** [comment]
In the above commit, after a connection, a relayering is scheduled for the simulation step.  This appears to solve the problem.  @Denz1994 can you please pull and verify?

**Comment by Denz1994** [comment]
After pulling and reviewing, I can't reproduce the bug or any similar bugs.

Thanks @samreid for fixing this.
