### ISSUE TITLE
Can schematic resistors in carousel use the same image?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#389]
During interviews, students thought there may be some meaning associated with the stroke weight of the schematic resistors in the carousel. 
![image](https://user-images.githubusercontent.com/8419308/28378603-f3c060b4-6c6d-11e7-8846-923bb713300d.png)

Luckily, students didn't extend this idea to comparing the size of the resistor symbols in the play area, which are sized so that the width is the same as the lifelike counterpart.
![image](https://user-images.githubusercontent.com/8419308/28378877-05e97612-6c6f-11e7-96a7-338f57510abc.png)

@samreid would it be possible to use the same image for the schematic resistors in the carousel? Once grabbed, the resistor would be appropriately sized as in the image above.

Here's what I'm imagining the updated carousel would look like:
![image](https://user-images.githubusercontent.com/8419308/28379105-cda138de-6c6f-11e7-9d94-527eda276eac.png)

**Comment by samreid** [comment]
Fixed above and will be ready for testing in next version.

**Comment by arouinfar** [comment]
@samreid no need to publish a new dev just for this. Pulled master and it looks great!
