### ISSUE TITLE
Series ammeter inconsistently displays 0

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#391]
Discovered in dev.91 for https://github.com/phetsims/QA/issues/26 on latest Mac/Chrome. Possibly related to https://github.com/phetsims/circuit-construction-kit-dc/issues/96.

The voltmeter and non-contact ammeter display a "?" when the probes aren't making contact with components (or when in a non-conductive area of component). For consistency, the series ammeter should do the same.

The series ammeter is also inconsistently displaying 0 amps/blank readout

These situations should always show ?
![image](https://user-images.githubusercontent.com/8419308/28476088-e8d253e8-6e0b-11e7-98e2-5ead72adf77b.png)
![image](https://user-images.githubusercontent.com/8419308/28476090-f0f3ec58-6e0b-11e7-9715-f7293708b758.png)

These situations should always show 0 
![image](https://user-images.githubusercontent.com/8419308/28475861-32c87ece-6e0b-11e7-957f-3902ee38b405.png)
![image](https://user-images.githubusercontent.com/8419308/28475893-4e1d8e3a-6e0b-11e7-8e1f-79d73d5ad505.png)

Desired behavior
* Display ? if neither/only one vertex is attached to something
* Display 0.000 A if both vertices are attached, but the circuit is incomplete

**Comment by arouinfar** [comment]
Doesn't need to be addressed for AAPT

**Comment by samreid** [comment]
Proposed fix is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.98/circuit-construction-kit-dc_en.html 

@arouinfar can you please test?

**Comment by arouinfar** [comment]
👍
