### ISSUE TITLE
Pointer area is wrong for SeriesAmmeter

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#398]
![image](https://user-images.githubusercontent.com/679486/30035056-441b94e2-9163-11e7-82ff-d9dfc159c412.png)

**Comment by samreid** [comment]
Fixed above, would be good to discuss with @jonathanolson why this fix is necessary.

**Comment by jonathanolson** [comment]
It's necessary right now because it keeps a reference.

**Comment by samreid** [comment]
Sounds good, thanks!
