### ISSUE TITLE
maxWidth needed on Battery's edit node

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/circuit-construction-kit-common#399]
![cck-area-1](https://user-images.githubusercontent.com/480878/30082086-c78eebb0-9246-11e7-8789-faf9181ad67f.PNG)

Overlaps with stringTest=long (more problematic with custom stringTest above).

**Comment by jonathanolson** [comment]
See https://github.com/phetsims/circuit-construction-kit-common/issues/317

**Comment by samreid** [comment]
Fixed, @jonathanolson can you please review?

**Comment by jonathanolson** [comment]
Looks good, thanks!
