### ISSUE TITLE
CCK common/dc include TWEEN dependency

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/circuit-construction-kit-common#400]
Is this vestigial (it looks so)?

https://github.com/phetsims/circuit-construction-kit-common/issues/317

**Comment by samreid** [comment]
I tried removing it, but it appears to be used by SUN/Carousel.

**Comment by jonathanolson** [comment]
Understood, good for now (will probably remove after https://github.com/phetsims/tasks/issues/360), thanks!
