### ISSUE TITLE
Multitouch issues

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#401]
@jonathanolson identified some multitouch issues, we should document them here then I'll try to address them.

**Comment by jonathanolson** [comment]
It looks like it should be possible to drag a vertex with multiple fingers, by basically dragging the vertex itself with one finger, and dragging connected components with other fingers.

Another example would be dragging two adjacent wires.

Ideally we'd have a lock on the vertex-level, that would prevent a vertex already being dragged from starting another drag.

**Comment by jonathanolson** [comment]
That's the only major thing I'd recommend handling.

See https://github.com/phetsims/circuit-construction-kit-common/issues/317

**Comment by samreid** [comment]
I confirmed that I see flickering when trying to drag the same vertex by the vertex node + by an adjacent circuit element node.

**Comment by samreid** [comment]
Given the existing implementation of CircuitLayerNode.dragVertex, it seems insufficient to track which vertices are already being dragged since we need to know whether to allow each start/drag/end event--instead we must track which pointer is dragging them and allow events to be processed if the pointer is the one that started the drag.  I'll commit something for review shortly.

**Comment by samreid** [comment]
Committed above, @jonathanolson and I are discussing on Slack, but I'll reassign to @jonathanolson in case we proceed with this strategy.

**Comment by samreid** [comment]
@jonathanolson can you please review the subsequent fixes (prevents Wire vertices from ending up with bad values for `isDragging`)?

**Comment by jonathanolson** [comment]
I'm not sure how this fixes the problem, or how the problem was caused.

The code looks safe (although somewhat more verbose), so I'm fine either if you want to close the issue or discuss.

**Comment by samreid** [comment]
To elaborate on the bug and why it may have caused the symptoms I saw, the implementation in `vertex-test` was like so:

```js
      this.dragHandler.startDrag = function( event ) {
        if ( circuitLayerNode.canDragVertex( wire.startVertexProperty.get() ) && circuitLayerNode.canDragVertex( wire.endVertexProperty.get() ) ) {
          SimpleDragHandler.prototype.startDrag.call( this, event );
        }
      };
```

However, `canDragVertex` was implemented like so:

```js
    canDragVertex: function( vertex ) {
      var vertices = this.circuit.findAllFixedVertices( vertex );

      // If any of the vertices in the subgraph is already being dragged, then this vertex cannot be dragged.
      for ( var i = 0; i < vertices.length; i++ ) {
        if ( vertices[ i ].isDragged ) {
          return false;
        }
      }
      for ( i = 0; i < vertices.length; i++ ) {
        vertices[ i ].isDragged = true;
      }

      return true;
    },
```

Imagine if the Wire startVertex had `canStartDrag` true but the endVertex had `canStartDrag` false.  Then the startVertex would get marked incorrectly as `isDragged=true`, and hence will nevermore be draggable.

**Comment by jonathanolson** [comment]
Ack, sorry about accidentally putting the isDragged mutator in what was supposed to be an immutable method. Looks good.
