### ISSUE TITLE
filename prefixes don't follow PhET conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#404]
This issue applied to both circuit-construction-kit-common and circuit-construction-kit-black-box-study.  

The convention for filename prefixes is to use either the full name of the repository, or the abbreviated acronym for the repository.  E.g for expression-exchange, we would have either ExpressionExchangeConstants.js or EEConstants.js.   The choice is up to the developer, should be applied consistently, and should not duplicate an abbreviation that is already used by another repository.  

circuit-construction-kit-common and circuit-construction-kit-black-box-study don't use either convention.  circuit-construction-kit-common uses the prefix "CircuitConstructionKit", while circuit-construction-kit-black-box-study uses the prefix "BlackBox".   If verbosity is the issue, they could use "CCKC" and "CCKBBS" respectively.

I don't know if this was flagged in code review.

**Comment by samreid** [comment]
Fixed in the preceding commits.  @pixelzoom or @jonathanolson do you want to review?

**Comment by jonathanolson** [comment]
I didn't flag this in my code review, as it's something I've also done. I'd prefer @pixelzoom reviews due to that.

**Comment by pixelzoom** [comment]
Looks good.  

@samreid To clarify... Is `BlackBoxQueryParameters` query parameters that are specific to a screen named "Black Box"?  Or are they specific to a sim?  I've never seen *QueryParameters.js file that is screen-specific. (I tried to run circuit-construction-kit-black-box-study_en.html, but it fails at startup.)

**Comment by samreid** [comment]
I will rename BlackBox*.js to CCKBBS*.js in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/61.  

> Does BlackBoxQueryParameters contain query parameters that are specific to a screen named "Black Box"? Or are they specific to a sim? 

They are for the "Circuit Construction Kit: Black Box Study" sim, which was nicknamed as Black Box for some of the filenames, which will be fixed in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/61.
