### ISSUE TITLE
Zero-length wires break charge animation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#405]
Subtlely different than #281 since we are dealing with actual zero-length wires (not "near" zero-length wires). You can create these by:

1. Make a circuit with at least 3 consecutive wires. The specifics of the circuit other than this probably don't matter.
2. Enable electrons, can't get this to happen with conventional arrows yet.
3. With your 3 consecutive wires, take one of the middle vertices (number 62 in below gif) and drag it to the top left corner of the screen. Keep dragging past the screen bounds so that the wire is positioned at (0, 0).
4. Do the same thing with the wire's other vertex (number 64) so it too is placed at (0, 0).

If an assertion wasn't thrown here, you will need to sort of "push" the vertices closer to the edge by continuing to try and drag them off screen.

![cckdc18](https://user-images.githubusercontent.com/5863899/31088940-9b85e202-a75f-11e7-8cba-09c5ab86814f.gif)

```
ChargeAnimator.js?bust=1506962237850:282 Uncaught TypeError: Cannot read property 'distance' of undefined
    at ChargeAnimator.propagate (ChargeAnimator.js?bust=1506962237850:282)
    at ChargeAnimator.step (ChargeAnimator.js?bust=1506962237850:154)
    at Circuit.step (Circuit.js?bust=1506962237850:781)
    at IntroScreenModel.step (CircuitConstructionKitModel.js?bust=1506962237850:219)
    at Sim.stepSimulation (Sim.js?bust=1506962237850:842)
    at Sim.runAnimationLoop (Sim.js?bust=1506962237850:782)
```

Do these steps again, but with conventional arrows (or no current) for a fun consequence. A set-up with a zero-length wire will not let you attach anything to it!

![cckdc19](https://user-images.githubusercontent.com/5863899/31089056-fb0b5b58-a75f-11e7-91ae-5c3a0c4368b8.gif)

I did all of this on master, but was able to reproduce in dev.162 (except without the assertion because of assertion filtering). For the record, this will cause electron bunching in dev.162, but that's not what this issue is discussing! Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/51.

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.162/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.162 2017-09-19 15:30:35 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1419x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3da47e60","branch":"listeners"},"babel":{"sha":"8024993e","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"beecf7e3","branch":"master"},"circuit-construction-kit-common":{"sha":"b0a1151d","branch":"master"},"circuit-construction-kit-dc":{"sha":"0b1708fd","branch":"master"},"dot":{"sha":"d2a1e0db","branch":"master"},"joist":{"sha":"4ac9bf9d","branch":"master"},"kite":{"sha":"5a200449","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"b7e4a6a4","branch":"master"},"scenery-phet":{"sha":"f8b1c996","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"569ad84b","branch":"master"},"tandem":{"sha":"3b161ec8","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by BryceAG** [comment]
I found a couple of things to add to this issue. First, the charge animation is not the only part that is broken, it is the entire display. The sim is still interactive but appears frozen. In the gif below I reproduce the broken circuit, but then move a battery onto the screen, maximize the display, and switch to conventional current. The display only updates after switching to conventional, but the battery and display size also update at that time.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/15327201/31092232-eeb023c4-a76a-11e7-8068-ec1473a124ab.gif)

Also I was able to reproduce the part where you can't attach anything to the wires with electron current too.

**Comment by samreid** [comment]
Proposed fix committed above.  @phet-steele and @BryceAG can you take a look?

**Comment by phet-steele** [comment]
Nice hollywooding, the assertion is fixed for me. However, I still cannot connect components to vertices 61 & 68 (in my original gif).

**Comment by samreid** [comment]
Interesting, thanks!  I'll look into it.

**Comment by phet-steele** [comment]
@samreid, trying to cut the zero-length connection throws:

```
assert.js:22 Uncaught Error: Assertion failed: invalid value: Vector2(NaN, NaN)
    at window.assertions.assertFunction (assert.js:22)
    at Property.set (Property.js?bust=1507062400979:140)
    at Vertex.setPosition (Vertex.js?bust=1507062400979:124)
    at Circuit.translateVertexGroup (Circuit.js?bust=1507062400979:561)
    at Circuit.js?bust=1507062400979:533
    at Array.forEach (<anonymous>)
    at Circuit.cutVertex (Circuit.js?bust=1507062400979:521)
    at CircuitLayerNode.js?bust=1507062400979:334
    at PushButtonModel.js?bust=1507062400979:161
    at Array.forEach (<anonymous>)
window.assertions.assertFunction @ assert.js:22
set @ Property.js?bust=1507062400979:140
setPosition @ Vertex.js?bust=1507062400979:124
translateVertexGroup @ Circuit.js?bust=1507062400979:561
(anonymous) @ Circuit.js?bust=1507062400979:533
cutVertex @ Circuit.js?bust=1507062400979:521
(anonymous) @ CircuitLayerNode.js?bust=1507062400979:334
(anonymous) @ PushButtonModel.js?bust=1507062400979:161
fire @ PushButtonModel.js?bust=1507062400979:160
(anonymous) @ PushButtonModel.js?bust=1507062400979:84
emit2 @ Emitter.js?bust=1507062400979:216
_notifyListeners @ Property.js?bust=1507062400979:207
_setAndNotifyListeners @ Property.js?bust=1507062400979:195
set @ Property.js?bust=1507062400979:142
up @ ButtonListener.js?bust=1507062400979:49
buttonUp @ DownUpListener.js?bust=1507062400979:125
up @ DownUpListener.js?bust=1507062400979:58
dispatchToListeners @ Input.js?bust=1507062400979:790
dispatchEvent @ Input.js?bust=1507062400979:760
upEvent @ Input.js?bust=1507062400979:629
mouseUp @ Input.js?bust=1507062400979:341
pointerUp @ Input.js?bust=1507062400979:557
run @ BatchedDOMEvent.js?bust=1507062400979:57
fireBatchedEvents @ Input.js?bust=1507062400979:204
batchEvent @ Input.js?bust=1507062400979:180
batchWindowEvent @ BrowserEvents.js?bust=1507062400979:279
onpointerup @ BrowserEvents.js?bust=1507062400979:310
```

**Comment by samreid** [comment]
Proposed fix committed above, @phet-steele can you take a look on phettest?

**Comment by phet-steele** [comment]
You fixed the assertion in https://github.com/phetsims/circuit-construction-kit-common/issues/405#issuecomment-333968178, but of course we still have https://github.com/phetsims/circuit-construction-kit-common/issues/405#issuecomment-333904472, so back to you @samreid!

**Comment by samreid** [comment]
Here is the rule that prevents connection in this circumstance:

```js
        // (7) a wire vertex cannot connect if its neighbor is already proposing a connection
        // You can always attach to a black box interface
        if ( !candidateVertex.blackBoxInterfaceProperty.get() ) {
          var neighbors = self.getNeighborCircuitElements( candidateVertex );
          for ( i = 0; i < neighbors.length; i++ ) {
            var neighbor = neighbors[ i ];
            var oppositeVertex = neighbor.getOppositeVertex( candidateVertex );

            // is another node proposing a match to that node?
            for ( var k = 0; k < self.vertices.length; k++ ) {
              var v = self.vertices.get( k );
              if ( neighbor instanceof Wire &&
                   v !== vertex &&
                   v !== oppositeVertex && v.positionProperty.get().equals( oppositeVertex.positionProperty.get() ) ) {
                return false;
              }
            }
          }
        }
```

Basically, it thinks that the opposite vertex already has a proposed connection (snapping behavior) because it sees an unattached vertex with the exact same coordinates.  I don't remember why we added this rule.  We could maybe refine it by checking that the `v` vertex has `isDragged` true?

**Comment by samreid** [comment]
I added the `isDragged` check and confirmed that the corner issue can connect and tested on iPad2 you still cannot connect when another connection is proposed, committing.

**Comment by samreid** [comment]
Proposed fix pushed above, @phet-steele can you please test it out on phettest?

**Comment by phet-steele** [comment]
@samreid does the above commit cause this error when I press a battery's flip button?

```
Uncaught Error: Assertion failed: Cannot add the same listener twice
    at window.assertions.assertFunction (assert.js:22)
    at Emitter.addListener (Emitter.js?bust=1507230568175:97)
    at Property.link (Property.js?bust=1507230568175:246)
    at Battery.linkVertex (CircuitElement.js?bust=1507230568175:148)
    at Emitter.emit2 (Emitter.js?bust=1507230568175:216)
    at Property._notifyListeners (Property.js?bust=1507230568175:207)
    at Property._setAndNotifyListeners (Property.js?bust=1507230568175:195)
    at Property.set (Property.js?bust=1507230568175:142)
    at Property.set value [as value] (Property.js?bust=1507230568175:236)
    at Circuit.flip (Circuit.js?bust=1507230568175:1126)
```

**Comment by samreid** [comment]
That is a new issue from axon's merge, I'll create a new issue.

**Comment by samreid** [comment]
@phet-steele I created a new issue for the listener problem, anything else for this issue?

**Comment by phet-steele** [comment]
I think we are fixed here, thanks @samreid.
