### ISSUE TITLE
Probes do not update value when components are pushed away from them

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#407]
1. Set up a short with two wires and a battery (this isn't the only possible setup, but I had to tell you to set _something_ up!)
2. Drag the wire connection out so you've made a triangle shape with decently long side lengths, like this:
<img width="313" alt="screen shot 2017-10-02 at 2 11 24 pm" src="https://user-images.githubusercontent.com/5863899/31097217-c7b6ceb0-a77b-11e7-8dd8-eda5397a9fa7.png">

3. Place the ammeter probe _just_ on the inner edge of a wire, like this:
<img width="452" alt="screen shot 2017-10-02 at 2 11 36 pm" src="https://user-images.githubusercontent.com/5863899/31097218-c7b743a4-a77b-11e7-9f1c-3230e23424ab.png">
4. Cut the wire-wire connection! The ammeter will correctly be reading 0.00 A....but it shouldn't be reading anything at all! It isn't anywhere near the wire's hit area. Wiggle the other wire to "update" the probe to the correct readout.
<img width="497" alt="screen shot 2017-10-02 at 2 11 45 pm" src="https://user-images.githubusercontent.com/5863899/31097219-c7be42e4-a77b-11e7-926b-5b2e797a1fdb.png">
(after wiggling the right wire)
<img width="477" alt="screen shot 2017-10-02 at 2 11 55 pm" src="https://user-images.githubusercontent.com/5863899/31097220-c7be7e1c-a77b-11e7-9440-3ebf2c199e09.png">
5. Go back to the setup in step 2. Place a voltmeter probe on a battery terminal and the other at the wire-wire connection, like this:
<img width="487" alt="screen shot 2017-10-02 at 2 12 22 pm" src="https://user-images.githubusercontent.com/5863899/31097221-c7bfcab0-a77b-11e7-90e1-affb263f027e.png">
6. Cut the wire-wire connection! Same story with the correct value being read, but there shouldn't be a value at all. Wiggle the battery to "update" the readout.
<img width="510" alt="screen shot 2017-10-02 at 2 12 30 pm" src="https://user-images.githubusercontent.com/5863899/31097222-c7c10470-a77b-11e7-94ac-14f76b02631e.png">
(after wiggling the battery)
<img width="530" alt="screen shot 2017-10-02 at 2 12 35 pm" src="https://user-images.githubusercontent.com/5863899/31097223-c7cad540-a77b-11e7-9677-984b5f743a01.png">
Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/51.

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.162/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.162 2017-09-19 15:30:35 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1419x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3da47e60","branch":"listeners"},"babel":{"sha":"8024993e","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"beecf7e3","branch":"master"},"circuit-construction-kit-common":{"sha":"b0a1151d","branch":"master"},"circuit-construction-kit-dc":{"sha":"0b1708fd","branch":"master"},"dot":{"sha":"d2a1e0db","branch":"master"},"joist":{"sha":"4ac9bf9d","branch":"master"},"kite":{"sha":"5a200449","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"b7e4a6a4","branch":"master"},"scenery-phet":{"sha":"f8b1c996","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"569ad84b","branch":"master"},"tandem":{"sha":"3b161ec8","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by samreid** [comment]
Cut calls Circuit.solve which calls circuitChangedEmitter.emit, which updates the values in the node.  But perhaps something is out of sync?  AmmeterNode uses Node.hitTest which I thought would be synchronous, but perhaps we have to wait for a display.update?

**Comment by samreid** [comment]
Good one @phet-steele, can you please test the fix committed above?

**Comment by samreid** [comment]
Dev version is available here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.163/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
Cool fix, thanks @samreid.
