### ISSUE TITLE
Electron lines

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#408]
@samreid @jonathanolson CCK is also suffering from electron lines on my computer (see https://github.com/phetsims/circuit-construction-kit-common/issues/281#issuecomment-333920759)

<img width="819" alt="screen shot 2017-10-03 at 11 33 30 am" src="https://user-images.githubusercontent.com/5863899/31196265-4fecbd50-a90a-11e7-96f0-f17f5c00dfdc.png">
<img width="794" alt="screen shot 2017-10-03 at 11 33 52 am" src="https://user-images.githubusercontent.com/5863899/31196264-4fc2403e-a90a-11e7-9424-4a00c24fd807.png">

This is the same issue as phetsims/john-travoltage/issues/193. Details from that issue include:

- Chrome issue, currently 61.0.3163.100
- I use a 15-inch retina, mid-2015 model MacBook pro
- @samreid cannot reproduce with his MacBook (I don't know specs, but I know it is a new model)
- Cannot reproduce with `?rootRenderer=canvas`. Looks likely to be a Chrome SVG issue, possibly high-dpi specific.
- Happens now in at least four sims: JT, CCKDC, ExEx, and GAO.
- (it was requested to be made into a common-code issue but hasn't received too much attention lately)

Seen with dev.163. For phetsims/QA/issues/51.
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.163/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.163 2017-10-03 16:38:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"1fd5dcd3","branch":"master"},"babel":{"sha":"adecb659","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"c4082c17","branch":"master"},"circuit-construction-kit-common":{"sha":"fb48ca32","branch":"master"},"circuit-construction-kit-dc":{"sha":"372785fb","branch":"master"},"dot":{"sha":"8c2cfa7f","branch":"master"},"joist":{"sha":"f59c30f2","branch":"master"},"kite":{"sha":"207e833f","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"3b901d84","branch":"master"},"scenery-phet":{"sha":"849ff831","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"5f279f5d","branch":"master"},"tandem":{"sha":"de2aad71","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by samreid** [comment]
@ariel-phet can you help prioritize with respect to CCK 1.0?

**Comment by ariel-phet** [comment]
@samreid sounds like @phet-steele is the only one who has seen this issue, and it is pretty minor, deferred for now. Definitely not part of 1.0 work.

**Comment by samreid** [comment]
https://github.com/phetsims/scenery/issues/810 was deferred, I'll defer this to match it.

**Comment by samreid** [comment]
This issue has not been observed for a long time.  Closing, but we can reopen if it is observed in upcoming dev tests.
