### ISSUE TITLE
Cutting and deleting while dragging breaks interaction

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#414]
1. Connect at least two fixed length elements together.
2. Click/touch a vertex.
3. Begin dragging the same vertex, the cut button remains.
4. Use another finger (or the delete button) to press the cut button while dragging.

Everything in each vertex group is now un-interactive (cannot be dragged). You may still snap to the newly cut vertices, but not to any others within the original vertex group.
![cckdc23](https://user-images.githubusercontent.com/5863899/31567778-5577b164-b02e-11e7-8c19-568d29b73742.gif)

This same procedure can be done with deleting instead of cutting. Replace instances of vertices in the above procedure with the body of an element:
1. Connect at least two fixed length elements together.
2. Click/touch an element.
3. Begin dragging the same element, the highlight remains.
4. Use another finger (or the delete button) to press the delete button while dragging.

Not labelling as multitouch since we allow cutting/deleting with a key press (the delete button), so you can do this without multiple fingers.

Does not throw an error.

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/51.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.166/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.166 2017-10-11 16:23:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"b8dd4e51","branch":"master"},"babel":{"sha":"45eca7d2","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"66763c36","branch":"master"},"circuit-construction-kit-common":{"sha":"7d852b4c","branch":"master"},"circuit-construction-kit-dc":{"sha":"22604c0e","branch":"master"},"dot":{"sha":"84bc5146","branch":"master"},"joist":{"sha":"3eff115f","branch":"master"},"kite":{"sha":"9689a3de","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"db7ea875","branch":"master"},"scenery-phet":{"sha":"a90363b5","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"d57850fd","branch":"master"},"tandem":{"sha":"f399e7ee","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by ariel-phet** [comment]
@samreid this seems like a legit bug since it breaks the interaction and does not technically require multitouch. Worth 1-2 hours of investigation. If it is turning into more and that, let's you and I discuss.

**Comment by samreid** [comment]
On current master (includes some changes compared to what was tested in initial comment) I am not seeing the bug for pressing the delete button.  I do see the bug for cutting a dragged vertex though on iPad.

**Comment by samreid** [comment]
The simplest solution is to prevent cutting vertices that are being dragged (committed above).  It isn't a perfect user experience because the cut button is still visible and enabled for a dragged vertex, but pushing it does nothing.  However, I think this will be rare and when it does happen it will no longer create dead circuit elements, so perhaps it is good for 1.0.

**Comment by ariel-phet** [comment]
@samreid that seems like an acceptable solution

**Comment by ariel-phet** [comment]
@phet-steele can you verify on master?

**Comment by phet-steele** [comment]
@samreid this works for the cut button, but I'm still having issues with the delete button. Can we try the same approach as the cut button?

**Comment by samreid** [comment]
Thanks for the suggestion, proposed fix is committed, can you please test?

**Comment by phet-steele** [comment]
Nice! Thanks.
