### ISSUE TITLE
Dragged elements can be bounced, causing their vertices to be moved

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#415]
1. Drag out three fixed length elements. Don't connect them. I like to use a lightbulb for one of the three (you should too if you like to have fun!)
2. Drag the lightbulb by its body until it snaps to a vertex, DON'T release. Just hold the lightbulb in place while snapped.
3. With another finger, take the lonely element and snap it to the same vertex you chose in step 2. Release and let it connect.

This should cause the lightbulb you were holding to bounce away. If it doesn't, repeat. If it does, drag the lightbulb around and notice that one of its vertices is misplaced. You can do this with any element, but the lightbulb is especially fun since creating a circuit with it will create jumping electrons. You'll see this towards the end of the video, look at the upper lightbulb socket.
![cckdc24](https://user-images.githubusercontent.com/5863899/31568326-ee8000bc-b030-11e7-820f-521e587654fd.gif)

@ariel-phet @samreid Easy fix for this seems to be to not let user controlled elements be bounced?

(ignore that the video is on phettest)
Seen on iPad Air 2 iOS 9.3.5. For phetsims/QA/issues/51.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.166/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.166 2017-10-11 16:23:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"b8dd4e51","branch":"master"},"babel":{"sha":"45eca7d2","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"66763c36","branch":"master"},"circuit-construction-kit-common":{"sha":"7d852b4c","branch":"master"},"circuit-construction-kit-dc":{"sha":"22604c0e","branch":"master"},"dot":{"sha":"84bc5146","branch":"master"},"joist":{"sha":"3eff115f","branch":"master"},"kite":{"sha":"9689a3de","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"db7ea875","branch":"master"},"scenery-phet":{"sha":"a90363b5","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"d57850fd","branch":"master"},"tandem":{"sha":"f399e7ee","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by ariel-phet** [comment]
I see this as an edge-case, and not critical to fix. @phet-steele seems to feel this would be an easy fix. Your call @samreid if you want to try to fix after a quick investigation (feel free to defer if not)

**Comment by samreid** [comment]
The commit above prevents bumping when vertices are being dragged.  It appears to fix this case on iPad.  I also tested that dragging one battery on top of another still correctly bumps away.  But this could use some testing to make sure nothing else is disturbed.

**Comment by phet-steele** [comment]
This is working for me, thanks!
