### ISSUE TITLE
TypeError: null is not an object (evaluating 'v.x')

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#416]
Testing on current master.

1. Highlight a battery.
2. Drag that battery.
3. While dragging, flip the battery with another finger.

Throws:
```
[Error] TypeError: null is not an object (evaluating 'v.x')
	subtract (Vector2.js:701)
	dragVertex (CircuitLayerNode.js:581)
	drag (FixedCircuitElementNode.js:152:83)
	move (SimpleDragHandler.js:142)
	dispatchToListeners (Input.js:790)
	dispatchEvent (Input.js:760)
	branchChangeEvents (Input.js:688)
	moveEvent (Input.js:653)
	touchMove (Input.js:440)
	run (BatchedDOMEvent.js:67)
	fireBatchedEvents (Input.js:204)
	batchEvent (Input.js:180)
	batchWindowEvent (BrowserEvents.js:279)
	ontouchmove (BrowserEvents.js:518)
```

Seen on iPad Air 2 iOS 9.3.5. For phetsims/QA/issues/51.

**Comment by ariel-phet** [comment]
This bug does not seem to affect sim use. @samreid your call if you want to do anything about it for 1.0

Feel free to mark deferred if this is more than a short fix (less than 30 minutes)

**Comment by samreid** [comment]
I added a check that should prevent the error.  The behavior looks the same on iPad, but hopefully doesn't throw the error. I didn't tether to verify this yet.  I'll leave assigned to me and also assign to @phet-steele to see who gets a tether report first.

**Comment by samreid** [comment]
I simulated multitouch on mac chrome and verified the error is gone.  Reassigning to @phet-steele to double check everything.

**Comment by phet-steele** [comment]
Fixed, thanks.
