### ISSUE TITLE
Ammeters don't update after deletions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#418]
Very similar to #407, but deals with components being deleted instead of moved. Right off the bat...the voltmeter seems to handle things well (or at least it's harder to make break), so ignore it in this issue.

1. Setup a circuit like this:

<img width="710" alt="screen shot 2017-10-13 at 4 56 53 pm" src="https://user-images.githubusercontent.com/5863899/31569404-09de431c-b038-11e7-9614-464f25443aae.png">
2. Delete the wire the ammeter is measuring. The ammeter will still show current. The in-line one will be correct.

<img width="717" alt="screen shot 2017-10-13 at 4 57 01 pm" src="https://user-images.githubusercontent.com/5863899/31569405-09ed794a-b038-11e7-8c2c-f9a9c98d7831.png">
3. Now setup the same thing, except make the battery 0 V.

<img width="668" alt="screen shot 2017-10-13 at 4 57 11 pm" src="https://user-images.githubusercontent.com/5863899/31569406-09fdf6f8-b038-11e7-98bc-89580178d342.png">
4. Delete the wire the ammeter is measuring. Both ammeters will still show current. So when the in-line ammeter measures 0.00 A before the deletion, it breaks?

<img width="720" alt="screen shot 2017-10-13 at 4 57 16 pm" src="https://user-images.githubusercontent.com/5863899/31569407-0a0d0ecc-b038-11e7-8946-2b4a3ed37440.png">

To be clear, the problem is that ammeters will still measure current when there should be none. Moving a circuit element will fix the readouts.

Seen on macOS 10.12.6 Chrome. For phetsims/QA#51.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.166/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.166 2017-10-11 16:23:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"b8dd4e51","branch":"master"},"babel":{"sha":"45eca7d2","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"66763c36","branch":"master"},"circuit-construction-kit-common":{"sha":"7d852b4c","branch":"master"},"circuit-construction-kit-dc":{"sha":"22604c0e","branch":"master"},"dot":{"sha":"84bc5146","branch":"master"},"joist":{"sha":"3eff115f","branch":"master"},"kite":{"sha":"9689a3de","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"db7ea875","branch":"master"},"scenery-phet":{"sha":"a90363b5","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"d57850fd","branch":"master"},"tandem":{"sha":"f399e7ee","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by ariel-phet** [comment]
@samreid this seems like a more legit bug. Since moving circuit elements fixes it, I could live with it for 1.0, but would prefer not to. Worth investigating a fix.

**Comment by samreid** [comment]
Proposed fix is above, @phet-steele can you please investigate?

**Comment by phet-steele** [comment]
@samreid steps 1 & 2 are fixed, but 3 & 4 haven't change for the SERIES ammeter (the contact ammeter is fine). Starting at 0.00 A, the series ammeter doesn't update after a delete:

<img width="849" alt="screen shot 2017-10-16 at 10 25 25 am" src="https://user-images.githubusercontent.com/5863899/31623344-5a0caf6a-b25c-11e7-8387-f3f103584f77.png">

**Comment by samreid** [comment]
Many thanks @phet-steele, proposed fix committed.

**Comment by phet-steele** [comment]
Works great, thanks @samreid!
