### ISSUE TITLE
?stringTest=double ammeter readout expands over vertices

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#419]
@samreid I don't think this is a big deal, but it looks odd. If you look below, the readout is expanded over the vertices slightly. This is also true of the image in the sensor tool box. Not so sure it even needs to expand that far?

<img width="639" alt="screen shot 2017-10-17 at 2 58 03 pm" src="https://user-images.githubusercontent.com/5863899/31689160-d046b3fc-b34b-11e7-9a2c-b6ccc9cb2c35.png">

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/55.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.1/circuit-construction-kit-dc_en.html?stringTest=double
Version: 1.0.0-rc.1 2017-10-17 18:05:58 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"8a8ff7d2","branch":"HEAD"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"b8a3c09a","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"11736e99","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"5cbdc391","branch":"HEAD"},"dot":{"sha":"84bc5146","branch":"HEAD"},"joist":{"sha":"92b186e2","branch":"HEAD"},"kite":{"sha":"067109a8","branch":"HEAD"},"phet-core":{"sha":"054b2d6d","branch":"HEAD"},"phetcommon":{"sha":"b13138d2","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"c9c3052a","branch":"HEAD"},"scenery-phet":{"sha":"124c1c25","branch":"HEAD"},"sherpa":{"sha":"0d590744","branch":"HEAD"},"sun":{"sha":"082fee37","branch":"HEAD"},"tandem":{"sha":"98e9917c","branch":"HEAD"},"twixt":{"sha":"a2eaa10a","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@samreid....I'm not entirely sure if the readout has a maxWidth 😄  
<img width="759" alt="screen shot 2017-10-17 at 3 07 24 pm" src="https://user-images.githubusercontent.com/5863899/31689554-fa79828e-b34c-11e7-8046-4dfda3d87413.png">

**Comment by phet-steele** [comment]
I suppose it is also important to note that you cannot see electrons passing through?

**Comment by samreid** [comment]
Fix pushed to master and needs to be merged into the RC for RC.2.

**Comment by samreid** [comment]
Merged and ready for testing in next rc.

**Comment by samreid** [comment]
Dev version is here: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.167/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Will be ready for RC testing in https://github.com/phetsims/QA/issues/59

**Comment by phet-steele** [comment]
Looks great.
