### ISSUE TITLE
Ammeter border is too close for comfort

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#420]
@samreid @arouinfar I'm concerned that the black "border" of the contact ammeter dips down too closely to the title string. What do you think? Do we have room to move these strings down (or some other solution)? We never noticed since the default english string "Current" has the small character "r" in the middle of the word. However, "Hello" as tall characters.
<img width="343" alt="screen shot 2017-10-17 at 3 39 05 pm" src="https://user-images.githubusercontent.com/5863899/31691113-1f0aae8e-b352-11e7-9b5d-3ab8dc6b2fc2.png">

Similarly, some sort of logographic language might have tall characters that overlap:
<img width="339" alt="screen shot 2017-10-17 at 3 46 52 pm" src="https://user-images.githubusercontent.com/5863899/31691196-6e243fbc-b352-11e7-8dd7-2e61e33944ef.png">

For phetsims/QA/issues/55.

**Comment by arouinfar** [comment]
Good catch @phet-steele. 

Seems like this would easily be fixed by moving the title string down by a pixel or two @samreid.

**Comment by samreid** [comment]
Proposed fix after adjustment:

![image](https://user-images.githubusercontent.com/679486/31965759-995b998c-b8c5-11e7-873f-dcd472cd9d13.png)

**Comment by samreid** [comment]
Committed to the branch and ready for testing in next RC.

**Comment by samreid** [comment]
Dev version is here: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.167/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Will be ready for RC testing in https://github.com/phetsims/QA/issues/59

**Comment by phet-steele** [comment]
Looks great.
