### ISSUE TITLE
Unrealistic pencil resistance

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#422]
In CCK, the pencil's resistance is 300 ohms. I have never given this number much thought until I started working on the Teacher Tips.

Pure graphite has a resistivity of 0.0000138 ohm-meters, and a typical wooden pencil has a core diameter of 2.2mm, and a length of 17.5cm (when new), resulting in a resistance of ~0.6 ohms. The CCK pencil is pretty stubby, so it would likely be perceived to be shorter than a typical wooden pencil, making the resistance even smaller.

In reality, pencil cores are typically a mixture of graphite and clay, which increases the resistance a bit to ~5-25 ohms, depending on the hardness. At best, 300 ohms is 12x too large (again, assuming the dimensions of a typical brand new pencil).

I realize that 300 ohms was likely chosen so there would be an item with a mid-range resistance in the grab bag (everything else is 0, 10^6 , or 10^9 ohms), but it still seems like an arbitrary choice to me. While I did not run into user complaints about the pencil resistance on Unfuddle, I am not particularly keen on describing the pencil as "graphite" or "pencil lead" (as we do in Java) when it has such an large resistance.

A few options
1.  Change pencil resistance to something a bit more realistic, perhaps 25 or 30 ohms. 
2.  Keep pencil resistance at 300 ohms, but do not describe it as graphite in the Teacher Tips (as was originally intended)

Given the lack of user complaints, I would be fine with option (2) if the original intention was to have a mid-range resistance in the grab bag. Thoughts @samreid @ariel-phet?

**Comment by samreid** [comment]
I'd prefer to use an accurate estimate for the pencil resistance.

**Comment by ariel-phet** [comment]
@arouinfar interesting point. I would go for a realistic resistance. Since we have so much adjustable resistance, I think this is fine.

On a related note, in a future version of the sim, it might be interesting to have a resistor that can have its resistance changed via dimensional changes. So when you tap to edit you change the cross section or just change the length (or both). That would tie nicely to RIAW. Perhaps we should make a separate issue for that as a possible future feature.

**Comment by ariel-phet** [comment]
@samreid please go ahead and change the pencil resistance.

**Comment by arouinfar** [comment]
Great suggestion @ariel-phet! I've opened the above issue for a resistor with adjustable dimensions.  

@samreid let's go with a 25 ohm pencil.

**Comment by samreid** [comment]
Fixed in the RC branch, ready for testing in next RC.

**Comment by samreid** [comment]
Dev version is here: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.167/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Will be ready for RC testing in https://github.com/phetsims/QA/issues/59

**Comment by phet-steele** [comment]
Great!
