### ISSUE TITLE
Edge has poor performance when dragging light bulbs

### ISSUE THREAD

**Issue by BryceAG** [phetsims/circuit-construction-kit-common#423]
related to phetsims/QA#55

When dragging a light bulb in Edge, the frame rate will drop to ~10 fps. It does not happen for other objects, just light bulbs. Both normal and high resistance light bulbs will cause the error, and dragging by the body or one of the joints does not matter.

In the gif below I drag a battery for comparison, then drag the light bulb. It initially drops to 30 fps, but will correct itself to 11 fps at the end.
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/15327201/31743813-c9ec6604-b419-11e7-80db-39a62041d2e4.gif)

**Comment by ariel-phet** [comment]
@samreid lets not spend any time on Edge performance for 1.0

**Comment by samreid** [comment]
@arouinfar and @ariel-phet do you want any work on this for the AC publication?

**Comment by samreid** [comment]
I marked as `type:wontfix` based on discussion in the slack channel.  Up to @ariel-phet whether it should also be closed.

**Comment by ariel-phet** [comment]
I am fine with this issue being closed
