### ISSUE TITLE
Cut button can be dismissed without dismissing the highlight

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#427]
@samreid this requires touch input (because I think `touchSnag` is needed).

1. Connect two elements together and drag their connection near the carousel.
2. Place them in such a way that when the cut button is shown, the button covers (or at least somewhat overlaps) and object in the carousel, like this:
<img width="358" alt="screen shot 2017-10-24 at 12 47 57 pm" src="https://user-images.githubusercontent.com/5863899/31962247-4d8e2d72-b8ba-11e7-8e97-0894bedd5425.png">

3. Press your finger down on the cut button so it depresses, but don't release.
4. Drag your finger so that `touchSnag` picks up the element beneath the cut button.

This will dismiss the cut button, but not the highlight around the node.
![cckdc27](https://user-images.githubusercontent.com/5863899/31962258-5722b60a-b8ba-11e7-85ae-ace725de85cc.gif)

Seen on macOS 10.12.6 Chrome (with emulated touch) and iPad 2 iOS 9.3.5. For phetsims/QA/issues/55.

URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.1/circuit-construction-kit-dc_en.html
Version: 1.0.0-rc.1 2017-10-17 18:05:58 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"8a8ff7d2","branch":"HEAD"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"b8a3c09a","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"11736e99","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"5cbdc391","branch":"HEAD"},"dot":{"sha":"84bc5146","branch":"HEAD"},"joist":{"sha":"92b186e2","branch":"HEAD"},"kite":{"sha":"067109a8","branch":"HEAD"},"phet-core":{"sha":"054b2d6d","branch":"HEAD"},"phetcommon":{"sha":"b13138d2","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"c9c3052a","branch":"HEAD"},"scenery-phet":{"sha":"124c1c25","branch":"HEAD"},"sherpa":{"sha":"0d590744","branch":"HEAD"},"sun":{"sha":"082fee37","branch":"HEAD"},"tandem":{"sha":"98e9917c","branch":"HEAD"},"twixt":{"sha":"a2eaa10a","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
Seems like a non problematic edge case, will investigate as part of 1.1

**Comment by samreid** [comment]
In design meeting today, we decided it is enough of a corner case that it can be closed.
