### ISSUE TITLE
Flickering item when rapidly grabbing items from the carousel

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#428]
@samreid @ariel-phet, on somewhat slower devices (I say somewhat because this is still seen on good iPads, but hard to see on laptops), you can see a flickering effect when rapidly grabbing/releasing an item out of the carousel. I usually see this more when grabbing the last of an item.

This is easy to do with one-ofs, like the dollar bill. While rapidly grabbing then releasing the item, if you look towards the center of the screen, you can see your item flicker:
![cckdc28](https://user-images.githubusercontent.com/5863899/31963716-e56df920-b8be-11e7-8418-71123aa2c5b3.gif)

@samreid I took some frames from that video that maybe reveal something:

Frame 0 (before release)
<img width="580" alt="screen shot 2017-10-24 at 1 22 28 pm" src="https://user-images.githubusercontent.com/5863899/31963728-ef079338-b8be-11e7-843c-996c692a3a9d.png">

Frame 1 (after release). Note how the object was being disposed, and there are floating vertices over the carousel. Does the image belong to those vertices?
<img width="580" alt="screen shot 2017-10-24 at 1 22 42 pm" src="https://user-images.githubusercontent.com/5863899/31963729-ef1c7de8-b8be-11e7-9145-4b655d987172.png">

Frame 2 (after release). Looks like I grabbed another one very quickly. So grab -> release -> grab within three frames?
<img width="579" alt="screen shot 2017-10-24 at 1 22 55 pm" src="https://user-images.githubusercontent.com/5863899/31963730-ef314430-b8be-11e7-841d-d79c1872d57d.png">

Seen on iPad Air 2 iOS 11.0.3 and ***barely*** seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/55.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.1/circuit-construction-kit-dc_en.html
Version: 1.0.0-rc.1 2017-10-17 18:05:58 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"8a8ff7d2","branch":"HEAD"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"b8a3c09a","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"11736e99","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"5cbdc391","branch":"HEAD"},"dot":{"sha":"84bc5146","branch":"HEAD"},"joist":{"sha":"92b186e2","branch":"HEAD"},"kite":{"sha":"067109a8","branch":"HEAD"},"phet-core":{"sha":"054b2d6d","branch":"HEAD"},"phetcommon":{"sha":"b13138d2","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"c9c3052a","branch":"HEAD"},"scenery-phet":{"sha":"124c1c25","branch":"HEAD"},"sherpa":{"sha":"0d590744","branch":"HEAD"},"sun":{"sha":"082fee37","branch":"HEAD"},"tandem":{"sha":"98e9917c","branch":"HEAD"},"twixt":{"sha":"a2eaa10a","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
This seems unlikely to cause any pedagogical issues, but it is not super aesthetically pleasing, deferring for now, will look into for 1.1

**Comment by samreid** [comment]
I tested master on Mac Chrome with x6 throttling, and I tested the published version of CCK DC on an iPad 3.  Neither site showed this symptom, closing until we see this problem again.
