### ISSUE TITLE
use of prototype common code for animation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#430]
Noted while working on phetsims/twixt#4.

CCK:C is using EaseAnimation, which is documented as:

```js
 * WARNING: PROTOTYPE, see https://github.com/phetsims/twixt/issues/3 before using!
 * Not fully documented or stabilized. May be deleted
```

Should we be using prototype code for animation in production sims?

**Comment by samreid** [comment]
Resolved in 89ab99a9e09be3a9abe672c1eb11653ac696c1c2, closing.
