### ISSUE TITLE
User suggestion: increase AC frequency range

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#436]
> I have used your simulation for a long time and I found it very useful. I have one question about an Electric part, an AC/DC Kit. 
> Please, can you tell me is it possible to set the frequency of the AC generator higher than 2 Hz? For example to 50Hz.

Current range:
![image](https://user-images.githubusercontent.com/5090275/42466537-6bf91bd2-836c-11e8-96f0-6b85f6fa56a9.png)

**Comment by samreid** [comment]
The design doc for AC doesn't explicitly state the range, but it does show this slider, which looks like 0-2:

![image](https://user-images.githubusercontent.com/679486/65054628-1de6d900-d92b-11e9-8b40-14d51282d8eb.png)

@arouinfar what would you like to do with this issue?

**Comment by arouinfar** [comment]
@samreid I think it'd be impossible to use a household standard of 50 or 60 Hz, particularly when considering the need to show the current animation, resolution of the charts, and performance implications. We have considered creating a Household flavor of CCK which would have a realistic frequency, but would likely not show the current animation or have the ability to tune the frequency.

The HTML5 design uses the same range and default as Java. However, it might be good to check in with the team to see if we might consider extending the range a bit more, perhaps to 5 Hz.

**Comment by samreid** [comment]
During design meeting, we discussed that in the future we may show a household circuit that has 50-60Hz and doesn't depict electrons.  Closing.
