### ISSUE TITLE
evaluate stepper option to Carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#437]
Carousel was converted to use TWIXT/Animation in https://github.com/phetsims/sun/issues/381.  The default is `stepper: 'manual'`, which means that the client must call `step` to control the Carousel's animation.   To avoid having to make changes in this sim, `stepper: 'timer'` was added to Carousel call sites, which means that the animation will run automatically using the sim Timer.  

The responsible developer should evaluate what `stepper` value should be used.

**Comment by samreid** [comment]
We are discussing using an `{Emitter}` instead of a `{string}`, defaulting to the PHET_CORE Timer emitter, in https://github.com/phetsims/twixt/issues/19.  I'll put the issue on hold until that is complete.

**Comment by samreid** [comment]
Since this carousel is decoupled from the model, it can run using the default value of timer.  Closing.
