### ISSUE TITLE
User suggestion: analogical representation

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#440]
> And, I'd like to put in a plug for an idea I sent you folks last spring about the Circuit Construction Kit. I consider it an accessibility issue not necessarily based on physical/learning challenges but instead based on disinterest with technical things -- not a typical group we might think of when trying to provide increased access in education, but as a teacher I sure have to!
> 
> I got the idea by what you folks had in the bottom left hand corner of that sim:
> ![image](https://user-images.githubusercontent.com/5090275/48164156-f18c1600-e29e-11e8-88ab-e10c5f396501.png)
> 
> The idea is to add a 3rd button in addition to the Physical and Schematic representation or a circuit & parts. This would be an "Analogical" representation using water, pipes, pumps and some fun loads in the system. In science class, to help students visualize this, some of us science teachers build actual (physical) systems of pipes, pumps, turbines but this is hard to make and we don't have a class set of them and they aren't very interactive so it becomes a demo--not bad but nothing compared to what a 3rd button, an "analogy" button linking to a water-circuit analogy could do!

**Comment by samreid** [comment]
@arouinfar and/or @ariel-phet where would you like to go with this issue?

**Comment by arouinfar** [comment]
@samreid @ariel-phet I think this goes well beyond the scope of the learning goals for CCK. If we really wanted to address the water analogy, it would best be done in its own standalone sim.

That said, while the water analogy is fairly ubiquitous and useful for simple DC circuits, it isn't perfect. I think it would take some careful design -- both artistically and pedagogically -- for this to work.

**Comment by ariel-phet** [comment]
@arouinfar I agree, this suggestion goes way beyond the scope of this sim. I often use water analogies in my own teaching regarding things like Voltage or resistance or such, but that is really just a separate conceptual sim. Such analogies would (as AR pointed out) not easily be represented in a more complicated circuit. I am going to close this issue.
