### ISSUE TITLE
I need not circuit design tool, just short form of circuit

### ISSUE THREAD

**Issue by TrustyMan** [phetsims/circuit-construction-kit-common#441]
Hello, everyone.
I need html PhET circuit simulation.
![image](https://user-images.githubusercontent.com/29589220/48715639-63297400-ec50-11e8-8f40-9628f91f2dba.png)
My circuit simulation should be like this function.
Students chooses votages and all 3 resistors.
and the simulation shows the effect of changes by altering brightness, Vmax = 12v, Rmax = 10 ohm.

**Comment by samreid** [comment]
@ariel-phet or @arouinfar where would you like to go with this issue?  Should we use it an an example case for a PhET-iO wrapper?

**Comment by ariel-phet** [comment]
This situation is completely able to be set up with the current HTML5 simulation. If @TrustyMan wishes to make this situation, it can be accomplished currently and a worksheet could be built around it. I don't think we should pursue this issue further or make an iO wrapper with this situation given that it is limited in scope, and our sims are generally made to be quite flexible.
