### ISSUE TITLE
User suggestion: lightbulb should burn out

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#442]
> In class we've been using the circuit simulator. I have a suggestion/request for the simulator. The lightbulb should burn out when overloaded instead responding like a short circuit. When too much power goes through the circuit the battery catches on fire but in reality the bulb should burn out and the circuit should stop working. 
> 
> 
> Keep up the great work and look forward to using more of the programs as they move to HTML5.

**Comment by samreid** [comment]
@arouinfar or @ariel-phet can you recommend how to proceed with this issue?

**Comment by ariel-phet** [comment]
@samreid I believe we treat our lightbulbs like ideal resistors that can handle any amount of current. I think now that we have the fuse as an option in the published version that this is a non-issue, since the fuse can be employed to get to this learning goal. 

@arouinfar feel free to close if you agree.

**Comment by arouinfar** [comment]
Agreed @ariel-phet, closing.

**Comment by samreid** [comment]
One more question--should we reach out to the customer to let them know they can use the fuse to reach this learning goal?

**Comment by arouinfar** [comment]
Good idea @samreid. 

@oliver-phet can you follow up with this user and let them know that we've recently added a fuse to the sim, which should be able to address their stated goal.

**Comment by oliver-phet** [comment]
Email to user sent.
