### ISSUE TITLE
undesirable '{0}' replacement 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#444]
Noted in https://github.com/phetsims/scenery-phet/issues/446.

In CircuitElementEditContainerNode, you're doing a replacement of one pattern with another, since these strings will be used with NumberControl:

```js
            StringUtils.fillIn( resistanceOhmsValuePatternString, {
              resistance: '{0}'
            } ),

            // Adapter to take from {{named}} to {0} for usage in common code
            StringUtils.fillIn( voltageVoltsValuePatternString, {
              voltage: '{0}'
            } ),
```

Using '{{value}}' instead of '{0}' is preferred, now that NumberControl supports it.  But you could avoid the replacement altogether by using '{{value}}' in your string values.   I.e., change these string to contain '{{value}}':

```
  "resistanceOhmsValuePattern": {
    "value": "{{resistance}} ohms"
  },

  "voltageVoltsValuePattern": {
    "value": "{{voltage}} volts"
  },
```

**Comment by pixelzoom** [comment]
If you decide to not change the strings and continue to do the replacement, please use `NumberDisplay.NAMED_PLACEHOLDER`, not the literal `'{{value}}'`.

**Comment by samreid** [comment]
If I change the template variables as specified in https://github.com/phetsims/circuit-construction-kit-common/issues/444#issue-406903423, will I make that change in babel as well as the english strings?  Will it create any complications or errors for rosetta or pre-existing translations?

**Comment by jbphet** [comment]
Yes, this would need to be changed in the existing babel translations as well, and you'd need to do a maintenance release at the same time.  In this particular case, I would suggest leaving the string format values as they are and just updating the code that adapts them to work with `NumberControl`.

**Comment by samreid** [comment]
CCK is now using only `{{names}}` instead of `{0}`, can this issue be closed?

**Comment by pixelzoom** [comment]
I don't see any usages of `{{name}}`. @samreid Did you mean "using only `{{value}}` instead of `{0}`?

**Comment by samreid** [comment]
I meant CCK is only using the double brace pattern with appropriate variable terms, including but not limited to `{{resistance}}`, `{{value}}` `{{current}}` etc.
