### ISSUE TITLE
Capacitor plates view should be backed by kite shapes for hit detection

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#451]
Unlike Java, we would like to get voltage readings on the plates. Therefore, we should draw them in code and use kite shapes for hit detection.

@arouinfar does this also mean you can read the current on a capacitor plate?

**Comment by arouinfar** [comment]
> @arouinfar does this also mean you can read the current on a capacitor plate?

@samreid good question. Yes, t think the current probe should read in the same places at the voltmeter probes.

**Comment by samreid** [comment]
Capacitor Lab Basics looks like it already has good bounds support, we are considering reusing that code in #452

**Comment by samreid** [comment]
Fixed, closing.
