### ISSUE TITLE
Use pattern or code from Capacitor Lab: Basics for laying out charges on the plates

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#452]
Use pattern or code from Capacitor Lab: Basics for laying out charges on the plates

**Comment by arouinfar** [comment]
@samreid I think we can use the exact same method for dealing with charge density. I do not think we would want to show the electric field between the plates, as that goes well beyond the goals of CCK.

The default orientation of the capacitor is more like this.
![clb](https://user-images.githubusercontent.com/8419308/63979735-d16c5400-ca76-11e9-8ec1-f60943d852f6.png)

The `+` is symmetric and looks fine, but the `-` looks really odd with a 90* rotation. I would prefer the default orientation of the capacitor to have the more natural looking charge appearance. @samreid could you rotate the `-` 90* so that it's horizontal for the default orientation of the capacitor?

**Comment by samreid** [comment]
I am not familiar with the code in Capacitor Lab: Basics, but it seems worth investigating factoring out this code that renders these plates and charge distributions.

Pros:
* Avoiding duplicated code, less to create and maintain
* Making an improvement in one sim will improve both sims
* Uniform representation for capacitors across sims
* Reusable by other capacitor-related sims in the future

Cons:
* Up front cost to factor out and generalize the capacitor node
* If we later decide to deviate the representations, it will introduce some complexity

@jessegreenberg are you familiar with this code?  What problems do you foresee with trying to generalize the plates+charges nodes?

**Comment by samreid** [comment]
One more con I discovered while investigating this:

* PlateChargeNode is rendered using CanvasNode--will this create too many retina layers and overflow the memory?  Or maybe we can limit the sim to a small number of capacitors, like 3?

**Comment by samreid** [comment]
I loaded this into CCK and added some mock model parts to create it.  It came out like so (I haven't rotated the negative charges yet):

![image](https://user-images.githubusercontent.com/679486/64070098-fa2b4f80-cc16-11e9-9f2e-ce446caf38f1.png)

And this allowed me to use namespace to see all of the Capacitor Lab: Basics types that are directly or transitively loaded:

* BoxNode
* BoxShapeCreator
* CCKStrategyWithRounding
* CLBConstants
* CLBModelViewTransform3D
* CapacitorNode
* EFieldNode
* IGridSizeStrategy
* PlateChargeNode
* PlateNode
* VacuumPlateChargeNode

One option would be to move all of that (except for CLBConstants) to scenery-phet/js/capacitor, and that seems like the right thing to do but it's a drastic change and I'd like to discuss it with another developer before taking that step.

@Denz1994 @jonathanolson @jessegreenberg @pixelzoom what do you think?

**Comment by pixelzoom** [comment]
While I wrote the Java version, that was a long long time ago, and I had little to do with the JavaScript version.  Perhaps I'm listed as `@author` because it was a relatively-direct port, but I haven't compared implementations.

**Comment by jonathanolson** [comment]
I don't recall the CLB implementation being terribly generalizable, but I'd generally defer to your judgment @samreid. If it looks good to use (with that patch), go for it.

**Comment by samreid** [comment]
My feeling is I would need to duplicate a lot of what is in CLB for CCK, so factoring out as much as possible seems nice.  Due to the large number of files (10), it seems like it warrants a separate subdirectory in scenery-phet.  

> If it looks good to use (with that patch), go for it.

To clarify, the patch set up CCK to use CLB as a dependency, I didn't factor out the files yet.

**Comment by jessegreenberg** [comment]
It has been a several years since I worked on CL:B but generalizing definitely seems nice and worth it to me. I took a quick look through the files and while some like CLBModelViewTransform use CLBConstants for defaults it seems like they are not strictly tied to CLB.

**Comment by samreid** [comment]
In https://github.com/phetsims/scenery-phet/issues/537 I ported Capacitor Lab: Basics CapacitorNode to scenery-phet.  That code still needs to be reviewed, and there are some follow-up items, but I'll create separate issues for those.  Closing.
