### ISSUE TITLE
Where should the probes attach to the Voltage/Current charts?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#455]
The mockup shows them attaching at the right in the toolbox:

![image](https://user-images.githubusercontent.com/679486/53349588-a8f27a00-38da-11e9-867d-2b6d0284363e.png)

And at the left in the play area:

![image](https://user-images.githubusercontent.com/679486/53349613-b90a5980-38da-11e9-9cb2-3dec90ca16e1.png)

I think it makes more sense to attach them at the right since that is where the new data appears.  @arouinfar thoughts?

**Comment by arouinfar** [comment]
The icons in the toolbox are actually screenshots of the wave detector in Bending Light. I created the mockups before the updated chart tools had been designed, so those were meant as a stand-in.  

The icons should be a shrunken version of the tool itself, similar to what was done in Wave Interference:
![image](https://user-images.githubusercontent.com/8419308/53371578-31dad700-3916-11e9-994a-5c1de2839001.png)

@samreid please let me know if you would like an updated mockup.

**Comment by samreid** [comment]
To clarify, I thought it improve the design slightly for the wires to attach where the data is flowing in--at the right.  Maybe it doesn't matter too much, but I thought I'd bring it up.

I agree about having the icon be a shrunken version of the play area tool, however we decide that will look.

**Comment by arouinfar** [comment]
> To clarify, I thought it improve the design slightly for the wires to attach where the data is flowing in--at the right.

Ah, understood. Re-reading your original comment, that point does come across clearly.

I personally think it looks a bit better to have the probes on the left, though I think this is a detail I'd prefer to work out once I can test it in the sim. Can we wait on this for a bit @samreid?

**Comment by samreid** [comment]
Yes, we can see it in practice and decide later.

**Comment by samreid** [comment]
The sim seems functional enough to test this.  The advantage of having the probes on the left is that because the meter is dragged from the right, the circuit will be on the left.  @arouinfar can you please test in context and let me know your recommendation for this issue?

**Comment by arouinfar** [comment]
Played a bit in master, and the probe positioning is feeling natural to me @samreid. Let's close.
