### ISSUE TITLE
Do the charts need to support a "no value" value?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#456]
In Java, the charts omit data when the value is undefined, like so:

![image](https://user-images.githubusercontent.com/679486/53443787-af135400-39c9-11e9-8842-4392d9a2e4c4.png)

Griddle does not support that feature at the moment.  Should we invest in that feature for griddle, or should we simplify and say that when the chart probes are not connect to something, the readout value is zero, like so:

![image](https://user-images.githubusercontent.com/679486/53443851-d79b4e00-39c9-11e9-816c-75fed293d4e8.png)

**Comment by arouinfar** [comment]
@samreid great question. Probe-like tools generally display "no value" when they aren't reading a value. This provides feedback to the user that the probes aren't correctly placed on the thing being measured.   Here are a few examples:

![image](https://user-images.githubusercontent.com/8419308/53527923-6fba3580-3aa5-11e9-8505-d1829df404a4.png)

However, this doesn't perfectly generalize to a chart tool, such as the Voltage Chart. I like the behavior of Java -- the line stops drawing. I think continuing to draw the line at zero value would send the wrong message. Ideally, I think the chart would continue to scroll, but no line would be drawn. The dots on the right side of the tool could remain at zero, though.

Thoughts @ariel-phet?

**Comment by arouinfar** [comment]
The Wave Detector in Wave Interference has the desired no value behavior. If a probe is removed from the wave area, the line stops drawing and the previously recorded data will scroll away. The only strange thing in WI is that the dot retains the y-position of the last recorded value. This seems a bit odd to me, but it's also not that jarring.

**Comment by ariel-phet** [comment]
@arouinfar @samreid I agree with @arouinfar that there should be a "no value" behavior. Reading zero is incorrect, since there is really nothing to read, and could imply a ground, or a false positive.

**Comment by samreid** [comment]
Support was added in https://github.com/phetsims/griddle/issues/33 and the behavior looks correct for CCK AC:

![image](https://user-images.githubusercontent.com/679486/55677751-bcfea380-58aa-11e9-8dde-df253da02f82.png)

Closing.
