### ISSUE TITLE
User suggestion: random motion of electrons before circuit is switched on

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#457]
For https://github.com/phetsims/circuit-construction-kit-ac-and-dc/issues/4. 

[Unfuddle Ticket #3588](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3588)
> "the simualation is great, except that you may want to include making the blue ball "electrons" in random motion even before the circuit is switched on. I think it is more accurate. Thank you."

While in reality the electrons would always be in motion, I think keeping them frozen until a circuit is complete makes it really clear that the current is switched on. However, this request is somewhat akin to the random motion of the sound particles in Wave Interference (though not in technical implementation), so we may want to consider it.

A few thoughts of what this random motion could look like
* 1D vibration along the path of circuit (we don't want electrons outside of the bounds of circuit elements).
* Vibrations should be small and visually distinct from electron motion in a high-R circuit.
* Vibrations would cease once the circuit is complete, otherwise it might muddy the clean animation of the electrons moving through the circuit.

Marking for design meeting discussion.

**Comment by samreid** [comment]
> Vibrations would cease once the circuit is complete, otherwise it might muddy the clean animation of the electrons moving through the circuit.

What if there is a very small but nonzero current?

**Comment by samreid** [comment]
During design meeting, @ariel-phet pointed out that the random motion would be distracting from the main learning goals.  Closing.
