### ISSUE TITLE
Numerical instability when breaking a junction in an LR circuit

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#458]
For https://github.com/phetsims/circuit-construction-kit-ac-and-dc/issues/4

Steve Pollock reported in [Unfuddle Ticket #3070](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3070).
> In this series circuit, breaking a junction is of course a "bad thing" to do (in real life, it would probably spark.) I was curious what the phet sim would do. It instantly turns off the current (which I suppose is the best you could do, sparking is pretty impossible, although you might have put a junction on fire?  But I think your choice is fine - the current WOULD turn off, quite quickly) But when you have the "voltage chart" active, the plot of voltage turns into a solid blue plot, at least for certain locations of the probes. (Screenshot 4 below)  Perhaps that's your way of saying something terrible happened, but that I don't really get - once the current has gone to zero (as the sim shows), the voltage should not be pathological anywhere, the only pathology was for the brief instant when you broke the circuit. And it turns out that whether the plot goes to "all blue" or just "zero line" depends on where exactly the two voltage crosshairs are on the circuit.
![image](https://user-images.githubusercontent.com/8419308/53699619-a34bd700-3da7-11e9-9aab-668627fc2e2b.png)

@samreid replied:
> I reproduced the problem--it looks like a numeric instability for the system of equations with a charged inductor when disconnected.
> Thanks for pointing out these problems--I've seen the current chart problem back as early as March 2008 but haven't fixed it yet.  The inductor problem is new to me, and I was able to replicate the problem you described.  I think it is due to a numeric instability of a disconnected charged inductor.  I added your comments to our bug tracker and will make a note to let you know if/when we resolve them.

This looks a legacy bug, so assigning @samreid.

**Comment by samreid** [comment]
I did not observe the same bug in master (note the bottom right battery is really an inductor):

![image](https://user-images.githubusercontent.com/679486/65822185-efa3ac00-e1fc-11e9-8284-52b03758db37.png)
