### ISSUE TITLE
User suggestion: increase AC voltage range

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#461]
> I would like to ask if you can make some slight adjustments so as I may use this in training for Adults that I teach Home Appliance Technology.
I am looking for AC voltages of 120, the scale only goes to 100.

Java version AC Voltage Dialog:
![image](https://user-images.githubusercontent.com/5090275/53747625-ec139680-3e60-11e9-8222-a3163393f6a1.png)

**Comment by arouinfar** [comment]
The range for the AC Voltage will match the voltage range for the battery, which was extended to 120 V in CCK: DC. @oliver-phet can you let the user know that we will be accommodating this request in the HTML5 version of CCK: AC?

**Comment by oliver-phet** [comment]
Will do, thanks!
