### ISSUE TITLE
Add a fuse

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#463]
> Is there any way you can incorporate adjustable amperage fuses in this trainer?

**Comment by samreid** [comment]
I moved this to the "common" directory since the work will be done in this repository.

**Comment by samreid** [comment]
@arouinfar should we add a slot to the carousels so the fuse can be on the first page?

**Comment by arouinfar** [comment]
For some added context, @kathy-phet emailed:
> Can you two [SR & AR] connect on Thursday to discuss the "fuse" component?
>
>We previously discussed having the fuse about the size of the switch, and being able to set its breakpoint (in Amps) with a slider. Then if current exceeds, it has some animated pop and shows a broken wire image inside. And some sort of "Reset Fuse" button pops up somewhere next to the fuse?
>
>I would like to be able to share a dev version of this capability for a perspective partner to try out by the end of April, so perhaps next week Sam could take some time from wave interference to see if he can implement this feature?


@samreid I think the fuse is a bit advanced, so I would put it in the 2nd slot of the 2nd page of the carousel. For screens without a carousel (RLC & Lab on CCK: AC), I would add the fuse just above the switch.

Here's a quick mockup of the fuse, showing increasing current ratings.
![image](https://user-images.githubusercontent.com/8419308/55494634-636f4e00-55f8-11e9-8903-6b9d90d626fd.png)

When the current exceeds the tolerance, the fuse could looks something like this
![image](https://user-images.githubusercontent.com/8419308/55494779-ae896100-55f8-11e9-88c0-d1ba5d638f72.png)

Here's some mockups of the edit menu. Users can set the current rating (range and default TBD), and when the fuse blows the reset button will become active and the slider will be inactive.
![image](https://user-images.githubusercontent.com/8419308/55495254-b7c6fd80-55f9-11e9-9fbd-266b2447cade.png)

**Comment by kathy-phet** [comment]
I like it overall. I think we would need to make something that was a transitional animation - spark or something - to help students really focus in on the fuse being blown.

**Comment by arouinfar** [comment]
@kathy-phet I took a stab at the animation. Is this in line with what you were envisioning?

![fuse](https://user-images.githubusercontent.com/8419308/55512807-4438e680-5621-11e9-9efb-5345bf87ce25.gif)

**Comment by kathy-phet** [comment]
Thanks, Amy! Yes, that is generally matching what I was thinking. Seems like it would draw student attention.

**Comment by samreid** [comment]
Looks great!  I'm wondering if it should be accompanied by a sound effect?  Or will it be too odd if the sim only has sonification for 1 thing?

**Comment by kathy-phet** [comment]
I agree a sound would be nice. I think this will be sonified at some point, so perhaps hold off. @emily-phet - What do you think re sound for this one thing now or hold off?

**Comment by samreid** [comment]
I created a new issue for dealing with animation for tripping the fuse.

**Comment by samreid** [comment]
I committed an initial draft of the fuse.  It has a fixed max current and cannot be reset, but I'll address that in a new issue.

**Comment by samreid** [comment]
I also opened an issue to discuss fuse sonification.

**Comment by samreid** [comment]
I split out the remaining work into other issues.  @arouinfar please let me know if I missed anything.  Putting this issue on hold until sub-issues are closed.

**Comment by arouinfar** [comment]
> I split out the remaining work into other issues. @arouinfar please let me know if I missed anything. 

Looks good to me @samreid!

**Comment by samreid** [comment]
Let's close this issue and follow-up in https://github.com/phetsims/circuit-construction-kit-common/issues/500 and its child issues.

**Comment by jingis2020** [comment]
good day every one i need a guide  on how to add additional wire (black wire) in html5 DC circuit simulator it will be great if some one help me out thanks and best regard hope to have a positive   answer
