### ISSUE TITLE
Where should the fuse appear in the carousels?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#465]
For "CCK DC" should we add a new carousel slot and put Fuse at the bottom?  Or something else?

**Comment by samreid** [comment]
In https://github.com/phetsims/circuit-construction-kit-common/issues/463#issuecomment-479560860 @arouinfar said

> @samreid I think the fuse is a bit advanced, so I would put it in the 2nd slot of the 2nd page of the carousel. For screens without a carousel (RLC & Lab on CCK: AC), I would add the fuse just above the switch.

**Comment by samreid** [comment]
This is fixed for CCK DC but I haven't started RLC or Lab yet so cannot address those yet.

**Comment by arouinfar** [comment]
@samreid let's include the fuse in the 2nd spot on the 2nd page. The grab bag items will follow in the same order used in CCK: DC.

**Comment by samreid** [comment]
Currently the code supports a fixed number of items per page.  When I use the same items from circuit-construction-kit-dc/js/intro/view/IntroScreenView.js, this leaves two items on the final page, like so:

```js
// This page is duplicated in the Lab Screen View
wireToolNode,
circuitElementToolFactory.createRightBatteryToolNode( 10, tandem.createTandem( 'rightBatteryToolNode' ) ),
circuitElementToolFactory.createACVoltageToolNode( 10, tandem.createTandem( 'rightBatteryToolNode' ) ),
circuitElementToolFactory.createLightBulbToolNode( 10, tandem.createTandem( 'lightBulbToolNode' ) ),
circuitElementToolFactory.createResistorToolNode( 10, tandem.createTandem( 'resistorToolNode' ) ),
circuitElementToolFactory.createCapacitorToolNode( 10, tandem.createTandem( 'capacitorToolNode' ) ),
circuitElementToolFactory.createInductorToolNode( 10, tandem.createTandem( 'inductorToolNode' ) ),
circuitElementToolFactory.createSwitchToolNode( 5, tandem.createTandem( 'switchToolNode' ) ),

new Node( { children: [ wireToolNode ] } ), // Wire should appear at the top of each carousel page
circuitElementToolFactory.createFuseToolNode( 10, tandem.createTandem( 'fuseToolNode' ) ),
circuitElementToolFactory.createDollarBillToolNode( 1, tandem.createTandem( 'dollarBillToolNode' ) ),
circuitElementToolFactory.createPaperClipToolNode( 1, tandem.createTandem( 'paperClipToolNode' ) ),
circuitElementToolFactory.createCoinToolNode( 1, tandem.createTandem( 'coinToolNode' ) ),
circuitElementToolFactory.createEraserToolNode( 1, tandem.createTandem( 'eraserToolNode' ) ),
circuitElementToolFactory.createPencilToolNode( 1, tandem.createTandem( 'pencilToolNode' ) ),
circuitElementToolFactory.createHandToolNode( 1, tandem.createTandem( 'handToolNode' ) ),

new Node( { children: [ wireToolNode ] } ), // Wire should appear at the top of each carousel page
circuitElementToolFactory.createDogToolNode( 1, tandem.createTandem( 'dogToolNode' ) )
```

@arouinfar is this acceptable, or should we invest in generalizing this code so that different pages can have different number of items?  If we do generalize that code, how would you want to organize the items on the pages?

**Comment by arouinfar** [comment]
@samreid I think the UX of varying the number of slots in the carousel by page would be pretty strange. I don't think we need to go there.

We could decide to move the switch to the 2nd page, which would leave 3 items on the last page, but that could be decided with the pixelpolishing #507.

**Comment by samreid** [comment]
I added the grab bag items to the RC and Lab screens, I agree we can pixel polish the exact order and contents in #507, anything else for this issue?

**Comment by arouinfar** [comment]
Thanks @samreid. Fuse placement looks good, closing.
