### ISSUE TITLE
Add animation for tripping the fuse

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#466]
@kathy-phet said:

> I think we would need to make something that was a transitional animation - spark or something - to help students really focus in on the fuse being blown.

@arouinfar replied:

@kathy-phet I took a stab at the animation. Is this in line with what you were envisioning?

![fuse](https://user-images.githubusercontent.com/8419308/55512807-4438e680-5621-11e9-9efb-5345bf87ce25.gif)

@kathy-phet replied:

> Thanks, Amy! Yes, that is generally matching what I was thinking. Seems like it would draw student attention.

**Comment by samreid** [comment]
I asked on slack developer channel:

Sam Reid [9:33 PM]
How would you deal with an animation like this?

https://github.com/phetsims/circuit-construction-kit-common/issues/463#issuecomment-479657637
(just the yellow part)
Ask for a stack of PNGs and iterate through them?  Do it in code?  Something else?

**Comment by arouinfar** [comment]
@samreid I created the animation by scaling a single image over a few frames.
![image](https://user-images.githubusercontent.com/8419308/55560064-ad197080-56ac-11e9-84d9-46988515904c.png)

**Comment by samreid** [comment]
Chris Malley [7:46 AM]
I’d do it in code.  Create a unit `{Shape} sparkShape` that describes the yellow part (only needs to be done once).  Create an associated `{Path} sparkPath`. When the fuse breaks, `step` will progressively scale `sparkShape`:

```const scale = ...;
sparkPath.shape = sparkShape.transformed( Matrix3.scaling( scale, scale ) );```
(edited)

Might save you a bit of time to get the SVG data for `sparkShape` from Amy.

Chris Malley [7:55 AM]
Btw… The reason I’m not scaling `sparkPath` is because you want the `lineWidth` to remain constant.
Since you have a small number of animation frames, you also might consider precomputing `{Shape[]} sparkShapes`.

Chris Malley [8:09 AM]
On second thought, I wouldn’t do this in `step`.  I’d use `Animation` with `stepEmitter: timer`.

Sam Reid [8:58 AM]
Thanks!  Sounds like a good plan

**Comment by arouinfar** [comment]
Here you go @samreid! I've also cleaned up the artwork a bit. The .ai and .svg are in the .zip file.

[spark.zip](https://github.com/phetsims/circuit-construction-kit-common/files/3044711/spark.zip)

**Comment by samreid** [comment]
I committed a first draft for the animation, it can be reviewed in phettest.  @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Looks great @samreid! I'll tag for design meeting for review with @kathy-phet and @ariel-phet.

**Comment by kathy-phet** [comment]
Fuse looks great! Thanks! (But I'm seeing some odd stuff in CCK DC on phettest -- a different bulb with no electrons at all flowing through, the voltage probe meter, etc ---- FYI). I'm hoping we can possibly publish this fuse upgrade in CCK DC before we finish CCK AC - preferrably before July.

**Comment by kathy-phet** [comment]
Or at least make a nice dev version for someone to use

**Comment by samreid** [comment]
Thanks @kathy-phet, I opened issues for the problems you identified.  If you are aware of other problems, please let me know and I'll take a look.

**Comment by arouinfar** [comment]
@ariel-phet and I reviewed the animation in today's brainstorming meeting, and generally like the look of the animation.

@samreid we have one tweak to suggest. If the fuse is immediately re-blown, fix the fuse (show the unbroken image) before replaying the tripping animation.

**Comment by samreid** [comment]
Re-labeling for design to clarify if the unbroken image should be shown for 1 frame, or for some range of milliseconds.

**Comment by samreid** [comment]
@ariel-phet said OK for @samreid to make the call regarding how long to depict as long as it is easy to see that the fuse was temporarily repaired.

**Comment by samreid** [comment]
After the preceding commit, the current must exceed the current rating for 0.1 seconds to trip the fuse.  @ariel-phet or @arouinfar can you please review this behavior on phettest?  Let me know if you prefer a different time limit or want to investigate a different rule.

**Comment by arouinfar** [comment]
@samreid this looks wonderful! I think the time frame is enough to show that the fuse has been temporarily repaired before blowing again. This should make it clear to users that they need to make some adjustment to the circuit (such as increasing the current rating or decreasing the voltage) so the fuse can remain repaired.

**Comment by ariel-phet** [comment]
Looks good to me to, closing.
