### ISSUE TITLE
Fuse should have an adjustable max current and be resettable

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#467]
From https://github.com/phetsims/circuit-construction-kit-common/issues/463

@arouinfar said:

Here's some mockups of the edit menu. Users can set the current rating (range and default TBD), and when the fuse blows the reset button will become active and the slider will be inactive.
![image](https://user-images.githubusercontent.com/8419308/55495254-b7c6fd80-55f9-11e9-9fbd-266b2447cade.png)

**Comment by samreid** [comment]
Committed in https://github.com/phetsims/circuit-construction-kit-common/commit/6fac769cbe0be422189aeab37677c59e1192401e

During testing, it was very useful to be able to change the current rating when the fuse was tripped.  Is this something that would be useful to teachers & students as well?

**Comment by arouinfar** [comment]
> During testing, it was very useful to be able to change the current rating when the fuse was tripped. Is this something that would be useful to teachers & students as well?

I think so! I found it very useful to be able to change the current rating of a blown fuse. Otherwise, resetting a fuse still connected to the circuit will result in immediately blowing the fuse again.

I'd like to review the current flow with @kathy-phet and @ariel-phet in our brainstorming meeting next week, so tagging for design meeting.

@samreid in the meantime, can you update the minimum current rating to 0.5 A? It's currently 0 A, which seems odd to me.

**Comment by samreid** [comment]
I changed the minimum current rating to 0.5 amps. Unassigning for now.

**Comment by arouinfar** [comment]
@phet-steele suggested these font-awesome repair icons as alternatives to the reset button. 

<img src="https://user-images.githubusercontent.com/8419308/55738698-d99ef680-59e4-11e9-89e5-d583202157a8.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/55738707-e02d6e00-59e4-11e9-8f73-a26177b9c17d.png" width=150>

For the fuse, these icons may be a bit clearer. However, the capacitor and inductor also have a reset button in their edit panel to clear the E/B fields. 

Let's review the icon choice in design/brainstorming meeting.

**Comment by arouinfar** [comment]
@ariel-phet and I reviewed the fuse's edit panel, including the current rating default and range. Things are generally looking good, with the exception of the icon for the reset/repair fuse button, which I've moved to the issue above.
