### ISSUE TITLE
Fuse filament should have varying thickness and should split when tripped

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#469]
From https://github.com/phetsims/circuit-construction-kit-common/issues/463#issuecomment-479560860

@arouinfar said:

>  Here's a quick mockup of the fuse, showing increasing current ratings.
![image](https://user-images.githubusercontent.com/8419308/55494634-636f4e00-55f8-11e9-8903-6b9d90d626fd.png)

> When the current exceeds the tolerance, the fuse could looks something like this
![image](https://user-images.githubusercontent.com/8419308/55494779-ae896100-55f8-11e9-88c0-d1ba5d638f72.png)

**Comment by samreid** [comment]
@arouinfar have you shared the AI for the fuse?  Sorry if I missed it.

**Comment by samreid** [comment]
I added a rough draft for the filament stroke and tripping, visible on phettest.

**Comment by samreid** [comment]
I received the artwork and added it, ready for review on phettest.

**Comment by arouinfar** [comment]
@samreid the artwork and filament look good! I'll tag for design meeting for review with @kathy-phet and @ariel-phet.

**Comment by samreid** [comment]
On several occasions, the fuse has tripped when an electron is right in the middle, and it obscures the broken filament graphic:

![image](https://user-images.githubusercontent.com/679486/55662738-96ba0480-57d3-11e9-9586-cb05459580ed.png)

I wonder if we should exaggerate the break so it is easier to see even when electrons are in the way.

**Comment by arouinfar** [comment]
@ariel-phet and I reviewed the general flow today, and the behavior is looking good.

> On several occasions, the fuse has tripped when an electron is right in the middle, and it obscures the broken filament graphic

@samreid here are some tweaks we could make to address the obscuring issue
* Exaggerate the break angle a bit more
* Increase the separation between the wire segments so that there's some padding between the electron and the edge of the wires

**Comment by samreid** [comment]
Notes from #481 

> We will increase the angle of the fuse split, and maybe cut off a tooth or two so even if an electron is in the way, you will see the current path interrupted.

**Comment by samreid** [comment]
After the commit, the default tripped fuse looks like this:

![image](https://user-images.githubusercontent.com/679486/56167170-ad5f1900-5f94-11e9-9bd4-49ad7ce141de.png)

@arouinfar and @ariel-phet does this look OK to you?  You can test it interactively and with different filament thicknesses on phettest.

**Comment by ariel-phet** [comment]
It is looking good to me on master, it definitely has a very "broken" appearance, and seems to clearly have negative space around the fuse wires regardless of thickness or where the electron falls.

**Comment by arouinfar** [comment]
Agreed @ariel-phet! Looks great @samreid.
