### ISSUE TITLE
Should we add a rectangle around the component controls?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#472]
Currently none of our circuit element controls have a border:

![image](https://user-images.githubusercontent.com/679486/55600173-269a7880-5718-11e9-825c-2d1305fb9259.png)

But the proposal for https://github.com/phetsims/circuit-construction-kit-common/issues/467 showed a shaded area:

![image](https://user-images.githubusercontent.com/679486/55600184-344ffe00-5718-11e9-8855-94786d6d7a81.png)

Should I add that for all circuit element types?

**Comment by arouinfar** [comment]
@samreid for CCK: AC, the edit panel potentially has up to 3 controls in addition to the delete button, so we decided to add a transparent panel. While the components in CCK: DC don't have as many edit options, I think it might be nice to keep a consistent look. So let's try adding the panel to all CCK flavors.

**Comment by samreid** [comment]
I added the rectangle for grouped components.  For controls where there is only a trash button and for the switch readout, I thought it looked better without.  @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Looks great @samreid! Tagging for design meeting for final sign-off.

**Comment by arouinfar** [comment]
>  For controls where there is only a trash button and for the switch readout, I thought it looked better without.

Agreed @samreid. @ariel-phet and I reviewed this today, and it looks good!
