### ISSUE TITLE
Light bulb electron path is broken

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#473]
Identified by @kathy-phet in https://github.com/phetsims/circuit-construction-kit-common/issues/466#issuecomment-480417045, the electrons are jumping across the light bulb.

**Comment by kathy-phet** [comment]
Ignore name change

**Comment by samreid** [comment]
Fixed, @arouinfar can you please test the light bulb electron path, with the electrons traveling both ways and report any problems you discover?  Close if all is well.

**Comment by arouinfar** [comment]
@samreid the electron and conventional current paths through the light bulb look good in master.
