### ISSUE TITLE
convert from disposeActions to dispose{{Type}}

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#475]
In https://github.com/phetsims/sun/issues/492, we identified that CCKC is using the depreciated `disposeActions` pattern.   

In https://github.com/phetsims/sun/issues/492#issuecomment-479745084, @samreid said:
> It seems straightforward to move these occurrences to the `disposeEmitter` pattern.

CCKC occurrences are in `CircuitElementNode` and `ValueNode`.

**Comment by pixelzoom** [comment]
If you do this after https://github.com/phetsims/sun/issues/493, please update phet-software-design-patterns.md.  You can remove the note about `disposeActions`, since it will no longer exist.

**Comment by samreid** [comment]
I converted to use the `disposeEmitter` pattern.  However, our patterns document indicates the emitters should be named like `disposeEmitter{{TypeName}}`.  I'm struggling with that part, because it is making that part of the code harder to read, particularly for `disposeEmitterCircuitElementNode`.

**Comment by samreid** [comment]
I added the suffices in the preceding commit.  If it still bothers me in the future, I'll reopen.

**Comment by samreid** [comment]
@pixelzoom this seemed pretty straightforward, but I thought I should ask if you would like to review.

**Comment by pixelzoom** [comment]
I skimmed the commits quickly, looks straightforward. Closing.
