### ISSUE TITLE
remove Tween preload?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#478]
I don't see TWEEN used anywhere in CCK, but I see this preload in package.json for all 4 CCK repos:

```js
    "preload": [
      "../sherpa/lib/Tween-r12.js"
    ]
```

Can this preload be removed?

**Comment by samreid** [comment]
Zoom and carousel animation now seem to work without tween, so I'll commit this.  Thanks @pixelzoom!

**Comment by samreid** [comment]
Removed, closing.
