### ISSUE TITLE
Icon for reset/repair fuse button

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#479]
Offshoot of #467 

The reset icon isn't the the best fit for the button that repairs the fuse because
(1) it doesn't give an indication of what will actually happen 
(2) implies the current rating will reset to default

In our [brainstorming meeting](https://docs.google.com/document/d/1bueLDNUhlGuYUMFVvQW2wlZMRknLG7ClZfVMd0GL6ag/edit#heading=h.7mt2qcxt23mc), @ariel-phet suggested some iconic representations for repairing the fuse.  Self-assigning to mock up a few alternatives.

**Comment by arouinfar** [comment]
Alternative ideas:
* Show an intact filament, since the button is only active when the fuse needs to be repaired.
* Show intact filament with up/down arrows at the repair point.

**Comment by arouinfar** [comment]
@ariel-phet @samreid here are some options for the reset/repair fuse button.

![image](https://user-images.githubusercontent.com/8419308/56245191-02199700-605c-11e9-9f68-90491381693b.png)

I quite like the simplicity of (e) and (g), though (a) and (b) could also work. I'm not so crazy about the other options, as they look a bit too busy and/or unclear to me.

**Comment by samreid** [comment]
(g) is my favorite so far!

**Comment by arouinfar** [comment]
Thanks @samreid. Since a wrench came up as a potential icon in a previous issue, here's a mockup of that too:

**Comment by ariel-phet** [comment]
(e) (f) (g) all work for me

I personally like (f) the best in terms of clarity, but agree the others are simpler (and would likely work just fine)

**Comment by arouinfar** [comment]
Thanks @ariel-phet!

Since @samreid and I prefer (g) and it's not far off from @kathy-phet's suggestion to show an intact filament, I'd like to see how it looks in the sim. We can then review it in context as a team.

@samreid can you proceed with (g)?  Is this an  icon you could draw in code, or would you prefer an asset?

**Comment by samreid** [comment]
I'll draw that in the code, thanks!

**Comment by samreid** [comment]
I reused the same code that draws the fuse filament, so the phase isn't exactly like in the (g) mockup.  @arouinfar can you please review on phettest and let me know if you have any recommendations?

![image](https://user-images.githubusercontent.com/679486/56510447-0e33a780-64e7-11e9-87cc-8df658d91656.png)

**Comment by arouinfar** [comment]
I like it! We should probably review with @kathy-phet and @ariel-phet in design meeting.

**Comment by samreid** [comment]
@kathy-phet says this icon looks fine.
