### ISSUE TITLE
Layer the solder blob above wires but below other components

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#48]
In https://github.com/phetsims/circuit-construction-kit-basics/issues/42#issuecomment-203475993 @ariel-phet said:

> One suggestion I would have (but it is definitely not necessary for MVP) is to layer the solder blob above the wire, but below all other components. I think that would tend to make wire joints look nicer. But that would purely be an aesthetic change.

> assigning to @arouinfar for her opinion

**Comment by samreid** [comment]
Here's a pic of an odd-looking wire joint with the current layering:

![image](https://cloud.githubusercontent.com/assets/679486/14147112/71734686-f657-11e5-8f0f-9744d0011861.png)

**Comment by samreid** [comment]
> One suggestion I would have (but it is definitely not necessary for MVP) is to layer the solder blob above the wire, but below all other components.

If we use a straightforward layering (with no clipping hacks) with the solder is always in front of wires and always behind all other components, this implies that wires could never go in front of other components, like this:

![image](https://cloud.githubusercontent.com/assets/679486/14147328/3428f8e2-f658-11e5-8558-4fb270409c62.png)

The solder is currently in a dedicated back layer.  But we could restructure the layering and add rules at each junction like so:

when something connects to a vertex:
move connected wires to the back
move solder after the connected wires
move components to the front

But when a wire is selected, it should be brought to the front, so it will drag in front of other things.  What would happen to the solder if an adjacent wire was brought to the front?

**Comment by samreid** [comment]
I had an idea for a way to implement this, will investigate soon.

**Comment by samreid** [comment]
My idea was to create a wire solder layer that is always in front, but the solder only shows if only wires are attached, but this yields this odd behavior where a component can go between the wires and the solder like this:

![image](https://cloud.githubusercontent.com/assets/679486/14148971/1cc84f8e-f65f-11e5-8608-5b09676cdc18.png)

So it seems to get this right we would need to interleave the solder nodes and add re-ordering logic for the different cases.  Let's hear from @arouinfar before spending time on this.

**Comment by arouinfar** [comment]
@samreid I think it would look much, much cleaner if the solder joint could obscure wire connections. That being said, I agree with @ariel-phet that this is not something that needs to be in the MVP, especially since it will clearly require some nuanced layering.

> But when a wire is selected, it should be brought to the front, so it will drag in front of other things. What would happen to the solder if an adjacent wire was brought to the front?
To summarize the above paragraph in a question: should we be able to drag a wire in front of a battery, if they are connected?

Regardless of solder layering, it looks like there's some funkiness with the layering. Selecting an item does not bring it to the front (left). It's also possible to drag a wire through the connection of two other wires (right).

![image](https://cloud.githubusercontent.com/assets/8419308/14151790/ed82527a-f66c-11e5-84b1-faa0d4ef150f.png)        ![image](https://cloud.githubusercontent.com/assets/8419308/14151885/6e62d1f8-f66d-11e5-90d7-24a6e55f244c.png)

**Comment by samreid** [comment]
This issue has been reported as not-for-MVP, and I created a side issue for the problem reported in the previous comment.  Demoting priority.

**Comment by samreid** [comment]
Fixed above and looking good in a variety of cases:

![image](https://cloud.githubusercontent.com/assets/679486/14808802/998398d0-0b45-11e6-92ed-9d30b795aae4.png)

However, I suspect that there will be many corner cases we will have to address.  I'll leave this issue open to request @arouinfar to test the layering of solder, but please report issues in new issues.

**Comment by arouinfar** [comment]
@samreid it doesn't appear that this issue was resolved in dev.8, so I tried to pull master to take a look. There's no repo visible for Black Box on phettest, and it appears that circuit-construction-kit-basics is now actually housing CCK: Basics, not Black Box. (It used to be Black Box.)

![image](https://cloud.githubusercontent.com/assets/8419308/14848508/46c187a8-0c83-11e6-9b8e-564f2c73192a.png)

Reassigning to @samreid to provide me with a testable version.

**Comment by samreid** [comment]
Sorry, this fix was made after dev.8, can you please take a look at http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box/1.0.0-dev.9/circuit-construction-kit-black-box_en.html

**Comment by arouinfar** [comment]
Looks great @samreid!

**Comment by phet-steele** [comment]
A wire will appear above the solder in the following scenario, seen in the #126 version. Before trying to reproduce, note it is VERY important to watch the order of events. The order in which wires/components are taken from the toolbox and placed into the play area is the whole reason this procedure works:

1. Place any number of objects into the play area. Doesn't matter what they are.
2. Take a wire and place it in the play area. Do NOT let it attach to anything, just place it by its lonesome.
3. Now, connections MUST be made by dragging objects *from* step 1 *towards* wires from step 2. Reversing this order will not yield incorrect solder layering.

![cckbb05](https://cloud.githubusercontent.com/assets/5863899/15872885/07a7158c-2cb9-11e6-98ec-3a05052a0e88.gif)

**Comment by samreid** [comment]
It is difficult for me to see the incorrect solder layering in the above screencast, @arouinfar or @phet-steele can you please comment?

**Comment by phet-steele** [comment]
@samreid it's everything that gets connected to the bottom right wire. For instance, the very first connection made in the video shows the middle wire connecting to the bottom right wire. That connection shows the bottom right wire layered above the solder.

**Comment by phet-steele** [comment]
@samreid, this could probably be its own issue, but revealing or switching between investigate and build brings all solder to the top layer.

**Comment by samreid** [comment]
I'll move the preceding comment to a new issue.

**Comment by samreid** [comment]
I also moved the comment from https://github.com/phetsims/circuit-construction-kit-common/issues/48#issuecomment-224398479 to a separate issue.
