### ISSUE TITLE
Proposal to switch red/black leads on volt meter

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#482]
In using CCK, I always end up naturally creating a circuit and measuring a negative voltage. I think it would be better if natural use, first led to measuring a positive voltage. That is pulling a battery, bulb, some wires, then connecting, then measuring (without crossing leads), gave a positive. I find myself swiching the leads all the time, and creating crossed wires in doing so. 

My proposal is to switch the ordering of the leads on the voltmeter, so the ground is on the left and the red wire is on the right. This would work to flip the sign and mean that you naturally measure a positive voltage. 

Thoughts?

**Comment by arouinfar** [comment]
> Switching the leads seems totally reasonable. 

Agreed!

**Comment by samreid** [comment]
@kathy-phet requested this feature to be included in the next release.

**Comment by samreid** [comment]
I showed the voltmeter black probe on the left and red probe on the right in the pushed commit.  I published a dev version here: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.6/phet/circuit-construction-kit-dc_en_phet.html

@arouinfar, @ariel-phet or @kathy-phet can you please test out the voltmeter and let me know if I've missed anything?

**Comment by arouinfar** [comment]
@samreid the voltmeter is working nicely, but I noticed that the dots at the base of the wires are the wrong color.  Here are updated asset files:

[voltmeter-body.zip](https://github.com/phetsims/circuit-construction-kit-common/files/3149697/voltmeter-body.zip)

**Comment by ariel-phet** [comment]
@samreid besides @arouinfar comment above (nice attention to detail!) all looks good. As mentioned in email, lets do a sanity dev test, but otherwise, I think this issue can be closed.

**Comment by samreid** [comment]
Nice catch @arouinfar, I committed the new artwork.  Can you review on phettest and close if all is well?

**Comment by arouinfar** [comment]
Looks good @samreid!

**Comment by KatieWoe** [comment]
Incredibly minor nitpick, but should the lab screen's nav bar and home screen icon be changed since the default position and the tilt of the colors has changed?
![shouldnavchange](https://user-images.githubusercontent.com/41024075/57259164-d7e44500-701b-11e9-9a67-41f086e96783.png)

**Comment by KatieWoe** [comment]
Feel free to close again if not worth it

**Comment by samreid** [comment]
I agree it would be good to update if not too much trouble.

**Comment by arouinfar** [comment]
Nice catch @KatieWoe! @samreid I couldn't find an .ai file for the screen icon, either locally or in the assets directory, so I think it was probably code generated. Can you swap the probes?

**Comment by samreid** [comment]
I reversed the probes for the lab screen icon in the commit.  @arouinfar can you please take a look and see if it's good?

**Comment by arouinfar** [comment]
Looks great, thanks @samreid!
