### ISSUE TITLE
Add a pause/play button?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#483]
While exploring https://github.com/phetsims/QA/issues/311 it occurred to me that a pause/play button could be useful.  If a student want's to add reset multiple fuses, depending on the set up one may be blown out before the other could be restarted.  In general, it could be useful for a student to fully set up a circuit before starting it.  Of course, this could all be accomplished by the student with an appropriately placed switch, which may be more pedagogically useful anyway.  Thought I'd add the idea for consideration.

**Comment by phet-steele** [comment]
@KatieWoe, FWIW do `?showDepictValuesToggleButton` if you want to try it out.

**Comment by arouinfar** [comment]
Thanks for the suggestion @KatieWoe. 

>  Of course, this could all be accomplished by the student with an appropriately placed switch, which may be more pedagogically useful anyway.

Agreed. I think play/pause could be useful in some instances, but I think it's more pedagogically beneficial to use switches appropriately. I'll mark this for design meeting to see if others on the team agree.

**Comment by samreid** [comment]
@kathy-phet said it is fine to not have play pause.
