### ISSUE TITLE
Can't tell fuse is blown

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#484]
Looking at https://github.com/phetsims/QA/issues/311 I noticed that there is no visual difference between a working and a blown fuse in the schematic scene.  I was unable to find a representation of a blown fuse, but I did see a fuse with an indicator light represented as:
![blownfuseled](https://user-images.githubusercontent.com/41024075/56767432-fa977380-6768-11e9-9cfa-6d985ad014f5.png)
with the arrow/line/circle representing an LED that would light up if the fuse blows (I think).

The image bellow is of a blown fuse in sim.  You can tell because of the behavior of the circuit and the fact that the yellow button to fix the fuse is active, but that is only seen if focusing on the fuse, and if there are multiple fuses the student may not know which ones blew.  I think it would be useful to have some kind of indicator here.
![visdif](https://user-images.githubusercontent.com/41024075/56767673-89a48b80-6769-11e9-91d8-ebaf79648a85.png)

**Comment by arouinfar** [comment]
Thanks for bringing this up @KatieWoe. It's not something we've had an explicit design discussion about.

While I do agree that it is a challenge to realize that a fuse has blown in schematic mode, I'm not sure that we need to do anything here. I think it's one of the trade-offs of using schematic. We could break the iconic filament, but I think we'd be likely to get pushback from folks for breaking the schematic convention. I'm curious if @samreid or @ariel-phet agrees.

I'll mark this for design meeting.

**Comment by ariel-phet** [comment]
@KatieWoe though we did not have an explicit discussion, I think we should not "make up a schematic"

I actually thought about this issue when I switched to schematic mode, but seeing that no "blown" fuse exists as a schematic it seemed like we should not try to do anything here.

I think we can close this issue.
