### ISSUE TITLE
Freeze on IE when focusing on an item

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#485]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
IE
**Problem description:**
For https://github.com/phetsims/QA/issues/311.  When focusing on a circuit item to change it's resistance or voltage, the sim freezes and must be refreshed.  Does not occur for items like the wire where a trash button is the only thing available.  So far only seen on IE, but it makes the sim unusable.
**Steps to reproduce:**
1. Grab a battery, resistor, or fuse
2. Click on the item so that a slider that would control some property would come up
3. The sim will now no longer respond to any clicking and must be refreshed.

**Screenshots:**
![focusfreeze](https://user-images.githubusercontent.com/41024075/56821087-b52b8280-680a-11e9-968e-aa3e840a2811.gif)

Troubleshooting information (do not edit):

<details>
  
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.3/phet/circuit-construction-kit-dc_en_phet.html
Version: 1.1.0-dev.3 2019-04-25 18:12:14 UTC
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; rv:11.0) like Gecko
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Is this problem also in the published version?

**Comment by KatieWoe** [comment]
No it is not.

**Comment by samreid** [comment]
Is an error message reported in the console?

**Comment by KatieWoe** [comment]
![console](https://user-images.githubusercontent.com/41024075/56905786-2020c780-6a5e-11e9-879a-e62bcd5a64b1.png)

**Comment by samreid** [comment]
I pushed a proposed fix to address https://github.com/phetsims/scenery-phet/issues/493, however, it cannot be tested with assertions enabled because some assertions in our codebase use Array.prototype.includes.  So I've published a dev version for testing this: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.4/phet/circuit-construction-kit-dc_en_phet.html

@KatieWoe can you please check if it is OK now?

**Comment by KatieWoe** [comment]
Problem seems to be solved there @samreid

**Comment by samreid** [comment]
Thanks, I'll close this issue.
