### ISSUE TITLE
Inconsistent voltage measurement after changed resistance

### ISSUE THREAD

**Issue by etwa4650** [phetsims/circuit-construction-kit-common#486]
<b>Test Device</b>

Jordan

<b>Operating System</b>

Mac OS 10.14.4

<b>Browser</b>

Google Chrome

<b>Problem Description</b>

for https://github.com/phetsims/QA/issues/311

When measuring the voltage going through a fuse, the voltage reader displays different number depending on whether the black probe is placed on the wire, or the connecting joint.

<b>Steps to Reproduce</b>

Initial setup:
<img width="607" alt="Screen Shot 2019-04-26 at 10 11 58 AM" src="https://user-images.githubusercontent.com/26493147/56821544-da6cc080-680b-11e9-81fb-410c4c3d577b.png">

The resistor is set at 300 ohms,
The Battery is set at 100 volts,
The fuse is set at 20.0 A

With the black probe placed on the joint connecting the fuse and the wire, and the red probe placed on the joint connecting the fuse and the battery.

With the black probe placed on the joint, the voltage reads 0.00 V

Move the black probe to the wire, and the voltage reads 0.001 V

<img width="633" alt="Screen Shot 2019-04-26 at 10 19 08 AM" src="https://user-images.githubusercontent.com/26493147/56821916-d2f9e700-680c-11e9-99f9-c81b47de6eed.png">

If the resistor is increase to 200 ohms, the voltage will alternate between 0.001 at the joint and 0.002 on the wire.

Once the resistance is increased passed 200 ohms or the voltage of the battery is increased, the voltage readings at the joint and the wire are equal.

**Comment by arouinfar** [comment]
Nice find @etwa4650!

> The resistor is set at 300 ohms,
The Battery is set at 100 volts,
The fuse is set at 20.0 A

By the way, if you take the screenshot with the "Values" checkbox on, you'll see the values over the circuit components. Might save you a bit of time with future circuit construction kit issues. :)
<img src="https://user-images.githubusercontent.com/8419308/56833754-9dfd8c80-682c-11e9-92f5-6fd404cb896c.png" width=200>

@samreid this behavior does look pretty strange to me. Can you look into it?

**Comment by ariel-phet** [comment]
@arouinfar @etwa4650 @samreid I actually do not think this is a bug...the wires (and the fuse itself) have some small resistance for the model too work. As you measure the voltage over a longer run of low restive elements, you will get more voltage drop. My guess is that the volt meter is not measuring "true zero" in the first case, but it is below the threshold to show 0.001 V.

**Comment by arouinfar** [comment]
> My guess is that the volt meter is not measuring "true zero" in the first case, but it is below the threshold to show 0.001 V.

Agreed, but at small voltages the voltmeter should be displaying a third decimal place, which is why I asked @samreid to look into it.

**Comment by samreid** [comment]
It's unclear what action to take or what the desired behavior is for this issue.  

> Move the black probe to the wire, and the voltage reads 0.001 V

As @ariel-phet said, this is due to the internal resistance of the wire.

> Agreed, but at small voltages the voltmeter should be displaying a third decimal place

Is the voltmeter sometimes supposed to show "0.000 V"?

**Comment by arouinfar** [comment]
> Is the voltmeter sometimes supposed to show "0.000 V"?

For some reason I had thought that this was the case, but looking at the published version, the ammeter reverts to two decimal places when the current dips below 0.001 A. I suppose I was just a bit rusty. :)

I think it would get really messy to decide when to display `0.000 A` vs. `0.00 A`, so I don't think we need to go there. I'll go ahead and close.
