### ISSUE TITLE
Images in other parts of carousel appear

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#487]
Test device:
Dell
Operating System:
Win 10
Browser:
Edge
Problem description:
For https://github.com/phetsims/QA/issues/311
When dragging items out of the left carousel box, the items in other parts may briefly become visible.  The wire in the box seems to disappear when this happens, even if it is not out.  Only seen on Edge so far.  Does not occur in published version that I've seen.  Does not seem to occur in Edge dev version.
Steps to reproduce:
1. Go to the first screen.
2. Start dragging out the wires and batteries while carefully watching the carousel box

Screenshots:
![ghostpieces](https://user-images.githubusercontent.com/41024075/56823589-8cf35200-6811-11e9-8918-ae6cbc3928a8.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.3/phet/circuit-construction-kit-dc_en_phet.html
Version: 1.1.0-dev.3 2019-04-25 18:12:14 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Language: en-US
Window: 1536x751
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by ariel-phet** [comment]
Since this is Edge only, and appears to not occur in Edge dev version, we will punt.

Marking deferred.

**Comment by KatieWoe** [comment]
Seen again in https://github.com/phetsims/QA/issues/361

**Comment by samreid** [comment]
I believe we dropped support for edge, and I haven't seen this bug. Closing for now, but please reopen if I'm wrong or if it recurs.
