### ISSUE TITLE
Inconsistencies in which fuse blows

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#490]
Test device:
Dell
Operating System:
Win 10
Browser:
Firefox
Problem description:
For https://github.com/phetsims/QA/issues/311
When a number of fuses are all in series and have the same threshold, a current over that should blow them all out, instead of just one at random.  In addition, if one fuse is lower threshold, it is not always the one to blow out.
Steps to reproduce:
1. Build a series circuit with fuses (one with a lower rating than the others), a switch, and a battery
2.  With the switch open, increase battery voltage so that it could blow out any of the fuses
3. Close switch and observe
4. Open switch, reset fuse, and repeat step 3

Screenshots:
![image (1)](https://user-images.githubusercontent.com/41024075/56829140-30e3fa00-6820-11e9-9153-f4b5e59292ca.png)
![image](https://user-images.githubusercontent.com/41024075/56829142-30e3fa00-6820-11e9-8d51-0765b17f3971.png)

Troubleshooting information (do not edit):

<details>

Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.3/phet/circuit-construction-kit-dc_en_phet.html
Version: 1.1.0-dev.3 2019-04-25 18:12:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

Since components in series have equal current, I would expect equally rated fuses to blow simultaneously. If the fuses have different ratings, the lowest rated should blow first. @samreid any idea what's going on here?

**Comment by ariel-phet** [comment]
@arouinfar @KatieWoe I actually don't agree. 

For one, you don't put multiple fuses in series. That is just really an non-real world approach. 

Sure, you could do it. And I am pretty confident that one will blow before the others. There are going to be small differences in the fuses, and once one blows, no more current will be flowing. I think it is actually fairly realistic for one to somewhat randomly blow if you have equivalent ones in series.

**Comment by KatieWoe** [comment]
That makes sense.  I tried looking up what would happen, but didn't find much because every result boiled down to "don't do that, it's dangerous."

**Comment by arouinfar** [comment]
> Sure, you could do it. And I am pretty confident that one will blow before the others. There are going to be small differences in the fuses, and once one blows, no more current will be flowing.

Sure, but as you say, that's because the fuses aren't actually identical. We could take that approach, but the sim is still buggy. Here, the lowest-rated fuse is still intact, which is non-physical.

![image](https://user-images.githubusercontent.com/8419308/56919043-d398b480-6a7c-11e9-84ca-3ed5386a97bc.png)

I would be fine with a single fuse blowing, assuming they were equally rated, as that is easy enough to explain in a real-world context.

**Comment by samreid** [comment]
If the current was gradually increased, the fuse with the lowest rating will trip first.  However, the test that is described for this issue is where all fuses are tripped simultaneously, since the current is 9 amps.  Therefore, it seems reasonable for a random fuse to trip.

For completeness, I'll mention I did try increasing the `timeCurrentRatingExceeded` threshold, but that has the same behavior.  If we want multiple fuses to trip at once, we will need another batching mechanism or further investigation.

**Comment by arouinfar** [comment]
> If the current was gradually increased, the fuse with the lowest rating will trip first.

Ah, I guess I had forgotten that detail from the original report. Tested this out, and the sim is behaving correctly.

> since the current is 9 amps. Therefore, it seems reasonable for a random fuse to trip.

Looking more carefully at the sim, it doesn't actually appear to be a random fuse. If you build a circuit with a few fuses in series, the fuse closet to the negative terminal of the battery will blow first. Repairing it will lead to the 2nd fuse getting blown, and so on. It's like the sim knows where the current "left off" and so the first fuse that it encounters will be blown, which seems really weird to me. @samreid is this somehow coincidence, or does the sim actually keep track of where the current left off?

![seriesfuses](https://user-images.githubusercontent.com/8419308/56926294-ad7c1000-6a8e-11e9-88d5-c3ee55a15ac2.gif)

**Comment by samreid** [comment]
It looks like the fuses are tripping in the order they are added to the model.  For instance, I added fuses in the left-to-right order:  1 4 2 5 3 and saw that they tripped in the order the were added: 1, 2, 3, 4, 5.

**Comment by arouinfar** [comment]
Thanks for the clarification @samreid. I am still somewhat uncomfortable with the idea that a higher rated fuse can blow before a lower-rated one. However, as @ariel-phet points out, connecting fuses in series does not have a real-world application, so I don't think we are likely to do any real harm here. I also made a note about series fuses in the Teacher Tips.

**Comment by Denz1994** [comment]
I noticed this issue while exploring the sim during a code review of the fuse node. I expected the fuses should blow out in sequential order, but when this wasn't the case, I pinged @samreid who directed me to this issue.

I thought the observation was worth noting in this issue.
