### ISSUE TITLE
Pointer Areas hard to hit

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#491]
For https://github.com/phetsims/QA/issues/311.  The pointer areas for the +/- minus buttons are too small to use effectively on an iPad.  On the published version, the title of the box was also clickable.  Now that this is removed, I had trouble hitting those buttons.
![toosmall](https://user-images.githubusercontent.com/41024075/56831861-8a9bf280-6827-11e9-885a-8f3920eb5260.png)

**Comment by arouinfar** [comment]
@samreid please dilate the touch areas of the `ExpandCollapseButton` like so:

![image](https://user-images.githubusercontent.com/8419308/56833533-fda76800-682b-11e9-81be-f4a69acb0d82.png)

**Comment by samreid** [comment]
Proposed fix is pushed, @arouinfar can you please review?

**Comment by arouinfar** [comment]
👍

**Comment by KatieWoe** [comment]
Looks good in dev test.  Also worth noting that per https://github.com/phetsims/sun/issues/477#issuecomment-488749407 the titles are now clickable again.
