### ISSUE TITLE
Code Review for Fuse and FuseNode

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#495]
From https://github.com/phetsims/circuit-construction-kit-common/issues/494.  CCK has an intermediate (minor) release coming up with a new feature of a Fuse component.  The code was developed in Fuse.js (123 lines) and FuseNode.js (186 lines) and can be tested by:

1. Open CCK DC
2. Go to the 2nd page of the carousel
3. Add a fuse to the play area.

Design decisions are described in #463 and related issues.

@ariel-phet asked if @Denz1994 can please look into this.  I'm not sure what the priority is, but it is not too many lines of code, so may not take too long.  @Denz1994 please reach out to me with questions, comments, etc.

**Comment by Denz1994** [comment]
REVIEW comments have been added to address code review suggestions. I will follow up with @samreid via a zoom call for added input regarding memory usage and the tripping behavior.

**Comment by samreid** [comment]
For this review comment:

```js
      // REVIEW: Inline conditional statement? Dev choice.
      // this.isTrippedProperty.value = this.timeCurrentRatingExceeded > 0.1;
      if ( this.timeCurrentRatingExceeded > 0.1 ) {
        this.isTrippedProperty.value = true;
      }
```

This logic should only be used to trip the fuse, not to untrip it, so the inline conditional statement would not have the correct behavior.

**Comment by samreid** [comment]
Thanks for the helpful feedback @Denz1994, I addressed the REVIEW comments.  Can you please review?

**Comment by Denz1994** [comment]
Thanks for the clarification regarding https://github.com/phetsims/circuit-construction-kit-common/issues/495#issuecomment-506441296. I'm going to reassign to @samreid for closure. The doc updates are much appreciated.

**Comment by samreid** [comment]
Thanks, this issue seems ready to close.
