### ISSUE TITLE
Memory leak when disposing fuse node.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#499]
Found during https://github.com/phetsims/circuit-construction-kit-common/issues/495.

Using Chrome (incognito) I followed these steps on the Lab Screen:

1. Take heap snapshot
2. Drag out max amount (10) of fuses in the play area (making sure not to connect them)
3. Take heap snapshot
4. Click trash can button for each fuse in the play area to dispose of them until none were left.
5. Take heap snapshot

Comparing the initial snapshot to the last one produced a memory increase of about 10 mb over 50 fuse disposals. Results are posted below.

Similar results were recorded for dragging the fuses into the carousel for disposal. @samreid Thought this is something worth looking into. Assigning to @samreid for further investigation.

Heap snapshot comparing initial play area with final play area after 50 disposals. Here we see a delta of +10 `Fuse` and +10 `ResetFuseButton` objects.  Note there is a duplicate 16th snapshot as a sanity check.
![image](https://user-images.githubusercontent.com/13894380/58126151-44487200-7be0-11e9-95ba-a3038f358050.png)

**Comment by samreid** [comment]
Same problem for resistors.  Dragging out 10 resistors then pressing reset all shows 10 resistors still in memory.

**Comment by samreid** [comment]
A few minutes of fuzzing: 
![image](https://user-images.githubusercontent.com/679486/60292282-fb1fc800-98d9-11e9-8acd-0d27d784751c.png)

**Comment by jessegreenberg** [comment]
After https://github.com/phetsims/scenery/issues/982, here are a collection of heap snapshots with ?fuzz in CCK-DC, taken every 30-45 seconds.
![image](https://user-images.githubusercontent.com/6396244/60361115-61285000-99ab-11e9-9e8a-6d5fee33dde8.png)

**Comment by samreid** [comment]
The wide variability is due to creation and deletion of components.  A less noisy test would be to press Reset All right before each memory snapshot, but currently we have no way to do that during fuzzing.  Here are my results from a run:

![image](https://user-images.githubusercontent.com/679486/60372644-7d7fb900-99ba-11e9-9d59-abd9c2de103e.png)

**Comment by samreid** [comment]
I launched the sim with ?fuzz, then captured a memory profile, then let it run for a few minutes, then paused fuzzing via `phet.chipper.queryParameters.fuzz=false` then captured another memory profile.  No problems indicated between the two snapshots.

![image](https://user-images.githubusercontent.com/679486/60378860-5343f080-99e6-11e9-94d1-780e595b65af.png)

Following @Denz1994 instructions from the top comment, I still see an allocation for the first Fuse/FuseNode but after that, subsequent creation/deletion do not appear.  Perhaps the first one is just some startup overhead?  I followed these steps:
1. Launch sim.
2. Create one fuse and dispose it with "erase button"
3. Capture memory profile
4. Create 3 fuses then delete each with the erase buttons
5. Capture memory profile.

I saw no fuse deltas for this use case:
![image](https://user-images.githubusercontent.com/679486/60378952-d7e33e80-99e7-11e9-8444-6a66d1cb628c.png)

@Denz1994 can you please review?  Close if all is well.

**Comment by Denz1994** [comment]
Thanks, @jessegreenberg for the help on this one. I'm seeing similar results after repeating @samreid test from https://github.com/phetsims/circuit-construction-kit-common/issues/499#issuecomment-506921285.

I'm going to close this one since the initial memory leak is not evident any longer in the memory profiles.
