### ISSUE TITLE
Which inductor schematic symbol should we use?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#503]
I'm seeing several schematic symbols to represent inductors:

![image](https://user-images.githubusercontent.com/679486/64180091-6ed1da00-ce21-11e9-9aa9-e3d57c208581.png)

![image](https://user-images.githubusercontent.com/679486/64180267-bce6dd80-ce21-11e9-869f-b9e7cfb05a89.png)

![image](https://user-images.githubusercontent.com/679486/64180283-c708dc00-ce21-11e9-9ef8-8911025c8343.png)

**Comment by ariel-phet** [comment]
To me, the "generic air-core" is the clearest, but the generic or IEC-style air cooled also seems fine to me.

**Comment by arouinfar** [comment]
The Java version of the sim uses an IEC-like symbol.
![image](https://user-images.githubusercontent.com/8419308/64202894-79a36380-ce4f-11e9-959b-9ba946c4c49f.png)

Generally, the generic/air-core symbol seems most prevalent in the US. I checked 4 intro textbooks & Hyperphysics, and most use the generic/air-core symbol -- just 1 textbook used the IEC symbol.
<img src="https://user-images.githubusercontent.com/8419308/64203072-f46c7e80-ce4f-11e9-8c43-e1db914e9f83.png" width=150>

That said, there have been a few requests to use the IEC symbol of a resistor (see https://github.com/phetsims/circuit-construction-kit-common/issues/429), so we will likely get pushback for not using the IEC symbol. In https://github.com/phetsims/circuit-construction-kit-common/issues/429#issuecomment-448352441, I suggested that we could allow users to switch between IEEE and IEC symbols in the Options menu.

**Comment by samreid** [comment]
Maybe we could use ParametricSpringNode for one of these views.

From today's meeting, we would like to add a global options menu to select IEC vs IEEE.  Defaults for 1.0 will be IEEE, since that is what we have been doing.  Perhaps if we have an assistant, they can help with the different schematic shapes.

**Comment by samreid** [comment]
@kathy-phet also noted that it was tricky choosing a bulb schematic that matched our vertex layout.  That may need to remain the same between IEEE/IEC

**Comment by samreid** [comment]
@kathy-phet points out that a query parameter should be able to select between these options.

**Comment by samreid** [comment]
https://www.ee.iitb.ac.in/~spilab/Tips/ansii_graphic_symbols_for_electrical_and_electronics_daigrams_1993.pdf is titled:

> IEEE Standard
American National Standard
Canadian Standard
Graphic Symbols for Electrical and
Electronics Diagrams
(Including Reference Designation Letters)

and shows:

![image](https://user-images.githubusercontent.com/679486/68076520-2a0fe400-fd7b-11e9-9178-a065bc0fdc74.png)

![image](https://user-images.githubusercontent.com/679486/68076537-63e0ea80-fd7b-11e9-97a2-211ff446d8b7.png)

**Comment by samreid** [comment]
Wikipedia shows:

![image](https://user-images.githubusercontent.com/679486/68076545-87a43080-fd7b-11e9-8733-0880ad99e2cf.png)

@arouinfar can you please review this and the preceding comment and let me know what you recommend for IEEE?  I was confused about whether we are showing the magnetic core bars, or why the IEEE doc says "this symbol is deprecated and should not be used".

I'll also proceed in creating the IEC air-core schematic, since it seems it may also be the IEEE one or part of it.

**Comment by samreid** [comment]
I added this one:

![image](https://user-images.githubusercontent.com/679486/68089246-12406a80-fe24-11e9-8563-d1615eaac13f.png)

Unassigning until I hear back about the preceding comments.

**Comment by arouinfar** [comment]
@samreid the schematic inductor looks good in master. I'll go ahead and close this issue since further discussion of the IEEE/IEC symbols belongs in #429.
