### ISSUE TITLE
Should probes snap to objects?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#504]
From https://github.com/phetsims/circuit-construction-kit-common/issues/294

Should probes snap to objects?  For example, when a voltmeter probe is near a battery, should it snap to show it is in contact?  Likewise, when the user puts a probe on a wire, then moves the wire, should the probe follow?

**Comment by arouinfar** [comment]
@samreid I'm not sure if this is something we really need to pursue. As far as I know, we haven't had any complaints in regards to #294.

**Comment by samreid** [comment]
Sounds good, let's close for now and we can reopen if we change our minds.
