### ISSUE TITLE
Should the placement of the lifelike/schematic buttons be underneath the carousel in both AC and DC sims?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#505]
The design doc for AC says:

> Lifelike/Schematic radio buttons
> Buttons are grouped below the carousel for better proximity to the circuit components.

It would simplify the code as well as making the user interfaces more consistent (between the sims) to have the buttons in the same spot.  What do you recommend?

Also, I have a bit of deja vu about this, so my apologies if I have already asked (couldn't find a paper trail).

UPDATE: Tagging for https://github.com/phetsims/circuit-construction-kit-common/issues/449

**Comment by arouinfar** [comment]
We relocated the scene buttons due to crowding on the Lab screen
![image](https://user-images.githubusercontent.com/8419308/64299251-acc02280-cf35-11e9-842a-aaf8a780ec28.png)

I prefer the the sizing/positioning of these button in the current AC design, and think it could be a change we carry over to the DC sim. 

How does that sound to you @ariel-phet?

**Comment by ariel-phet** [comment]
Seems fine to me.

**Comment by samreid** [comment]
Fixed in the preceding commits, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@samreid looks good, but I think we could probably move the radioButtonGroup down a bit so there's more padding between the carousel and the buttons. Can you try bumping it down a bit, maybe 10 px or so?

**Comment by samreid** [comment]
I bumped it down 10px in the commit.  But I thought I should ask: right now it is positioned 20px below the carousel no matter how big the carousel is.  Would it be better to position it a fixed distance above the zoom buttons instead?  Different screens have different carousel sizes.

**Comment by samreid** [comment]
@arouinfar and I agreed to close this issue, and address the preceding comment during pixel polishing phase.

**Comment by arouinfar** [comment]
@samreid I think it's better to keep the button placement relative to the carousel position, as there is a possibility that the zoom buttons may get relocated in the carousel pixel polishing done in #507.

I don't think we'll need to make any further changes here, but I'd like @samreid to confirm before closing.

**Comment by samreid** [comment]
Sounds good, thanks!  Closing.
