### ISSUE TITLE
Should the lifelike/schematic button group be horizontal instead of vertical?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#506]
From #505 

@arouinfar have you considered making the lifelike/schematic buttons horizontal instead of vertical?  Even if it exceeds the width of the carousel, it may make it easier to visually parse--as it stands (vertical), they kind of seem like two more choices of circuit element.

We could also move it lower--by the zoom buttons, if it helps.

**Comment by arouinfar** [comment]
@samreid I'd rather not have horizontal radio buttons, as it would cut into the play area which could look pretty odd. We could bump the buttons down a bit so there's some more negative space between the carousel and the buttons, but we can handle the polishing in #505.
