### ISSUE TITLE
Should the RLC toolbox be a carousel or panel?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#507]
Related to https://github.com/phetsims/circuit-construction-kit-common/issues/465, I noticed that CCK used to have code in ee5186b9db5f87697c4e7176fd4dafc035e6be4b where it used to switch between panel vs carousel depending on the number of items as part of https://github.com/phetsims/circuit-construction-kit-common/issues/330.  Eventually we decided to make all of the other CCK screens use carousels, and took effort to make sure they look uniform (same dimensions) on every screen.

I thought I'd double check whether we want a carousel or not for the RLC screen.  The proposal in #465 is to have a panel (not carousel) with 9 items in it.

We should also think forward to if/when we develop a CCK Intro sim--if that has a panel instead of carousel, we could spend the time implementing that now and using it in RLC.

**Comment by samreid** [comment]
In discussion today, @arouinfar and I agreed it would be nice to keep it as a carousel, and add grab bag items in the later pages.  @arouinfar will determine what appears in each page.

**Comment by arouinfar** [comment]
1/9/20 design meeting notes

* Carousel on all screens
* Grab bag items on all screens
* @arouinfar will pixel polish the RLC carousel, including icon size and top/bottom padding.

**Comment by arouinfar** [comment]
@samreid here are the pixel polishing requests for the AC carousel. I don't know how much is shared with DC, but I am fine with any of these tweaks making their way over to DC too.

- [ ] Make carousel 10 px taller
- [ ] Reduce padding between carousel buttons and first/last item to 20 px
- [ ] Reduce large icons (light bulb, capacitor, inductor) by 10%
- [ ] Padding between icon and label is 3 px
- [ ] Equal padding between carousel items

Here's a comparison of the current (left) and proposed (right) carousels. (Note that lifelike/schematic buttons were moved down 10 px to maintain the padding between them and the carousel.)
![image](https://user-images.githubusercontent.com/8419308/100946489-add95a00-34c0-11eb-83af-19bd8023585d.png)

**Comment by samreid** [comment]
I'll move the preceding comment to a new issue and close this one, since we determined that carousels will appear on all screens.

**Comment by samreid** [comment]
I moved the preceding comment to a new issue, closing.
