### ISSUE TITLE
Voltage text box moves when zoom in/out

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/circuit-construction-kit-common#515]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.6

**Browser:**

Safari 10.1.2

**Problem description:**

While testing the CCK DC, I noticed that the text box for the voltage on a battery can move when one zooms in if the circuit is large, the battery has been flipped upside down and is on fire. This is for phetsims/QA/issues/48.

**Steps to reproduce:**

1. Zoom out.
2. Check the "Values" box.
3. Put a battery in the center of the screen.
4. Connect a wire from the negative terminal to the upper left corner of the screen.
5. Connect a wire from the positive terminal to the lower right corner of the screen.
6. Complete the circuit by connecting another wire to the loose ends of the other two wires.
7. Flip the battery.
8. Zoom in.

**Screenshots:**

![sep-08-2017 16-55-34](https://user-images.githubusercontent.com/31285590/30233984-9ca510b0-94b6-11e7-82c7-88f706a461d7.gif)

**Troubleshooting information (do not edit):**

Name: ‪Circuit Construction Kit: DC‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.160/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.160 2017-09-07 18:03:16 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
Language: en-US
Window: 1440x727
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.25.17)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"7083c475","branch":"master"},"babel":{"sha":"5b127384","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"66110366","branch":"master"},"circuit-construction-kit-common":{"sha":"a165d9ef","branch":"master"},"circuit-construction-kit-dc":{"sha":"2722c8da","branch":"master"},"dot":{"sha":"630fb098","branch":"master"},"joist":{"sha":"f51d5ab4","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"phet-core":{"sha":"30da7870","branch":"master"},"phetcommon":{"sha":"1a5ceb11","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"fc2d1cf1","branch":"master"},"scenery-phet":{"sha":"55f204d3","branch":"master"},"sherpa":{"sha":"e29820c9","branch":"master"},"sun":{"sha":"1ed8afa5","branch":"master"},"tandem":{"sha":"37243b99","branch":"master"},"twixt":{"sha":"6f27c1ff","branch":"master"}}

**Comment by samreid** [comment]
In master on Chrome, the voltage text box now travels with the battery in this scenario.  Closing.
