### ISSUE TITLE
Consider allowing multiple voltmeters

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#518]
For phetsims/circuit-construction-kit-ac-and-dc#4. 

@samreid raised a few design issues in the following tickets.

[Unfuddle Ticket #389](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/389)
> The voltmeter / multimeter is excellent but only one can be used on
the screen. If 2 or 3 voltmeters could be on screen at same time this would help me
explain potential divider circuits better.

[Unfuddle Ticket #375](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/375)
>Design Issue: This may have already been discussed, but I thought I’d share it. On the right-most tool bar/palette under the title “Tools,” there are 6 tools: Voltmeter, Ammeter(s), Non-Contact Ammeter, Stopwatch, Current Chart, and Voltage Chart. These tools operate in 3 different ways:
>1) Voltmeter, Non-Contact Ammeter, and Stopwatch: when you check the box, the tool appears in the play area. You are not allowed to have multiple tools (e.g., multiple voltmeters). To remove these items, you have to uncheck the box.
>2) Ammeter(s): when you check the box, the tool appears in the tool bar/palette and then you have to drag it into the play area. You are allowed multiple Ammeters. To remove these items, you have to right click and choose “Remove.”
>3) Current and Voltage Chart: when you click on the button, the chart appears in the play area. You are allowed to have more than one Current (or Voltage) Chart at a time. To remove the tool, click on the red “X” on the top left corner of the chart.
>
>It seems a bit odd to have these different tools operate in different manners. Why not choose one standard, and create a palette similar to that for circuit elements where the user drags and drops the tool in the play area, right clicks to remove, and is allowed to have more than one of the same tool in the play area? It does not seem to make sense to have these tools operate in different manners—they are all tools.

Most of these concerns are addressed in the HTML5 design, with the exception of allowing multiple voltmeters. In CCK: DC, there are four in-line ammeters. We could do something similar with the voltmeter (or non-contact ammeter). Marking for design meeting discussion.

**Comment by samreid** [comment]
We would like to try 2x ammeter, 2x voltmeter, but only 1x of each chart.

**Comment by samreid** [comment]
If we are going to limit the number of voltmeters to 2, then I think I should code it like `model.voltmeter1` and `model.voltmeter2`.  However, if we anticipate PhET-iO should be able to create more than 2, then I might put group them in an array or Group, like `model.voltmeters.voltmeter_1`, etc.  @arouinfar, @ariel-phet or @kathy-phet what do you think?

**Comment by ariel-phet** [comment]
I really think more than 2 is overkill. Generally comparing/contrasting 2 parts of a circuit would be the most pedagogically useful in my opinion (such as voltage drop in the symmetric cases of series and parallel resistors). I also think with the size of the play area, 3 would just get unnecessarily crowded.

**Comment by kathy-phet** [comment]
I think 2 is sufficient. And agree with Ariel, that 3 is getting too crowded.

**Comment by arouinfar** [comment]
Thanks for checking in @samreid. Like @kathy-phet and @ariel-phet, I don't think we need to allow more than 2 meters.

**Comment by samreid** [comment]
Fixed in the commits and working well in local testing, closing.
