### ISSUE TITLE
How to simulate charges passing between the capacitor plates?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#524]
We would like to show that no electrons pass between the capacitor plates.  In Java this was accomplished with constructive area geometry, creating many clipping areas where the electrons aren't shown in front of the capacitors.  The desired behavior is something like so:

![Kapture 2019-10-10 at 9 40 52](https://user-images.githubusercontent.com/679486/66584307-1f7a7a00-eb42-11e9-913e-aeaa68864b42.gif)
 

It has some quirky behaviors like so:

![Kapture 2019-10-10 at 9 37 10](https://user-images.githubusercontent.com/679486/66584038-9f541480-eb41-11e9-9220-4cb364f15b0c.gif)

Some ideas:
1. For electrons that are in the Capacitor circuit element, apply a clipping region to that electron image.
2. Render a clipped version of capacitors (just the middle) in front of everything

I'd love to hear if @jonathanolson has better ideas.

**Comment by jonathanolson** [comment]
I'm not sure I understand the exact desired behavior, as it seems like electrons are shown in front of the capacitors in some situations in the animations above? Do you mean they shouldn't be shown between the plates?

**Comment by samreid** [comment]
It's supposed to be a pseudo-3D effect.  In the topmost animation, the left plate is " in front", and electrons flow into it.  Then they flow out of the back of the right plate, so are "behind" it.

**Comment by jonathanolson** [comment]
I'm curious if splitting the capacitors into two nodes, one layered in front of the electrons, and the other behind would work? That's probably the highest-performance option. Alternatively having a clipping region defined for the electrons.

CAG might work too, but performance would be potentially an issue, unless it's smart about knowing when to use it (i.e. don't CAG every single electron shape at every frame).

**Comment by samreid** [comment]
Here's initial testing of per-node clipping:

```js
      if ( this.charge.circuitElement instanceof Capacitor ) {
        if ( this.charge.distance > 20 && this.charge.distance < 100 ) {
          const rightEdge = 50 - this.charge.distance;
          this.clipArea = Shape.rect( 0, 0, rightEdge, 1000 );
        }
        else {
          this.clipArea = null;
        }
      }
```

**Comment by samreid** [comment]
From slack:

Sam Reid 9:49 AM
I think I need to do something like Node.localToParentShape(), but all I can find are bounds and point.  What should I do?

Jonathan Olson 9:50 AM
node.transform.transformShape( shape ) would work. Or shape.transformed( node.matrix ). Let me know if named varieties would be good long-term

Sam Reid 9:50 AM
Would I need to do the inverse of one of those?

Jonathan Olson 9:51 AM
node.transform.inverseShape( shape ) would be the parent-to-local variety.  Or shape.transformed( node.matrix.inverted() )

Sam Reid 9:51 AM
Thanks, I appreciate it!

**Comment by samreid** [comment]
After the preceding commit, everything is looking good for lifelike.  We will also need to do the same thing for schematic.

**Comment by samreid** [comment]
Implemented above, working much better than in Java.  Some minor TODOs marked in the code and one side issue opened above.  Closing.
