### ISSUE TITLE
Clip electrons in battery schematic view

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#527]
From #524, I noticed that charges are clipped between schematic capacitor plates but not batteries.  @arouinfar should we also apply clipping to the electrons when they appear in schematic batteries?

![image](https://user-images.githubusercontent.com/679486/66771405-6ab0c780-ee77-11e9-8746-54c4834a806a.png)

**Comment by arouinfar** [comment]
@samreid I don't think we need to be worried about a clipping mask for the battery. The gap in the capacitor is physical and matches the electron flow of the lifelike circuit, so the clipping mask feels natural.
