### ISSUE TITLE
It seems like the plate charge should change when the capacitance changes

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#538]
Currently in the simulation, if you wire up a capacitor to a battery, then change the capacitance, the displayed charge on the capacitor remains the same and no charge flows.  But I suspect it should change according to `q=CV`.  But when changing the capacitance, will the current also flow through the circuit?  I'm not sure why it doesn't already have the expected behavior, and I'm not sure how complicated it would be to implement the expected behavior, but I thought I should reach out and make sure we are the same page about what the expected behavior should be.  @arouinfar can you please comment?

**Comment by arouinfar** [comment]
> Currently in the simulation, if you wire up a capacitor to a battery, then change the capacitance, the displayed charge on the capacitor remains the same and no charge flows. But I suspect it should change according to q=CV. 

That sounds really buggy to me. I would also expect the charge to change in accordance with `q=CV`. The Java sim appears to handle the charge density correctly when changing C or V. @samreid can you investigate?

**Comment by samreid** [comment]
I fixed this in the preceding commits.  @arouinfar can you please review the behavior on phettest?

**Comment by arouinfar** [comment]
Looks good in master @samreid!
