### ISSUE TITLE
AC source should have settable phase on lab screen

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#539]
AC source should have settable phase on lab screen

**Comment by samreid** [comment]
Like this:

![image](https://user-images.githubusercontent.com/679486/67826575-985e5900-fa92-11e9-9543-83699617833a.png)

**Comment by samreid** [comment]
From slack, I said:

> I need a number control like this: Where should I look or start?

Jonathan Olson 9:41 PM
> That doesn't transfer over directly. I'll presumably create my own? And not sure, I'd look at NumberControl layouts

Sam Reid 9:42 PM
> It looks like all 4 NumberControl layouts include the slider

**Comment by arouinfar** [comment]
@samreid I'm fairly certain this component is called a NumberSpinner.

**Comment by samreid** [comment]
I added a settable phase control, but there is a problem to discuss.  In order to smoothly and continuously change the frequency without disrupting the waveform, I've been matching the phase shift when frequency changes.  This makes for great waveforms, but it seems odd that the phase control changes as you change the frequency.  I considered adding 2 phase controls: (a) a latent one which is used for frequency matching and (b) the user-controlled one which sets an additional phase.  @arouinfar you can see the behavior in master on phettest.  Can you recommend how to proceed?

**Comment by samreid** [comment]
At design meeting, we decided that matching the phase as the frequency is changed is not important.  Keeping the phases simple and aligned is more important.  We will delete this part.

**Comment by samreid** [comment]
I removed the code that matches phase as frequency is changed, and restricted the phase control to the lab screen.  I also internationalized the label.  Closing.
