### ISSUE TITLE
AC Source should have settable internal resistance on the lab screen

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#540]
AC Source should have settable internal resistance on the lab screen

**Comment by samreid** [comment]
This will be in an advanced panel like so:

![image](https://user-images.githubusercontent.com/679486/67641255-88921980-f8c6-11e9-8e01-1857ad0f85e8.png)

**Comment by samreid** [comment]
Here is how it currently looks in CCK DC:

![image](https://user-images.githubusercontent.com/679486/70377975-35a17e00-18d8-11ea-9afe-0145752706af.png)

The code will be simpler, easier to maintain and instrument if we unify it across DC and AC sims.  Should the DC simulation be revised to use a pattern more like the one proposed for AC, perhaps using the term "Battery" instead of "Source"?

**Comment by arouinfar** [comment]
@samreid I would be fine with using the layout shown in https://github.com/phetsims/circuit-construction-kit-common/issues/540#issuecomment-546731448 for both sims if it is possible for AC and DC to use different strings. For AC, "Source" is the more appropriate term, while "Battery" is more appropriate for DC.

**Comment by samreid** [comment]
I committed an initial draft, @arouinfar can you please review it in the DC sim as well as the AC sim?

**Comment by arouinfar** [comment]
@samreid the accordion box contents look good in cck-dc and cck-ac, but the alignment of "Advanced" is a bit off.
<img src="https://user-images.githubusercontent.com/8419308/72547390-cd847700-3849-11ea-9748-1aacb66a6844.png" width=200>

The padding between the ExpandCollapseButton and the title string is excessive. Let's cut it down so the padding is more like this
![image](https://user-images.githubusercontent.com/8419308/72547621-379d1c00-384a-11ea-89dc-8a8a67277bbb.png)

**Comment by samreid** [comment]
I removed the spacing in the commit, @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid!
