### ISSUE TITLE
The inductor should have a clear button

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#542]
Like #541 the inductor will need a clear button.

**Comment by samreid** [comment]
I noted there are some icon ideas in the design doc.

**Comment by arouinfar** [comment]
@samreid if you need a place-holder, I would suggest using the reset icon, which is what is in the latest version of the mockups.

![image](https://user-images.githubusercontent.com/8419308/67720045-a16aff80-f998-11e9-9aef-c7bcbd9b0fdc.png)

Looking at the [4/9/19 meeting notes](https://docs.google.com/document/d/1bueLDNUhlGuYUMFVvQW2wlZMRknLG7ClZfVMd0GL6ag/edit#heading=h.ofumvjk8grba), another suggestion was to use a magnet with the with the ban symbol on top. There are font-awesome icons for the magnet (u+f076) and ban icon (u+f05e). The ban icon is pretty heavy, so we may want to just draw our own.

![image](https://user-images.githubusercontent.com/8419308/67723567-10992180-f9a2-11e9-950f-988a5a28c5f0.png)

From left to right
1. Stock font-awesome icons. Ban is too heavy, imo
2. Thinner ban icon + stock magnet
3. Thinner ban icon + magnet rotated 90*
4. Thinner ban icon + magnet rotated -45*

Personally I think option (4) is the most readable. @samreid @ariel-phet what do you think?

**Comment by ariel-phet** [comment]
@arouinfar agreed with (4) - but it seems an eraser icon could also work

**Comment by samreid** [comment]
Based on the nice idea in https://github.com/phetsims/circuit-construction-kit-common/issues/541#issuecomment-547523152, I added the "ban" lightning bolt for both the inductor and the capacitor.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@samreid this is looking good on master. I'll tag for design meeting for the team's sign off.

**Comment by samreid** [comment]
The design team agreed this icon works well for inductor and capacitor, closing.
