### ISSUE TITLE
Check units for capacitor

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#544]
We should check on the values for C=keA/d to make sure the values are reasonable.

**Comment by samreid** [comment]
Using a 0.2 F capacitor, with e0 = 8.85E-12, we have:

0.2 = 8.85x10 -12 * A/d
d= 4.425e-11 * A

It seems we are really "cartooning" up the plate separation relative to plate areas.  @arouinfar should we do anything about this, or leave it as-is?  You can see the current version of plate depiction on phettest.

**Comment by arouinfar** [comment]
@samreid the behavior on master is what we had envisioned. At minimum capacitance, the plates are as far apart as possible. At maximum capacitance, the plates are as close as possible (while still looking reasonable). Between the extrema, the separation scales linearly. These distances are of course exaggerated, but the goal here is to have some visual indication of the capacitance. This also shows one possible way that C could be physically adjusted. 

The behavior can remain as-is, so closing.
