### ISSUE TITLE
Negative to Negative allows Circuit

### ISSUE THREAD

**Issue by gregmax17** [phetsims/circuit-construction-kit-common#546]
I attached a screen shot to show a better example. I have a negative and negative attached yet the lightbulb is lit up.

<img width="465" alt="Screen Shot 2019-10-18 at 9 57 43 AM" src="https://user-images.githubusercontent.com/220331/67685620-0869c380-f95b-11e9-9ad9-113756531c4c.png">

**Comment by samreid** [comment]
If those are all 9 volt batteries, then the net voltage will be 9 + 9 - 9 volts = 9 volts, still enough to power the light bulb.
