### ISSUE TITLE
The coin can read current but not voltage

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#550]
During testing, I noticed that the coin can detect current with the current sensor but not voltage with the voltmeter.  This is true in master and the published DC version.  I can't recall if this is by design, or by an oversight, or if we wanted to implement this but didn't know how or didn't have time.  @arouinfar can you please comment?

**Comment by arouinfar** [comment]
Currently, the voltmeter is only able to read on the wires and vertices, while the non-contact ammeter can read within the bounds of any circuit component. The bounding box for circuit components is rectangular, which generally aligns with the physical bounds of the circuit components, but there are some odd corner cases such as this:
![image](https://user-images.githubusercontent.com/8419308/70580913-9fd54f80-1b72-11ea-987f-bef6a23f68fd.png)

I think it's important that the voltmeter only provides a reading when the probes are touching something conductive. We could expand the behavior to include the bounds of the coin and paperclip, but I think that could get a bit dicey. If we use the same rules as the current meter (read anywhere within the rectangular bounds), there will be plenty of situations where the voltmeter probes won't quite be touching something metallic, but the probe produces a reading.

I would rather leave things the way they are now. As far as I know, we haven't had anyone write into phethelp about the current behavior.

@samreid if you agree, please close. If not, I'd be happy to discuss further or in a future design meeting.

**Comment by samreid** [comment]
I'm happy to leave things as they are, just wanted to make sure it was a deliberate choice, and that we have a way to track it.  Closing.
