### ISSUE TITLE
Fix the length scaling of wires

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#553]
Let's call a battery 5cm and use it to rescale the physics.

```js
const METERS_PER_VIEW_COORDINATE = 0.015273409966500692;
```

This should reduce the overall resistance.

We will try to have the correct copper resistivity, but if this change causes too many odd ramifications, we can potentially change the resistivity.

In the lab view, we'll want the updated "resistivity" control to make sure it creates a measurable change.

See #245 

@ariel-phet recommended to run this past him after first draft.

**Comment by samreid** [comment]
Changes in the commit:

* A battery is now 0.05m long
* Resistance is now determined as `R = rho * L / A`.  Resistance = resistivity * Length / cross sectional area.  Previous version used R = 1E-5 * L
* Resistivity taken from https://en.wikipedia.org/wiki/Electrical_resistivity_and_conductivity says copper has rho=1.68E-8 Ohm * m
* Wire cross sectional area taken from http://www.sengpielaudio.com/calculator-cross-section.htm, I went with AWG Wire Gauge of 20 has 0.52mm^2 = 5.2e-7m^2
* I changed the max resistivity (for the advanced controls) to 1000x the default resistivity, so that the overall behavior (current as a function of resistivity has the same behavior as the previous version).

> This should reduce the overall resistance.

The resistance of the default length wire in the previous version was: `0.000015273409966500693 Ohms`
The resistance of the default length wire after the changes I described is: `1.68E-8* 0.05/5.2E-7 = 0.0016153846153846155`.  This is approximately 100x higher.  

@ariel-phet, can you please review these figures and recommend how to proceed?  What value do you recommend for the gauge/cross sectional area of the wire?  I chose AWG Wire Gauge of 20 arbitrarily.

**Comment by ariel-phet** [comment]
Hey @samreid for our "near ideal wires" on the first screen lets go with a cross section of around 5e-4 m^2 (that is a pretty big wire diameter wise, but I think on the first screen we are trying to approximate ideal as closely as possible, and we want to see if we can push the resistance of the wires down a bit).

If you can do that and publish a dev version, I can play and we can see if there are unintended consequences.

**Comment by samreid** [comment]
I increased the wire cross sectional area to 5E-5m^2 and updated the "lots" value of the wire resistivity.  Here's a dev version:
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.5/phet/circuit-construction-kit-ac_en_phet.html

**Comment by ariel-phet** [comment]
@samreid I did some quick checks of behavior and physics, as well as looking at the "short circuit" example with both DC and AC. Everything is looking quite nice. Closing - we can always adjust if QA runs into some issues, but I think we are in a good place
