### ISSUE TITLE
update resistance of the hand

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#554]
A user wrote into phethelp
> I'm a middle school teacher and my class is going over electricity and circuits but I noticed something that doesn't make sense to me. When student hook up the human hand to their circuits the light bulb goes out. I thought the human body conducts electricity. Could you please help me understand?

The resistance of the hand matches the Java version, but it is an order of magnitude too high. Most sources list the value around 100000 ohms.

@samreid please update the value to 100000.

**Comment by arouinfar** [comment]
This now means that the max current through the hand will be ~4 amps in CCK: DC. Since the hand is disembodied, we do not have the same reservations around electrocution as we do with the dog (#512).

**Comment by samreid** [comment]
Also, from our design meeting yesterday, the specification is that the hand should be flammable.

**Comment by samreid** [comment]
I changed the hand resistance to 100000 Ohms, @arouinfar would you like to test in context?  Close if all is well.

**Comment by samreid** [comment]
I noticed there are other parts to update, self assigning until fully fixed.

**Comment by samreid** [comment]
OK, thanks for your patience.  This one is ready for testing now, please let me know how it goes.

**Comment by arouinfar** [comment]
Looks good in master, thanks!
