### ISSUE TITLE
Lifelike/schematic radio buttons should be side by side instead of top/bottom

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#555]
From yesterday's design meeting, it sounded like we wanted to make the lifelike/schematic radio buttons side by side instead of top/bottom.  @arouinfar is that your understanding as well?  I didn't see if there was another issue for that.

Somewhat related to https://github.com/phetsims/circuit-construction-kit-common/issues/505

**Comment by arouinfar** [comment]
@samreid this was indeed considered during design meeting, but I don't know that we made a decision. The given the width of the carousel and the aspect ratio of the buttons, the alignment will probably look a bit odd if we stack them side-by-side.
![image](https://user-images.githubusercontent.com/8419308/72296696-7c8d3c80-3617-11ea-90d8-3c1378870d96.png)

As I work on the pixelpolishing in #507, I will consider this to be an option, but it's more likely that we would relocate the zoom buttons.

**Comment by samreid** [comment]
Can this issue be closed?

**Comment by arouinfar** [comment]
This issue is stale, and the placement of the lifelike/schematic buttons was addressed in https://github.com/phetsims/circuit-construction-kit-common/issues/618. Closing.
