### ISSUE TITLE
ResetAllButton gets stuck in pressed position

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#556]
Occurs in cck-ac and cck-dc on master. When the ResetAllButton is pressed, it gets stuck in the pressed position and the sim freezes.
![image](https://user-images.githubusercontent.com/8419308/72369749-fb3cb500-36bd-11ea-9c7d-f65ec379c45b.png)

The sim will also partially reset -- some of the circuit components will return to the carousel and the radio buttons/checkboxes reset. Tools do not return to the toolbox.

**Comment by samreid** [comment]
Thanks @arouinfar, I pushed a fix for this.  Please close if all is well.

**Comment by arouinfar** [comment]
Looks good in master, thanks!

**Comment by arouinfar** [comment]
Actually... the voltage and current charts aren't returning to the toolbox.

**Comment by samreid** [comment]
I recommend moving the aforementioned comment to a new issue.  It is a different symptom and will have a different solution.  I'll create a new issue now.
