### ISSUE TITLE
the voltage and current charts aren't returning to the toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#557]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/556, the voltage and current charts aren't returning to the toolbox.

**Comment by samreid** [comment]
Fixed (and one related issue opened), @arouinfar please test and close if this issue is addressed.

**Comment by arouinfar** [comment]
Fixed in master. Thanks @samreid
