### ISSUE TITLE
grab bag value labels left behind on resetAll

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#559]
Likely related to #556 #557 #558

Only appears to affect grab bag items.

1. Drag out grab bag item
2. Reset All
3. Turn on values, and the value label of the grab bag item(s) previously in the play area will appear.

![grabbag](https://user-images.githubusercontent.com/8419308/72372750-2a562500-36c4-11ea-8fcc-2fcd3438536a.gif)

**Comment by samreid** [comment]
It seems like we need to embed household items in a PhetioGroup so they can be treated uniformly and disposed.  See CircuitElementToolFactory

**Comment by samreid** [comment]
While working on this, I noticed a related issue, so I opened https://github.com/phetsims/circuit-construction-kit-common/issues/560.  But this issue seems to be addressed.  @arouinfar can you please verify?

**Comment by arouinfar** [comment]
Looks fixed in master, thanks!
