### ISSUE TITLE
Dropping an item in the toolbox doesn't dispose the readout

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#560]
Discovered during https://github.com/phetsims/circuit-construction-kit-common/issues/559, Dropping an item in the toolbox doesn't dispose the readout.

**Comment by samreid** [comment]
The proposed fix is working well on my side, and probably also fixed latent bugs in other ways of disposing a circuit element (such as the delete key).  @arouinfar can you please verify?  Close if all is well.

**Comment by arouinfar** [comment]
@samreid I never observed the original bug, so I don't know exactly what I'm comparing against. However, the labels/readouts all appear well-behaved in master when disposed.
