### ISSUE TITLE
grab bag item resistance incorrect

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#563]
The paper clip, coin, and pencil resistances are incorrect in master.
![image](https://user-images.githubusercontent.com/8419308/72548946-f8bc9580-384c-11ea-92c4-07e31e6b2605.png)

Here are the correct values (latest)
![image](https://user-images.githubusercontent.com/8419308/72548993-1984eb00-384d-11ea-9297-334a5e12960c.png)

**Comment by samreid** [comment]
Good catch, please review.

**Comment by arouinfar** [comment]
All good in master
