### ISSUE TITLE
Publish a dev version of AC by Wednesday, January 22

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#565]
At this week's status meeting, it was requested to publish a dev version by the end of next week.  Aiming to have something ready by Wednesday evening sounds nice, so we can discuss it Thursday.

**Comment by samreid** [comment]
I asked if this version would require QA testing, and @kathy-phet said design team testing would be sufficient.

**Comment by samreid** [comment]
I published a dev version from our current status:
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.6/phet/circuit-construction-kit-ac_en_phet.html

@ariel-phet @arouinfar @kathy-phet can you please review and let me know if anything must be changed for this checkpoint?

**Comment by arouinfar** [comment]
@samreid that version is looking pretty good to me. It would be nice to address #536 if it's a quick change, though not critical.

**Comment by ariel-phet** [comment]
@samreid all is looking pretty good.

I think for this dev version I would comment out the "play area zoom buttons" - currently they overlap the schematic/realistic buttons in a way that looks broken. I know we are not really pixel polishing yet, but those zoom buttons are very noncritical if someone looks at the dev version, and I think it will look cleaner for this purpose, they can be put back in right after this dev version is published.

**Comment by ariel-phet** [comment]
No need for @kathy-phet to review for this checkpoint, assigning back to @samreid

**Comment by samreid** [comment]
I addressed the 2 issues raised above and published a version here:
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.9/phet/circuit-construction-kit-ac_en_phet.html

@ariel-phet and/or @arouinfar would you like to review?

**Comment by arouinfar** [comment]
@samreid dev.9 is looking good to me!

**Comment by samreid** [comment]
Assigning to @kathy-phet so she is aware of dev.9.

**Comment by samreid** [comment]
The prototype has been published for a while now, closing.
