### ISSUE TITLE
Reduce size of slider thumbs

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#566]
Noticed during #540 and not required for the dev version needed for #565.

The slider thumbs for the Wire Resistivity and Source/Battery Resistance are quite large. 
![image](https://user-images.githubusercontent.com/8419308/72943905-865c2180-3d34-11ea-9810-0ef8a1e6f8cd.png)

@samreid can you reduce the size by 30%? This would buy us a bit of extra vertical space. Currently, the Advanced panel is pretty close to the component editing panel.

**Comment by samreid** [comment]
Fixed in the above commit, and adjusted tick marks accordingly.  This applies to both DC and AC sims, but does not affect the controls for, say, battery voltage or other circuit controls.

@arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good @samreid, thanks!

I need to do a larger review for pixel polishing, and I plan to open an issue next week. I'll comment on the component edit controls there.
