### ISSUE TITLE
Edit panel pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#571]
Necessary to make room for the play/pause/step buttons in phetsims/circuit-construction-kit-ac#18.

- [x] Reduce slider track length to 130 px
- [x] Reduce slider thumb height to 20 px
- [x] Reduce the amount of space between the slider track and tweaker buttons (mockup has 15 px padding).
- [x] 25 px padding between UI elements
- [x] Center panel in the space between the carousel and right-side panels
- [x] Bottom-align panel with ResetAllButton

![image](https://user-images.githubusercontent.com/8419308/78292561-75721e00-74e4-11ea-9f29-5c387828f970.png)

**Comment by samreid** [comment]
It looks like the labels were lost in the transfer.

**Comment by samreid** [comment]
After my first pass, it is looking like this:

![image](https://user-images.githubusercontent.com/679486/78404374-83df3900-75bb-11ea-8127-8d4e696e47ee.png)

**Comment by samreid** [comment]
Is our prototype English-only?  It looks like this in stringTest=double:
![image](https://user-images.githubusercontent.com/679486/78404587-fc45fa00-75bb-11ea-9464-1212c80246c9.png)

**Comment by samreid** [comment]
@arouinfar can you take a look at the current version and let me know what you recommend?

**Comment by arouinfar** [comment]
@samreid these changes look good in master.

Th prototype is English only, but we'll want to apply appropriate maxWidths to the strings so the panel doesn't expand. Back to you @samreid.

**Comment by samreid** [comment]
I adjusted the sizes in the commit, ready for review.

**Comment by arouinfar** [comment]
Looks good in master @samreid!
