### ISSUE TITLE
Electrons aren't centered when wire is at an angle

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#575]
Electrons aren't centered when wire is at an angle

![image](https://user-images.githubusercontent.com/679486/78515978-2262ca00-7775-11ea-927e-2d3dbf120211.png)

**Comment by samreid** [comment]
I simplified this code a lot, and tested with capacitor clipping areas and transparency.  It seems more centered now, and I didn't see any problems, but @arouinfar could you please double check?

**Comment by arouinfar** [comment]
I haven't noticed any issues with the electron alignment in master @samreid.
