### ISSUE TITLE
User suggestion: resistor values, multiple voltmeters

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#576]
> I'm not sure how possible it would be, BUT I REALLY need to Simulate REAL world resistance values! Having values limited to 120 Ohms for one resistor and skipping by 100 ohms for the other resistor is almost useless.
> I need the REAL values the students would use in their labs.
> There is a list of typical values online, but they are typically 330, 470, 560, 820, 1000, 1200, 2200, 3300, etc...  
> A list is here: https://ecee.colorado.edu/~mcclurel/resistorsandcaps.pdf
>  
> This is for the DC only and AC&DC Circuit Construction Labs.
>  
> I sent another suggestion today that having multiple Voltage meters much like you have multiple Current meters would be a Good update!
>  
> I have been teaching Electricity /Electronics to Vocational students for 23 years and an Electronics Technology class at my Community College for 2 years.
> It has been difficult getting a simple, easy to use, graphic simulator for my Lab work during this nightmare of COVID19.
> But these few changes would allow my college class to perform 90% of their Labs!

**Comment by arouinfar** [comment]
> Having values limited to 120 Ohms for one resistor and skipping by 100 ohms for the other resistor is almost useless. I need the REAL values the students would use in their labs.
There is a list of typical values online, but they are typically 330, 470, 560, 820, 1000, 1200, 2200, 3300, etc...

At first, I thought the user's request would be addressed by directing them to use the tweaker buttons to edit the resistance. However, it seems that both the slider thumb and tweaker buttons also move in steps of 100 ohms! This makes the tweakers absolutely useless. Generally, they should increment the value in the smallest possible step size, but with a range of 9900 ohms, I think steps of 1 ohm is overkill. We could achieve this user's goals by changing the tweaker step size to 10 ohms.

We may also want to consider including the high resistance and high voltage components in CCK: AC, but perhaps just on the Lab screen. I'll move this to a separate issue for design team discussion.

> I sent another suggestion today that having multiple Voltage meters much like you have multiple Current meters would be a Good update!

I'm a bit behind on phethelp emails related to CCK, but I am fairly certain we have had other requests for multiple voltmeters. CCK: AC has 2 voltmeters and non-contact ammeters, so perhaps we should do the same in CCK: DC.  

@samreid if you have no objections, please make the following changes:
- [ ] For high-R bulbs and resistors, change the tweaker step size to 10 ohms.
- [ ] For high-V batteries, change the tweaker step size to 10 V.
- [ ] In CCK: DC, add a 2nd voltmeter and non-contact ammeter to the toolbox for both screens.

**Comment by samreid** [comment]
I updated the high resistance and high voltage controls, and noticed that we already added 2x voltmeters and ammeters in https://github.com/phetsims/circuit-construction-kit-common/issues/518.  I also noted that the deltas for regular resistors and batteries was incorrectly 1 instead of 0.5, so I corrected that. Ready for review.

**Comment by arouinfar** [comment]
Thanks @samreid. The tweaker increments look correct in master, but the thumb is no longer snapping as it used to.

I'd like to maintain the same constrainValue currently in the latest published version.
- [ ] High-V battery: 100 V
- [ ] High-R resistor/bulb: 100 ohms

**Comment by samreid** [comment]
I committed a proposed fix, @arouinfar can you please review?

**Comment by samreid** [comment]
We discussed this in today's meeting--the changes above are great.  We would like one more change, for the basic resistor and battery, the slider knob should round to whole numbers, not 0.5, which is the tweaker delta.

**Comment by samreid** [comment]
Committed as recommended, and fixed a bug that gave the wrong deltas for the high resistance light bulb.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master @samreid
