### ISSUE TITLE
User suggestion: add high-R and high-V components to CCK: AC

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#577]
From https://github.com/phetsims/circuit-construction-kit-common/issues/576.

> I'm not sure how possible it would be, BUT I REALLY need to Simulate REAL world resistance values! Having values limited to 120 Ohms for one resistor and skipping by 100 ohms for the other resistor is almost useless.
> I need the REAL values the students would use in their labs.
> There is a list of typical values online, but they are typically 330, 470, 560, 820, 1000, 1200, 2200, 3300, etc...  
> A list is here: https://ecee.colorado.edu/~mcclurel/resistorsandcaps.pdf
>  
> This is for the DC only and AC&DC Circuit Construction Labs.

The resistance values will be addressed in #576. However, only CCK: DC has high-R and high-V components. High-R bulbs and resistors were a new addition in HTML5, but all Java flavors of CCK include high-V batteries. In the spirit of flexibility, I think we should include the high-R and high-V components in CCK: AC, though perhaps only on the Lab screen (as was done in CCK: DC).

I have a few other phethelp emails in my inbox related to CCK, so I will double check those to see if there are any other requests for this feature.

**Comment by arouinfar** [comment]
I didn't find any other requests for this in my inbox, so unassigning myself.

**Comment by samreid** [comment]
@arouinfar is this issue ready for work?  Should I proceed with this step:

> In the spirit of flexibility, I think we should include the high-R and high-V components in CCK: AC, though perhaps only on the Lab screen (as was done in CCK: DC).

**Comment by arouinfar** [comment]
@samreid I would like to add these components to CCK:AC, but it's something we should run by the team. Let's discuss at the next design meeting.

**Comment by arouinfar** [comment]
Discussed in the 9/17/20 design meeting, and decided against making this change.

This could be a bit of a slippery slope. If we add high-V batteries, should we also add high-V AC sources? What about high-C or high-L components? 

The primary concern of the user was addressed by fixing the tweaker increments in https://github.com/phetsims/circuit-construction-kit-common/issues/576.
