### ISSUE TITLE
CCK AC does not behave correctly with battery RC circuit and discharging switch across capacitor.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#583]
MD: I built an RC circuit with a battery and a switch. The behavior is correct. See attached pic1, CorrectBehavior.  But when I add a switch across the capacitor, and close the switch the capacitor should discharge. It does not. See attache pic 2, NOT correct behavior.

He said he could use a fix for this in 3 weeks for classroom usage.

I did not receive screenshots with the email report.  Is this the main problem?

![image](https://user-images.githubusercontent.com/679486/84799762-fc01ac00-afb9-11ea-814e-b1e757ce85a3.png)

@arouinfar and @kathy-phet do you want me to investigate this in the near future?

**Comment by kathy-phet** [comment]
This is indeed high priority to fix. It's a very significant physics bug. Please go ahead and look into its cause.

**Comment by kathy-phet** [comment]
Here are the pictures from Mike D: 
![DCRCCrktCorrectBehavior](https://user-images.githubusercontent.com/5096804/84926123-27eb6300-b088-11ea-893a-707ec9089423.PNG)
![DCRCCrktNOTCorrectBehavior](https://user-images.githubusercontent.com/5096804/84926133-2ae65380-b088-11ea-9dc6-9281a825660a.PNG)

**Comment by samreid** [comment]
Observations during investigation:
1. The same problem can be triggered by adding a battery in series with a capacitor and plain wires (no resistance).
2. This problem can be seen in master and on the published prototoype.
3. The default wire resistivity is 1.68e-8 Ohms.  Turning this up to 0.0007641532709788131 eliminates the problem, but shows higher resistance than we want.
4. The default minimum timestep is 5E-15, in one test it looked like reducing that fixed the problem, but I can't reproduce that now.

**Comment by kathy-phet** [comment]
Can you find a dev version where this works? We did that tweaking around making sure the lightbulb did not light when things were shorted, and I'm wondering if that is causing this issue.

**Comment by samreid** [comment]
Dev.2 works OK
Dev.6 works OK
Dev.9 works OK
Dev.10 works OK
Dev.11 has the correct behavior but takes a long time to run (sometimes >10 seconds)
Dev.12 broken

**Comment by samreid** [comment]
Here's a patch that restores this behavior.  It is still to-be-determined whether all parts of the patch are necessary, and what problems they will re-introduce:

```diff
Index: js/model/TimestepSubdivisions.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/model/TimestepSubdivisions.js	(revision 42d9e6587abd23cbac4b07f7b7bc2227acee0aff)
+++ js/model/TimestepSubdivisions.js	(date 1592855805892)
@@ -13,10 +13,10 @@
 import ResultSet from './ResultSet.js';
 
 // threshold for determining whether 2 states are similar enough; any error less than errorThreshold will be tolerated.
-const MIN_DT = 1E-13 / 20;
+const MIN_DT = 1E-5;
 
 //threshold for determining whether 2 states are similar enough; any error less than errorThreshold will be tolerated.
-const ERROR_THRESHOLD = 1E-5;
+const ERROR_THRESHOLD = 1E-8;
 
 class TimestepSubdivisions {
 
@@ -60,7 +60,8 @@
    */
   getTimestep( state, steppable, dt ) {
     if ( dt < MIN_DT ) {
-      throw new Error( 'nonlinear' );
+      return MIN_DT;
+      // throw new Error( 'nonlinear' );
     }
     else if ( this.errorAcceptable( state, steppable, dt ) ) {
       return dt;
```

**Comment by samreid** [comment]
I don't recall the reasoning behind skipping the nonlinear steps, but applying the patch above together with other fixes from https://github.com/phetsims/circuit-construction-kit-common/issues/572 still seems reasonable, but we probably need a way to have a smaller DT when the sim is paused so it doesn't accumulate time too fast.

**Comment by kathy-phet** [comment]
Sam - Can you comment on things that might break because of this patch? So @ariel-phet and @arouinfar can keep an eye out for behavior?

**Comment by samreid** [comment]
The main changes in the commits are:

* Increase MIN_DT back to 1E-5.  In https://github.com/phetsims/circuit-construction-kit-common/issues/572 I believed it needed to be lower than the paused timestep, but I discovered that's not true.  There is pre-existing logic that takes min of (MIN_TIMESTEP and the requested dt).  With this value too low (like 1E-15) it was taking 10-20 seconds to run one model update
* Still run the physics even if a nonlinearity is detected.  This seems to be critical for updating circuits with no resistance.  I'm not sure why that was introduced for https://github.com/phetsims/circuit-construction-kit-common/issues/572, but perhaps we can discover that as part of testing.

@arouinfar can you please test the behavior for this issue and https://github.com/phetsims/circuit-construction-kit-common/issues/572#issuecomment-608708226 using phettest master?

**Comment by arouinfar** [comment]
@samreid master seems to be okay. I've confirmed that the buggy paused behaviors described in https://github.com/phetsims/circuit-construction-kit-common/issues/572#issuecomment-608708226 are not present in master, and the capacitor is looking ok. I tested several cases, but I think it'd be good if @ariel-phet can also do some sanity testing.

**Comment by ariel-phet** [comment]
@samreid I checked fairly thoroughly for the capacitor cases, and then look carefully at RLC circuits and everything seems to check out so far. No obvious issues. 

Feel free to go ahead and publish a new dev version for the website

**Comment by samreid** [comment]
Thanks for testing, I'll close this and open a new issue about publishing a new prototype.
