### ISSUE TITLE
User request: unknown resistors

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#585]
> Is there a way to program or add specific resistor with know value (unknown value to the student)  in the sim Circuit Construction Kit (AC+DC), Virtual Lab?
> 
> Im looking to build a test with the sim in wich the students would have to use Ohm's law to find the value of different resistors (U=RI). I would need 5 specific resistors that would be hidden from the students.

**Comment by oliver-phet** [comment]
Another comment from the user:

> It would only need the be copy paste of the resistors already in the sim, but with the value set and hidden to the view. Just like the pencil already in there that had a R=25 Ohms.

**Comment by ariel-phet** [comment]
I believe this same user also wrote directly to @samreid 



> I have a specific test that I would like to implement for my students using a Phet simulation. But after watching the tutorial you made on youtube for coding PhET, I was overwhelmed by the time it would take to learn how to code a few simple changes I would need. So I am contacting you directly to see if you or someone would be able to help me with my request.
> 
>  
> 
> I would need to add 5 specific ``mystery'' resistors with known values (unknow to the student)  in the sim Circuit Construction Kit (AC+DC), Virtual Lab.
> 
>  
> 
> Im looking to build a test with the sim in wich the students would have to use Ohm's law to find the value of the different resistors (U=RI).
> 
> I was thinking that copy and pasting 5 times the resistor component would not take that long (for a coder already working with Git/Phet coding). The resistors would simply need to be tagged with a number (R1, R2, R3, R4,R5) for the student to identify them. The other component needed would be to disable the slider scale to adjust the resistance value and to make it a fixed hidden value. Exactly like the double ended pencil already in the sim that has an unmarked value of 25 Ohm for its resistance.
> 
>  
> 
> Let me know if that would be possible to add in the sim or the person I should contact for my projet.
> 
> I already contacted the general Phet Help adress and they transfered my request to the team. So sorry if this request get to you two times.
> 
>  
> 
> Thanks for your help!
>

**Comment by ariel-phet** [comment]
@samreid could you comment here on what the "lowest cost" way to implement mystery resistors would be?

I would think something like a query parameter that just takes numerical arguments, something like:

`?mysteryResitors=15,10,3`

I would think a "mystery resistor" would have to have no identification bands, but I assume those bands are "drawn in code" so they could just be removed. We would also need to find a place for these to go, perhaps on a new carousel screen page? And then just label them sequentially "Mystery 1" "Mystery 2" etc.

I suppose ideally to support the request above the mystery resistors would need some kind of label on them, when in the play area.

I am guessing this is all a fair bit of work even if we did something pretty "bare bones" -- but it does align with some eventual goals of having mystery/black box features to CCK.

Please give a rough estimate of what you think such a feature would cost, but no need to do any work on it.

**Comment by arouinfar** [comment]
I really like the idea of allowing for customizable mystery resistors, and I think a lot of teachers would love them.

> I would think something like a query parameter that just takes numerical arguments, something like:
`?mysteryResitors=15,10,3`

This sounds like a good approach to me.

> We would also need to find a place for these to go, perhaps on a new carousel screen page?

The best place would probably be at the end of the carousel on each screen. Not all carousels have a completely full final page, so some of the mystery resistors may share space with standard components.

> I suppose ideally to support the request above the mystery resistors would need some kind of label on them, when in the play area.

We could use the plain [resistor asset](https://github.com/phetsims/circuit-construction-kit-common/blob/master/images/resistor.png), and then superimpose a label like `Rn`, where the subscript `n` would denote the nth mystery resistor. We should probably allow the `R` to be localizable.

We'll also need some other parameters like the number of mystery resistors to allow (5-6 seems like plenty to me), and the acceptable range (maybe 1-10000 ohms?). A few other thoughts:
* Selecting a mystery resistor will bring up the trash button, similar to the grab bag items.
* Turning on Values will display `? Ω`.

**Comment by samreid** [comment]
Sketching out different aspects of the work for this:

* New query parameter support (0.5 hours)
* Encrypting the query parameters so students can't just look at the URL to see the answers (2-4 hours?)
* Pagination for new elements in the carousel (1 hour).  Do we want a wire at the top of each new page?  That would be (2-3 hours.)
* New `circuitElementToolFactory` Node (2 hours)
* New view node or different options for ResistorNode, including i18n (3 hours)
* Turning on "Values" displays "? Ω" (1-2 hours)

Adding up the values above is an estimate of around 10-15 hours for a rough draft, before we start pixel polishing and testing.

Other questions:
* Will we eventually want to add this feature for batteries, light bulbs, capacitors, etc?
* Is this for "DC", "AC", "DC Virtual Lab" etc?  Would it behave different in Virtual Lab?

**Comment by samreid** [comment]
In https://github.com/phetsims/circuit-construction-kit-common/issues/597#issue-697216958 it was requested that we publish this sim by January and there is plenty to do before then.  Should this issue be prioritized for that release?

**Comment by arouinfar** [comment]
Given the timeline, this may be hard to squeeze into the initial release. 

I'll request time for CCK: AC in next Thursday's design meeting so we can check in on this (and other issues) with the team.

**Comment by arouinfar** [comment]
Discussed at the 9/17/20 design meeting

This will not be in the initial release of CCK: AC.

This is a feature that seems more appropriate for CCK: Black Box, a Mystery screen, or an app. 

For a mystery screen, we could have set mystery R1, R2, R3, and then R4 could be randomly generated. Another alternative could be a query parameter like `?mysterySet=1` etc, where the values are defined in the Teacher Tips.

**Comment by arouinfar** [comment]
We've received another request for this feature on phethelp:

> The bulb's default resistance and the resistor's default resistance are the same.  In the spirit of constructivism, is it possible to either a) make each component default to a different resistance, and/or b) make a non-changeable 'mystery' resistance for a bulb and a resistor, so that students can figure it out on their own?

**Comment by samreid** [comment]
This feature will be possible in the 1st PhET-iO release.  @arouinfar do we additionally need a phet-brand solution for this?

**Comment by arouinfar** [comment]
@samreid there is no need for a true phet-brand solution for this. The path forward here (and for other features like save/load) is to create some sort of PhET-iO lite product created for teachers.

**Comment by samreid** [comment]
Based on @arouinfar's remark, it seems we should close this issue.
