### ISSUE TITLE
Publish a new prototype version with the capacitor fixes from #583

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#586]
From https://github.com/phetsims/circuit-construction-kit-common/issues/583, we would like to publish a new version of the prototype on the website.  I'm marking as high priority since MD is hoping to use this in the classroom in the near future.

@mattpen can you comment on the process for uploading a new prototype?

@ariel-phet there are two ways to proceed for building the fixed version:
(a) We can publish a new dev version and run it through QA testing.  This would require QA time, and would test many changes that have accrued in master, and likely discover several new bugs that would need to be addressed before publication.
(b) I can build a new dev version that has all the same code as the published prototype, with the addition of the 3 commits from https://github.com/phetsims/circuit-construction-kit-common/issues/583.  We do not have a process for this since it is not an actual RC, but I can manually take the SHAs from the prototype and create a branch then apply the deltas into the patch.  This would probably take up to 2 hours to get it built, but then would only require spot testing instead of thorough testing.

@ariel-phet how do you recommend to proceed?

**Comment by mattpen** [comment]
Is this for CCK-AC? If so, to update the prototype, simply replace this file with the new version:

```
phet-server:/data/web/static/phetsims/sims/html/circuit-construction-kit-ac/latest/circuit-construction-kit-ac_en.html
```

**Comment by ariel-phet** [comment]
@samreid lets go with option (b) for the moment, QA won't be able to do a thorough test for awhile

**Comment by samreid** [comment]
@kathy-phet asked me to run the fixed version past MD, I'll try to build a dev version following strategy (b) to share with him.

**Comment by samreid** [comment]
The prototype version is 1.0.0-dev.12, the dependencies.json is https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.12/phet/dependencies.json.

**Comment by samreid** [comment]
I pushed a one-off version here: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-prototype.1/phet/circuit-construction-kit-ac_en_phet.html

**Comment by samreid** [comment]
MD reported: 

> Issue with capacitor not discharged is resolved. All working as expected now, thanks!!! 
I notice that my PC fan comes on when I run this sim. Sim seems to need a lot or CPU time and memory to run -- about 50% CPU according to task manager.  What is especially puzzling is that the CPU usage does not decrease significantly when I pause the sim.

I will open a new issue for that new problem.

Before posting this new version to the website, can @arouinfar or @ariel-phet spot check this built version (link is in the previous comment)?  Even a few minutes testing should be sufficient, with at least part of the test looking at time dependent behavior with and without capacitors.  If it tests out OK, you can assign @mattpen and give him the go-ahead to overwrite the prototype on the PhET homepage.

**Comment by arouinfar** [comment]
@samreid the one-off looks fine to me, and I made sure to test the play/pause and capacitor behavior.

**Comment by samreid** [comment]
Thanks @arouinfar.  @mattpen can you please promote the one-off version https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-prototype.1/phet/circuit-construction-kit-ac_en_phet.html to be the new prototype accessible from the website?

**Comment by mattpen** [comment]
https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/latest/circuit-construction-kit-ac_en.html has been updated to 1.0.0-prototype.1

**Comment by samreid** [comment]
Thanks @mattpen, I'll notify @kathy-phet and MD.  Closing.
