### ISSUE TITLE
IO types should serialize by using NullableIOReferenceIO

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-common#591]
While working on https://github.com/phetsims/phet-io/issues/1685, I am finding myself converting a lot of fromStateObject methods into the stateToArgsForConstructor that look like this:

```js
  /**
   * @param {Object} stateObject
   * @returns {Object}
   * @public
   */
  static fromStateObject( stateObject ) {
    if ( stateObject.circuitElementID === null ) {
      return { circuitElement: null };
    }
    if ( phet.phetio.phetioEngine.hasPhetioObject( stateObject.circuitElementID ) ) {
      return { circuitElement: phet.phetio.phetioEngine.getPhetioObject( stateObject.circuitElementID ) };
    }
    else {
      throw new CouldNotYetDeserializeError();
    }
  }

```

This feels like a great place to try out:

`NullableIO(ReferenceIO( ObjectIO ) ).fromStateObject( stateObject.circuitElementIO )`

Maybe a specific IO type instead of `ObjectIO`?

Try it out and see how it goes! If it doesn't work, then we should work on ReferenceIO to support this, instead of all this duplication with a pattern already in place in ReferenceIO.

**Comment by samreid** [comment]
I investigated this and couldn't find where this code is being run, and I wasn't certain that it should be run.  I'll raise for discussion on Wednesday meeting.

**Comment by samreid** [comment]
Point taken and I'll use ReferenceIO in the future where appropriate.  For this issue, it was better to make those buttons static, so I removed the corresponding IO Types. Closing.
