### ISSUE TITLE
User suggestion: design of 'connections'

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#592]
> The only other suggestion I would have for circuits, is how the 'connections' are shown in the simulations.
> 
> At the moment, a simple circuit in the Phet virtual lab looks like this:
> ![image-2](https://user-images.githubusercontent.com/5090275/88862674-1e443780-d1be-11ea-93fc-15f62149a27e.png)
> 
> Our students would be expected to draw this circuit like this:
> ![image-3](https://user-images.githubusercontent.com/5090275/88862677-22705500-d1be-11ea-9971-43d4c242db00.png)
> 
> Other than the different symbols for the lamps/bulbs, in your simulation the 'connections' are very prominent. I understand that this helps with manipulating the circuit, but maybe minimising the grey circles would help make it clearer to students? Just a thought.

**Comment by samreid** [comment]
@arouinfar what do you recommend for this issue?

**Comment by arouinfar** [comment]
I don't think we should remove the vertices in schematic mode. They are important for circuit manipulation, especially on touch. I would also push back on the suggestion that students have trouble with interpreting the schematic circuit with prominent vertices, as this is the first request we've had of this nature.

While we could try removing or reducing the size of the gray circle (while keeping the dashed circle intact), I don't think it's the best use of @samreid's time.
