### ISSUE TITLE
Use only one decimal place in StopwatchNode display

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#595]
In https://github.com/phetsims/scenery-phet/issues/565 StopwatchNode gained the option of having only 1 decimal place in the readout. Since the StepForwardButton increment is 0.1s, the StopwatchNode doesn't need more than 1 decimal place.

@samreid please update the StopwatchNode display to have only one decimal place.

**Comment by arouinfar** [comment]
See https://github.com/phetsims/scenery-phet/issues/617 for further discussion of StopwatchNode precision.

**Comment by samreid** [comment]
Implemented in the commit and ready for review.

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid.
