### ISSUE TITLE
Assertion failed: countProperty should match array length.

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-common#596]
This CT error was partially recorded in https://github.com/phetsims/circuit-construction-kit-common/issues/594, but is its own problem.

@samreid and I dove into a state wrapper issue regarding the countProperty of trashButtonGroup. The primary issues we looking into is that trash buttons were not being set to state again. This primarily is because they are view dynamic elements, but aren't following either of the two patterns that I would expect to see to support dynamic elements.

1. Treat these elements as tradition dynamic elements, in which they are stateful, support create/dispose, and the downstream sim is set up to have these elements swapped out on state set when they are disposed. We briefly looked into this patter by extending the trash button PhetioGroup's method: `createNextElement` by grabbing it from the list in the PhetioGroup if it already existed before creating it. This is not a pattern we normally use for the view because of MVC. All of the UI in the edit panel is tied to a single model element (like `resistor_0`). and so we move on to. . . .
2. My preferred recommendation is to use the "upside-down U/trident/'only the models are stateful'" pattern (see https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-guide.md#model-vs-view-dynamic-elements). In this pattern view dynamic elements listen to when model elements are created, and create themselves in response. This is likely how the actual `resistorNode_0` should be set up (to listen to the `CircuitElement`), but also for this secondary dynamic view component I will call the `UIEditPanel`. See https://github.com/phetsims/charges-and-fields/blob/b9e57b474268dc84151b341a356d949469b8896e/js/charges-and-fields/view/ChargesAndFieldsScreenView.js#L257-L270 for the example in CAF. Here I recommend a similar solution that we also create the `UIEditPanel`  there too.

Currently the creation of the `UIEditPanel` is coming from a Property listener. This is one reason why there are many issues when restoring state. Elements are created when the state is set by the `PhetioGroup`, and they are created again when that listener fires. In general this countProperty assertion is this class of problem.

A couple more thoughts we touched on:
* There may be a fair amount of refactoring in `CircuitElementEditContainerNode` to make sure that the UIEditPanel for each dynamic element is created in response to the model creation.
* There is an assumption with dynamic elements that if they are stateful, then they need to be created by the end of the state engine setState call so that all stateful elements can be set. For example, if the visibleProperty of a UI Node has customization applied to it for resistor_0, then it needs to be created when the resistor_0 gets created so that in the next iteration of state set the visibleProperty can be set. This doesn't mean that all UIEditPanels need to be created eagerly, but rather that CircuitElement.js instances need to know whether or not they should create a UIEditPanel. That should be part of CircuitElementIO's state. 
* Everything up until this point has been discussion based on what is ideal. I know that there are priorities and dealines that are keeping all of CCK from being instrumented at this time. It isn't totally clear that the above is the best solution given the set of requirements in https://github.com/phetsims/circuit-construction-kit-common/issues/589. That said I don't want to recommend spending time uninstrumenting a simulation, as that feels like a step in the wrong direction. I would really push for making sure that base instrumentation includes state support for the model elements and their cooresponding view components. I would also be happy to assist in this. 

Good luck!!

**Comment by zepumph** [comment]
Here is a patch that shows our investigation of (1). You also need to make TrashButton.js phetioState:true for this:

<details>

```diff

Index: js/view/CircuitElementEditContainerNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/view/CircuitElementEditContainerNode.js	(revision ea029d351cc3e0dd6e2260747f4cd570e5894dbd)
+++ js/view/CircuitElementEditContainerNode.js	(date 1598648099918)
@@ -87,8 +87,12 @@
     }, options );
     const groupTandem = tandem.createGroupTandem( 'circuitElementEditNode' );
 
-    const trashButtonGroup = new PhetioGroup(
-      ( tandem, circuitElement ) => new TrashButton( circuit, circuitElement, tandem ),
+    const trashButtonGroup = new TrashButtonPhetioGroup(
+      ( tandem, circuitElement ) => {
+        const trashButton = new TrashButton( circuit, circuitElement, tandem );
+        circuitElement.disposeEmitterCircuitElement.addListener( () => trashButtonGroup.disposeElement( trashButton ) );
+        return trashButton;
+      },
       [ null ], {
         phetioType: PhetioGroupIO( TrashButtonIO ),
         tandem: tandem.createTandem( 'trashButtonGroup' )
@@ -176,14 +180,14 @@
           );
           editNode = new EditPanel( [
               resistanceControl,
-              trashButtonGroup.createNextElement( selectedCircuitElement )
+              trashButtonGroup.getOrCreateNextElement( selectedCircuitElement )
             ]
           );
         }
         else if ( isResistive ) {
 
           // Just show a trash button for non-editable resistors which are household items
-          editNode = trashButtonGroup.createNextElement( selectedCircuitElement );
+          editNode = trashButtonGroup.getOrCreateNextElement( selectedCircuitElement );
         }
         else if ( isBattery ) {
           const circuitElementEditNode = new CircuitElementNumberControl(
@@ -209,7 +213,7 @@
               // Batteries can be reversed
               reverseBatteryButtonGroup.createNextElement( selectedCircuitElement ),
               circuitElementEditNode,
-              trashButtonGroup.createNextElement( selectedCircuitElement )
+              trashButtonGroup.getOrCreateNextElement( selectedCircuitElement )
             ]
           );
         }
@@ -231,7 +235,7 @@
           editNode = new EditPanel( [
               resetFuseButtonGroup.createNextElement( selectedCircuitElement ),
               fuseCurrentRatingControl,
-              trashButtonGroup.createNextElement( selectedCircuitElement )
+              trashButtonGroup.getOrCreateNextElement( selectedCircuitElement )
             ]
           );
         }
@@ -241,7 +245,7 @@
         else if ( isSeriesAmmeter || isWire ) {
 
           // Just show a trash button
-          editNode = trashButtonGroup.createNextElement( selectedCircuitElement );
+          editNode = trashButtonGroup.getOrCreateNextElement( selectedCircuitElement );
         }
         else if ( isACSource ) {
           const children = [
@@ -278,7 +282,7 @@
               tandem: groupTandem.createNextTandem()
             } ) );
           }
-          children.push( trashButtonGroup.createNextElement( selectedCircuitElement ) );
+          children.push( trashButtonGroup.getOrCreateNextElement( selectedCircuitElement ) );
           editNode = new EditPanel( children );
         }
         else if ( isCapacitor ) {
@@ -300,7 +304,7 @@
           editNode = new EditPanel( [
             clearDynamicsButtonGroup.createNextElement( selectedCircuitElement ),
             capacitorEditControl,
-            trashButtonGroup.createNextElement( selectedCircuitElement )
+            trashButtonGroup.getOrCreateNextElement( selectedCircuitElement )
           ] );
         }
         else if ( isInductor ) {
@@ -320,7 +324,7 @@
           editNode = new EditPanel( [
               clearDynamicsButtonGroup.createNextElement( selectedCircuitElement ),
               inductanceControl,
-              trashButtonGroup.createNextElement( selectedCircuitElement )
+              trashButtonGroup.getOrCreateNextElement( selectedCircuitElement )
             ]
           );
         }
@@ -378,5 +382,24 @@
   }
 }
 
+class TrashButtonPhetioGroup extends PhetioGroup {
+
+  /**
+   * @public
+   * @param {CircuitElement} circuitElement
+   * @returns {PhetioObject|*}
+   */
+  getOrCreateNextElement( circuitElement ) {
+    for ( let i = 0; i < this._array.length; i++ ) {
+      const arrayElement = this._array[ i ];
+      if ( arrayElement.circuitElement === circuitElement ) {
+        return arrayElement;
+      }
+    }
+    return this.createNextElement( circuitElement );
+  }
+}
+
+
 circuitConstructionKitCommon.register( 'CircuitElementEditContainerNode', CircuitElementEditContainerNode );
 export default CircuitElementEditContainerNode;

```

**Comment by zepumph** [comment]
I think this is worth the time to investigate. I would hate to turn state testing off for a partial instrumentation where stateful customizations are delivered to a client.  The requirements for https://github.com/phetsims/circuit-construction-kit-common/issues/589 are very simple and I would hate to hold up that priority. My preference would be to do this right in a complete way. That said, we should keep in the back of our minds that we can uninstrument the entire view for circuit elements similarly to how you opted for putting Tandem.OPTIONAL [here](https://github.com/phetsims/circuit-construction-kit-common/blob/58d7ded0a3bfe7eaeac35a1539bbe48636586a1c/js/view/CircuitLayerNode.js#L262)

**Comment by samreid** [comment]
Thanks for the discussion and the clear direction, I'm confident that I could proceed as prescribed.  However, after reflection, I think the core implementation and PhET-iO interface will be simpler if the trash button is a singleton rather that a group.  For instance, instead of trashButton_37 being able to delete a particular circuit element, it seems simpler that there is only one `trashButton` and it deletes the selected circuit element.  This is also in line with (2) in the phet-io instrumentation guide:

> 2. Can it be created eagerly? Allocating dynamic elements on startup simplifies the instrumentation process, especially when supporting PhET-iO state and API validation.

The same applies to the reset fuse button, reverse battery button, etc.  I'd like to investigate this first.

**Comment by samreid** [comment]
This strategy seems like it is working well, closing.

**Comment by zepumph** [comment]
Just noting here that I'm not totally convinced this will work in all cases though. For example the battery voltage number control. It cannot be a singleton, and will need to be created after there is a voltageProperty in the model for the circuit element. Likely the easiest thing to do for now is to make those components `phetioState:false` unless it is really challenging.
