### ISSUE TITLE
CCK: AC needs homescreen + navbar icons

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#599]
CCK: AC needs homescreen + navbar icons

It currently looks like this:

![image](https://user-images.githubusercontent.com/679486/92975973-b46aaf00-f446-11ea-8bff-d6fb4dc44df4.png)

**Comment by arouinfar** [comment]
@samreid let's try these icons:
![image](https://user-images.githubusercontent.com/8419308/93823611-53e62980-fc1f-11ea-8728-40c2c63466d0.png)

Please let me know if you would prefer to draw these in code or would like assets. I'll need to clean up the mockups a bit more to make them asset-quality.

**Comment by samreid** [comment]
Drawing all 3 of those in code would take half a day or more, and would lead to increased code complexity that would need to be maintained.  Providing them as assets gives us the leeway to adjust them independently of the artwork in the sim.  But if we always want them to exactly match what is in the sim, rendering them with code is a way to do that without having to make adjustments in both.  I'm inclined to recommend they would be provided as assets, but I think we should discuss before deciding.

**Comment by samreid** [comment]
By the way, I think they look great, but maybe not all of the details (such as dotted lines) are necessary on the latter two.

**Comment by arouinfar** [comment]
I cleaned up the icons, and have attached the assets. Ready for you @samreid.

[cck-ac-screen-icons.zip](https://github.com/phetsims/circuit-construction-kit-common/files/5303094/cck-ac-screen-icons.zip)
![image](https://user-images.githubusercontent.com/8419308/94642479-71f7fd80-02a1-11eb-86d5-4c9b0bdcde16.png)

**Comment by samreid** [comment]
I added the screen icons. They look great, my only recommendation is maybe to increase the thickness of the light bulb brightness lines if we would like them to appear better in the navigation bar.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/679486/95546523-1246d400-09be-11eb-8e25-55f422828416.png)

**Comment by arouinfar** [comment]
Thanks @samreid. The icons generally look good in master, and I agree the light rays could be a bit thicker. Here are the updated assets: 
[revised-screen-icons.zip](https://github.com/phetsims/circuit-construction-kit-common/files/5419911/revised-screen-icons.zip)

**Comment by samreid** [comment]
Thanks, I committed the new icon.  Back to @arouinfar for review, close if all is well.

**Comment by arouinfar** [comment]
👍
