### ISSUE TITLE
When zooming out, one tick label is not shown.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#600]
From https://github.com/phetsims/circuit-construction-kit-common/issues/536 When zooming out, one tick label is not seen

![image](https://user-images.githubusercontent.com/679486/93104941-b2ce0080-f66b-11ea-95f1-90779548b104.png)

**Comment by samreid** [comment]
The problem is in `getLinePositionsInGrid`.  If I add this slack of 1E-6, then it works out OK, but that doesn't seem like a very good solution (what if we are plotting things on that scale).  Here's a patch with the slack.  @jessegreenberg can you please review and advise?

```diff
Index: js/GridNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/GridNode.js	(revision c69ff50943e1ebb206c0a39db3d308362e36cc86)
+++ js/GridNode.js	(date 1600098331283)
@@ -312,7 +312,7 @@
 
     // the model-view transform may have flipped relative bottom and top with an inverse vertical transformation,
     // make sure we start the array with lower values
-    for ( let y = Math.min( modelMin, modelMax ) + distanceToGridLine; y <= Math.min( modelMin, modelMax ) + modelSpan; y += spacing ) {
+    for ( let y = Math.min( modelMin, modelMax ) + distanceToGridLine; y <= Math.min( modelMin, modelMax ) + modelSpan+1E-6; y += spacing ) {
       positions.push( y );
     }
 
```

**Comment by jessegreenberg** [comment]
A fix for this was made in the above commits, @samreid can you please review? I added an option to set the precision when necessary so this doesn't happen. I couldn't think of a good general way to fix this that didn't require specifying the desired precision at some point.

**Comment by samreid** [comment]
Would it work to iterate from `min` to `max + spacing/2`?

```js
    for ( let y = Math.min( modelMin, modelMax ) + distanceToGridLine; y <= Math.min( modelMin, modelMax ) + modelSpan+1E-6 + spacing/2; y += spacing ) {
       positions.push( y );
     }
```

In this way, the spacing will automatically compensate for the precision and we won't need an extra degree of freedom.

**Comment by jessegreenberg** [comment]
I think that would result in too many lines, we want to keep all lines within modelMin + modelSpan. Say `modelSpan` is 10, `spacing` is 6, we will have lines at [ 0, 6, 12 ] and we shouldn't have any greater than 10.

**Comment by samreid** [comment]
@jonathanolson do you have time to review this issue and recommend how to proceed?

**Comment by samreid** [comment]
Or what about taking a fixed ratio of the range?

```js
  const min = 0;
  const max = 9.999999999;
  const range = max - min;
  const spacing = 5;
  for ( let i = min; i <= max + range * 1E-6; i += spacing ) {
    console.log( i );
  }
```

**Comment by samreid** [comment]
What about computing the number of grid lines to show, and rounding to the nearest whole number if it is very close to a whole number?  This seems reasonable and eliminates the extraneous degree of freedom, but I can't get it working, perhaps because I don't understand `distanceToGridLine`:

```js
    const numberOfPositions = Math.abs( modelSpan ) / spacing;
    const rounded = Utils.roundSymmetric( numberOfPositions );
    const numberOfPositionsInGrid = Math.abs( numberOfPositions - rounded ) < 1E-6 ? rounded : Math.floor( numberOfPositions );

    for ( let i = 0; i <= numberOfPositionsInGrid; i++ ) {
      positions.push( minPosition + i * spacing );
    }
```

**Comment by jonathanolson** [comment]
Where is the comparison that is causing things not to display? Usually adjusting comparisons is a good approach.

**Comment by jonathanolson** [comment]
Or:
```js
const epsilon = Math.abs( modelMax - modelMin ) * 1e-7
for ( let y = Math.min( modelMin, modelMax ) + distanceToGridLine; y <= Math.min( modelMin, modelMax ) + modelSpan + epsilon; y += spacing ) {
```

**Comment by samreid** [comment]
Thanks @jonathanolson, I appreciate it.  Based on the recommendation from @jonathanolson I committed a change that automatically handles the round-off error for the tick labels.  This allowed me to remove the API for `gridLinePrecision`.  I added another step to address @jessegreenberg's comment in https://github.com/phetsims/circuit-construction-kit-common/issues/600#issuecomment-693006722, to make sure nothing goes out of range.  This is working properly in Circuit Construction Kit AC.  @jessegreenberg can you please review?

**Comment by jessegreenberg** [comment]
I see, that is very cool - nice work! I tested GridNode in its other usages and the grid is being drawn correctly in all places I reviewed.

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
