### ISSUE TITLE
Chart labels are recreated every frame

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#601]
From https://github.com/phetsims/circuit-construction-kit-common/issues/536, labels are continually redrawn as the chart scrolls, this is probably a performance problem.  Note: the chart scrolls horizontally but recreates the vertical labels each frame since it doesn't distinguish between the dimensions.

**Comment by samreid** [comment]
@jessegreenberg can I put this on your radar as something I may need help with?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/griddle/commit/b10edda2375bad17ecef739e02ede4e22e22fd44 should be an improvement for this by only redrawing horizontal/vertical labels when necessary. @samreid can you please review?

**Comment by samreid** [comment]
This is looking much better, thanks!  In testing in CCK-AC, I noticed that it is no longer creating the labels every frame.  However, I noticed that even though it only have 5 labels, it creates them twice.  You can test this by adding this line where the vertical label text is created:

```js
console.log('create vertical label')
```

Then when you zoom in or out in CCK AC Voltmeter, instead of creating 5 new labels, it creates 10 each time.  This is likely in the noise and would not block publication, but I thought I should mention it.  Should we open a side issue for that?

**Comment by samreid** [comment]
I decided to open a griddle issue for that last point, and will close this one, thanks @jessegreenberg!
