### ISSUE TITLE
Profile and improve performance regarding PDOMPeer.js

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#605]
In https://github.com/phetsims/circuit-construction-kit-common/issues/572 @kathy-phet pointed out the sim can use a lot of CPU.  Let's profile it and see if there is room for improvement.

**Comment by samreid** [comment]
Dragging around a single wire shows most of the time is spent in PDOMPeer.js

![image](https://user-images.githubusercontent.com/679486/95540705-ba54a100-09ae-11eb-8ade-62dba3063960.png)

@jessegreenberg can you please recommend someone to investigate?

**Comment by jessegreenberg** [comment]
I see, Ill take a look - @samreid can you comment on the priority of this issue? Does this need to be resolved quickly for upcoming deadlines or publications?

**Comment by jessegreenberg** [comment]
Also,
> the sim can use a lot of CPU

How was this measured? Was there a noticeable drop in performance, or was it noticed that the browser's CPU usage was abnormally high?

**Comment by samreid** [comment]
> I see, Ill take a look - @samreid can you comment on the priority of this issue? Does this need to be resolved quickly for upcoming deadlines or publications?

We would like to create an RC branch at the end of November.

> How was [CPU] measured? Was there a noticeable drop in performance, or was it noticed that the browser's CPU usage was abnormally high?

@kathy-phet mentioned that CCK tends to use a high amount of CPU compared to other sims.  I think this means her fan turns on sooner?

The profile above was created when just dragging a single element, this is not under a demanding load and I wouldn't expect that to use a lot of CPU--I was just trying to identify where time was being spent in the profiler.  It seemed like 8+6+5+5 = 24% time triggered by PDOMPeer was noteworthy.

**Comment by jessegreenberg** [comment]
OK thanks - In https://github.com/phetsims/scenery/issues/1088 I am proposing a way to opt out of this when we don't need it. By passing `positionSiblings: false` to VertexNode and CircuitElementNode options, I am no longer seeing time spent in these functions.
![image](https://user-images.githubusercontent.com/6396244/95798374-d19dd200-0cbf-11eb-8ccb-3de77ed4d4e4.png)


But I think there is probably a better way that doesn't require options in the sim, we are going to discuss that next in https://github.com/phetsims/scenery/issues/1088

**Comment by samreid** [comment]
I made other performance improvements in https://github.com/phetsims/circuit-construction-kit-common/issues/640, and will hence focus this issue on PDOMPeer.js

**Comment by samreid** [comment]
@jessegreenberg can you please report on the status of this issue, and how it pertains to the upcoming publication of Circuit Construction Kit?

**Comment by samreid** [comment]
@jessegreenberg does this block publication of CCK AC?

**Comment by jessegreenberg** [comment]
After changes in https://github.com/phetsims/scenery/issues/1088 and https://github.com/phetsims/scenery/issues/1094, there shouldn't be a performance loss related PDOMPeers. Let me make sure I can reproduce the screenshot in https://github.com/phetsims/circuit-construction-kit-common/issues/605#issuecomment-707393305 on master (not seeing any time in PDOMPeer positioning), then I think this can be closed.

**Comment by jessegreenberg** [comment]
Confirmed, a built version with --minify.mangle=false and dragging around a resistor, I don't see time in PDOMPeer.
![image](https://user-images.githubusercontent.com/6396244/105383236-e521d880-5bde-11eb-88cd-562ff2a5c08e.png)


@samreid I think this can be closed, back to you.

**Comment by samreid** [comment]
Excellent, thanks @jessegreenberg, closing.
