### ISSUE TITLE
Should the ammeters show negative values?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#606]
In https://github.com/phetsims/circuit-construction-kit-common/issues/10, @Nibbos said:

> Hi, Sam.
Just a quick fix wanted in the Circuit Builder, please.
Can we have the ammeter also giving negative current readings, to show the
directional nature of current - just as you have done with the voltmeter
readings, please?
Many thanks.
Conor

See also https://github.com/phetsims/circuit-construction-kit-common/issues/508 for a discussion of current direction, which came up for the current chart.

**Comment by samreid** [comment]
From https://github.com/phetsims/circuit-construction-kit-common/issues/508#issuecomment-707267680

> Hi. Working with d.c. circuits and determining V-I characteristics for ohmic resistors requires ammeters to display negative current when polarity of battery is reversed. Students can then plot V versus I and determine R from 1/gradient of the graph.
Can negative currents be indicated on the ammeters just as negative voltage appear on the voltmeters, please?

**Comment by arouinfar** [comment]
Hi @Nibbos, we considered your request about adding negative values of current, but felt that for this simulation keeping the current display as representing the amount of current flowing in all situations better matched the main learning goals. Additionally, since the probes of the voltmeter can just be swapped, it is really up to the student to set up the correct measuring experiment. Even if current had some notion of sign here, the students could end up with mis-matched signs, depending on how they conducted their measurements. So while we are very supportive of adding the non-ohmic bulb, we hope you understand the decision not to add negative currents.

@samreid this is something we've discussed in the past and decided against, so closing.

**Comment by Nibbos** [comment]
Hi, Amy.
Thanks for all the hard work you and your team put into the Phet
simulations.
The non-ohmic bulb will be really valuable for us here in the UK.
We can work around the lack of negative value currents with a little
teacher explanation, but thanks for considering my request.
To cap it all off, a diode (or LED), thermistor and LDR would be very
welcome additions to complete this package. I'm happy to help out with
advice or comment to assist matching their behaviour with curriculum
content.
Many thanks once again.
Kind regards
Conor

**Comment by oliver-phet** [comment]
Another user requested this feature:

> Here at Hunter, we are using your Phet. There is a glaring problem, your ammeters have no polarity. I want to teach about conservation of energy. I need to know if I have a positive or negative current. You have not built your voltmeters without polarity. Please remedy this situation by creating a positive and negative lead in your ammeters.

**Comment by samreid** [comment]
We discussed that since we now have current charts and worked out the current signs, we can leverage this for the numeric circuit value readout.  We would like to add a query parameter and phet button => options feature for this.  This would be for the in-line ammeter, and probe ammeter.  Reversing the in-line ammeter should not negate the value.

The query parameter will be: `?ammeterReadout=signed` `?ammeterReadout=magnitude`
The options dialog text will read: "Ammeter Readout: magnitude | signed" (radio buttons)

In DC it would just be in the query parameter and in the options dialog.
In all flavors it will be same.  

Other ideas we didn't like: `?signedAmmeters`, `?ammeters=positive` `?ammeters=positiveAndNegative` `?ammeters=magnitude` `?ammeters=signed`

**Comment by samreid** [comment]
I added the "signed" form for the ammeter, and basic tests seem to be working correctly.  I noticed that the inline ammeter and ammeter probe were using slightly different code, so I unified them to use the same code.  For testing:

* Try the query parameters `?ammeterReadout=signed` and `?ammeterReadout=magnitude`
* Try changing this value from the options menu 
* Create circuits and make sure the initial current in that circuit is positive.  Then reverse a battery or use an AC source to make the currents negative. 
* Test that the in-series ammeter and the probe ammeter and chart ammeter have the same values and signs. 
I'll publish a dev version.

**Comment by samreid** [comment]
UPDATE: Please test in the newer version: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.48/phet/circuit-construction-kit-ac_all_phet.html

**Comment by samreid** [comment]
In today's design meeting, @arouinfar said basic testing was looking good.  @ariel-phet said he saw a few surprising results, but wanted to test more thoroughly.  Maybe we will put this on hold until #784 is closed.

**Comment by samreid** [comment]
#784 seems reasonable, and like it should no longer block testing of this issue.

**Comment by samreid** [comment]
This would be good to explicitly test in QA with the signed ammeter.  Looking for discontinuities, or anything that seems incorrect.

**Comment by samreid** [comment]
We requested testing for this issue in https://github.com/phetsims/qa/issues/748, and some side issues were reported.  I'm inclined to close this and work on the discovered issues.  @KatieWoe please reopen if there's anything else specific to this issue.
