### ISSUE TITLE
Get rid of attach: true

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#608]
From https://github.com/phetsims/circuit-construction-kit-common/issues/607

> For the SwitchNode FireListener, for now I have specified `attach:false` as indicated by @pixelzoom and it is working well.  However, @jonathanolson said that means it could now touch-snag to start another drag in the same operation.  He said we may be able to get rid of `attach:false` if we identify the other listener that is attaching to the pointer.

The competing listeners are 

```js
// In FixedCircuitElementNode
this.dragListener = new CircuitLayerNodeDragListener(...);
```

```js
// in SwitchNode
const fireListener = new FireListener( {
```

If `attach:false` is in either one, then the switch can be dragged and opened/closed.  

It could be possible to change `CircuitLayerNodeDragListener` to extend FireListener, and have the `SwitchNode` listen for that `fire` event (so there is only input listener on the switch), but other subclasses would not use the `fire` behavior.  

@jonathanolson how do you recommend to proceed?

UPDATE: DragListener and FireListener are sibling children of PressListener.  There is no apparent easy way to have a DragListener that is also a FireListener.

**Comment by samreid** [comment]
This does not seem critical for the upcoming milestone, but it should be completed before any PhET-iO release.

**Comment by jonathanolson** [comment]
Is it... crazy to refactor PressListener/FireListener behavior into mixins (but where PressListener/FireListener are concrete types with those premixed), so that we could include both of those behaviors?

It also seems tricky to me that we'd want to have two listeners here... what happens when one activates and the other doesn't?

**Comment by samreid** [comment]
Unassigning until we work toward our first PhET-iO release.

**Comment by samreid** [comment]
From today's phet-io meeting: Assigning to @samreid to see how this pertains to the data stream or phet-io instrumentation.  Please reach out to @jonathanolson as necessary to proceed.

**Comment by samreid** [comment]
In discussion, @arouinfar said this didn't seem too serious, but we can check with @jonathanolson for upcoming release.

**Comment by samreid** [comment]
`attach: false` is used 17 times across our codebase, we have not demonstrated significant negative effects.  The PhET-iO data stream seems reasonable.  I recommend closing this issue, and we can reopen if/when we discover code review problems or usability issues with this setting.
