### ISSUE TITLE
Non-ohmic light bulb resistance should be updated, because brightness uses it and it appears in the display

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#612]
From https://github.com/phetsims/circuit-construction-kit-common/issues/10

Today we observed that the brightness was the same, but that's because the value wasn't updated.

```js
Brightness should be different

    const updateBrightness = Property.multilink(
      [ lightBulb.currentProperty, showResultsProperty, lightBulb.resistanceProperty ],
      ( current, running, resistance ) => {
        const power = Math.abs( current * current * resistance );

        let brightness = toBrightness( 0.35, power );
```

It wasn't clear whether we should hide the resistance value or show it.  If it's easy, I'll show it, then we can decide whether it should be redacted.

**Comment by samreid** [comment]
@kathy-phet said:

> Default realistic bulb should be dimmer (higher resistance) than a default ideal bulb.

**Comment by kathy-phet** [comment]
To clarify @samreid - I said, it should be dimmer when hooked up to the default battery. It should be 10 ohms (same ohms as the ideal bulb) when "cold" - not hooked to anything.

**Comment by kathy-phet** [comment]
And if they are in "series", then actually the real bulb would be brighter than the ideal bulb. In parallel, the real bulb is dimmer than the ideal bulb.

**Comment by samreid** [comment]
Comparing defaults after the commit:

![image](https://user-images.githubusercontent.com/679486/97727739-5f3a3980-1a96-11eb-99b8-3b45bffc3f4e.png)

![image](https://user-images.githubusercontent.com/679486/97727855-7c6f0800-1a96-11eb-9fce-3a89d00ed613.png)

Also, the resistance is now displayed with "show values":

![image](https://user-images.githubusercontent.com/679486/97728021-a9bbb600-1a96-11eb-9145-334079a9e737.png)

@arouinfar can you please review?

**Comment by samreid** [comment]
We reviewed this in today's meeting and agreed it is working nicely.  

@kathy-phet said if we get teacher requests, we may consider a query parameter to omit the ohm readouts from realistic bulbs.

Closing.
