### ISSUE TITLE
Change socket color for realistic bulb

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#613]
Related to https://github.com/phetsims/circuit-construction-kit-common/issues/10.  At today's design meeting, we agreed the realistic bulb should look different than the ideal light bulb, and this may be done by drawing the socket differently.  High priority since we would like to publish this soon.

**Comment by arouinfar** [comment]
Here are the bulbs currently in CCK:
![image](https://user-images.githubusercontent.com/8419308/98628817-a6b19880-22d4-11eb-97d1-9918cf74e798.png)

In design meeting we discussed making the socket a metallic-looking red. Here's a mockup with the coiled filament (see #614). @samreid if this color looks reasonable to you, I'll send you the asset.
![lightbulb-3_lightbulb_front_realistic](https://user-images.githubusercontent.com/8419308/98628850-b92bd200-22d4-11eb-96c3-cc93d9ff6c50.png)

**Comment by samreid** [comment]
That seems good to me.  Do you want a 2nd opinion from @ariel-phet before we proceed?

**Comment by ariel-phet** [comment]
I like that red color, definitely makes it stand out.

**Comment by arouinfar** [comment]
Great, thanks! The final assets will be delivered once we're done iterating on #614.

**Comment by arouinfar** [comment]
@samreid the updated assets are linked in https://github.com/phetsims/circuit-construction-kit-common/issues/614#issuecomment-725689411.

**Comment by samreid** [comment]
I added the images in the commit.  To see them in the toolbar, you might need to remove the pencil (until another issue is fixed).  Other than that, can you please review?

**Comment by samreid** [comment]
OK I think that commit will help.  Ready for review.

**Comment by arouinfar** [comment]
Looks great in master, thanks @samreid!
