### ISSUE TITLE
The realistic bulb filament should have a distinct appearance

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#614]
From https://github.com/phetsims/circuit-construction-kit-common/issues/10, the filament should change color as a function of resistance

**Comment by samreid** [comment]
I found the filament is rasterized and in the mipmaps/ directory, see https://github.com/phetsims/circuit-construction-kit-common/blob/a93e39506338f2960bbb2d7c0ea54f30da61d573/mipmaps/lightbulb-middle.png

It is used in `CustomLightBulbNode.js`.  We didn't see it yesterday because it was in mipmaps/ instead of images/.

Some options for how to proceed:
1. @jonathanolson is working on color filters in scenery that may be able to do this.  If so, we would still need to separate the filament into its own layer.
2. Convert the filament part into code
3. Skip this request or find another way to depict the change in resistance, or to depict the realistic bulbs.

@arouinfar can you please advise?

**Comment by samreid** [comment]
I saw there are sampled points in the model for the electron path, in https://github.com/phetsims/circuit-construction-kit-common/blob/aa6fe2c38306c6e16840df59a859f67def7b55e7/js/model/LightBulb.js#L29-L41

We could use these to render the filament, but it would need additional work to make it curved instead of lines.  I believe the electron paths are all linear at the moment.

**Comment by samreid** [comment]
@ariel-phet clarified that the filament doesn't need to change color continuously as a function of resistance, rather a single different color would be sufficient.  @ariel-phet also recommended a "coiled look" for the filament for this.  @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
I mocked up a coiled look, where the coils are a darker shade of the filament color. 

Option 1: Coils around the horizontal portion of the filament
![lightbulb-1_lightbulb_middle_realistic](https://user-images.githubusercontent.com/8419308/98628222-54bc4300-22d3-11eb-82f9-d71c329c7b8e.png)

Option 2: Coils around the entire element
![lightbulb-2_lightbulb_middle_realistic](https://user-images.githubusercontent.com/8419308/98628223-54bc4300-22d3-11eb-8b2d-cc0176cf9801.png)

We originally discussed something like option 1. I thought the ending of the coils looked a bit abrupt, so I decided to try  option 2. It's a bit tricky to loop the coils around the corners, but I still think it looks better overall.

What do you think @ariel-phet @samreid? (Note that socket color will be addressed in #613.)

**Comment by samreid** [comment]
At the size it will appear in the simulation, I think it will be difficult to see the coils.  Perhaps they should be exaggerated so they can be clearer?  I see the argument for having the coils all around the path, but it seems cleaner just to have it around the horizontal portion, depending on how we exaggerate it.

**Comment by arouinfar** [comment]
Thanks @samreid. Here are a few more iterations with larger, less densely spaced coils.

![lightbulb_lightbulb_front_realistic](https://user-images.githubusercontent.com/8419308/98746858-8b499a80-2373-11eb-9da1-0b1c0682479f.png) ![lightbulb_lightbulb_front_realistic](https://user-images.githubusercontent.com/8419308/98746633-1c6c4180-2373-11eb-97a5-83b047243369.png) ![lightbulb_lightbulb_middle_realistic](https://user-images.githubusercontent.com/8419308/98746634-1d04d800-2373-11eb-91b5-8a1e2bceed20.png)

**Comment by samreid** [comment]
I searched Google Images for "incandescent light bulb filament" and looked for ones that might seem familiar to people, with clearly visible loops, and this one stood out. What do you think?

![image](https://user-images.githubusercontent.com/679486/98747334-8cc79280-2374-11eb-9d11-33299452809a.png)

**Comment by ariel-phet** [comment]
@arouinfar I would lean towards the direction of option 1 in https://github.com/phetsims/circuit-construction-kit-common/issues/614#issuecomment-725034280

I would also go with @samreid recommendation of a direction and make the coils have more space, thicker stroke, and bigger radius (I am thinking if I am using this sim on something like a phone, I will hardly see those coils, so I think we want to basically go as heavy and exaggerated as we can and still feel aesthetically comfortable).

**Comment by arouinfar** [comment]
Thanks for the feedback @samreid @ariel-phet! Here's an option with exaggerated coils. The smaller version is a rough approximation of the size in the sim.
![lightbulb_lightbulb_front_realistic copy](https://user-images.githubusercontent.com/8419308/98866059-9232e480-2429-11eb-84de-ffac7aa3d849.png)<img src="https://user-images.githubusercontent.com/8419308/98866059-9232e480-2429-11eb-84de-ffac7aa3d849.png" width=75>

I think the exaggerated coils are certainly visible at sim resolution, while still looking reasonable. I'm happy to pixel polish it further if there are any suggestions for color, stroke weight, ellipse diameter/eccentricity, etc. I can also adjust things in real-time over zoom.

In the event the team is happy with the latest iteration, here are the updated assets:
[realistic-lightbulb.zip](https://github.com/phetsims/circuit-construction-kit-common/files/5526988/realistic-lightbulb.zip)

**Comment by samreid** [comment]
Looks great to me, but I'll wait for consensus before integrating them into the sim.

**Comment by samreid** [comment]
Do you just want to show the electrons going in front of the coils, or something more complicated with z-ordering?

**Comment by arouinfar** [comment]
@samreid I am fine with showing the electrons traveling on top of the coils. The coils do have a front and back layer, so it would be possible to sandwich the electrons between them, but that would complicate the assets. The current implementation of the light bulb already has separate back, middle, and front artwork.

**Comment by samreid** [comment]
I think it would send the wrong message to show the electron going through like a tunnel.

**Comment by ariel-phet** [comment]
@arouinfar I think the latest iteration looks awesome! Very clearly distinguishable . I agree the electrons just traveling on top of the coils is fine in my opinion. Nice work.

**Comment by arouinfar** [comment]
Awesome, thanks! @samreid the assets (including the updated socket) are linked in https://github.com/phetsims/circuit-construction-kit-common/issues/614#issuecomment-725689411.

**Comment by samreid** [comment]
I added the images in the commit.  To see them in the toolbox, you might need to remove the pencil (until another issue is fixed).  Other than that, can you please review?

**Comment by arouinfar** [comment]
The realistic bulb looks great!

![image](https://user-images.githubusercontent.com/8419308/99295382-95035000-2802-11eb-90d4-6aee93d29035.png)
