### ISSUE TITLE
Create a spreadsheet that depicts I, V, R values for the realistic bulb

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#615]
From https://github.com/phetsims/circuit-construction-kit-common/issues/10, @kathy-phet asked me to create a spreadsheet with I, V, R values, and plotting I vs V, and R vs I.

**Comment by samreid** [comment]
It was requested that I produce an Excel spreadsheet, but I wonder if it would be simpler if I created a Google Spreadsheet.

**Comment by samreid** [comment]
I recorded data from the simulation and plotted it in Google Spreadsheets here: https://docs.google.com/spreadsheets/d/1bolSLoxkewPamtv8sID5ABNGc9nTPL_fEk9DjetTaA0/edit#gid=0

Here is I vs V:

![image](https://user-images.githubusercontent.com/679486/97729986-e1c3f880-1a98-11eb-8aed-e1626eeb0bcb.png)


Here is R vs I

![image](https://user-images.githubusercontent.com/679486/97730029-f0121480-1a98-11eb-8a35-3c520aad5400.png)

Ready for review.

**Comment by samreid** [comment]
Here's the patch I used to plot the data:

```diff
Index: js/model/ModifiedNodalAnalysisAdapter.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/model/ModifiedNodalAnalysisAdapter.js	(revision aa6fe2c38306c6e16840df59a859f67def7b55e7)
+++ js/model/ModifiedNodalAnalysisAdapter.js	(date 1604074254456)
@@ -222,6 +222,11 @@
         // shift by base so at V=0 the log is 1
         resistorAdapter.value = 10 + coefficient * V / logWithBase( V + base, base );
         resistorAdapter.circuitElement.resistanceProperty.value = resistorAdapter.value;
+
+        window.log = window.log||'V\tI\tR\n';
+        const R = resistorAdapter.value;
+        const I = V/R;
+        window.log +=`${V}\t${I}\t${R}\n`;
       }
     } );
 

```

**Comment by kathy-phet** [comment]
@samreid - these curves look good to me. Can you run them by our Github teacher commenters, and by Mike D as well?

**Comment by samreid** [comment]
I posted in https://github.com/phetsims/circuit-construction-kit-common/issues/10 and also asked Mike D in email.

**Comment by samreid** [comment]
@arouinfar would like to move this sheet into the sim design folder.

**Comment by arouinfar** [comment]
I've copied the sheet into the sim design folder, and it now lives here: 
https://docs.google.com/spreadsheets/d/1l8yLXjOYhH1hVs1lv6INd7ga97otqGgxobHOjN929_I/edit#gid=0
