### ISSUE TITLE
Zoom buttons need magnifying glasses

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#620]
From today's design meeting, "+" and "-" are overloaded in CCK, and showing those as button icons without other context will be confusing.  We need the magnifying glass icons.  This is for the charts and for the play area zoom buttons.

@ariel-phet also indicated the flat buttons are good.

**Comment by samreid** [comment]
The play area zoom buttons already have magnifying glasses, so I'll move this to the AC milestone.

**Comment by samreid** [comment]
I opened https://github.com/phetsims/scenery-phet/issues/645, but the play area zoom buttons look like this:

![image](https://user-images.githubusercontent.com/679486/100655373-69a35980-3308-11eb-86bd-fce6ecf5c99f.png)

Should the chart zoom buttons look identical to the play area zoom buttons?  If so, what styling/coloring should we use?

**Comment by samreid** [comment]
I discussed this with @pixelzoom in https://github.com/phetsims/scenery-phet/issues/645 and on slack.  His opinion was that the +/- buttons are already perfectly clear in context, and that adding the complexity of changing icons for the ZoomButtonGroup is unwarranted.

I recommend we do one of the following (no particular order):
1. Spend the time to generalize ZoomButtonGroup so that it can support arbitrary icons
2. Accept the "+"/"-" text icons

I'd recommend against a custom or one-off solution for this case.

@arouinfar @ariel-phet @kathy-phet can you please recommend how to proceed?

**Comment by pixelzoom** [comment]
If you add the ability to use magnify glass icons, you'll also need to factor that icon out of ZoomButton.

**Comment by pixelzoom** [comment]
... or better yet, switch to using the fontawesome icons for the magnifying glasses:

https://fontawesome.com/icons/search-plus?style=solid
https://fontawesome.com/icons/search-minus?style=solid

**Comment by samreid** [comment]
Would it be OK if ZoomButtonGroup was hardcoded to use the magnifying glass icons?

**Comment by pixelzoom** [comment]
Do you mean as an option, or instead of +/- ?

**Comment by pixelzoom** [comment]
And I'm still trying to understand... If you want the ZoomButton look (magnifying glasses) why not just use a pair of ZoomButtons?  That's what has been done in other sims that use "magnifying glass" zoom buttons. What's special about CCK, and why does it need to use ZoomButtonGroup?

**Comment by samreid** [comment]
> Do you mean as an option, or instead of +/- ?

It would simplify things if we can use the same icons everywhere.  But if we need flexibility, then we should make it possible/easy to specify any icon.

> why not just use a pair of ZoomButtons

ZoomButtonGroup adds:

* Layout
* Pointer areas
* Disposal
* Enabled
* Deltas

Why should this be duplicated?

**Comment by pixelzoom** [comment]
If you want to add the ability to show magnifying glass icons to ZoomButtonGroup, you'll need at least 2 options:

* An option to indicate whether to show magnifying glasses or +/-, probably something clunky like `useMagnifyingGlassIcons`.
* An option to scale the FontAwesomeNodes that display the magnifying glass icons. Either something like `magnifyingGlassIconsScale` or `fontAwesomeOptions` if you want to go the nested-options approach.

Then you'll have the problem that some options (e.g. textOptions and fontAwesomeOptions) are ignored depending on which the type of icons displayed. 

Another approach would be to pass make ZoomButtonGroup a base class, with subclasses that pass in the desired icons nodes.  That would probably be preferable to complicating the ZoomButtonGroup API.

**Comment by pixelzoom** [comment]
> Another approach would be to make ZoomButtonGroup a base class, with subclasses that pass in the desired icons nodes.

```js
class ZoomButtonGroup extends LayoutBox {
   constructor( zoomInIcon, zoomOutIcon, zoomLevelProperty, options ) {
      ...
   }
}

class PlusMinusZoomButtonGroup extends ZoomButtonGroup {
    constructor( zoomLevelProperty, options ) {

      options = merge( {
         textOptions: {...}
         ...
      }, options );

      const zoomInIcon = new RectangularPushButton( {
        new Text( MathSymbols.PLUS, options.textOptions )
      } );

      const zoomOutIcon = new RectangularPushButton( {
        new Text( MathSymbols.MINUS, options .textOptions )
      } );

      super( zoomInIcon, zoomOutIcon, zoomLevelProperty, options );
    }
}

class MagnifyingGlassZoomButtonGroup extends ZoomButtonGroup {
    constructor( zoomLevelProperty, options ) {

      options = merge( {
         fontawesomeNodeOptions: {...}
         ...
      }, options );

      const zoomInIcon = new FontAwesomeNode( 'search-plus-solid', options.fontawesomeNodeOptions );
      
      const zoomOutIcon = new FontAwesomeNode( 'search-minus-solid', options.fontawesomeNodeOptions );

      super( zoomInIcon, zoomOutIcon, zoomLevelProperty, options );
    }
}
```

**Comment by samreid** [comment]
The preceding proposal https://github.com/phetsims/circuit-construction-kit-common/issues/620#issuecomment-736683290 looks good to me, let me know if you would like me to implement it.

**Comment by pixelzoom** [comment]
If you need it now, go for it.  You'll need to add the fontawesome glyphs to FontAwesomeNode.js.

**Comment by pixelzoom** [comment]
Before you begin...  I'm still skeptical that any of this is needed.  I haven't heard a response to why this is needed for CCK (+/- seems clear to me in the context of the chart), and why it's desirable to have 3 different "looks" for zoom buttons in PhET sims.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/circuit-construction-kit-common/issues/620#issue-747057037, you said:
> Should the chart zoom buttons look identical to the play area zoom buttons? If so, what styling/coloring should we use?

I should also point out that these buttons will not look identical to the play area zoom buttons. They will be using fontawesome icons.  And they will not be separated by space.   And if you have thoughts about adding that space to ZoomButtonGroup, that's going to complicate the pointer areas, which are currently implemented based on the assumption that the there is no space between the buttons, and the pointer areas therefore need to be shifted.

**Comment by samreid** [comment]
OK let's wait until we hear from designers.  @kathy-phet @arouinfar or @ariel-phet the main questions are:

* Does the CCK chart require magnifying glass icons, or are "+" and "-" OK?
* If so, should the play area buttons and the chart zoom icons have the same look?
* If not, will we have other sims where the zoom buttons will need to show icons other than "+" and "-"?

@pixelzoom please add other questions if I missed anything.

**Comment by kathy-phet** [comment]
I prefer the magnifying glass - due to what was discussed. That +/- are overloaded in this context. I could imagine other places (e.g. math sims) where we might want to use magnifying glasses.

**Comment by ariel-phet** [comment]
@pixelzoom since "positive" and "negative" can refer to the sign of charges, the sign of voltage etc, they are "overloaded" in the sense that @kathy-phet points out. Since the chart is moving, it seems like we don't want to have any confusion that perhaps polarity is flipping. So I think ideally we would have two different zoom buttons (the very clean ones used in natural selection, and a simple magnifying glass version when "+" and "-" are potentially overloaded in meaning for the sim). So in general, I think using that "cleaner/modern" look as described above is preferable going forward unless there is a pedagogical concern (which in CCK, there is)

@samreid -- I do personally prefer if the look of zoom buttons is consistent within a sim, so I would say in the ideal we would just have two versions of zoom button going forward. One with magnifying glasses, one without. But that is just my preference to ideally help keep things simpler and less versions of the UI component.

**Comment by arouinfar** [comment]
I think the current look of ZoomButtonGroup (+/-, flat appearance, touching) is ideal for most graphs. It has a really clean design that doesn't compete with the graph contents, and when next to an axis the icon meaning is clear. It's perfect for Natural Selection and Fourier: Making Waves. It'll probably also end up in sims that currently use magnifying glass zoom buttons in graphs, such as Blackbody Spectrum. 

However, I do share @ariel-phet and @kathy-phet's concerns around the interpretation of the +/- zoom buttons in the Voltage/Current charts in CCK. I think the +/- has the potential to be confusing, and would rather use the magnifying glass. Even if CCK didn't have the sign baggage, I would probably still prefer the magnifying glass in the chart for within-sim consistency. I don't think ZoomButtonGroup is eye-catching enough or adequately cues its purpose to be standalone zoom buttons in a play area, such as those in CCK or Projectile Motion.

> I would say in the ideal we would just have two versions of zoom button going forward. One with magnifying glasses, one without

This would be my preference too. The magnifying glass buttons should probably have a more traditional button-like appearance (shading, rounded corners) and padding between them. I'd be fine with keeping the current icons, or we could try the fontawesome icons suggested by @pixelzoom.

**Comment by samreid** [comment]
@pixelzoom can you please comment on whether we should use `new Text( MathSymbols.PLUS )` vs `new PlusNode()`?

**Comment by pixelzoom** [comment]
Use `MathSymbols.PLUS` and `MathSymbols.MINUS` when the icons are +/-.

Use FA icons `'search-plus-solid'` and `'search-minus-solid'` for magnifying glasses.

**Comment by samreid** [comment]
Can you please comment why to prefer `Text(MathSymbols.PLUS)` vs `PlusNode()`?  They look like this:

PlusNode
![image](https://user-images.githubusercontent.com/679486/102130932-b4e06080-3e0e-11eb-8ca3-0a45cebded3c.png)

vs

Text
![image](https://user-images.githubusercontent.com/679486/102131016-cf1a3e80-3e0e-11eb-959a-d646d19b9bd2.png)

Also, scenery-phet already has a magnifying glass node with a white glass I'm planning to use:

![image](https://user-images.githubusercontent.com/679486/102131104-f3761b00-3e0e-11eb-94dd-e6db3d99b19a.png)

**Comment by pixelzoom** [comment]
> Can you please comment why to prefer Text(MathSymbols.PLUS) vs PlusNode()? They look like this:

Simpler implementation.  Imo `PlusNode` and `MinusNode` should be deprecated.

**Comment by pixelzoom** [comment]
> Also, scenery-phet already has a magnifying glass node with a white glass I'm planning to use:

Again, simpler implementation.  I would replace the icons in ZoomButton with FA icons.

**Comment by samreid** [comment]
@pixelzoom and I discussed and agreed to keep `MagnifyingGlassNode` instead of going to FA for this case, since we have many places where we want to keep `MagnifyingGlassNode` and it already looks good and has been well tested, and supports the white glass.  I also recommended using the `PlusNode` and `MinusNode` shapes to rule out any abnormalities due to odd fonts, and @pixelzoom agreed that would be OK as long as I match the look to what is already in natural selection and fourier.

The other recommendations from our discussion were:
* Create a new issue: accommodate spacing in ZoomButtonGroup pointer areas
* Rename MagnifyingGlassNode.radius to glassRadius
* Create a chip-away issue to update other sims to use this new common code.

**Comment by samreid** [comment]
I committed as @pixelzoom and I discussed.  @pixelzoom do you have time to review?  If not, please reassign to @ariel-phet to request another reviewer.

**Comment by samreid** [comment]
I added one more commit to use the magnifying glasses in the CCK chart.

**Comment by pixelzoom** [comment]
A bit of cleanup needed.  In the above commits:

* In MagnifyingGlassZoomButtonGroup.js, this assertion is needed in, as you're potentially (silently) blowing away an icon specified by the client:

`assert && assert( !options.magnifyingGlassNodeOptions.icon, 'MagnifyingGlassZoomButtonGroup sets magnifyingGlassNodeOptions.icon' );`

* In PlusMinusZoomButtonGroup.js, this constant isn't going to make sense to future readers. Size of what? Why the funky computations involving magic numbers?

`const DEFAULT_SIZE = new Dimension2( 20 * 0.35, 3.6 * 0.35 );`

* In PlusMinusZoomButtonGroup.js, this line is unnecessary. You've already set `size: DEFAULT_SIZE` above, so you can just pass `options.iconOptions` to the icons.

`const plusMinusNodeOptions = merge( { size: DEFAULT_SIZE }, options.iconOptions );`

Base to @samreid for review of these changes.

**Comment by samreid** [comment]
I reviewed the changes and did not have further recommendations, thanks!  Closing.
