### ISSUE TITLE
Dropping a meter in the toolbox is too eager

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#621]
Right now, a meter drops in the toolbox if any edge overlaps.  This is too eager, especially for the large voltmeter chart + ammeter chart.  For those, the center should overlap to trigger dropping in.

**Comment by samreid** [comment]
I committed the proposed fix, @arouinfar can you please review?  Close if all is well.

**Comment by arouinfar** [comment]
This feels much better now, thanks @samreid
