### ISSUE TITLE
All fonts in the carousel should be the same size

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#624]

**Comment by samreid** [comment]
This already seems OK in the DC version (for English)

![image](https://user-images.githubusercontent.com/679486/99886762-4c7dd500-2bfc-11eb-83e3-a1de89ee356e.png)

I think we were seeing `maxWidth` effects in AC, for example this is running with stringTest=double:

![image](https://user-images.githubusercontent.com/679486/99886784-733c0b80-2bfc-11eb-9c5e-dcca7e184c9b.png)

@arouinfar does anything need to be done on this issue for the DC realistic bulb milestone?

**Comment by arouinfar** [comment]
@samreid looks good in DC.

For AC, I'm seeing a maxWidth issue with "CAPACITOR" but I think it should fit if re-cased to "Capacitor" which will be handled in #623
![image](https://user-images.githubusercontent.com/8419308/100241995-88ad8000-2ef1-11eb-946e-eacb1f440213.png)
