### ISSUE TITLE
Dropping a realistic bulb in the toolbox when "add realistic bulbs" is unchecked shouldn't show a bulb

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#625]
Dropping a realistic bulb in the toolbox when "add realistic bulbs" is unchecked shouldn't show a bulb

**Comment by samreid** [comment]
Also, checking "add realistic bulbs" when there are none creates an 11th bulb.

**Comment by samreid** [comment]
I think it's fixed in the commit.  @arouinfar can you please test?

**Comment by arouinfar** [comment]
@samreid looks good in master!
