### ISSUE TITLE
User suggestion: compass

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#626]
> A suggestion-For your circuit construction kits, do you think you could add a working compass?
> That way students can see the defection, and that helps me teach that electricity and magnetism are connected. That would also make it possible for students to do more from CASTLE labs from Pasco.

**Comment by arouinfar** [comment]
I'm fairly certain that this would be a major model change, as I doubt there is information about the magnetic field in the play area. This is not a request we will be able to accomodate, and it's really best served by [Faraday's Electromagnetic Lab](https://phet.colorado.edu/en/simulation/faraday). Can you share this sim with the user @oliver-phet?

**Comment by samreid** [comment]
> I'm fairly certain that this would be a major model change, as I doubt there is information about the magnetic field in the play area.

It seems straightforward to use the Biot-Savart Law to compute the magnetic field at a point, if we (a) only compute it for straight wires or components (e.g., not light bulbs) and (b) only compute it at a point, like for a compass, and not for showing the entire field (like ferromagnetic magnetic filaments), which could be more performance intensive.  For me, the more important question is whether we want it to be in the scope of the learning goals for this sim.  I agree Faraday's Electromagnetic Lab works pretty well, but it doesn't exactly show the Biot-Savart Law.  But maybe we would eventually have another sim that focuses on that learning goal?

**Comment by arouinfar** [comment]
Good to know @samreid!

> For me, the more important question is whether we want it to be in the scope of the learning goals for this sim. I agree Faraday's Electromagnetic Lab works pretty well, but it doesn't exactly show the Biot-Savart Law. But maybe we would eventually have another sim that focuses on that learning goal?

I really don't see it within the scope of CCK's learning goals. We would need more constraint to properly focus on Biot-Savart Law, which really doesn't mesh with the sandbox nature of CCK. Faraday's EM Lab would be a closer fit, but with 5 screens, I don't see that sim getting any bigger. We could probably use an electrodynamics sim, but that's a long ways off.

**Comment by oliver-phet** [comment]
I replied to the user, but forgot to add that to this issue. Here's the reply from the user:

> I totally use the Faraday’s Phet! Thank you for it!  I just try and get the electricity and magnetism connection perhaps earlier than most teachers, dropping seeds along the way.  It’s be nice to have an Orstead’s visualization from the top and to the side, that would help with the idea of it being a FORCE for a motor with the right hand rule (layering)

**Comment by samreid** [comment]
Since we don't have plans to introduce a compass into CCK, and the user has been notified, it seems we should close this issue.
