### ISSUE TITLE
add a cue that indicates when all data is outside a chart's range

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#627]
This came up while I was collaborating on some bamboo (chart) changes with @samreid.  I was testing my changes in the context of CCK-AC, and he referred me to the Voltage meter.   I put the meter across a 9v battery, didn't see anything, and thought the meter was broken.   The problem was that all data was off scale, and I needed to zoom out.   I suspect that students may also be prone to this problem.  We had this identical problem in Natural Selection, and added a cue when _all data_ is off scale.  

Here's our Slack discussion, and the Natural Selection example:

Chris Malley  11:29 AM
Which variant of CCK should I run if I want to test use of bamboo?

Sam Reid  11:29 AM
AC. It is in the voltage and current charts, in the toolbox

Chris Malley  11:31 AM
Is the voltage meter operational? If I measure the voltage across a 9v battery, I see nothing on the chart.

Sam Reid  11:31 AM
zoom out maybe?

Chris Malley  11:32 AM
Ah, yes.

Sam Reid  11:32 AM
Maybe we need a better initial value.

Chris Malley  11:33 AM
Has anyone discussed a cue that indicates that _all data_ is off scale?  We had this identical problem in Natural Selection, and did this:

<img width="903" alt="screenshot_741" src="https://user-images.githubusercontent.com/3046552/101941516-52d0f280-3ba5-11eb-8a98-38100708a97d.png">

Sam Reid  11:34 AM
We didn’t discuss it yet, feel free to create an issue if you wish, or slack Amy about it

**Comment by pixelzoom** [comment]
@samreid also asked about supporting this in bamboo.

Sam Reid  11:38 AM
Should that be a standard griddle building block somehow?

Chris Malley  11:41 AM
Not until we identify something that is appropriate for most sims.  I doubt that something as heavy as "Zoom out to see data" will pass muster for the tiny charts in CCK:AC.

**Comment by arouinfar** [comment]
Thanks for the suggestion @pixelzoom. I think the core problem in CCK is that the default zoom level does not match up with the default voltage. It wasn't always like this, though. @samreid please make the default zoom range for the voltage chart [-10, 10]. The default range for the current chart looks good.

I'm not sure I would add a warning message or cueing arrow to communicate range. The chart will only appear to be empty in situations where the value is static, and then the standard voltmeter or ammeter would be a better choice.  The charts are meant to display the oscillating behavior of an AC circuit or a the exponential behavior of an RLC circuit. A message like `Out of Range` or `Zoom Out` could work for static situations, but would probably be really messy for oscillating/exponentially changing data. When the data is in motion, it is much more obvious that the zoom level is not optimal. 

For example:
![image](https://user-images.githubusercontent.com/8419308/103563748-8ccaa700-4e7a-11eb-8113-600b28ab7364.png)

**Comment by samreid** [comment]
I agree with the preceding comment, and changed the voltage chart default range to -10..10.  @arouinfar can you please review?  Close if it's working as desired.

**Comment by arouinfar** [comment]
👍🏻
