### ISSUE TITLE
Dragging a chart out of the control panel when zoomed out has wrong coordinate frame

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#628]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/620, dragging a chart node out of the control panel while zoomed out has the drag in the wrong coordinate frame.

The chart drag listener is defined in js/view/CCKCChartNode.js.  The forwarding listener is declared in js/view/SensorToolbox.js

**Comment by samreid** [comment]
After the chart has been dropped in the play area, it drags at the correct rate.  So it seems the problem is only with the `createForwardingListener` when dragging out of the toolbox at the zoomed-out-scale.  I'm not sure how to investigate this and could use help.  @ariel-phet can you please recommend someone to assist on this problem?

**Comment by ariel-phet** [comment]
This seems like it probably falls in @jonathanolson wheelhouse. If he is not available I recommend chatting with @jessegreenberg

**Comment by jessegreenberg** [comment]
I tried to take a look, but didn't notice any odd behavior dragging the voltmeter or ammeter out of the SensorToolBox. I wasn't too sure what kind of zoom you meant so I tried with the charts zoomed out using their zoom buttons, at various levels of native browser zoom, and at various levels of zoom with PhET's pan and zoom feature. In each case the draggable object followed the mouse as I would expect. Is there anything else I am missing to test?

**Comment by samreid** [comment]
To reproduce the problem, launch CCK-AC Screen 1, then press the "zoom out" button in the bottom left of the screen, then drag a voltage chart from the toolbox.  It drags at about half of the rate and gets disassociated from the mouse.  @jonathanolson and I have scheduled an appointment to investigate further.

**Comment by samreid** [comment]
@jonathanolson and I addressed this in the commits, thanks @jonathanolson !
