### ISSUE TITLE
Tweaker Buttons can be misaligned when text changes size due to i18n

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#635]
From https://github.com/phetsims/wave-interference/issues/433, 

> Similar to #420 and https://github.com/phetsims/scenery-phet/issues/513 and noted during https://github.com/phetsims/QA/issues/405, the tweaker buttons don't always line up.  They are positioned based on the height of the number control which may change based on the height of the text.  Hence the "align the bottom" strategy proposed in #420 doesn't also align the tweaker buttons.

![image](https://user-images.githubusercontent.com/679486/63202572-88b0a600-c047-11e9-8abc-2eb042904fb4.png)

@ariel-phet said:

> @samreid I am fine with us not solving this as a part of [waves intro] RC, but it should be solved in a general way since again, this layout will occur again in CCK AC (a sim destined to have many many translations).

A later dev meeting consensus said:

> We decided to come back to this when @ariel-phet returns because we aren't sure how much time we should spend on resolving issues involving these layout functions vs just adding what we need to support custom cases.

Then in April, @zepumph commented:

> @ariel-phet feels like there are bigger fish to fry at the moment, and mentions that this may be needed for CCK AC. We will tackle it then.

I created this issue so we can address it as it pertains to CCK AC upcoming milestone.  Self-assigning to report on status, then I'll likely assign to @ariel-phet for discussion.

**Comment by samreid** [comment]
Here is the AC source control panel with stringTest=double. It's less problematic than the case in Wave Interference because there are no tick labels here.

![image](https://user-images.githubusercontent.com/679486/102958391-f8d00700-4499-11eb-90d8-00a08f9698a6.png)

I see a slight misalignment of the latter tweaker buttons (they are a bit high), but this doesn't seem problematic enough to require work before AC 1.0 is released.  I recommend closing this sim-specific issue and continuing with more general layout features in https://github.com/phetsims/sun/issues/48.  @ariel-phet what do you recommend?

**Comment by ariel-phet** [comment]
@samreid, agreed.
