### ISSUE TITLE
Will the charts ever show more than one data series?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#637]
I could make a simplification in the code if we think the CCK: AC charts will always only show one data series at a time.  At the moment, they are generalized to support multiple series, but I don't think we are using that feature.  @arouinfar can you please comment?

UPDATE: Discovered this question while working on https://github.com/phetsims/circuit-construction-kit-common/issues/634

**Comment by arouinfar** [comment]
@samreid I don't see any reason why we would want to display multiple series in a single chart. In fact, I think that would be very confusing in this context.

**Comment by samreid** [comment]
Thanks, I simplified the code, closing.
