### ISSUE TITLE
Why does the AC Source look so blurry?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#642]
In #633 @samreid noticed the capacitor charges can sometimes look a little blurry which got me thinking about how much the blurry appearance of the AC source has been bothering me.

![image](https://user-images.githubusercontent.com/8419308/103565994-89391f00-4e7e-11eb-884e-ccc5fa475028.png)

It is noticeably lower quality than the other components. @samreid is there something we could do to improve the look? Is the asset quality significantly different from the others? Should we try mostly drawing it in code and decorate it with a sine wave asset?

**Comment by samreid** [comment]
I increased the resolution without changing the size, therefore I'll move it back to AC milestone.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
It looks so much better now, thanks @samreid!
![image](https://user-images.githubusercontent.com/8419308/103681899-5017b200-4f45-11eb-9fd3-6e2db6090c4b.png)
