### ISSUE TITLE
Voltage probe can get stuck past the sim borders and can't be grabbed

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/circuit-construction-kit-common#645]
**Test device**
Lenovo ThinkPad

**Operating System**
Win10

**Browser**
Chrome, Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/587
When dragging out the Voltage or Current probes (either screen), if you drag out to the edge of the screen one of the probes is stuck past the border and you cannot grab it. The only way to change this without clicking the orange reset button is to drag the tool back into the toolbox. 
 
**Visuals**

![circuitissue](https://user-images.githubusercontent.com/72031637/103791941-e9070580-4ff7-11eb-9f77-b49bbbcc58ef.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.2.0-dev.10 2021-01-05 20:31:01 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Thanks for discovering and reporting this bug.  I committed a fix to master.  Can you please verify on master?  This is for a dev test, so will not need to be cherry-picked to any branches.

**Comment by brooklynlash** [comment]
It looks fixed on master! Everything looks great. So sorry for the delayed response.
