### ISSUE TITLE
Screenshot performance slow even with no items on screen

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/circuit-construction-kit-common#646]
**Test device**
Lenovo ThinkPad

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
This is for https://github.com/phetsims/QA/issues/587
When taking a screenshot of either screen, it takes up to 10 seconds for the screenshot to download, even when no items are on the screen. 

**Visuals**
![circuitsc2](https://user-images.githubusercontent.com/72031637/103795362-bc082200-4ffa-11eb-8428-e6034a431d1d.gif)
![circuitsc](https://user-images.githubusercontent.com/72031637/103795364-bca0b880-4ffa-11eb-8846-542cda2f97e5.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.2.0-dev.10 2021-01-05 20:31:01 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Co-assigning @jonathanolson in case he has ideas about this before I investigate.

**Comment by samreid** [comment]
@amanda-phet pointed out there is a similar problem in 2/4 screens of Number Line Operations.

**Comment by samreid** [comment]
It took around 4-5 seconds on my mac/chrome.

**Comment by arouinfar** [comment]
I think this is a general issue in master. Taking screenshots in Fourier: Making Waves took more than 5 seconds on my Mac/Chrome.

**Comment by arouinfar** [comment]
@samreid I added this issue to the DC milestone. Milestones can't handle things across repos, so I can't tag the underlying scenery issue.

**Comment by samreid** [comment]
@jonathanolson fixed https://github.com/phetsims/scenery/issues/1139 and it has been reviewed and closed.  @arouinfar can you double check that CCK seems reasonable after that change?  Close if all is well.

**Comment by arouinfar** [comment]
Screenshot performance is snappy in master, closing.

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/610 I was seeing a bit of slowness on iPadOS 14. Not too bad, but it usually better on that device.

**Comment by arouinfar** [comment]
https://github.com/phetsims/scenery/issues/1139 was considered bad enough to block all sim publication, so I need more information before I can make a call about CCK. 

@KatieWoe can you provide more information? Is iPadOS 14 the only platform you see the issue on? Does it happen in other sims on master? Can you quantify the delay, are we talking 2-3 seconds or something worse?

**Comment by samreid** [comment]
I tested on iPad 7 running iOS 14.4 with RC.2 and it was around a second (perhaps 1.2 sec) to generate the screenshot.

**Comment by arouinfar** [comment]
> I tested on iPad 7 running iOS 14.4 with RC.2 and it was around a second (perhaps 1.2 sec) to generate the screenshot.

That sounds reasonable to me @samreid. I'm comfortable closing this issue if you are.

**Comment by KatieWoe** [comment]
I saw it a bit on ChromeOS, but in both cases it was less than 2 seconds.

**Comment by samreid** [comment]
That seems like an acceptable delay for generating a screenshot, closing.
