### ISSUE TITLE
Create a virtual lab version for AC

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#647]
Today, we agreed we would like to create a virtual lab AC version.

**Comment by samreid** [comment]
I finished setting this up, and it appears OK on my side.  @arouinfar can you please test?

**Comment by arouinfar** [comment]
@samreid the Virtual Lab flavor shouldn't include the non-contact ammeter. It should be removed from the toolbox and the label should be changed to `Ammeter`.

**Comment by samreid** [comment]
Good catch!  For unknown reasons, it looks like bayes/phettest is missing this commit https://github.com/phetsims/circuit-construction-kit-ac/commit/fee31fdbe929695ab371ddb047acb16822aa11fe

Also, I noticed that in DC-Virtual lab it reads "Ammeters" instead of "Ammeter"--should that be changed to singular as well?

**Comment by arouinfar** [comment]
The Virtual Lab flavors look good, including the singular/plural "Ammeter(s)" label.
