### ISSUE TITLE
Should toolbox carousel scroll to the top when realistic lightbulb added

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#648]
**Test device**
MacBook Air
**Operating System**
10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/587.
When checking the "Add Realistic Bulbs" checkbox, the tool carousel scrolls back to the top. This can be a bit odd, especially if you were already on the last panel where the bulb would be. Turning off the box does not seem to do this.

**Visuals**
![addbulbscroll](https://user-images.githubusercontent.com/41024075/104076584-bca7e080-51d3-11eb-9836-707d99ec598b.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.2.0-dev.10 2021-01-05 20:31:01 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1265x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Good catch @KatieWoe. It's supposed to scroll to the page that contains the Realistic Bulb.

**Comment by samreid** [comment]
I committed a proposed fix, ready for review in master.  This is for a dev test, so would not need to be cherry picked into any branches.

**Comment by KatieWoe** [comment]
Looks fixed in master. Now scrolls to bottom

**Comment by samreid** [comment]
Excellent, thanks for reporting this problem.  New SHAs will be taken when we move to RC, closing.
