### ISSUE TITLE
Shouldn't Resistance Increase with Length of Wire?

### ISSUE THREAD

**Issue by DevonQui** [phetsims/circuit-construction-kit-common#650]
**Test device**
MacBook Pro

**Operating System**
Big Sur 11.0.1

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/QA/issues/587

Considering that the simulation gives people the option to look at values like resistance and voltage, shouldn't the resistance of the wire increase as the length of the wire increases? It's been a while since I've even studied that type of physics so the changes in resistance might be completely negligible in terms of the scale of the simulation but I thought it might be worth considering nonetheless. Thoughts?

**Steps to reproduce**

**Visuals**
Short Length has 20 Ohms
<img width="339" alt="Screen Shot 2021-01-11 at 4 15 26 PM" src="https://user-images.githubusercontent.com/72042459/104249726-3dabe580-5429-11eb-8dd2-dd1de2953f58.png">

Long Wire also has 20 Ohms
<img width="1044" alt="Screen Shot 2021-01-11 at 4 15 55 PM" src="https://user-images.githubusercontent.com/72042459/104249737-43093000-5429-11eb-983c-13727444efec.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.2.0-dev.10 2021-01-05 20:31:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
Language: en-us
Window: 1440x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
The wires do have resistivity, and on the lab screen, there is an option to change the wire resistivity:

![image](https://user-images.githubusercontent.com/679486/104251699-88c7f780-542d-11eb-9b3e-cbd55f3807fa.png)

What you are seeing on this display is that the battery has an internal resistance of 20 Ohms:
![image](https://user-images.githubusercontent.com/679486/104251905-fffd8b80-542d-11eb-92da-8ca73bb58c43.png)

But I can't figure out how you got it up to 20 Ohms.  @DevonQui or @arouinfar any ideas about that?

**Comment by arouinfar** [comment]
@samreid it looks like @DevonQui found a bug.

The label on the battery is only supposed to be indicative of the internal resistance of the battery and should be completely independent of the wire resistivity. 

> But I can't figure out how you got it up to 20 Ohms. @DevonQui or @arouinfar any ideas about that?

Set the internal resistance of a high-V battery to 10 ohms, and then short it. Maximize the voltage, and the displayed resistance will increase to 20 ohms. Reducing the internal resistance to 0 ohms does nothing; the value label will still show 20 ohms. Break the circuit, and the displayed resistance will match the value of the battery resistance slider.

**Comment by samreid** [comment]
In https://github.com/phetsims/circuit-construction-kit-common/issues/245 we agreed to recompute the battery internal resistance when the battery current threshold is exceeded, I think that's what we are seeing here.  @arouinfar can you please advise?

**Comment by samreid** [comment]
Proposal from design meeting: only show the displayed value of the slider, not the computed battery internal resistance.  Only show the internal resistance if the slider is set to non-zero.  We should be clear to update the teacher tips since this could be a source of confusion (if the internal resistance differs from what is displayed).

**Comment by samreid** [comment]
I changed the battery readout value to only display the user-specified internal resistance, not the computed internal resistance.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master @samreid.

**Comment by samreid** [comment]
Thanks, I'll mark this for a double-check in the RC.

**Comment by samreid** [comment]
On second thought, this seems good to close.
