### ISSUE TITLE
Switching screens makes interacting with carousel difficult/impossible

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#651]
**Device**
iPad 6th Gen
**OS**
iPadOS 14
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/587. Wasn't able to reproduce on Mac 10.15 or iPhone iOS 13.
When you are on one screen, switch to the other with the nav bar, and switch back it is difficult or impossible to use the carousel arrows or pick up tools from that box. Other interactions, such as tools already in the play area, seem to still work. This occurs with both screens. Reloading the page is the only way I've found to fix so far. I plugged the device in to a Mac to look at the console and no errors came up.

**Comment by KatieWoe** [comment]
Does not happen in published. On master it doesn't seem to happen right now.

**Comment by KatieWoe** [comment]
Potentially connected oddity I saw on ChromeOS. When you switch from one screen to the other, the mouse over the carousel arrows is an arrow rather than a hand. pressing down on a button does nothing the first time, but then the mouse will become a hand and you can interact as intended. I wonder if this is a less breaking version of this bug.

**Comment by KatieWoe** [comment]
Saw on Win 10 Chrome as well, so it seems more general than ChromeOS.

**Comment by samreid** [comment]
I'm wondering if this dev version was published with the bad SHAs that affected https://github.com/phetsims/sun/issues/672 ?

**Comment by samreid** [comment]
I could not reproduce this problem on iPhone 12, but I'll also test on iPad.

**Comment by KatieWoe** [comment]
Yeah, I think it may be something about iPadOS, since I didn't see it on my phone either. But I also have iOS 13 on my phone, so it may be connected to version.

**Comment by samreid** [comment]
I was easily able to reproduce this problem on an iPad 7 running iOS 14.3.  The problem is very severe.  I did a fresh build from master and the problem is gone.  So https://github.com/phetsims/sun/issues/672 is still a candidate for what caused the problem, but we still don't know exactly what caused https://github.com/phetsims/sun/issues/672.  Still, this seems corrected and ready for review in the next RC.

**Comment by KatieWoe** [comment]
This looks good in rc.1
