### ISSUE TITLE
"Realistic Bulb" text is somewhat shrunken, should we change the name to "Real Bulb" to shorten it?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#652]
From https://github.com/phetsims/circuit-construction-kit-common/issues/629.  "Realistic Bulb" text is somewhat shrunken, should we change the name to "Real Bulb" to shorten it?  If so, we would change the name in the code, query parameter, checkbox, etc.  In order to have a maxWidth that accommodates "Realistic Bulb" the icon width must be unnaturally wide.

It currently looks like this:
![image](https://user-images.githubusercontent.com/679486/104657566-6973d900-567e-11eb-9437-ba9c9e1c108f.png)

**Comment by samreid** [comment]
@arouinfar and I agree the connotation of "realistic" is a little better.  @kathy-phet what do you recommend?

**Comment by arouinfar** [comment]
> @arouinfar and I agree the connotation of "realistic" is a little better.

Based on connotation alone, I think "realistic" is better, but with the other design concerns, I'd go with "real".

Another benefit of using "real" is that the query parameter will be shorter `addRealBulbs` instead of `addRealisticBulbs`.

**Comment by kathy-phet** [comment]
I'm OK with changing to real, although I do agree with "realistic" as conveying more meaning/sentiment.

I do want to mention that on phettest I did not see either version - I only saw "Light Bulb" twice.

**Comment by arouinfar** [comment]
> I'm OK with changing to real, although I do agree with "realistic" as conveying more meaning/sentiment.

Thanks @kathy-phet. @samreid let's proceed with changing things over to "Real Bulb". Please update the component label in the carousel, the checkbox label, and the query parameter.

> I do want to mention that on phettest I did not see either version - I only saw "Light Bulb" twice.

That sounds strange to me. "Light Bulb" does appear twice for the regular and high-R bulbs, but I'm still seeing "Realistic Bulb" in master:
![image](https://user-images.githubusercontent.com/8419308/105427279-04822b00-5c0a-11eb-8cb3-9b1540affd8e.png)

**Comment by samreid** [comment]
Changed in the commits, @arouinfar can you please test?

**Comment by arouinfar** [comment]
Looks good in master @samreid.
