### ISSUE TITLE
Battery tool icon has too much blank space between it and the label

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#653]
From https://github.com/phetsims/circuit-construction-kit-common/issues/629.  We had a similar problem with capacitors recently, I'll take a look.

**Comment by samreid** [comment]
![image](https://user-images.githubusercontent.com/679486/104658193-8957cc80-567f-11eb-8930-6643c4780c19.png)

**Comment by samreid** [comment]
This is caused by the larger vertical height of the schematic battery icon.  You can see this if you switch back and forth between lifelike & schematic.  If we want to reduce the size of the battery schematic icon, we cannot simply scale it without its width and line width getting out of sync compared to the other schematic elements.  @arouinfar how do you recommend to proceed?

**Comment by arouinfar** [comment]
Oh, that makes sense @samreid. I don't think we should make any changes to the schematic battery, so I'll go ahead and close.
