### ISSUE TITLE
Disable keyboard navigation for AC and AC virtual lab

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#656]
@jessegreenberg pointed out that AC should not be keyboard accessible yet, it probably needs this snippet:

```js
// Support accessibility for deleting selected circuit elements, but don't support broader tab navigation until it
// is complete
document.addEventListener( 'keydown', event => {
  const keyCode = event.keyCode || event.which;
  if ( keyCode === KeyboardUtils.KEY_TAB ) {
    event.preventDefault();
  }
} );
```

**Comment by samreid** [comment]
To make this work @jessegreenberg points out they will also need `"supportsInteractiveDescriptions": true` in package.json.

**Comment by samreid** [comment]
Fixed in the commits and seems to be testing OK on my system.  @jessegreenberg can you please review or spot check as you see fit?

**Comment by jessegreenberg** [comment]
This looks good to me and I tried to test to make sure it works. I tried CCK:AC, CCK:DC, CCK:AC Virtual Lab and CCK:DC Virtual Lab. For all of them I could delete components by pressing the "backspace" key, but I was not able to tab around the sim.

**Comment by samreid** [comment]
Thanks @jessegreenberg! Closing.
