### ISSUE TITLE
Investigate a schematic icon for AC source

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#657]
From https://github.com/phetsims/circuit-construction-kit-common/issues/629, we would like to investigate a schematic icon for AC source.  @arouinfar can you please take the lead?

**Comment by arouinfar** [comment]
@samreid this is the schematic icon for an AC source. It seems to be the same in both IEEE and IEC standards.

![image](https://user-images.githubusercontent.com/8419308/106308545-18d3b280-621e-11eb-862a-072b4680b4eb.png)

**Comment by samreid** [comment]
Should I use what is already in the code but (a) fixing the stroke and (b) getting rid of the +/- signs?

**Comment by arouinfar** [comment]
@samreid that sounds reasonable. For schematic, we should:

- [ ] Match stroke of other schematic icons
- [ ] Remove white fill
- [ ] Remove +/- signs

**Comment by samreid** [comment]
I proposed fixes for each recommendation in the commit, can you please review?  Note this also made corresponding minor modifications to the lifelike view.

**Comment by arouinfar** [comment]
@samreid  the new schematic looks great! I'm not so sure that I like the thicker outline stroke in the lifelike view. Would it be possible to dial it down a bit to look more similar to the other lifelike icons?
![image](https://user-images.githubusercontent.com/8419308/106317090-001dc980-622b-11eb-8f17-4dc08b7e6748.png) ![image](https://user-images.githubusercontent.com/8419308/106317107-04e27d80-622b-11eb-8a87-8bd8dcdd20ee.png)

**Comment by samreid** [comment]
I set the schematic stroke to 4 and lifelike stroke to 2.  Please review.  Feel free to adjust or request changes as you see fit.

**Comment by arouinfar** [comment]
Looks great, thanks @samreid!
