### ISSUE TITLE
Voltmeter can be "Lost" when zooming in on Lab section

### ISSUE THREAD

**Issue by DevonQui** [phetsims/circuit-construction-kit-common#658]
**Test device**
MacBook Pro

**Operating System**
11.0.1 Big Sur

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/QA/issues/605

When zooming out completely, placing the voltmeter on the edge of the sim screen, and then zooming in, the voltmeter will go off screen. I noticed that the ammeter doesn't have the same behavior because it stays within the bounds of the screen but the voltmeter doesn't have this property.

**Steps to reproduce**
1. Open the simulation
2.  Go over to the "Lab" section of the simulation
3. Click the zoom out (-) button on the lower right-hand side
4. Place both the ammeter and voltmeter on the left or right edge of the screen
5. Go back to lower right-hand side and press the "zoom in" (+) button now
6. Notice that the ammeter will resize and stay within the simulation screen whereas the voltmeter will resize and escape from the main sim screen

**Visuals**
Here's a link to a video of this issue...

https://drive.google.com/file/d/1eSAPMJtmUeFPOI4HSrgimFtb7Xt3n9yB/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC - Virtual Lab‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.0-rc.1/phet/circuit-construction-kit-dc-virtual-lab_all_phet.html
Version: 1.2.0-rc.1 2021-02-03 23:28:14 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
Language: en-us
Window: 1440x697
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by muedli** [comment]
I managed to lose both the voltmeter and the ammeter following @DevonQui's steps on iOS 14.3 + Safari 14.0.2.

**Comment by DevonQui** [comment]
I was also able to lose both using a different method. Shown below

First readjust the size of the window itself by stretching it super wide...
<img width="1264" alt="Screen Shot 2021-02-09 at 11 47 12 AM" src="https://user-images.githubusercontent.com/72042459/107412234-acce3580-6acc-11eb-841b-e9c585044dfa.png">


Then set the window size back to normal and the items will be lost. This still only happens to the ammeter and voltmeter and wasn't able to do it with any of the other sim elements using this method.
<img width="1274" alt="Screen Shot 2021-02-09 at 11 47 45 AM" src="https://user-images.githubusercontent.com/72042459/107412495-f028a400-6acc-11eb-8210-1b3d7e3e3852.png">

**Comment by samreid** [comment]
I committed a proposed fix, @DevonQui can you please test the fix in master?  If it seems correct, please reassign to me to cherry-pick into the RC branch.

**Comment by DevonQui** [comment]
@samreid checked this in master and the issue has been resolved.

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
Looks good in rc.2
