### ISSUE TITLE
Labels and Values have different sized pointer areas on the two screens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#661]
For https://github.com/phetsims/QA/issues/605. Very minor issue and appears in published version. Feel free to close.

The pointer areas for the Labels and Values checkboxes extend towards the end of the box they are in. However, even though the box itself seems to be the same width between screens, the pointer area on the first screen is shorter than the second screen.

![difpointarea](https://user-images.githubusercontent.com/41024075/107563982-f7b87d80-6b9e-11eb-9fe8-470d346f187b.gif)

**Comment by arouinfar** [comment]
@samreid I'm fine with closing this as wont-fix, but I'll leave it up to you.

**Comment by samreid** [comment]
I don't think this indicates a bug, I don't think it warrants attention for the upcoming CCK work, closing.
