### ISSUE TITLE
Unable to drag fuse slider to end of slider

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#662]
**Test device**
Lovelace
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/605.
When dragging the slider it increments by 1.0, but the arrows go by .1. This means that you can't drag the fuse to it's minimum setting. It stops at 1.0, but it's actual minimum is .5.
This was not an issue in the published version, which seems to be because the published sim increments this value by .5.
**Steps to reproduce**
1. Drag fuse out
2. Select fuse and use slider to try and minimize it's current rating 
3. Use arrows to fully minimize the rating

**Visuals**
![oneorpointfive](https://user-images.githubusercontent.com/41024075/107574234-b4184080-6bab-11eb-81cb-7652b380df1c.gif)

**Comment by arouinfar** [comment]
@samreid let's change the `constrainValue` to 0.5

**Comment by samreid** [comment]
In the commit, I round `constrainValue` to 0.5 instead of 1.  It seems OK on my side.  @arouinfar or @KatieWoe can you please review in master?  If it is OK, please reassign to me so I can cherry pick into the RC.

**Comment by arouinfar** [comment]
Looks good @samreid.

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
Looks good in rc.2
