### ISSUE TITLE
Virtual lab does not have options dialog to switch schematic type

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#663]
**Test device**
Lovelace
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/605. The CCK DC sim has an options dialog in the PhET menu that allows the user to switch between IEEE and IEC. The Virtual Lab version does not have the options dialog. Using the `schematicStandard=iec` query parameter does still work.

**Visuals**
<img width="958" alt="nooptions" src="https://user-images.githubusercontent.com/41024075/107577425-a8c71400-6baf-11eb-8fd3-7e2a523d87a5.png">

**Comment by arouinfar** [comment]
Nice find @KatieWoe! Looks like an oversight to me. @samreid all ac/dc flavors of CCK should have an options dialog for the schematic standard.

**Comment by samreid** [comment]
Thanks for discovering this problem, I corrected it in the commit.  Please review and if everything seems good in master, please reassign to me so that I may cherry pick to the branch.

**Comment by KatieWoe** [comment]
Options menu has been added on master

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
Looks good in rc.2
