### ISSUE TITLE
Conventional arrows break when objects are dragged out of toolbox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#664]
**Test device**
MacBookPro
**Operating System**
Mac 10.15
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/605.
When you have a circuit going, and you drag a new object out of the toolbox, the conventional arrows disappear. If you click on the battery the arrows will return, but will also appear on objects they shouldn't that aren't on a circuit.
Does not seem to happen in published.
**Steps to reproduce**
1. Build a simple circuit with wires, a lightbulb, and a battery
2. Switch to conventional arrows
3. Drag a resistor, switch, or other object out of the toolbox. Drop it in the play area but not on the circuit
4. Click the battery

**Visuals**
![conventionarrowsoff](https://user-images.githubusercontent.com/41024075/107585098-d82f4e00-6bba-11eb-820f-f50d077eee30.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-rc.1/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.2.0-rc.1 2021-02-03 23:24:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This does not seem to happen with the voltmeter or the single point ammeter. The in-circuit ammeter does cause this bug.

**Comment by KatieWoe** [comment]
Sometimes touching the battery may not bring the arrows back, but other interactions might.

**Comment by samreid** [comment]
I committed a proposed fix, @KatieWoe can you please test in master?  If it checks out, please reassign to me to cherry pick to the RC.

**Comment by KatieWoe** [comment]
Looks fixed from what I see on master

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
Looks good in RC.2
