### ISSUE TITLE
Update DC & DC-VL screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#665]
For #616 

There have been enough visual changes and new features to warrant new screenshots. These will need to be cherry-picked into the current release branch (sorry I didn't think of this sooner @samreid). 

Self-assigning to update the screenshots.

**Comment by arouinfar** [comment]
> These will need to be cherry-picked into the current release branch

Nevermind, I can commit them directly to master and the release branch.

**Comment by arouinfar** [comment]
@samreid I updated the screenshots in master and the 1.2 branches in the above commits. I think that should take care of things, but in case there's something else that needs to be done, I'll pass this off to you.

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610

**Comment by KatieWoe** [comment]
Screenshots look good and seem to be in the right folders
