### ISSUE TITLE
There should be no sound on the home screen icons or other joist parts

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#668]
Check that https://github.com/phetsims/joist/issues/680 is corrected in the patched RC.

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
I only seem to get sound with the dog bark
