### ISSUE TITLE
Joist touch up issue should be corrected

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#669]
From https://github.com/phetsims/joist/issues/658#issuecomment-772811567, we need to make sure it is corrected in next RC.

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
Looks good in rc.2
