### ISSUE TITLE
The next RCs should have the Android fixes

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#670]
From https://github.com/phetsims/phet-android-app/issues/155, the next RC's should work in Android

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
Looks ok using link in https://github.com/phetsims/QA/issues/608
