### ISSUE TITLE
Performance differences in published and current rc

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/circuit-construction-kit-common#673]
This is for https://github.com/phetsims/QA/issues/610, seen on Win10 Firefox. 

I noticed that when the batteries are current-overloaded on this rc (the battery is on fire), the performance gets substantially laggy, but on published it seems to work fine. On published, the current/electrons stop moving when you move the wires around and they don't in this rc, which seems to help the problem. 

Let me know if you need visuals for the difference in performance. On the 1.2 rc2 the lag is noticeable but the sim is usable, on published there is little to no lag.

**Comment by arouinfar** [comment]
> On published, the current/electrons stop moving when you move the wires around and they don't in this rc, which seems to help the problem.

Was this an intentional deviation @samreid?  Seems like we should be pausing the current representation when dragging components, like we used to do.

**Comment by samreid** [comment]
> On published, the current/electrons stop moving when you move the wires around and they don't in this rc, which seems to help the problem.

I compared published (1.1.5) to master and it seems the electrons have the same behavior when dragging.  Can you please confirm or let me know if I'm missing something?

**Comment by arouinfar** [comment]
@samreid I feel a bit crazy right now. I took latest (1.1.5) and 1.0.0 for a drive (macOS 10.15.7 Chrome/Safari) and I'm not seeing the current pause when elements are dragged. However, I have specific memories of the current pausing, and I know we must have talked about this before because the teacher tips say:

> The current animation will pause while a circuit element is dragged.

Regardless, this sounds serious to me:
> I noticed that when the batteries are current-overloaded on this rc (the battery is on fire), the performance gets substantially laggy, but on published it seems to work fine.

I have access to a Win10 machine, so I'll give it a test and report back.

**Comment by arouinfar** [comment]
@samreid here's the paper trail for the pausing current https://github.com/phetsims/circuit-construction-kit-common/issues/147

**Comment by samreid** [comment]
In #147 we decided to reset the phase of the electrons on each drag event.  That is what is happening in both master and the published version.  The effect is that if you smoothly and continuously drag the wire, the electrons will not move.  This also means if you drag very slowly (so that there are periods of time where the circuit isn't moving at all), then the electrons will stutter--move a little and reset on next drag event.  We have not investigated a pattern that would pause circuit movement on mouseDown/touchDown and resume it on release.

**Comment by arouinfar** [comment]
Thanks for the clarification about #147 @samreid. I do see a slight pause if I've reached the animation speed limit, so perhaps that's what I was thinking of.

> I have access to a Win10 machine, so I'll give it a test and report back.

Well, I couldn't get the sim to load in Firefox (never progressed past the splash screen), and I didn't have time to troubleshoot. Given the amount of QA testing, I'm inclined to believe this is an issue with the particular machine or Firefox settings, but here are the console messages.
![image](https://user-images.githubusercontent.com/8419308/109037406-e9cb2800-7687-11eb-8100-c5d953dbf5b7.png)

Without seeing how bad the lag is, it's hard to decide if this is blocking. @brooklynlash can you please share some screencaptures showing rc.2 and the latest published version?

**Comment by samreid** [comment]
I marked as "blocks sim publication" since it seems we shouldn't publish the RC until we know more about this problem.

**Comment by arouinfar** [comment]
Co-assigning @KatieWoe since this is the only issue that determines if CCK needs another round of testing or not.

**Comment by KatieWoe** [comment]
The failure in https://github.com/phetsims/circuit-construction-kit-common/issues/673#issuecomment-785230759 worries me much more than the performance, but I'm stumped as to how it happened. @arouinfar do you want to pair at some point to see if we can track it down?

**Comment by kathy-phet** [comment]
> We have not investigated a pattern that would pause circuit movement on mouseDown/touchDown and resume it on release.

This seems like a more robust solution.

**Comment by KatieWoe** [comment]
May look like https://github.com/phetsims/installer-builder/issues/107?

**Comment by samreid** [comment]
@arouinfar do you see the `runWeback` bug on any other PhET simulations on your Win/Firefox?

**Comment by arouinfar** [comment]
The problematic Win10/Firefox device is my husband's work computer, so I can't really commandeer it right now. He was able to open a few sims at random from the website (Equality Explorer and Gravity Force Lab), but several others are failing to load
![image](https://user-images.githubusercontent.com/8419308/109074299-d2eefa80-76b4-11eb-90eb-70f2434390b9.png)
![image](https://user-images.githubusercontent.com/8419308/109074316-d6828180-76b4-11eb-81f3-9eca85fac894.png)
![image](https://user-images.githubusercontent.com/8419308/109074321-da160880-76b4-11eb-94de-e932985ded06.png)

The yellow warning at the top related to Google Analytics doesn't seem to be the problem. If you click the shield button on the left side of the address bar and turn off the "Enhanced Tracking Protection", the warning disappears from the console, but the sim still fails to load.

**Comment by KatieWoe** [comment]
That is very concerning.

**Comment by brooklynlash** [comment]
@arouinfar regarding the lag on Firefox, I was not able to replicate it today with the same devices and same steps I used yesterday, which I think is odd, but I agree it is probably machine-dependent. I am not sure what you want for the screencaps but I can send whatever you need from my device.

**Comment by arouinfar** [comment]
Thanks @brooklynlash!  I dug up an old laptop, and didn't see any noticeable difference in performance in rc.2 and latest in Win10/Firefox, so I think we can close this issue.

I can move the failed sim-loading comments to another issue. @samreid can you recommend a repo? Since it's happening to published sims, I don't see why it would block the release of CCK.

**Comment by samreid** [comment]
Scenery has this code which looks related to the stack trace:

```js
  addRule( ruleString ) {
    // using a this reference so it doesn't need to be a closure
    this.stylesheet.insertRule( ruleString, 0 );
  }
```

So scenery seems like a good repo for this.

**Comment by samreid** [comment]
I opened https://github.com/phetsims/scenery/issues/1216, closing.
