### ISSUE TITLE
Pause the flow of electrons in a circuit on touch/mouse down and resume on up

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#674]
From https://github.com/phetsims/circuit-construction-kit-common/issues/673#issuecomment-785408131

I said:

> We have not investigated a pattern that would pause circuit movement on mouseDown/touchDown and resume it on release.

@kathy-phet replied:

> This seems like a more robust solution.

Should this be implemented for DC (the current release), or for the upcoming AC release?  Is it important that only the electrons in the circuit connected to the dragged element pause, or would it be OK or preferable to pause all electrons on drag (may be simpler)?

**Comment by arouinfar** [comment]
I don't know that I would invest any resources into this. It's currently being floated as a potential solution to a problem that we don't even know the severity of.

**Comment by arouinfar** [comment]
Since https://github.com/phetsims/circuit-construction-kit-common/issues/673#issuecomment-785447540 and https://github.com/phetsims/circuit-construction-kit-common/issues/673#issuecomment-785454672 failed to replicate the reported performance issue that lead to this idea, I'm going to close.
