### ISSUE TITLE
Strange pointer area for AC power source?

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-common#675]
I was playing with the sim, and realized it was a bit hard to touch the AC power source when using the "schematic" view. This doesn't happen in the lifelike view.

Here is a screenshot. Note the touch area in the top right only:

![image](https://user-images.githubusercontent.com/6856943/109190863-062b9b00-7742-11eb-9560-a9c4f16235a8.png)

**Comment by samreid** [comment]
Proposed fix in the commit, thanks for reporting this problem @zepumph, closing.
