### ISSUE TITLE
How to manage phase locking for separate AC sources?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#678]
From https://github.com/phetsims/circuit-construction-kit-common/issues/643 and related to https://github.com/phetsims/circuit-construction-kit-common/issues/622#issuecomment-749814222.

@arouinfar said:

> @samreid I didn't see any issues with the phase of the voltage charts, but I did run into an issue with the current sign. I created two simple AC circuits (AC source + default resistor) and the current charts showed opposite polarities. The circuits were otherwise identical.

@samreid replied:

Thanks for the report @arouinfar, I was able to reproduce this problem:

![image](https://user-images.githubusercontent.com/679486/104265085-10bbfa80-544a-11eb-8050-2f8810ea4293.png)

This problem occurs because the sign "sense" or directionality of the current is chosen when the circuit is closed.  If you complete the 2nd circuit when the 1st circuit is positive, they will have the same sense:

![image](https://user-images.githubusercontent.com/679486/104265163-3943f480-544a-11eb-825e-3c984222c94d.png)

We may be constrained about how we determine the current sign based on the solution in https://github.com/phetsims/circuit-construction-kit-common/issues/622#issuecomment-749814222.  @arouinfar can you please advise?

**Comment by samreid** [comment]
@arouinfar volunteered to discuss this with MD at their upcoming meeting.

**Comment by samreid** [comment]
@kathy-phet recommended that when current directionality is chosen for the 2nd circuit, match it with pre-existing AC sources.  I'll give it a try!

**Comment by samreid** [comment]
I tested this patch, but it didn't have the desired behavior:

```js
      // if there is an ac voltage source (other than this), use that to phase match the ac voltage sources.
      const otherACVoltageSources = circuit.acVoltageGroup.filter( ac => ac !== this );
      if ( otherACVoltageSources.length > 0 ) {
        this.isInitialCurrentNegative = otherACVoltageSources[ 0 ].isInitialCurrentNegative;
      }
      else {
        this.isInitialCurrentNegative = current < -epsilon ? true :
                                        current > epsilon ? false :
                                        null;
      }
```

Also, even before making this change, I observed that the current signs are not all consistent.  Going around the corner I saw the sign flip:

![image](https://user-images.githubusercontent.com/679486/127795589-ad1be0ec-2918-42de-b29c-123f4bdb3810.png)

**Comment by samreid** [comment]
Second patch:

<details>

```diff

Index: js/view/CircuitLayerNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/CircuitLayerNode.js b/js/view/CircuitLayerNode.js
--- a/js/view/CircuitLayerNode.js	(revision 557641ac9383edfc9a71501c112b9d2ea131db7b)
+++ b/js/view/CircuitLayerNode.js	(date 1629317678543)
@@ -265,7 +265,7 @@
 
           // Show the ValueNode for readouts, though series ammeters already show their own readouts and Wires do not
           // have readouts
-          if ( circuitElement instanceof FixedCircuitElement && !( circuitElement instanceof SeriesAmmeter ) ) {
+          if ( true || circuitElement instanceof FixedCircuitElement && !( circuitElement instanceof SeriesAmmeter ) ) {
             const valueNode = new ValueNode(
               circuit.sourceResistanceProperty,
               circuitElement,
Index: js/view/ValueNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/ValueNode.js b/js/view/ValueNode.js
--- a/js/view/ValueNode.js	(revision 557641ac9383edfc9a71501c112b9d2ea131db7b)
+++ b/js/view/ValueNode.js	(date 1629318246766)
@@ -73,7 +73,19 @@
 
     let contentNode = null;
     let updatePosition = null;
-    if ( circuitElement instanceof VoltageSource ) {
+    if ( true ) {
+      contentNode = createText( tandem.createTandem( 'resistanceText' ) );
+
+      // Items like the hand and dog and high resistance resistor shouldn't show ".0"
+      const linkCurrent = current => {
+        contentNode.text = current.toFixed( 6 ) + '' + ( circuitElement.isInitialCurrentNegative ? ' REV' : '' );
+        updatePosition && updatePosition();
+      };
+      circuitElement.currentProperty.link( linkCurrent );
+      disposeEmitterValueNode.addListener( () => circuitElement.currentProperty.unlink( linkCurrent ) );
+      contentNode.maxWidth = 200;
+    }
+    else if ( circuitElement instanceof VoltageSource ) {
 
       const voltageText = createText( tandem.createTandem( 'voltageText' ) );
       const voltageListener = voltage => {
Index: js/model/CircuitElement.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/CircuitElement.js b/js/model/CircuitElement.js
--- a/js/model/CircuitElement.js	(revision 557641ac9383edfc9a71501c112b9d2ea131db7b)
+++ b/js/model/CircuitElement.js	(date 1629318148519)
@@ -232,9 +232,30 @@
 
     // Take an initial current sign, but avoid measuring noise from the matrix solves in disconnected circuits
     if ( this.isInitialCurrentNegative === null ) {
+      console.log( 'taking sign' )
+
+      // if there is an ac voltage source (other than this), use that to phase match the ac voltage sources.
+      const otherACVoltageSources = circuit.acVoltageGroup.filter( ac => ac !== this );
+
+      // choose orientation so that the current is positive by default
       this.isInitialCurrentNegative = current < -epsilon ? true :
                                       current > epsilon ? false :
                                       null;
+
+      console.log( 'default ' + this.isInitialCurrentNegative );
+      console.log( otherACVoltageSources.length );
+
+
+      // However, if there is an AC source that is currently running negative, then flip the sign.
+      if ( otherACVoltageSources.length > 0 ) {
+        const rootSource = otherACVoltageSources[ 0 ];
+        console.log( rootSource.currentProperty.value < 0 );
+
+        if ( ( !rootSource.isInitialCurrentNegative && rootSource.currentProperty.value < 0 ) ||
+             ( rootSource.isInitialCurrentNegative && rootSource.currentProperty.value > 0 ) ) {
+          this.isInitialCurrentNegative = !this.isInitialCurrentNegative;
+        }
+      }
     }
     else if ( isReadyToClear ) {
 

```

</details>

**Comment by samreid** [comment]
After the commits, the behavior is as desired, and I haven't seen any discontinuities in my testing.  I think I should describe the proposed algorithm so that @arouinfar can help me think of (or test for) corner cases where it may have the wrong behavior.

All Circuit Elements start out with `currentSense: UNSPECIFIED`.  When any Circuit Element's current (absolute value) exceeds a threshold of `SENSE_TOLERANCE = 1E-6`, we determine its sense like so:

1. If there are no other Circuit Elements with a specified sense, choose its sense for the UNSPECIFIED Circuit Element so that the current is positive.  This matches our prior behavior.
2. If there is any other Circuit Element with a specified sense, choose the sense for the UNSPECIFIED Circuit Element so that its overall sign matches the overall sign of another Circuit Element.

This is accomplished via the two methods:

```js
    if ( this.currentSense === CurrentSense.UNSPECIFIED ) {

      // If there are other circuit elements, match with them.
      const otherCircuitElements = circuit.circuitElements.filter( c => c !== this && c.currentSense !== CurrentSense.UNSPECIFIED );
      if ( otherCircuitElements.length === 0 ) {

        // If this is the first circuit element, choose the current sense so the initial readout is positive
        this.currentSense = getSenseForPositive( current );
      }
      else {

        const rootElement = otherCircuitElements[ 0 ];

        const desiredSign = rootElement.currentProperty.value >= 0 && CurrentSense.FORWARD ? 'positive' :
                            rootElement.currentProperty.value >= 0 && CurrentSense.BACKWARD ? 'negative' :
                            rootElement.currentProperty.value < 0 && CurrentSense.FORWARD ? 'negative' :
                            rootElement.currentProperty.value < 0 && CurrentSense.BACKWARD ? 'positive' :
                            'error';

        assert && assert( desiredSign !== 'error' );
        this.currentSense = desiredSign === 'positive' ?
                            getSenseForPositive( current ) :
                            getSenseForNegative( current );
      }
    }
    else if ( isReadyToClear ) {

      // Reset directionality, and take new directionality when current flows again
      this.currentSense = CurrentSense.UNSPECIFIED;
    }
```

```js
const getSenseForPositive = current => current < -SENSE_TOLERANCE ? CurrentSense.BACKWARD :
                                       current > SENSE_TOLERANCE ? CurrentSense.FORWARD :
                                       CurrentSense.UNSPECIFIED;
const getSenseForNegative = current => current < -SENSE_TOLERANCE ? CurrentSense.FORWARD :
                                       current > SENSE_TOLERANCE ? CurrentSense.BACKWARD :
                                       CurrentSense.UNSPECIFIED;
```

@arouinfar can you please take a close look at these notes, and test several scenarios to see if the behavior is as desired?

**Comment by arouinfar** [comment]
@samreid this approach sounds reasonable, and things have generally been looking really good in master.

The only thing that seems a bit off is that the sign of the current and the direction of electron flow differ for AC and DC circuits. For example:
1. Build a simple DC circuit with a default battery, default resistor, and two wires. 
2. Measure the current with the Current Chart. The sign is positive and the electrons travel clockwise through the circuit.
3. Build a simple AC circuit as in (1) but with a default AC source.
4. Measure the current with the Current Chart. The sign is negative when electrons travel clockwise through the circuit.

**Comment by samreid** [comment]
I don't think we can use clockwise/anticlockwise as a factor here since the direction is arbitrary.  For instance, a clockwise circuit can be changed to an anticlockwise circuit without changing its topology:

![Kapture 2021-08-20 at 14 37 52](https://user-images.githubusercontent.com/679486/130290935-5d9f52eb-c0b8-4ac9-a621-24f14a3e7cbb.gif)

But I'm also not sure that I'm understanding the recommendation or problem.  @arouinfar can you please comment?

**Comment by arouinfar** [comment]
> I don't think we can use clockwise/anticlockwise as a factor here since the direction is arbitrary. 

You're absolutely right @samreid. I think what threw me off was that I built two similar-looking circuits (like the ones below) and the currents moved in opposite directions, but it's not an apples-to-apples comparison.
<img src="https://user-images.githubusercontent.com/8419308/130556357-cbf6a128-faf6-47d0-8487-aff545d44c52.png" width=200>

**Comment by samreid** [comment]
Would it help to switch the default phase of the ac sources?

**Comment by samreid** [comment]
In the commit, I changed the sign of the AC voltage source, and now it moves clockwise by default (like the standard battery).  Can you please review?  Please close if all is well.

**Comment by arouinfar** [comment]
Thanks @samreid! It looks good in master. 

> Please close if all is well.

Should we have QA test to see if they can find any issues with the polarity of the current? If not QA, perhaps @ariel-phet can take a look.

**Comment by samreid** [comment]
Yes, I'll add to the QA issues to test.  To test this issue, please test the case in the top comment, keeping in mind that the time of attachment (of the 2nd circuit) affects the result.  Please test a variety of circuits, checking for anything unusual about the current direction.  Note that the ammeter only reads the absolute value of current, and the charts are needed to see the current sign.  Please also check for any discontinuities, where the current changes sign as you move the probe from one component to the next.

**Comment by samreid** [comment]
Also tagging for design meeting to review the proposed solution in https://github.com/phetsims/circuit-construction-kit-common/issues/678#issuecomment-902784120

**Comment by KatieWoe** [comment]
So far I've found one oddity that I'm not sure if it is a problem or not. If you are dragging an element of the circuit while it is running, even if it doesn't impact the current, the electrons' visible current jumps around, though the current tool stays steady.
![movepiecesoddcurrent](https://user-images.githubusercontent.com/41024075/130832200-ea0d9a94-f6e6-4376-a06d-615bb229de4f.gif)

**Comment by samreid** [comment]
I reached out to @zepumph for help on this.  We'll schedule a meeting.

**Comment by samreid** [comment]
@zepumph and I worked on this today, and we observed that in creating a battery resistor circuit like so, then flipping the battery, the battery current readout doesn't change, but the resistor and wire currents do change sign:

![image](https://user-images.githubusercontent.com/679486/131709729-a8bfe5d2-7f8d-4549-a6c0-c03fd87f4010.png)

This is with the simplified code that only chooses things to be positive on their first nonzero current:

<details>

```diff

Index: js/model/CircuitElement.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/CircuitElement.js b/js/model/CircuitElement.js
--- a/js/model/CircuitElement.js	(revision 855d9628903e99a373bafb33521ef2e8519dce91)
+++ b/js/model/CircuitElement.js	(date 1630513871838)
@@ -92,6 +92,11 @@
       reentrant: options.isCurrentReentrant
     } );
     this.currentProperty.link( c => {
+
+      if ( this.constructor.name === 'Battery' ) {
+        console.log( c );
+      }
+
       assert && assert( !isNaN( c ) );
     } );
 
@@ -235,33 +240,43 @@
 
     if ( this.currentSense === CurrentSense.UNSPECIFIED ) {
 
-      // If there are other circuit elements, match with them.
-      const otherCircuitElements = circuit.circuitElements.filter( c => c !== this && c.currentSense !== CurrentSense.UNSPECIFIED );
-      if ( otherCircuitElements.length === 0 ) {
-
-        // If this is the first circuit element, choose the current sense so the initial readout is positive
-        this.currentSense = getSenseForPositive( current );
-      }
-      else {
-
-        const rootElement = otherCircuitElements[ 0 ];
-
-        const desiredSign = rootElement.currentProperty.value >= 0 && CurrentSense.FORWARD ? 'positive' :
-                            rootElement.currentProperty.value >= 0 && CurrentSense.BACKWARD ? 'negative' :
-                            rootElement.currentProperty.value < 0 && CurrentSense.FORWARD ? 'negative' :
-                            rootElement.currentProperty.value < 0 && CurrentSense.BACKWARD ? 'positive' :
-                            'error';
+      this.currentSense = getSenseForPositive( current );
 
-        assert && assert( desiredSign !== 'error' );
-        this.currentSense = desiredSign === 'positive' ?
-                            getSenseForPositive( current ) :
-                            getSenseForNegative( current );
+      if ( this.constructor.name === 'Battery' ) {
+        console.log( this.currentSense );
       }
+
+      // // If there are other circuit elements, match with them.
+      // const otherCircuitElements = circuit.circuitElements.filter( c => c !== this && c.currentSense !== CurrentSense.UNSPECIFIED );
+      // if ( otherCircuitElements.length === 0 ) {
+      //
+      //   // If this is the first circuit element, choose the current sense so the initial readout is positive
+      //
+      // }
+      // else {
+      //
+      //   const rootElement = otherCircuitElements[ 0 ];
+      //
+      //   const desiredSign = rootElement.currentProperty.value >= 0 && CurrentSense.FORWARD ? 'positive' :
+      //                       rootElement.currentProperty.value >= 0 && CurrentSense.BACKWARD ? 'negative' :
+      //                       rootElement.currentProperty.value < 0 && CurrentSense.FORWARD ? 'negative' :
+      //                       rootElement.currentProperty.value < 0 && CurrentSense.BACKWARD ? 'positive' :
+      //                       'error';
+      //
+      //   assert && assert( desiredSign !== 'error' );
+      //   this.currentSense = desiredSign === 'positive' ?
+      //                       getSenseForPositive( current ) :
+      //                       getSenseForNegative( current );
+      // }
     }
     else if ( isReadyToClear ) {
 
       // Reset directionality, and take new directionality when current flows again
       this.currentSense = CurrentSense.UNSPECIFIED;
+
+      if ( this.constructor.name === 'Battery' ) {
+        console.log( this.currentSense );
+      }
     }
   }
 

```

</details>

**Comment by samreid** [comment]
We also observed that with that patch, flipping a 2nd battery sometimes yields a blip in the curve:

![image](https://user-images.githubusercontent.com/679486/131709955-f62ab2e2-4af5-4d68-bc45-cb0b88d7b432.png)

**Comment by samreid** [comment]
@zepumph and I added a fix that solved the two preceding problems.  However, it did not help us with the primary problem for this issue.

**Comment by samreid** [comment]
We identified that we cannot have each component keep their sense even when disconnected--it leads to discontinuities.  @zepumph and I will continue to work on the known discontinuities and phase offsets.

**Comment by samreid** [comment]
@kathy-phet pointed out she sees problems with the AC source having the wrong sign.

**Comment by samreid** [comment]
I added more visual debugging tools with ?showCurrents, then @zepumph and I worked on this.  We solved several upstream problems and streamlined the implementation where we think the problem is.  We discovered that connecting a circuit when the AC source has a negative value gave a discontinuous reading.  Then I discovered a type error, which was fixed in the commit.  After fixing the type error, the behavior is fixed for the negative AC case.  I ran several tests where I made connections and different signs for the current, and everything was in phase.

![image](https://user-images.githubusercontent.com/679486/133503224-f90c39a1-a61d-47fb-8d38-190122604820.png)

@KatieWoe can you please test this out?

**Comment by KatieWoe** [comment]
These instances seem to be fixed in that dev version from what I can tell

**Comment by samreid** [comment]
In slack @KatieWoe said:

> For https://github.com/phetsims/circuit-construction-kit-common/issues/678, should I look for more examples?

I replied:

> I don’t think that’s necessary--as long as we keep our eyes peeled as we continue other testing. 

Closing.
