### ISSUE TITLE
Why isn't the stopwatch in the toolbox?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#680]
Noted while working on https://github.com/phetsims/scenery-phet/issues/659.

Sims that have a toolbox put the stopwatch in that toolbox: capacitor-lab-basics, energy-skate-park, masses-and-springs, wave-interference, wave-on-a-string.

Sims that don't have a toolbox control the stopwatch visibility with a checkbox: gas-properties, pendulum-lab

CCK doesn't follow this convention. It has a toolbox, but controls the stopwatch via a checkbox.  Why isn't the stopwatch in the toolbox?

**Comment by samreid** [comment]
This question seems best for @arouinfar.

**Comment by arouinfar** [comment]
In early iterations of the mockups, the stopwatch was in the toolbox. However, there really isn't much room for it. We could perhaps squeeze it into the bottom row but we would need to reduce the icon sizes and the label strings would be a bit cramped which is not great for i18n. 

The function of the stopwatch is also different than other tools. It doesn't directly measure anything within the circuit, while the others do.
