### ISSUE TITLE
PhET-iO Design: Add a "Power" derived property for resistive elements

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#681]
A researcher requested to have a measure of the bulb "brightness". Basically this comes down to having a derived power property associated with each resistive element as either P=|I(deltaV)| or P=I^2*R or P=(delta V)^2/R  whichever is easiest to calculate for the resistive elements in the sim. 

Is it possible to attach this property to the iO group archtype?

**Comment by samreid** [comment]
It seems like the best way to address this would be to move the `resistanceProperty` into `CircuitElement`.  Right now it is duplicated in many subclasses, but it seems all CircuitElements have a `resistanceProperty` now, even if the value is 0.  Then we could use that and the current to derive the power.

**Comment by arouinfar** [comment]
> A researcher requested to have a measure of the bulb "brightness". Basically this comes down to having a derived power property

Yes and no... the brightness is proportional to the power, but there is a ceiling at 2000 W, so we should be sure to make this clear in to the client (either in phetio documentation or a client guide).

> It seems like the best way to address this would be to move the resistanceProperty into CircuitElement. Right now it is duplicated in many subclasses, but it seems all CircuitElements have a resistanceProperty now, even if the value is 0. Then we could use that and the current to derive the power.

This approach sounds good to me @samreid.

**Comment by samreid** [comment]
The brightness for the bulb line display is computed as:

```js
const toBrightness = ( multiplier, power ) => {
  const maximumBrightness = 1;

  // power at which the brightness becomes 1
  const maximumPower = 2000;
  return Math.log( 1 + power * multiplier ) * maximumBrightness / Math.log( 1 + maximumPower * multiplier );
};
```

with `multiplier=0.35`

But the view also has a NumberProperty indicating the brightness.  In addition to the plan described in the preceding comments, should we also instrument the `brightnessProperty` itself?  Right now it is in the view side.

**Comment by samreid** [comment]
At today's meeting, we agreed the clients don't need an explicit instrumented property for the bulb brightness.

**Comment by rollcode** [comment]
Thanks @samreid . Does this mean that it will not be in i/o (no problem), or also that it will not be visible to the student? Thanks.

**Comment by samreid** [comment]
This issue is about instrumenting features for PhET-iO and will not change the student-facing user experience.

**Comment by samreid** [comment]
> But the view also has a NumberProperty indicating the brightness. In addition to the plan described in the preceding comments, should we also instrument the brightnessProperty itself? Right now it is in the view side.

From today's meeting, we will add the power `derivedProperty` but not instrument the `brightnessProperty`.

**Comment by samreid** [comment]
> It seems like the best way to address this would be to move the resistanceProperty into CircuitElement. Right now it is duplicated in many subclasses, but it seems all CircuitElements have a resistanceProperty now, even if the value is 0. 

That is incorrect. Capacitors and inductors do not have a resistanceProperty at the moment.  I looked at factoring out a `ResistiveCircuitElement` property, but this is incompatible with our type hierarchy because we must have `Wire extends ResistiveCircuitElement` and `Fuse extends FixedCircuitElement` but `Capacitor extends FixedCircuitElement`.  Without mixins, I don't see a place to factor out the resistance.  But ideal capacitors and inductors actually have 0 resistance, so maybe it would be OK to add that?  Perhaps I'll proceed with adding it directly in CircuitElement.

**Comment by samreid** [comment]
@arouinfar and I discussed this today, and we saw many different `resistanceProperty` values across different circuit elements, used in different ways.  Some behaving like derived properties, etc.

We saw that Capacitors and Inductors have an internal resistance of 1E-4.

We discussed leaving things as they are, but adding `powerProperty` to resistors and light bulbs. But it seems we need to check with @kathy-phet first.

**Comment by samreid** [comment]
I wrote on slack:

> @kathy I discussed https://github.com/phetsims/circuit-construction-kit-common/issues/681 with @arouinfar and we would like your feedback.  It wasn’t clear we should add resistanceProperty and hence powerProperty to all CircuitElements as we had planned, since we weren’t sure we wanted that for Capacitors, Inductors, etc.  Should we just add powerProperty to some CircuitElements, like LightBulb, Resistor, Battery?

**Comment by samreid** [comment]
I added powerProperty for LightBulbs, Resistors (includes grab bag elements) and Batteries.  I was getting different answers for batteries computing P=IV vs `I*I*R`.  The P=IV values seemed too high whether I used `voltageProperty` or `voltageDifferenceProperty`, and it was simplest to use one computation factored out, so I used `I*I*R` for the battery as well.  @arouinfar can you please review and test?

**Comment by kathy-phet** [comment]
Hi Sam, 
Actually P=IV is what I am thinking here... where in this case it is not power consumed from resistive part of battery, but power SUPPLIED" by the battery. So P=I*(voltage of the battery). It should add to the power used by any lightbulbs used in the circuit.

**Comment by samreid** [comment]
I wrote in slack:

> @arouinfar and I are discussing https://github.com/phetsims/circuit-construction-kit-common/issues/681 and it’s unclear how you want to treat the internal resistance of the battery.  It can go up to 10 ohms internal resistance, so it cannot be neglected.  Do you want a powerGeneratedProperty and a powerDissipatedProperty and a netPowerProperty?  We are on zoom design link if you want to chat.

**Comment by samreid** [comment]
In discussion, @kathy-phet recommended that for resistors, light bulbs and batteries would have: `powerDissipatedProperty`.  For batteries, we would add `powerGeneratedProperty` which is P=IV.

**Comment by samreid** [comment]
Fixed, and reviewed together.  Closing.
