### ISSUE TITLE
Change Battery Resistance Slider lower limit to "Tiny"

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#683]
If we keep a default battery resistance as 1e-6, then we need to change the lower limit of the slider to read "tiny".

**Comment by arouinfar** [comment]
@samreid looks good in master!

> I used the same "tiny" string as for the wire resistivity, but could decouple those if we think some language will want to use different terminology. 

 Good call. I don't see any reason to decouple them.

**Comment by phet-steele** [comment]
Looks good in phetsims/QA/issues/633!
