### ISSUE TITLE
When the battery resistance is set to "Tiny", then there should be no resistance readout on the battery

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#685]
When the battery resistance is set to "Tiny", then there should be no resistance readout on the battery.

This should be part of the upcoming cherry-picking.  Related to #683

**Comment by samreid** [comment]
Fixed, @arouinfar or @kathy-phet can you spot check?

**Comment by arouinfar** [comment]
Looks good in master @samreid

**Comment by phet-steele** [comment]
Looks good in phetsims/QA/issues/633
