### ISSUE TITLE
There is an extra odd tick mark in the center of the battery resistance control

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#686]
There is an extra odd tick mark in the center of the battery resistance control
![image](https://user-images.githubusercontent.com/679486/112535842-5cf0b880-8d72-11eb-9890-16b86483294e.png)

**Comment by samreid** [comment]
Double check the tick marks--maybe something was neglected when we changed "0" to "tiny".

**Comment by arouinfar** [comment]
@samreid I'm not seeing the odd tick marks in master
![image](https://user-images.githubusercontent.com/8419308/112910202-1f609800-90b0-11eb-8120-4a097182197b.png)

**Comment by samreid** [comment]
I also can no longer see the problem in master.  The most likely hypothesis is that it was during a test where we temporarily put the battery voltage to be 1 for testing, so the range was 1-10 instead of ~0 - 10.  Still, I see a potential numerical error which I will commit while I'm here.

**Comment by samreid** [comment]
Fixed, closing.

**Comment by samreid** [comment]
This does not need to be cherry-picked.
