### ISSUE TITLE
Wire Resistance: Lots should match published version

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#688]
@samreid - It looks like the wire resistivity on the "lots" end of the scale is much lower now than the published version. Ideally, that end would match the published version for resistivity, and its just the "tiny" side would be the new lower value of resistivity. Can you do that? 

I tested this rc: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.2-rc.1/phet/circuit-construction-kit-dc_en_phet.html

https://github.com/phetsims/QA/issues/633

**Comment by samreid** [comment]
Fixed in master and in the branches, the problem was that max resistivity was a multiple of min resistivity, I've decoupled them and taken the former max value.  Ready for QA.

**Comment by phet-steele** [comment]
Looks good in phetsims/QA/issues/633.
