### ISSUE TITLE
Values update when sim is paused after objects are grabbed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#699]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/646. Fairly minor.
The voltage value of the AC source changes with time. If you pause the sim and change an aspect of the source that would alter that value at a given time (such as frequency, voltage, or phase) it will stay at the previous value until you step forward or press play. However, if you drag another item, either out of the toolbox or just around the play area, the value of the changed source jumps to the new value.
**Steps to reproduce**
1. Pause the sim
2. Drag out two AC sources
3. Check the box to show values.
4. Change the frequency of one of the sources
5. Drag out another object and observe

**Visuals**
![dragupdate](https://user-images.githubusercontent.com/41024075/117510708-c9ea9700-af49-11eb-9c81-7a8a85f0d8b3.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.15/phet/circuit-construction-kit-ac_en_phet.html
Version: 1.0.0-dev.15 2021-04-30 16:33:26 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
It seems better to mark the circuit dirty when the characteristics of the ac voltage source changes.  This led me to discover that other circuit elements specify `getCircuitProperties` but `ACVoltage` does not.  Once I supplied that, the Voltage readout correctly updates when the voltage or frequency changes.  I noticed one other circuit element with a missing circuit property, I'll add it too.

**Comment by KatieWoe** [comment]
This seems to be the case on master

**Comment by samreid** [comment]
Thanks for testing, closing.
