### ISSUE TITLE
Emit alignProbesEmitter when probes are added

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#701]
From https://github.com/phetsims/circuit-construction-kit-common/issues/672, @jonathanolson asked:

```js
    // @public - emits when the probes should be put in standard relative position to the body
    // REVIEW: I see this called in subtypes after adding probes, could this be emitted then to obviate that need?
    this.alignProbesEmitter = new Emitter();
```

**Comment by samreid** [comment]
I removed the subclass calls to the emitter, and instead changed lazyLink to a link so the callback will happen when probes are added.  Ready for review.

**Comment by jonathanolson** [comment]
Looks good to me!
