### ISSUE TITLE
What is the convention for naming imported sounds?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#702]
In code review https://github.com/phetsims/circuit-construction-kit-common/issues/672 @jonathanolson asked:

```js
//REVIEW: What is the convention for naming of these?
import dogBarkSound from '../../sounds/dog-bark_mp3.js';
```

**Comment by samreid** [comment]
I don't see an established convention.  Here is a list of some hits for loading MP3 files:

![image](https://user-images.githubusercontent.com/679486/120540684-30769f80-c3a6-11eb-89db-711a99f64fb0.png)

The majority are named with *Sound, others with *Audio, others with sound-specific suffixes.  @jonathanolson how do you recommend to proceed?  Should we open a tambo issue for determining a convention?  Should we make changes for CCK?

**Comment by jonathanolson** [comment]
> Should we open a tambo issue for determining a convention?

I'm personally ok with variability, but it seems like a deviation from how we name images. Do you have a preference? I'm fine closing, or that we create a general issue to discuss.

**Comment by samreid** [comment]
@jbphet can you please advise how to proceed for this issue?  Should we transfer this issue to tambo?

**Comment by zepumph** [comment]
There is not a convention current convention, and we also noticed (and were surprised) that there doesn't seem to be a lint rule guiding our Image import names either.

We think that all variable names for the import should end in `Sound` (of type `WrappedAudioBuffer`). 

We used to have a lint rule for this, and we want it to come back.

Note https://github.com/phetsims/chipper/issues/894 as the discussion of why the lint rule wasn't copied over when converting to es6 modules.


@jessegreenberg volunteered to write a lint rule for this. We also want to have a lint rule that will check this for images, where the var name ends in `Image`. I'll leave it up to @jessegreenberg to decide if this is 1 lint rule or 2, and to create the common code issue if desired. Thanks @jessegreenberg!

**Comment by jessegreenberg** [comment]
I made https://github.com/phetsims/chipper/issues/1060 to create the lint rule. It has been added and the portion that checks for sound imports is working in master now. Images haven't been added yet for reasons described in that issue. Continued dev meeting discussions will happen in that issue so removing this one from the dev meeting project board.

Back to @samreid for this sim specific issue, anything left for this one?

**Comment by samreid** [comment]
There is some commented-out code and references to image files in chipper/eslint/rules/import-resource-variable-suffix.js.  Should that be updated at this time?

**Comment by jessegreenberg** [comment]
Thanks, I added a TODO to the rule describing the commented out code related to image files, left in but unused until we agree on whether we want that in https://github.com/phetsims/chipper/issues/1060#issuecomment-877475545

**Comment by samreid** [comment]
Got it, thanks!  I confirmed the rule is working as desired.  Closing.
