### ISSUE TITLE
Use an enumeration rather than predicates to associate model elements with tools

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#703]
During code review #672 @jonathanolson said:

```js
      //REVIEW: Would we be able to specify an enumeration in the model elements that specifies which tool it corresponds to, instead of using predicates?
      circuitElement => circuitElement instanceof Battery &&
                        circuitElement.initialOrientation === 'right' &&
                        circuitElement.batteryType === Battery.BatteryType.NORMAL,
```

**Comment by samreid** [comment]
I'm on the fence about this recommendation.  My hesitation comes from the numerous types that only require an instanceof check:

```js
circuitElement => circuitElement instanceof Wire,
circuitElement => circuitElement instanceof ACVoltage,
circuitElement => circuitElement instanceof Fuse,
circuitElement => circuitElement instanceof Capacitor,
circuitElement => circuitElement instanceof Inductor,
circuitElement => circuitElement instanceof Switch,
```

I'd rather not create a parallel "circuit element type" enumeration for these types that don't need it, and for the other types, it seems odd to have one way of doing something for half the types and another way for the other half.

@jonathanolson can you please advise?

**Comment by jonathanolson** [comment]
This seems fine, with the note that documentation to ensure that it covers everything AND is mutually exclusive would be good (was hard to tell just with a cursory read).

**Comment by samreid** [comment]
I added documentation in the commit, can you please review?

**Comment by samreid** [comment]
I added the "mutually exclusive" note as prescribed above, it sounds like everything else for this issue is complete.  Please reopen as appropriate.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by samreid** [comment]
I decided to keep the predicate.  It is working well and I don't want to introduce a separate data token that could get out of sync.
