### ISSUE TITLE
Performance testing and sign-off

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#705]
From #672, we need to do performance testing and sign-off

**Comment by samreid** [comment]
Problems were noted in https://github.com/phetsims/circuit-construction-kit-common/issues/696 and I commented in https://github.com/phetsims/circuit-construction-kit-common/issues/696#issuecomment-853316743, not sure what should be done for this publication.  @arouinfar can you please advise?

**Comment by arouinfar** [comment]
I tested a built version of CCK: AC on iPad (Hopper) and Chromebook (Lovelace) and didn't notice any issues other than #696.

<details> <summary> Hopper Troubleshooting Info</summary>

Name:  Circuit Construction Kit: AC 
URL: https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-ac/build/phet/circuit-construction-kit-ac_en_phet.html
Version: 1.0.0-dev.15 2021-08-24 16:07:10 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
Language: en-US
Window: 980x735
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {}
</details>

<details> <summary>Lovelace Troubleshooting Info</summary>

Name:  Circuit Construction Kit: AC 
URL: https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-ac/build/phet/circuit-construction-kit-ac_en_phet.html
Version: 1.0.0-dev.15 2021-08-24 16:46:55 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14092.35.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.51 Safari/537.36
Language: en-US
Window: 1366x649
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 4096
Texture: size: 16384 imageUnits: 32 (vertex: 32, combined: 192)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
Since all known problems are tracked elsewhere, closing.  We can reopen if there is a regression.
