### ISSUE TITLE
Pointer area review

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#706]
From #672, we need to review pointer areas

**Comment by samreid** [comment]
@jonathanolson commented:

> Touch areas in the carousel, and the zoom icons for the charts could potentially be expanded (I can move this to the issue that should be created above when needed).

**Comment by samreid** [comment]
I increased the touch area for chart zoom buttons and some of the round buttons.  @arouinfar can you please see if there is more to do here?

![image](https://user-images.githubusercontent.com/679486/120545181-90237980-c3ab-11eb-8d98-cc1c01b7bf0c.png)

**Comment by arouinfar** [comment]
The pointer areas all look good to me. I didn't notice any touch issues on iPad, either.
