### ISSUE TITLE
stringtest=long needs to be checked

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#707]
From https://github.com/phetsims/circuit-construction-kit-common/issues/672#issuecomment-832185006 @jonathanolson said:

`stringTest=long` should be checked:

![image](https://user-images.githubusercontent.com/480878/117058409-d10c6d80-acdb-11eb-990d-29597ef501f7.png)

**Comment by samreid** [comment]
I committed a proposed fix, and it is looking much better:

![image](https://user-images.githubusercontent.com/679486/120545980-8d755400-c3ac-11eb-8496-ecd43b083142.png)

@jonathanolson can you please review?

**Comment by jonathanolson** [comment]
Looks great!
