### ISSUE TITLE
Convert CircuitElement stateSchema to use ReferenceIO

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#708]
From https://github.com/phetsims/phet-io/issues/1774, we have:

```js
  stateSchema: {
    startVertexID: StringIO, // TODO: https://github.com/phetsims/phet-io/issues/1774 Should this be ReferenceIO?
    endVertexID: StringIO
  },
```

**Comment by samreid** [comment]
Fixed, it is working in the state wrapper but I wasn't 100% certain about the implementation, @zepumph can you please spot check and make sure this is barking up the right tree?

**Comment by samreid** [comment]
It looks reasonable and consistent with what I did for https://github.com/phetsims/circuit-construction-kit-common/issues/708.  I'll factor out the IO type in an upcoming commit.

**Comment by zepumph** [comment]
That really is the good stuff. Thanks
