### ISSUE TITLE
MeterBodyNode does not exist.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#709]
While testing a bamboo change, I ran across this comment in CCKCChartNode.js:

```js
 * Provides simulation-specific values and customizations to display time-series data in a MeterBodyNode.
```

I see MeterBodyNode referred to 15 times in cck-common, and 6 times in wave-interference.  I can find no definition for this class.  Did you rename something and forget to update comments?

**Comment by samreid** [comment]
I committed proposed fixes, @pixelzoom would you like to review?
