### ISSUE TITLE
What colors should be in the ColorProfile?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#710]
From https://github.com/phetsims/scenery-phet/issues/642 we agreed all sims should use ColorProfile.  Currently, Circuit Construction Kit doesn't appear to use ColorProfile at all.  @arouinfar can you recommend which colors should appear in the ColorProfile?

**Comment by arouinfar** [comment]
@samreid here are the things I can think of:
- [ ] Sim background
- [ ] Panel/AccordionBox background
- [ ] Panel/AccordionBox stroke
- [ ] Edit panel background
- [ ] Edit panel stroke (if it exists)
- [ ] Text fill
- [ ] Conventional current arrow fill (assuming it's not an image)
- [ ] Conventional current arrow stroke

There may be other general things that I'm unaware of, so perhaps look at Gas Properties as a recent-ish example.

**Comment by samreid** [comment]
Let's wait until https://github.com/phetsims/scenery-phet/issues/515#issuecomment-876655914 is addressed before going forward.

**Comment by matthew-blackman** [comment]
All color properties in https://github.com/phetsims/circuit-construction-kit-common/issues/710#issuecomment-875801826 have been instrumented. This issue is ready for a design review.

**Comment by samreid** [comment]
I took a quick look and cleaned up a few things.

**Comment by arouinfar** [comment]
Thanks @matthew-blackman @samreid. Everything looks good in the Color Editor on phetmarks.

The goal of colorProfile is to collect all colors in one place so it is easier for designers to iterate with the [Color Editor](https://bayes.colorado.edu/dev/phettest/phetmarks/color-editor.html?sim=circuit-construction-kit-dc&brand=phet). It also provides us with more flexibility to add support for `projector` or another color profile in the future. While we have support for instrumenting colorProfile, we decided in https://github.com/phetsims/scenery-phet/issues/515#issuecomment-880894417 that we don't need to expose every color to the client.  A recent example of this is calculus-grapher. Here is the full colorProfile:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/8419308/219239430-ec160446-337d-4e06-a880-785f615d72d0.png">

And we can see just a subset of these exposed in Studio, all related to representations of pedagogical value.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/8419308/219239574-9b1c76c5-f118-4477-88b5-ad89f11cea14.png">

If we do the same in CCK, I would probably only instrument `conventionalCurrentArrowFillProperty` and `conventionalCurrentArrowStrokeProperty`. @matthew-blackman @samreid can you uninstrument the rest?

**Comment by arouinfar** [comment]
Thanks @matthew-blackman, looks good!
