### ISSUE TITLE
Upgrade to FA5 for the battery refresh icon

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#712]
From https://github.com/phetsims/sherpa/issues/83

**Comment by samreid** [comment]
Before:
![image](https://user-images.githubusercontent.com/679486/126234157-a6a03202-0cd1-4ad9-82d1-3e79bfb499df.png)

After:
![image](https://user-images.githubusercontent.com/679486/126234262-37efbd8c-b897-48ae-819d-ea97ffd205cd.png)

@arouinfar does this look OK to you?

**Comment by arouinfar** [comment]
Looks good to me @samreid!
