### ISSUE TITLE
Interview on AC

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#714]
@arouinfar said we are at a good point to run our first AC interviews.

**Comment by arouinfar** [comment]
I shared an interview recruitment blurb/Google form with @stemilymill who has some contacts.

We have ongoing recruitment efforts with STEM departments at CU. Several EECE majors have responded, and they would be a good population for interviews.

**Comment by arouinfar** [comment]
@samreid before scheduling interviews I think we should first wrap up #678 and #693. I'd also like to send the sim through dev-lite testing.

**Comment by samreid** [comment]
@arouinfar reported 2 interviews with upper-level students.  They made low-pass and high-pass filters, AC-to-DC converters.  Nobody checked resonant behavior in these interviews.  2nd interview made connections between charged capacitors and batteries.  Observing current in a battery/resistor circuit with inductor.  Both intuitively used delete key without instruction.  Would be nice to select multiple circuit components at once.  Mainly to move things, but could also be used to delete multiple components.  No major problems observed.  It seemed like it led to inquiry.  It doesn't seem we need more interviews at this time, unless we scaffold something specific for RLC in particular.
