### ISSUE TITLE
Add fire artwork

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#72]
From #56, we may need to add fire artwork, @arouinfar said:

> I'll note we may want to add the fire graphic to the HTML5 version when the circuit is shorted, though not sure it is necessary for the MVP.

![image](https://cloud.githubusercontent.com/assets/679486/14762292/dc4ab0ea-0933-11e6-856d-56fb818309bb.png)

@arouinfar do you want different image files for the flame or any changes to how it appeared in the Java one (such as animating it, etc?)

**Comment by arouinfar** [comment]
Let's use the Java artwork for now @samreid. I will work on creatinf new artwork when I return from vacation.

**Comment by samreid** [comment]
@arouinfar can you create new artwork for this soon (or work with PhET's artist) so I don't need to rely on the Java version?

**Comment by arouinfar** [comment]
Fire artwork is not necessary for Stanford @samreid, but I will coordinate with our graphic artist to get new artwork for CCK: DC.

**Comment by samreid** [comment]
@kathy-phet said:

> Would it feasible to add fire to the battery to this branched version in a short circuit? Argenta said it is useful feedback - especially when electrons are hidden - and it would be great (but OK if not easy to tack on).

**Comment by samreid** [comment]
@arouinfar said:

> There hasn’t been any work done on the fire artwork yet, and I’m not sure if we could temporarily use the Java artwork. The intent has been that we’d have a graphic artist work on the fire artwork when the time came. Perhaps this is something Cheryl can work on when she starts?

**Comment by samreid** [comment]
Shima said:

> Definitely, battery on fire is a piece of art appreciated by all of our participants. Given the time frame,  if it is not possible to have the firework back, for now can we have the ammeter shows the same number for any short circuits. I am not sure which one requires more work. Currently, the ammeter shows different numbers in short circuit incidents: sometimes ">10^4" and sometimes an actual number, and it could be confusing for participants.

**Comment by samreid** [comment]
@kathy-phet said:

> Seems like you can ask Cheryl about the fire art work -- check with Ariel on that.

**Comment by samreid** [comment]
@kathy-phet said:

> I'm talking to Argenta, and classroom CCK use with be end of Feb or early March. Early unit will be on just the first screen. A week or so later would be CCK Black Box screen. 

Given this timeline, it seems reasonable that we could add flames, depending on our artist's schedule.

**Comment by samreid** [comment]
Based on the Java CCK, it seems like all circuit components with a high current should show a fire.

![image](https://cloud.githubusercontent.com/assets/679486/22302292/5c02a40a-e2eb-11e6-9df2-14de3ed4d17c.png)

@arouinfar should we render the flame as a static image as we did in Java, or would you like to animate it and add smoke?

**Comment by arouinfar** [comment]
> Given this timeline, it seems reasonable that we could add flames, depending on our artist's schedule.

As far as I know, the artist is starting fairly soon (perhaps immediately?) and doesn't have a ton of tasks, yet.

> @arouinfar should we render the flame as a static image as we did in Java, or would you like to animate it and add smoke?

@samreid I think a static image will work fine here. While an animation would certainly look nice, I don't think it's pedagogically necessary and it could also negatively impact iPad performance.

**Comment by arouinfar** [comment]
Tagging for https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/32.

**Comment by samreid** [comment]
@kathy-phet said the artwork is ready.  @arouinfar can you send it my way?

**Comment by arouinfar** [comment]
@samreid I've emailed you the assets.

**Comment by samreid** [comment]
I was working on adding light bulb flames when I realized they don't exist in the Java version:

![image](https://cloud.githubusercontent.com/assets/679486/22566405/f7a23688-e948-11e6-8811-679572e4d089.png)

@arouinfar thoughts?  I'm leaning toward keeping light bulb flames as long as they don't look too odd.

**Comment by samreid** [comment]
For instance, here's how it looks now:

![image](https://cloud.githubusercontent.com/assets/679486/22566499/58c9b850-e949-11e6-8669-7b618f8e78e9.png)

**Comment by ariel-phet** [comment]
@samreid I think keeping the lightbulb flames would be problematic. A resistor only heats up if it has resistance (P=I^2*R). So The battery is being short circuited, and probably assumed to have some small internal resistance, but if you are setting the lightbulb to no resistance, it should actually not get hot.

**Comment by arouinfar** [comment]
@samreid the Java version of CCK does not show a fire on the lightbulbs when shorted.

![image](https://cloud.githubusercontent.com/assets/8419308/22566561/ab87689e-e949-11e6-9ba8-d3a8557ba6dc.png)

**Comment by samreid** [comment]
@ariel-phet by that logic should we suppress fire on the resistors as well?  (Resistor fires *are* shown in Java, see https://github.com/phetsims/circuit-construction-kit-common/issues/72#issuecomment-275179321 )

**Comment by arouinfar** [comment]
Ah, I missed an earlier comment in the chain. I don't think the fire on the lightbulb is necessary, especially given @ariel-phet's comment.

**Comment by ariel-phet** [comment]
@samreid @arouinfar it depends...is the fire based on the current level? It just is incorrect to have a component with zero resistance catching fire.

**Comment by samreid** [comment]
Yes, in the Java there is a 10 Amp threshold.

**Comment by samreid** [comment]
I could add a rule: fire only displays if it is a battery or a component with resistance >= 0.01 Ohms.  I think the battery internal resistance is modeled as `1E-4` in the Java.  It looks like it is 0 in the HTML5--I'll create a new issue to see if that's an problem.

**Comment by samreid** [comment]
Assigned to @arouinfar and @ariel-phet for feedback.

**Comment by samreid** [comment]
This is mainly working in master (though we still need to discuss what to do with 0-resistance components).

Possible next steps:
1. backport this fix to the legacy branch
2. abandon the legacy branch and thoroughly test master

Master has diverged so much from the legacy branch that it is no longer to automatically or semi-automatically merge the changes. All changes now have to be done manually, this means extra work during development and that everything must be tested twice (in the branch and in master).  The best long term plan is to abandon the legacy branch and create a new stable branch from master--this would require one-time exhaustive testing but would save us the most time in the long run.  Every time we say "what if there is just one more minor change for the stale branch" there are many more changes for the stale branch.  So we should plan to stop making changes to this branch soon, whether (a) it requires no more changes or (b) we can use a fresh branch from master.

**Comment by samreid** [comment]
I'll plan to manually backport the fire from master to the branch, and I'll move the above comment to a new issue.

**Comment by samreid** [comment]
Back-merging this through cherry-picks has been possible because this is in circuit-construction-kit-common (not black box repo).

**Comment by samreid** [comment]
Here's a dev version of the branch: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.8/circuit-construction-kit-black-box-study_en.html

I'll sanity test then reassign to @arouinfar for further testing.

**Comment by samreid** [comment]
That version had buggy fire for the light bulb.  Based on discussion above I also removed the resistor fire and here's a new version for me to test:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.9/circuit-construction-kit-black-box-study_en.html

**Comment by samreid** [comment]
Seems OK during my testing, @arouinfar can you take a closer look?

**Comment by arouinfar** [comment]
Everything looks good, as far as the logic for the fire artwork. My one complaint would be the placement of the artwork looks a little off.

![image](https://cloud.githubusercontent.com/assets/8419308/22603097/34966bee-ea03-11e6-9715-810bfd95f2c3.png)

I think it would look a bit cleaner if the flames were shifted a bit to the left so that they would look more centered.

![image](https://cloud.githubusercontent.com/assets/8419308/22603365/42658fce-ea04-11e6-9b8f-64529adb8313.png)

**Comment by kathy-phet** [comment]
I'd like to continue the discussion around resistors catching fire as we move forward with CCK DC. Resistors can catch fire in the real world, and I think there is learning there (and fun).

**Comment by ariel-phet** [comment]
@kathy-phet I am fine with resistors catching fire at **low resistance** but not at zero resistance.

**Comment by kathy-phet** [comment]
Yes, I agree - that is where discussion should head in terms of where they will show fire.

**Comment by arouinfar** [comment]
@samreid I agree with @ariel-phet and @kathy-phet. I am fine with resistors catching fire so long as they have a low, but non-zero, resistance.

**Comment by samreid** [comment]
Fire artwork has been added, hence this issue will be closed.  We will follow-up in the aforementioned 2 issues.
