### ISSUE TITLE
Stepping a paused inductor causes voltage to oscillate rapidly

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#721]
Discovered while testing https://github.com/phetsims/circuit-construction-kit-common/issues/570 in a design meeting.  We set up this circuit:

![image](https://user-images.githubusercontent.com/679486/131037533-6e6a9a8f-a1c4-4cc2-ad57-fca122551f11.png)

Paused, then opened the switch, then stepped, and we saw rapid, buggy oscillation in the voltage chart.  I was unable to reproduce it following these instructions, so there must be more to it.

**Comment by samreid** [comment]
I am unable to reproduce the problem.  @KatieWoe can you please have the QA team try some variations of the above instructions?  You will know you found the error case when the voltage chart (or maybe current chart?) starts oscillating rapidly (>100Hz).  Please use https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.16/phet/circuit-construction-kit-ac_en_phet.html for testing.

**Comment by Nancy-Salpepi** [comment]
On MacBook air 11.4 + chrome:

I was able to get the voltage to oscillate drastically by following these steps:
1. Place the battery on the screen and then the inductor above it with significant space in between
2. Attach the two with a wire--connect to the inductor first and then to the battery
3. Attach the resistor to the right side of the inductor, followed by the switch
4. Attach a wire to the battery and the other end to the switch
5. Attach the voltage chart to the inductor
6. Close the switch 
7. Press pause prior to the voltage reaching zero
8. Open switch
9. Step forward
10. Press play

https://drive.google.com/file/d/1_5hbLBAKLMWEMCgnH8gRz20j10B8cSX5/view?usp=sharing

**Comment by samreid** [comment]
In about 6 trials of following the above instructions, the error only occurred in about 3 of those cases.  I observed the matrix condition number for the failures was around 1E24, much lower like 1E17 or less for the successes.

**Comment by samreid** [comment]
At today's design meeting, @kathy-phet asked @Nancy-Salpepi to see if this is still reproducible in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.24/phet/circuit-construction-kit-ac_en_phet.html

**Comment by Nancy-Salpepi** [comment]
After 10 attempts, I could not reproduce this issue.  @samreid, I believe this issue can be closed. 
![issuefixed](https://user-images.githubusercontent.com/87318828/132850802-e3c46fe6-b605-4335-b28a-891c82ace8da.gif)

**Comment by samreid** [comment]
Good idea to recheck it after https://github.com/phetsims/circuit-construction-kit-common/issues/738, on hold until then.

**Comment by samreid** [comment]
Now that #738 has a proposed solution, this is ready for re-testing.  @Nancy-Salpepi can you please take a look?  Please test using https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.25/phet/circuit-construction-kit-ac_en_phet.html

**Comment by Nancy-Salpepi** [comment]
@samreid now when the switch is closed, the voltage stays constant at 9 volts. 

<img width="1177" alt="Screen Shot 2021-09-15 at 12 54 15 PM" src="https://user-images.githubusercontent.com/87318828/133476549-37d5b7f9-efbb-45c8-be01-41bae9f68d8d.png">

**Comment by samreid** [comment]
Please note the placement of the probes--the picture in the preceding comment is measuring the voltage drop across the battery, which remains constant at 9V.  The red probe could be placed between the inductor and the resistor to measure the voltage drop across the inductor.

**Comment by Nancy-Salpepi** [comment]
Sorry about that @samreid.

I tried several times with the voltage probes in the correct places. The play/pause/step forward buttons are working as they should. I'm seeing the same thing as in video https://github.com/phetsims/circuit-construction-kit-common/issues/721#issuecomment-916862033

It looks good to close at this point.

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
