### ISSUE TITLE
the selection highlight for the capacitor seems too big

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#722]
Discovered in #719, the selection highlight for the capacitor seems too big:

![image](https://user-images.githubusercontent.com/679486/131124645-8dcb444b-d552-483c-b938-571f0a3882c8.png)

**Comment by samreid** [comment]
After the fix it looks like so:

![image](https://user-images.githubusercontent.com/679486/131201046-946d317e-35f7-41c5-bd94-588db66ff562.png)

@arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good to me. Thanks @samreid!
