### ISSUE TITLE
Should the charts reset when you put them in the toolbox?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#724]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/718, you can record data on a chart, then put it in the toolbox, then get it out of the toolbox and it still has the same data (and zoom level).  To me, it seems like it should reset, but we haven't discussed it before.  @arouinfar @ariel-phet or @kathy-phet what do you recommend?

**Comment by ariel-phet** [comment]
I would agree it should reset. Putting it in the tool box seems analogous to unplugging and instrument and putting it away, I could also envision cases where not resetting could cause a fair bit of confusion (for instance, a pair of students using the sim and the second to drive the sim pulls out a chart).

**Comment by samreid** [comment]
In the commit, the chart resets when it is put in the toolbox.  @KatieWoe, @ariel-phet or @arouinfar could you please verify and close?

**Comment by ariel-phet** [comment]
Looked good on master, closing
