### ISSUE TITLE
Incorrect voltage chart readout for simple AC source and battery

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#725]
Seen on phettest version of the sim on 8/30/2021

If you make the simple circuit shown in the video, when the voltage is measured across the battery you will get a constant voltage instead of an oscillating voltage. The voltage across the lightbulb is displayed correctly, but across only the battery is incorrect. 

https://user-images.githubusercontent.com/4051174/131365850-17672331-52ae-4ee0-bb96-d0e3f42d1649.mp4

**Comment by samreid** [comment]
@arouinfar and I reviewed the behavior above and we believe it to be the correct physical behavior.  From Kirkhoff's loop rule, traversing around a closed loop should give a sum of voltages adding to 0.  If the bottom battery is at 9V, and the AC source is at 9*sin(wt) V, the voltage drop across the light bulb must be equal to 9(1-sin(wt)) V.  Therefore the voltage across the battery remains at 9 V.  @ariel-phet do we have this right?

**Comment by ariel-phet** [comment]
@arouinfar @samreid yes, I think my brain was thinking about a floating ground for a DC offset, which we do not have here.
