### ISSUE TITLE
Play/pause issues and measurements

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#726]
In https://github.com/phetsims/circuit-construction-kit-common/issues/720#issuecomment-908456709, @Nancy-Salpepi said:

> I noticed an inconsistency when the resistance was changed in pause vs play mode.
> 
> I built the circuit shown above and the voltage curve remained smooth and consistent when the resistance was decreased while the sim was in play mode. The power source did not go on fire. When I paused the sim and changed the resistance from 10 to zero, it showed the power source on fire. When I pressed the play button, the fire went away and the voltage curve was smooth and consistent after an initial blip.
> 
> https://drive.google.com/file/d/1bo26iA8OlrUsNsh9XVH1PLFVUfrm7HiH/view?usp=sharing

@arouinfar can you please review the behavior, recommend how to proceed and mark it for the AC 1.0 milestone if it is necessary before publication?

**Comment by arouinfar** [comment]
@samreid something strange is going on here, but I don't think this is an issue with play/pause. 

![image](https://user-images.githubusercontent.com/8419308/131409061-e00bdc2e-d1ed-4987-90a6-a1e236f9987f.png)

The resistance in this circuit should be minimal. The wires contribute a bit of resistance, and with the changes in #727 the resistor should be 1E-8 ohms. However, the current appears to be [-2.5, 2.5] amps.

**Comment by samreid** [comment]
Thanks, I moved the preceding comment to a new issue.  Should anything else be done for this issue?

**Comment by samreid** [comment]
Today we discussed this in design meeting.  We saw a discontinuity in the voltage curve, and since current is proportional to dV/dT, there is a current spike.  So it is OK for the AC source to catch on fire for that frame:

![image](https://user-images.githubusercontent.com/679486/132756359-2bf553c2-164b-4776-9ccf-9ad7827c628a.png)
