### ISSUE TITLE
Current is not conserved when setting resistance to zero

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#727]
From https://github.com/phetsims/circuit-construction-kit-common/issues/720#issuecomment-908456709

@Nancy-Salpepi said:

> I also noticed in play mode that the electrons stop moving in the resistor when resistance is set at zero. There seemed to be some sputtering in the voltage chart as well.
> 
![Kapture 2021-08-30 at 11 18 16](https://user-images.githubusercontent.com/679486/131378587-a221effd-faac-4cce-b9e2-cf9b95f1a5fe.gif)

**Comment by samreid** [comment]
When the resistance drops to 0, the voltage from the solution is `-7.163178782256218e-26 `.  The current is computed as I=V/R, so also coming up around 0.

Some ideas:
* We could eliminate 0 resistance circuit elements from the equation, but we would still need a way to compute their current.
* Try giving the resistor a small number instead of 0?

**Comment by samreid** [comment]
I required circuit elements to have non-zero resistance, instead using `CCKCConstants.MINIMUM_RESISTANCE = 1E-8` for this case.  It fixes the symptoms of this problem.  @arouinfar do you think that is a reasonable solution, or is having a small nonzero resistance for resistors going to cause problems for some scenario?  Or should we go below 1E-8?

**Comment by arouinfar** [comment]
> I required circuit elements to have non-zero resistance, instead using `CCKCConstants.MINIMUM_RESISTANCE = 1E-8` for this case. It fixes the symptoms of this problem.

That sounds reasonable to me and it appears to be behaving correctly in dev.17.

However, I do wonder if we need to allow users to set the resistance to zero. Perhaps we could instead change the slider minimum to 1 ohm for standard bulbs and resistors. I'll tag for a design meeting to check in with the team.

**Comment by samreid** [comment]
That sounds reasonable.  But I'm wondering if a learning goal is that a 0-resistance wire and a 0-resistance resistor are physically the same in a circuit.

**Comment by samreid** [comment]
In design meeting, we agreed to leave the 0-value resistor.  @Nancy-Salpepi can you please test in the latest dev version and see if the problem is corrected?

**Comment by samreid** [comment]
In today's meeting @kathy-phet identified a case where we would like better behavior.  This resistor should be closer to negligible:

![image](https://user-images.githubusercontent.com/679486/131910580-462af156-5d10-4def-a867-d754952c3a98.png)


Also, @kathy-phet identified bunching in a similar circuit
![image](https://user-images.githubusercontent.com/679486/131910616-82235a23-7ec2-44db-99da-d78cd0542cc0.png)

**Comment by samreid** [comment]
I observed the minimum resistance for the 0 Ohm resistor was actually 1E-8, which was orders of magnitude larger than the resistance for a resistor-length wire, which was about 1.1E-10.  When I changed the minimum circuit element resistance to be 1.1E-10 instead of 1E-8, this behavior looked better:

![image](https://user-images.githubusercontent.com/679486/132623740-fc0a8d36-9421-4d57-a0ac-5679f8904e90.png)

Currently this value is coupled to other components, such as the default value for the fuse resistance (overridden in step), so this seems safe.  I'll commit and request review.

**Comment by samreid** [comment]
I published a dev version for testing here: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.24/phet/circuit-construction-kit-ac_en_phet.html

I'll label for design team review

**Comment by samreid** [comment]
In design meeting, this seems like it is working well.  Back to QA for more testing.

**Comment by samreid** [comment]
Can you please test in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.25/phet/circuit-construction-kit-ac_en_phet.html?

**Comment by stemilymill** [comment]
@samreid is this a significant difference? I'm not sure exactly what the thresholds/guidelines should be for this issue.

![zero resistor not zero](https://user-images.githubusercontent.com/85511101/133501152-56aa078f-0be3-40a1-a05e-cf4089c388e2.jpg)
![zero resistor not zero higher voltage](https://user-images.githubusercontent.com/85511101/133501163-6822287a-fa33-4c19-93e3-f6c959cdd5eb.jpg)

**Comment by samreid** [comment]
In today's design meeting, we agreed the current differences are small enough to not be a problem.  The difference is due to the path length difference, which is subtly different.  Therefore, this issue seems ready to close.
