### ISSUE TITLE
Add a user interface for which side the bulb connects on

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#73]
See #26, it could appear in the light bulb edit panel at the bottom of the screen (which appears when the light bulb is tapped).

Not necessary for MVP.

**Comment by samreid** [comment]
Radio buttons seem like the right user interface component for this.

**Comment by samreid** [comment]
From @arouinfar comment:

> We wouldn't add the connection toggle to the MVP, but it would nice to keep the code somewhere if we decide to add that functionality to future versions.

it is unclear whether we want this functionality at all.  I'll assign it to her for discussion at an upcoming design meeting.

**Comment by arouinfar** [comment]
Thanks for opening this issue @samreid. We should discuss if we want to add this functionality, and if so, how the UI should appear. I agree that radio buttons do seem like a good option. Tagging for design meeting.

**Comment by samreid** [comment]
Another option: make it always possible to connect to either side of the light bulb.  This may be non-trivial to design, but it could eliminate the need for a UI for selecting connection side.

**Comment by samreid** [comment]
See #238 for more discussion about light bulb UI.

**Comment by arouinfar** [comment]
@samreid looking at this issue again, I'm not sure that this is a necessary feature. That said, we can still discuss it at design meeting to see if the other team members agree. Self-assigning for now.

**Comment by arouinfar** [comment]
On second thought... I re-discovered this feature while playing with Java CCK, so my guess is that we'll want to keep this feature. I'll mock up some options for the next design meeting.

**Comment by samreid** [comment]
@arouinfar can you consider symmetrical attachments, to see if we can eliminate this problem.  For instance, instead of having the attachment point on the right or the left, having it in the center (but on the metal part in the front in z-layering)?

**Comment by arouinfar** [comment]
Are you suggesting something like this @samreid?

**Comment by samreid** [comment]
Yes, but perhaps it would help if the internal filament had one end pointing at the top vertex and the other end pointing at the bottom vertex, as an additional cue.

**Comment by arouinfar** [comment]
@samreid I think the problem with the vertex arrangement in https://github.com/phetsims/circuit-construction-kit-common/issues/73#issuecomment-283484902 is that there's not a clear way to show  how the filament attaches to the vertices (which will look odd with Show Electrons). I don't think I quite follow your latest comment. Perhaps we can briefly chat about this before/after status tomorrow?

**Comment by arouinfar** [comment]
If we decide to mirror the connection, we could add a mirroring button next to the resistance slider like so:

**Comment by arouinfar** [comment]
Discussed 3/16/17. This does not seem like a necessary feature. Closing.
