### ISSUE TITLE
The current probe cannot read different values while the sim is paused.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#730]
While working on https://github.com/phetsims/circuit-construction-kit-common/issues/678, I observed that the current probe cannot read different values while the sim is paused.  Is this by design or a known deficiency?  If not, is it important to work on for AC 1.0?

**Comment by arouinfar** [comment]
The voltmeter and ammeters are responsive while paused, but something strange is going on with the Voltage and Current charts.

Here's an example of what I see in cck-ac dev.17:
1. Build a simple circuit with a default AC source, resistor, and two wires.
2. Place current chart probe on a wire.
3. Pause the sim.
4. Move current probe off of the wire, chart does not change (I expected the dot to drop to 0 amps)
5. Return current probe to a circuit element. 
6. Change resistance or source voltage, and dot will move appropriately.

@samreid this is something that should be addressed for CCK: AC 1.0.

**Comment by samreid** [comment]
I changed the implementation so that even when the model is paused, the voltmeter chart and ammeter chart sample data.  Please use https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.19/phet/circuit-construction-kit-ac_en_phet.html for testing.  I also noticed that since that last point happens at the same time, the series are connected.  For instance, moving from the AC to DC it shows a solid connector line:

![image](https://user-images.githubusercontent.com/679486/131438370-3b1e3ace-be5a-470a-9633-34bde3cd2796.png)

@arouinfar can you please review?  Close if all is well.

**Comment by arouinfar** [comment]
@samreid I reviewed in master and the behavior looks good, thanks!
