### ISSUE TITLE
Current value seems inaccurate

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#731]
In https://github.com/phetsims/circuit-construction-kit-common/issues/726#issuecomment-908720804 @arouinfar said:

> @samreid something strange is going on here, but I don't think this is an issue with play/pause. 

![image](https://user-images.githubusercontent.com/8419308/131409061-e00bdc2e-d1ed-4987-90a6-a1e236f9987f.png)

> The resistance in this circuit should be minimal. The wires contribute a bit of resistance, and with the changes in #727 the resistor should be 1E-8 ohms. However, the current appears to be [-2.5, 2.5] amps.

**Comment by samreid** [comment]
According to https://circuitdigest.com/tutorial/capacitor-in-series-and-parallel-circuits, the current through a series AC/Capacitor circuit is given by i = dQ / dt = C (dV / dt).  Estimating from the voltage chart, I see the steepest slope is around dv = 28 V, dt/1s.  And the Capacitance is 0.1F.  So i=CdV/dt = 0.1*28 = 2.8V (give or take measurement error).  Does that sound right to you?

**Comment by samreid** [comment]
The physics in the preceding comment seems reasonable, to clean up the milestone, I'm going to leave this open and assigned to @arouinfar to double check at her convenience, but I'll remove from the milestone for now.  Please return to the milestone if something needs to be done before AC 1.0.

**Comment by samreid** [comment]
It would be good to finish up this issue, increasing priority.

**Comment by arouinfar** [comment]
Thanks @samreid, I think this one is safe to close
