### ISSUE TITLE
Incomplete circuit with switch and ?capacitorResistance=4E-6 has active current, electron bunching, flames

### ISSUE THREAD

**Issue by stemilymill** [phetsims/circuit-construction-kit-common#737]
**Test device**
Dell laptop

**Operating System**
Win10

**Browser**
Chrome 93.0.4577.63

**Problem description**

I'm not sure if this is particularly problematic since I have only seen it with the ?capacitorResistance query parameter, but I thought it might be relevant to https://github.com/phetsims/circuit-construction-kit-common/issues/693#issuecomment-912067138
While testing https://github.com/phetsims/circuit-construction-kit-common/issues/720 with different values for ?capacitorResistance, at 4E-6 I was building the exact same circuit https://github.com/phetsims/circuit-construction-kit-common/issues/720#issuecomment-912788224 and when I dragged out the last wire after adding the switch (which was still open), electrons flowed, bunched, the capacitor plates flashed solid blue/red, and the resistor caught fire. 

It took a few attempts, but I was able to (mostly) recreate the bug.

The resistor and lightbulb were both at default 10 ohms.

**Visuals**

https://user-images.githubusercontent.com/85511101/132400381-11fac50a-baaf-43e2-9378-20118535149a.mp4

Recreated, this is a long video

https://user-images.githubusercontent.com/85511101/132400458-b7934c61-7741-4249-90ef-68d9fb36fd31.mp4

<details>
<summary>Troubleshooting information:</summary>
<br>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.20/phet/circuit-construction-kit-ac_en_phet.html?capacitorResistance=4E-6
Version: 1.0.0-dev.20 2021-09-01 01:07:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
There is a proposed fix in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.23/phet/circuit-construction-kit-ac_en_phet.html, can you please test if it solves this problem too?

**Comment by samreid** [comment]
#738 has a proposed fix, can you please test in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.25/phet/circuit-construction-kit-ac_en_phet.html ?

**Comment by KatieWoe** [comment]
haven't been able to reproduce, but I'll let @stemilymill do the final confirmation since she found the initial bug.

**Comment by samreid** [comment]
On hold until https://github.com/phetsims/circuit-construction-kit-common/issues/739 has progress.

**Comment by stemilymill** [comment]
I have not been able to recreate this issue.
