### ISSUE TITLE
Capacitor voltages fluctuate when not connected

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#739]
From https://github.com/phetsims/circuit-construction-kit-common/issues/693, Capacitor voltages fluctuate when not connected

![image](https://user-images.githubusercontent.com/679486/133867240-cc8f02d5-8b0f-4f8c-a6fc-74a140897b27.png)

**Comment by samreid** [comment]
Somehow the node indices for the disconnected capacitor are ending up in the circuit matrix solution.

**Comment by samreid** [comment]
@zepumph and I discovered that the synthetic nodes were using the same indices as the vertex nodes.  Adding 100000 to all of the synthetic indices worked around the problem.  @zepumph and I tried making the node values the same as vertex.index, and that helped in the lookup but ultimately had the same problem because the synthetic indices were overlapping the vertex.index values.  Therefore we have to choose synthetic indices that do not overlap any indexing (whichever indexing strategy we use).

**Comment by samreid** [comment]
I found that the voltage node identifiers did not need to be numeric, so was able to label the synthetic ones as strings.  It seems to be testing OK and resolves this problem.

**Comment by samreid** [comment]
This is fixed and ready for testing.  For QA testing, this changed the code for the following circuit elements:

* Inductors
* Batteries
* AC Sources
* Capacitors

Let's test in this version: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.28/phet/circuit-construction-kit-ac_en_phet.html

**Comment by KatieWoe** [comment]
Things look good to me

**Comment by samreid** [comment]
Thanks, closing.
