### ISSUE TITLE
Connected wires should be nearby in z-ordering

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#74]
From #48 

Regardless of solder layering, it looks like there's some funkiness with the layering. Selecting an item does not bring it to the front (left). It's also possible to drag a wire through the connection of two other wires (right).

![image](https://cloud.githubusercontent.com/assets/8419308/14151790/ed82527a-f66c-11e5-84b1-faa0d4ef150f.png)        ![image](https://cloud.githubusercontent.com/assets/8419308/14151885/6e62d1f8-f66d-11e5-90d7-24a6e55f244c.png)

@arouinfar is this for MVP or later?

**Comment by arouinfar** [comment]
@samreid, the layering seems a bit like an edge case. Under normal circumstances, I don't think students should run into blocking issues. We can warn Stanford that the layering is not perfect, and that it's possible for students to run into situations like the ones pictured above.

**Comment by samreid** [comment]
@arouinfar I have been treating wires asymmetrically because it looked odd to me for the wires to go in front of the other components.  What do you think?  Can you discuss general rules for layering that will be best?  We can discuss at a design meeting if you wish.

**Comment by arouinfar** [comment]
@samreid I agree that it would look a bit odd for wires to go in front of other components. Can contiguous wire pieces be considered a single wire for layering purposes? For example, in the screenshot on the right above, could the two wires connecting the right side of the resistor to the right side of the bulb live in the same layer? It seems like that would prevent the bisecting issue.

**Comment by samreid** [comment]
@arouinfar can we punt on this issue (by not worrying about it)?  I suspect that in many cases, the wires will not overlap, and in many cases where they do overlap, there is no problem.

![image](https://cloud.githubusercontent.com/assets/679486/26434914/d2ac4292-40c8-11e7-9687-6a20d55d1f45.png)

**Comment by arouinfar** [comment]
Sounds reasonable to me @samreid!

**Comment by samreid** [comment]
Thanks, I'll close it and we can reopen this or similar issue if something more critical comes up.
