### ISSUE TITLE
Current travels through an open switch

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#745]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/744

It seems order dependent, but I reproduced it in dev.31 through dev.33 by battery, bulb, switch, wire -> connect.

**Comment by samreid** [comment]
I pushed a proposed fix and it seems to be testing OK.  @ariel-phet can you please verify in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.34/phet/circuit-construction-kit-ac_en_phet.html ?  Please close if it seems OK.

**Comment by ariel-phet** [comment]
So far this fix seems OK, closing and moving on to other testing
