### ISSUE TITLE
PhET Black Box: When revealing the answer, show component values

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#75]
In #30 there is a "reveal answer" mockup, but the component values (such as battery voltages) are not shown.  Should we show them in the revealed answer?

**Comment by arouinfar** [comment]
Great question @samreid! For resistors, the bands serve as a visual indicator. It's pretty clear if your resistor is or isn't a match to what's in the black box, though students may need to consult a chart if they want to know the precise value of the resistance. Batteries, on the other hand, do not have any visual indicator of their voltage, but it can easily be found with the voltmeter. I think for the purposes of the MVP,  the current implementation without values would work.

However, I think it would be nice to have a component value visible while in "reveal" mode. Potentially it could look something like this (values here are fake). If this is a quick thing to implement, it would be nice to have for the MVP, though not strictly necessary.

![image](https://cloud.githubusercontent.com/assets/8419308/14964054/dc3f92de-10bb-11e6-8fb6-2560908e6532.png)

**Comment by samreid** [comment]
> I think for the purposes of the MVP, the current implementation without values would work.

I'll remove the high-priority label.

**Comment by samreid** [comment]
Values are now shown during reveal, closing.
