### ISSUE TITLE
Consider static "values" display for AC sources

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#751]
Whiles testing 1.0.0-dev.36 I noticed that the when the values checkbox is checked, the voltage value for the AC source fluctuates rapidly. I am not sure that is a very useful feature since it is difficult to tell the max and min values of the source by watching this readout. I also think this sort of fluctuating readout might become problematic with description in the future. I think it would be better to decide on some static readout such as "+/- 10V" instead of having this rapidly fluctuating readout. 

Found as part of https://github.com/phetsims/circuit-construction-kit-common/issues/748

**Comment by arouinfar** [comment]
I really like this idea @ariel-phet. I have found myself opening the edit panel to confirm the max/min voltage of the AC source, and it can be a bit inconvenient. I believe this matches the Java behavior, so I would want to discuss it with the team before making the change. Let's discuss at design meeting.

**Comment by samreid** [comment]
We discussed whether this would show an inconsistent value for case where you see a changing current:

![image](https://user-images.githubusercontent.com/679486/140424187-240325f1-6ff2-433c-9e30-8f6a946946d7.png)

KP: For the student that doesn't understand the AC circuit, it makes it clear that it doesn't stay put.  You don't need a chart, it is easy to visualize that it is changing.  So it helps to show that it's a changing value.

You can still show the amplitude, but you have to click on the component.

We discussed a 3-line solution where it shows the amplitude, current value, and optionally the resistance (if source resistance is added).

We agreed to leave it as it is.
