### ISSUE TITLE
Carousel spacing issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#753]
Found as part of https://github.com/phetsims/circuit-construction-kit-common/issues/748

The spacing of items in the carousel seems to be a bit unbalanced (and this issue is also obvious in the schematic view as shown below) Particularly between the paper clip and coin it feel like the negative space is fairly different than the other items

![Carousel](https://user-images.githubusercontent.com/4051174/137838871-04741bea-b832-4582-b34a-58207d3ac28e.png)

noticed during https://github.com/phetsims/circuit-construction-kit-common/issues/748

**Comment by samreid** [comment]
Now that the carousel has separators, it looks much more balanced.  Closing.
