### ISSUE TITLE
Consider moving the battery to the second screen of the Carousel on RLC and Lab

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#754]
The carousel on the RLC and Lab screens feels a bit too packed, I wonder if we could move an item to the second page of the carousel. To me an obvious candidate is the battery, since the focus here is really AC circuits and although the battery can add some interesting contrast or allow for DC offsets, it might be fine to just put it on the second page of the carousel.

Currently on these screens the bottom left of the sim just feels more crowded than necessary

![cramped](https://user-images.githubusercontent.com/4051174/137839359-84737690-5bc2-4bd2-9a18-788d57e61fd8.PNG)

**Comment by samreid** [comment]
We agreed the components on the carousel 1st page are convenient to have access to all of them.  Perhaps when we fine tune the carousel in #753 this problem will be reduced.  We agreed this can be closed for now.
