### ISSUE TITLE
Bad voltage jitter in driven resonant circuit

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#758]
Seen as part of testing in https://github.com/phetsims/circuit-construction-kit-common/issues/748

In the driven resonant circuit seen below, I was getting some nasty jitter in the voltage readout, but the current readout is clean.

Capacitance 0.10 F
Inductance 0.253 H
Resistance 40 Ohm
AC source 100 V and 1 Hz

These values of capacitance and inductance were initially chosen to set up a natural frequency of 1 Hz. Adjusting the voltage does not improve the behavior much, nor does adjusting the driving frequency. Lowering the resistance does eventually clean up the voltage readout, but jitter can easily be seen as low as 10 Ohms in this circuit. Increasing the inductance to about 1.5 H also cleans up the behavior. But clearly there is currently a widely accessible range of values that produces poor behavior. 

![jitter](https://user-images.githubusercontent.com/4051174/137842378-17e4bb54-1a5d-491a-80ac-8d092c46562d.PNG)

**Comment by samreid** [comment]
I experimented with reducing the MIN_DT and ERROR_THRESHOLD in TimestepSubdivisions.ts.  However, reducing it lower and lower wrecked the performance before the curve smoothed out appreciably.  This is an emergent behavior from our solver and I'm not sure how to investigate it next.  @arouinfar or @ariel-phet can you brainstorm ideas where to look?

**Comment by samreid** [comment]
This case is not a problem for Java.  I edited the Java to take the inductor below its default of 10, set up the same characteristics and it did OK.  But it did print out "Time step too small" over and over:

![image](https://user-images.githubusercontent.com/679486/138030175-b9a06371-efb4-4fdd-ad01-a0ddbe2fb352.png)

**Comment by samreid** [comment]
At today's design meeting, we saw that the jitter was only in the voltage across the inductor and not across any of the other components, or in any of the currents.  @ariel-phet and I scheduled a meeting to take a closer look.

**Comment by ariel-phet** [comment]
@samreid I have not seen any jitter in this kind of circuit in 1.0.0-dev.43 during testin.

Before closing the issue, we might want QA to check performance of a circuit like this on a Chromebook

**Comment by samreid** [comment]
I can test on my son's school-issued chromebook, but I'll probably do so with capacitorResistance=1E-4 since we are considering that for https://github.com/phetsims/circuit-construction-kit-common/issues/769#issuecomment-961431451

**Comment by samreid** [comment]
Testing the resonant circuit in the top comment with dev.45 looks fine on the lenovo 300e chromebook. Despite the graininess of this video the motion seemed smooth and speedy.

![Kapture 2021-11-07 at 21 04 05](https://user-images.githubusercontent.com/679486/140682647-69bd8499-6536-4964-a6b4-ab78dd7af3ce.gif)

Running with ?capacitorResistance=1E-4 seemed about the same.  I compared sim time to wall time, and found that 3 cycles had passed in the current chart in 5 seconds of real time.  I clocked the same circuit on my Macbook Air running 5 cycles in 5 seconds of realtime.  

In https://github.com/phetsims/circuit-construction-kit-common/issues/758#issuecomment-953228045 we discussed that it is OK for the sim to be slower than realtime as long as it is internally consistent.  But I thought it would be good to double check that it may be as slow as a ratio of 3:5 on devices like this chromebook.  But if we decide that is not ok, I'm not sure how to address it.  @arouinfar can you please advise?

**Comment by samreid** [comment]
@arouinfar and I discussed this today.  Since it was smooth and speedy on the chromebook, and the time was internally consistent on the chromebook, this issue seems good to close.  It is ok running at 3:5 time.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by samreid** [comment]
I removed the TODO, closing.
