### ISSUE TITLE
Connecting a capacitor in parallel to other capacitors cause severe visual jitter

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#769]
In the simple DC circuit shown below, when the parallel capacitor is connected to the circuit a pretty severe visual jitter occurs that eventually settles down. However, this situation should be very stable, we should investigate the source of this instability. The video does not quite show how bad the jitter actually appears. 

Observed while testing https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.41/phet/circuit-construction-kit-ac_en_phet.html

https://user-images.githubusercontent.com/4051174/139292036-0bc2b354-946a-4e17-a94d-ed9aed7d95bd.mp4

**Comment by samreid** [comment]
I was able to reproduce the problem, and also confirmed that it does not happen in Java.  Java does show a sudden spike, but it damps out quickly.  The critical difference seems to be the resistance in the wires.  A default length wire in Java has a resistance of 1.5E-4 Ohms.  A default length wire in HTML5 has a resistance of 1.2E-8 Ohms.  To test the hypothesis that increasing the resistance would ameliorate this problem, I recalled that our HTML capacitors have an internal resistance, currently 1E-6.  I tried tuning it with the query parameter `?capacitorResistance=1E-4` and observed behavior similar to the Java behavior.  If I recall correctly, we have already tuned these resistances as high as we were comfortable with, so as not to disrupt other factors.  @arouinfar and @ariel-phet can you please advise?

**Comment by samreid** [comment]
To help understand the nature of the problem, I ran the following experiment.  
* Set the HTML capacitor internal resistance to 0 (was previously 1E-6) so the problem is at its worst.
* Decrease timestep min dt from 1E-3 to 1E-6
* Decrease timestep error threshold from 1E-5 to 1E-6.

I observed that this corrects the spiking oscillatory behavior in the circuit, for both the DC case and the AC case, however it wrecks the performance.  I think we have previously tuned these thresholds as low as they can be.

**Comment by ariel-phet** [comment]
Marking for discussion at design meeting

**Comment by samreid** [comment]
At today's design meeting, @arouinfar confirmed that `?capacitorResistance=1E-4` eliminates the "enveloping" problem seen above.  We are concerned that it could disrupt time constant calculations if this resistance is too high.

@ariel-phet will investigate with testing `?capacitorResistance=1E-4` in the latest dev version.

For reference, we added the capacitor resistance in https://github.com/phetsims/circuit-construction-kit-common/issues/695.  See also #720

**Comment by ariel-phet** [comment]
I tested 1.0.0-dev.45 with '?capacitorResistance=1E-4' and this issue appears to be resolved.

**Comment by samreid** [comment]
Thanks, I changed the default to be 1E-4.
