### ISSUE TITLE
The metallic part of the voltmeter probes should be conductive

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#77]
From #58, only the _point at the very tip_ of the voltmeter probes are being used for hit testing, not the entire silvery metal conducting-looking part.  We should made the entire tip conductive, perhaps by sampling points along it (since shape shape intersection is difficult in HTML5).  @arouinfar should we do this before MVP or is it OK for now since #58 is solved? (You can test #58 in next published version.)

**Comment by arouinfar** [comment]
@samreid, I don't think this is something we need to tackle for the MVP. Actually, I didn't notice any issues when testing #58, so I'm not sure if we need to make the entire probe tip conductive.

**Comment by arouinfar** [comment]
The voltmeter is used in several simulations, so it may be worth discussing making the entire tip conductive. But this seems more like a discussion around how a common component should behave, and less specific to CCK. I'll tag it for future discussion in design meeting.

**Comment by samreid** [comment]
The voltmeter is currently not a common component, and is specific to the CCK implementation.  It seems it would be best for the CCK or common code component to have physically correct behavior unless we don't have time to implement it properly and decide it is not too much of a problem.

**Comment by arouinfar** [comment]
Discussed 3/16/17.

The entire metallic part of the probe should be able to read voltages. @samreid will add additional sampling points (~5) to the probes.

**Comment by samreid** [comment]
May need to investigate #231 first.

**Comment by samreid** [comment]
Fixed and ready for testing on phettest.  @arouinfar can you take a look?

**Comment by samreid** [comment]
On second thought, I'll publish a dev version.

**Comment by samreid** [comment]
Dev version is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.13/circuit-construction-kit-dc_en.html

@arouinfar can you test?

**Comment by arouinfar** [comment]
Looks great! Thanks @samreid.
