### ISSUE TITLE
Model freezing in circuit with inductor and capacitor

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#772]
In https://github.com/phetsims/circuit-construction-kit-common/issues/770#issuecomment-961247642 @ariel-phet reported

@samreid I am still seeing some issues in 1.0.0-dev.43

Building a resonant circuit similar to the one above

1. Set up a resonant LC circuit as shown in the video
2. Charge the capacitor (using switch connected to the battery)
3. Isolate the capacitor (open the switch connected to the battery)
4. Get the resonant circuit going (close the switch for the LC circuit)
5. Pause the sim
6. Open the LC circuit switch, close it, then open it again
7. "Play" the sim
8. Close the LC circuit switch, for me this action freezes the sim irrevocably

https://user-images.githubusercontent.com/4051174/140386848-92b2d2df-3739-47d6-8bcf-c7f3b3a66cbf.mp4

**Comment by ariel-phet** [comment]
Need to test this with @ariel-phet will investigate with testing ?capacitorResistance=1E-4 in the latest dev version.

**Comment by ariel-phet** [comment]
@samreid I tried reproducing this bug using https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.45/phet/circuit-construction-kit-ac_en_phet.html?capacitorResistance=1E-4

With that dev version and capacitor resistance the bug does not appear, however, if I try 1.0.0-dev.45 without the `?capacitorResistance=1E-4` the bug is easily reproduced.

In my testing adding this capacitor resistance gets rid of this bug, and seems to give correct behavior otherwise.

Lets go ahead and make capacitorResistance=1E-4 the default value in the code.

**Comment by samreid** [comment]
Thanks, I adjusted the capacitor resistance to 1E-4 in https://github.com/phetsims/circuit-construction-kit-common/issues/769.  Leaving self-assigned to create a dev version for double checking.

**Comment by samreid** [comment]
The proposed inductorResistance in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.47/phet/circuit-construction-kit-ac_en_phet.html for https://github.com/phetsims/circuit-construction-kit-common/issues/774 doesn't help, however running with a profiler indicates the time is spent drawing too many charges on the capacitor:

![image](https://user-images.githubusercontent.com/679486/140847922-1bd0cbf4-9672-41d8-b352-fbef86a475a6.png)

**Comment by samreid** [comment]
Putting a 0.2 ohm resistor in series seems to help.  Also, in the worst case, it was trying to render 60,000 plus signs and another 60,000 minus signs.  I should limit that max.

**Comment by samreid** [comment]
I hypothesized that in the step, there was an unusual `dt` going to the model, but I only saw the expected values:

![image](https://user-images.githubusercontent.com/679486/140850086-fa3b2ce7-96de-45a8-bffe-78eb2d8bbab2.png)

But perhaps running the model with that tiny `dt` spikes the capacitor charge.

**Comment by samreid** [comment]
There is a bit of a spike in the inductor values:

![image](https://user-images.githubusercontent.com/679486/140850645-bde5ff4c-dfb4-4b0a-8024-b7aa71b35d36.png)

This is because:

```js
      const companionResistance = 2 * ltaInductor.inductance / dt;
      const companionVoltage = -ltaInductor.voltage - companionResistance * ltaInductor.current;
```

And we are dividing by `5E-13`.

So I'm not sure how to proceed on this model part, but at least I can fix the performance by reducing the max number of charges that can be rendered.

**Comment by stemilymill** [comment]
For https://github.com/phetsims/qa/issues/736

I'm not sure if this is helpful but it seems related: 

Several times I was able to freeze the sim in the manner shown in this video. You can still see the current still flowing here but the sim is not responsive to user input and eventually completely crashes.
This was taken with a very low frame rate, and I sped up the beginning (building the circuit) so the choppiness is not actual performance. I can work on getting a higher framerate recording.

https://user-images.githubusercontent.com/85511101/141181334-c6f1c341-487e-4651-b6fb-3dc4f92b4bae.mp4

**Comment by samreid** [comment]
I fixed the max number of charges problem in https://github.com/phetsims/scenery-phet/issues/713, but it seems we should still investigate the following:

(1) can we eliminate that inductor spike with low dt?
(2) Seeing if the previous comment was affected by the inductor spike, the capacitor charges, or something else?

**Comment by samreid** [comment]
I tested the circuit in https://github.com/phetsims/circuit-construction-kit-common/issues/772#issue-1045197327 and confirmed the problem is caused by the low values of dt, based on how we are simulating updates to the model when the sim is paused.  Currently PAUSED_DT is `5E-13` and that causes the inductor companion model values to spike, giving a 1E20 condition number for the matrix.  I did a binary search to find where the limit is for this value, and found that 1E-6 is ok for this circuit (shows normal expected charging behavior), whereas 1E-7 is not (capacitor gets immediately flooded).

If we set the PAUSED_DT to 1E-6, that means if you leave the sim paused for a full day, then `1E-6 * 60fps *60 sec/minute*60 min/hour *24 hour/day = 5.18 seconds` or around 5 seconds would elapse in the sim over the day.  That is certainly short enough that users would see things happening in the sim while paused.

I considered 2 solutions to this problem:

1. Switching to the "current source" companion model for the inductor.  However, that has an equivalent resistance of `Req=2L/dt` so would me similarly poorly conditioned for low dt.
2. Only updating the model when necessary, say, when a switch is closed or when a voltage is changed.  However, this has the problem that dragging a voltage slider back and forth would drive the sim to continuously update at 1E-6 per delta.  For normal cases, this might be OK since around 1/60 * 1E-6 ~ 16,000 events would be necessary to drive a single frame of time. 
 But for pathological circuits (poorly conditioned matrices and oscillating high current), that could cause circuit changes on every drag event.  We would also need to be careful to make sure that every property that might change a circuit behavior is observed.

I'm at a good point to check in with @ariel-phet and @arouinfar about how to proceed.

Also, since https://github.com/phetsims/circuit-construction-kit-common/issues/772#issuecomment-965690073 neither has pausing nor lagged by the number of charges drawn, I'll move it to a new issue.

**Comment by samreid** [comment]
@arouinfar and I discussed this today, and we agree that the 1E-6 paused dt seems like the most efficient solution.  I expressed concern that students may see values update while the sim is paused in that case, say, the current was 1.00 when paused, then later it reads 1.01 while paused.  @arouinfar thought that would be a rare and acceptable occurrence.  We also discussed the possibility of just triggering the update when some parameter changes, or when vertices are connected or disconnected.  In fact, since there is already infrastructure for that, we would like to try that first.  Self-assigning.

**Comment by samreid** [comment]
Let's put this on hold until https://github.com/phetsims/circuit-construction-kit-common/issues/780#issuecomment-969634307 is addressed because it has a proposal to put the dts in the numerator for the inductors.

**Comment by samreid** [comment]
We added the norton forward euler inductor and it seemed to be working ok, but we didn't want to switch between inductor models.  So we want to proceed with 1E-6 paused timestep.  I also reported that it seemed like dts were only being generated on circuit changes already.

**Comment by samreid** [comment]
We discussed this in today's design meeting.  Time will only pass when changing circuit elements.  If you drag a slider 1E6 times, that will drive time forward by one second.

@kathy-phet and @ariel-phet think this sounds reasonable.

**Comment by samreid** [comment]
I changed the paused dt to 1E-6.  I tried dragging a voltage slider for a while in the sim while paused and I didn't see anything move.  This will be ready for review on master or in next dev version.

**Comment by arouinfar** [comment]
@samreid the paused dynamics look good in dev.51 (and master). I was unable to reproduce https://github.com/phetsims/circuit-construction-kit-common/issues/772#issuecomment-965690073 with 
`?moreInductors` so I think the updates to paused dt addressed the issue. I'll leave it up to you to decide if further QA testing is necessary for this issue.

**Comment by samreid** [comment]
That seems good, thanks!  We can reopen if something is discovered in an upcoming test, but I don't think this issue needs to remain open for focused testing.  Closing.
