### ISSUE TITLE
Dog Yelp sound absent in virtual lab

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#777]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/736

The dog usually makes a yelping sound when it experiences a large amount of current. This occurs in the AC version, but not in the standalone virtual lab. I wasn't sure if that was intentional or not. I noticed that the published versions of both CCK DC and CCK DC Virtual Lab have sound. 

**Steps to reproduce**
1. Build the circuit shown
2. Once the battery goes on fire, open the switch next to the battery

**Visuals**
Standalone Virtual lab:

https://user-images.githubusercontent.com/87318828/141197796-6615d896-53fe-426d-8899-fa5916dff3f7.mov

CCK AC:

https://user-images.githubusercontent.com/87318828/141197881-ccb406e4-3ef0-4c17-8d38-a691ef7dc370.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC - Virtual Lab‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-dev.1/phet/circuit-construction-kit-ac-virtual-lab_all_phet.html
Version: 1.0.0-dev.1 2021-11-09 19:39:46 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1440x698
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
@samreid I don't see the tambo sound button in the navbar, so it looks like you haven't enabled audio in this sim.

**Comment by samreid** [comment]
Fixed and will be ready for confirmation in the next dev version.

**Comment by samreid** [comment]
Published in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-dev.2/phet/circuit-construction-kit-ac-virtual-lab_en_phet.html, @Nancy-Salpepi can you please verify and close if all is well?

**Comment by Nancy-Salpepi** [comment]
The tambo sound button is now on the nav bar and the dog yelping sound can be heard.
