### ISSUE TITLE
Phase shift doesn't work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#779]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/736.
Changing the phase on the ac sources does not seem to shift their phase from any of the other sources. If watching on a current probe, a spike occurs as you move the control, but the current returns to it's previous wave with no phase shift.

**Visuals**
![nophaseshift](https://user-images.githubusercontent.com/41024075/141364536-30b4f1a0-cd90-4011-ba07-fa31dba53a98.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.48/phet/circuit-construction-kit-ac_all_phet.html
Version: 1.0.0-dev.48 2021-11-09 19:35:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
In the gif above, you can see the two waves going out of phase:

![image](https://user-images.githubusercontent.com/679486/141594288-a3efd765-1027-42e1-92a8-31cc96317b6a.png)

Note the upper wave is headed down and the lower wave is headed up.  I tested and everything seems to be behaving as expected as far as I can see.  The spikes are not desirable but are a natural consequence of the sudden change in voltage.

@arouinfar can this issue be closed?

**Comment by samreid** [comment]
In today's discussion, @arouinfar commented that the phase shift is working, and @arouinfar will make a note in the teacher tips that the spikes are a natural physical response.  We will open a side issue about changing the delta from 10 to 15.

**Comment by arouinfar** [comment]
Added to the Teacher Tips issue, closing.
