### ISSUE TITLE
Unable to zoom on charts on iPad

### ISSUE THREAD

**Issue by stemilymill** [phetsims/circuit-construction-kit-common#782]
For https://github.com/phetsims/qa/issues/736.

Device: iPad Pro (10.5-inch)
iPadOS 15.0
Using Chrome 96.0.4664.36 and Safari

I am unable to zoom in or out on charts on iPad. The buttons do not respond.
However, the general zoom buttons work fine.

**Comment by samreid** [comment]
Thanks, good find!

**Comment by samreid** [comment]
I reached out for help on Slack:

> I’m getting mouse events but no touch events for the cck ac chart zoom buttons.  Any ideas?
> I checked the mouse areas weren’t buggy.
> I tested putting the buttons in this.addChild  instead of in the ChartNode and that fixes it, but it throws off the layout.
> You can reproduce the problem by launching CCK AC in the browser.  Then go to chrome dev tools and simulate a touch device.

**Comment by samreid** [comment]
I also tried swapping out the zoom buttons for a ResetAllButton with console.log, and that didn't fix the problem.  So the problem is extrinsic to the zoom button group.

**Comment by samreid** [comment]
@jessegreenberg said:

> Not sure why it would be for touch and not mouse, but is it related to this https://github.com/phetsims/scenery/issues/1150?

**Comment by samreid** [comment]
If I remove the drag listener from the backgroundNode, then the zoom buttons get mouse events.
It could be related to #1150
Yes, it sounds a lot like that problem case.
I can’t figure out how to apply the remedy “Having the non-interactive foreground set to pickable:false prevents this.” to this case.

Or why it only applies to touch but not mouse.

**Comment by jessegreenberg** [comment]
If I add `allowTouchSnag: false` to the DragListener options that also seems to fix it.

**Comment by samreid** [comment]
Thanks @jessegreenberg, that's the best solution yet.  I still don't understand the root cause but this may be good enough for publication.  Assigning @jonathanolson to ask about the root cause.  Assigning @arouinfar to ask if it is OK to disable touchSnag on the chart (while in the play area).

**Comment by arouinfar** [comment]
> Assigning @arouinfar to ask if it is OK to disable touchSnag on the chart (while in the play area).

That sounds acceptable to me. While in the play area, the charts are very large so I don't think touch snag adds anything to the experience. (I'd still want it for grabbing items out of the carousel and toolbox, though.)

**Comment by samreid** [comment]
Leaving open to verify on a touch device in the next dev version.

**Comment by ariel-phet** [comment]
The issue I was seeing previously with not being able to use the zoom in/out buttons on the current/voltage charts is working well on my Android 12 phone in chrome with dev 1.0.0-dev.51

**Comment by arouinfar** [comment]
This also looks good on my phone, but let's have QA verify on iPad in the next test cycle.
