### ISSUE TITLE
Unexpected charge distribution for series capacitors

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#786]
Discovered by @ariel-phet in https://github.com/phetsims/circuit-construction-kit-common/issues/784#issuecomment-976211615:

> In this second video if you discharge one of the capacitors while it is connected to the battery the charge does not redistribute as expected. Since these are identical capacitors the steady state solution should be for them to have identical charge on them. If you then unhook the voltage source and short the capacitors instead of discharging the charge redistributes in a very unphysical way (notice the two capacitors have opposite plate charges)

https://user-images.githubusercontent.com/4051174/142982784-cab76537-c9bb-49ef-ad29-4f822e0e0fa0.mp4

**Comment by samreid** [comment]
This issue needs to be on hold until #784 is corrected.

**Comment by samreid** [comment]
@ariel-phet and @arouinfar and I discussed this today, and it appears the behavior is correct.  When the left plate is discharged, then current flows until the voltage drop across both capacitors equals the battery voltage.  Since the right plate had a "head start", and the same current flows across both plates, the right plate ends up with more net charges.  @ariel-phet can this issue be closed?

**Comment by ariel-phet** [comment]
@samreid yes I think so. In case questions arise I did find this reference:

*The effect of trapped charge on series capacitors*
https://aapt.scitation.org/doi/10.1119/1.4916888

PDF available here (through CU library access)
https://aapt-scitation-org.colorado.idm.oclc.org/doi/pdf/10.1119/1.4916888
