### ISSUE TITLE
When should we record the user-created circuits?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#79]
For the research project, when should we record the user-created circuits?  Just when pressing "reveal", or continuously (as a function of time as it is being built?)

**Comment by arouinfar** [comment]
I would imagine that data would need to be recorded while the circuit is being built, not just when "Reveal" is pressed, but this is probably something @samreid should discuss with Engin. 

Data outfitting is not necessary for the MVP, but is likely a desired feature for the upcoming classroom study this Fall.

**Comment by samreid** [comment]
In the above commit, I'm outputting the circuit whenever topology changes or a circuit component is edited (same rules as for when the circuit is paused when ?showPauseButton) is used.
