### ISSUE TITLE
Clickable area of capacitors does not include middle of capacitor when not a schematic

### ISSUE THREAD

**Issue by stemilymill** [phetsims/circuit-construction-kit-common#790]
For https://github.com/phetsims/qa/issues/747.

The clickable area for the capacitor does not match the highlight box that appears when the capacitor is selected, and clicking in the area between the plates when the capacitance is low does not select the capacitor. In the schematic view, the clickable area is a rectangle  around the entire capacitor element.

I'm not sure if this is intentional or a bug, but it seems weird to me while playing with the sim and did make it slightly difficult to select the capacitor with touch input when capacitance was low.

![clickable area capacitor](https://user-images.githubusercontent.com/85511101/144142999-b9a1d747-e0e3-4189-afb3-82dead78d6b3.png)

![capacitor clickable area schematic](https://user-images.githubusercontent.com/85511101/144143015-8e64f5fd-9bb3-48ef-ade2-abfe3dd3d465.jpg)

Even when the plates appear to overlap but are actually not, clicking in the very center does not select the capacitor.

https://user-images.githubusercontent.com/85511101/144143202-36145b14-2994-4e28-81a9-e393d70ff42b.mp4

**Comment by KatieWoe** [comment]
To clarify, the mouse, at least, only clicks on the actual plates, rather than the space in between. When the plates are far apart this may cause issues, and may seem odd.

**Comment by samreid** [comment]
@arouinfar how should this behave?

**Comment by arouinfar** [comment]
@samreid can you extend the pointer areas of the lifelike capacitor to include the space between the plates? 

As an aside, the selection box around the schematic capacitor should be expanded. It currently looks like this:
![image](https://user-images.githubusercontent.com/8419308/144304498-fcab36e0-5d54-41b3-88f2-07c2b6f59e86.png)

**Comment by samreid** [comment]
Thanks, I moved that last request to a new issue.

**Comment by samreid** [comment]
I didn't see an easy way to add the hit area just between the plates (leaving the rest of the fine-grained hit area), so I added a rectangle hit area like so:

![image](https://user-images.githubusercontent.com/679486/144307486-328aeae8-1b38-4200-af54-629ffc8411a6.png)

@arouinfar does that seem OK?

**Comment by samreid** [comment]
I eroded it vertically a bit more in the commit, now it is more like:

![image](https://user-images.githubusercontent.com/679486/144307848-11cf8c9b-f80d-4ee4-8cc8-ce7df7bd330b.png)

**Comment by samreid** [comment]
@arouinfar and I reviewed this and agreed it seems ok, closing.
