### ISSUE TITLE
Flipping battery briefly leads to wrong sign for in line ammeter (and sometimes other ammeters)

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#793]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/748.
If you switch the direction of a battery before connecting a circuit, it will give a positive current, but may give a negative current for the first frame before switching to positive. This can best be seen with the in-line ammeter on the lab screen, but I have managed to get this to occur with the out of line ammeter on the RLC screen (but not the lab screen). I have, so far, not reproduced this with the graph ammeter.
**Steps to reproduce**
EDIT: Make sure the signed option for the ammeters is turned on!

In-line:
1. Go to the lab screen
2. Drag out a battery and switch it's polarity (this step can be done any time before finishing the circuit)
3. Build a circuit with a battery and in-line ammeter using the battery, do not connect it yet.
4. Pause the sim
5. Connect the rest of the circuit
6. Step forward a frame

Out-of-line ammeter:
1. Go to RLC screen
2. Build a circuit with a battery, lightbulb, and switch, with an ammeter viewing the current
3. Turn on the circuit with the switch
4. Turn off the circuit with the switch
5. Pause the sim
6. Flip the battery
7. Turn on the switch
8. Step forward the sim

**Visuals**
![swapbattery1](https://user-images.githubusercontent.com/41024075/144651339-fc8da1cb-a1f7-44c5-aaee-0405dd9aafb6.gif)
![swapbattery2](https://user-images.githubusercontent.com/41024075/144651348-7604508f-c231-412c-862f-21e1a9b3f567.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: AC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-rc.1/phet/circuit-construction-kit-ac_all_phet.html
Version: 1.0.0-rc.1 2021-12-03 15:30:26 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
May be related to https://github.com/phetsims/circuit-construction-kit-common/issues/606

**Comment by KatieWoe** [comment]
The second example also happens on the first screen.
<img width="953" alt="firstscreen" src="https://user-images.githubusercontent.com/41024075/144683454-b98405a5-3b8e-4e4c-80d3-74074fbe1be1.png">

**Comment by CliffordH123** [comment]
Tested on Windows 10 Firefox and wasn't able to reproduce it. May be Windows 11 related in some way

**Comment by KatieWoe** [comment]
Just realized I forgot to add the step of turning on the signed option in the option menu. I was unable to reproduce on iPad until I remembered. Sorry, added to the instructions.

**Comment by Nancy-Salpepi** [comment]
also seen with mac + chrome

**Comment by samreid** [comment]
I was able to reproduce the problems, thanks for the good find and instructions!  I pushed separate fixes for the series ammeter and non-series ammeter.  They both needed to listen for the currentSenseProperty, but they have different pipelines for it.  Ready for cherry picking and testing in next RC.

**Comment by KatieWoe** [comment]
This looks fixed in rc.2. Will reopen if something shows up.
