### ISSUE TITLE
iPad Reloads

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#798]
For https://github.com/phetsims/qa/issues/748
On iPadOS 15.1, with the query parameter `?showPointerAreas`, the sim crashed and reloaded after a few minutes of use. This seems similar to https://github.com/phetsims/molecule-shapes/issues/206

**Comment by KatieWoe** [comment]
This happened after I set up an AC circuit with a lightbulb and let it run for a few minutes.

**Comment by stemilymill** [comment]
I have tried to reproduce this several times, and been unable to. I am using iPad pro iPadOS 15.0. I'm going to update to 15.1 and try to reproduce again.

**Comment by arouinfar** [comment]
@stemilymill can you also try to reproduce https://github.com/phetsims/molecule-shapes/issues/206?

**Comment by KatieWoe** [comment]
I tried without `?showPointerAreas` and it didn't seem to happen.

**Comment by stemilymill** [comment]
I was unable to reproduce with iPadOS 15.1, and thus far also unable to reproduce https://github.com/phetsims/molecule-shapes/issues/206

**Comment by KatieWoe** [comment]
After a few minutes testing this on the iOS 14.8 device, I didn't see it there either.

**Comment by samreid** [comment]
@arouinfar and I discussed this today, we recommend creating a scenery-specific issue.  However, it is an internal query parameter, and not reproducible across different devices.  @arouinfar says it doesn't need to be fixed before publishing 1.0.  On the other hand, if there is a fix it could be good to cherry pick.

**Comment by samreid** [comment]
There has been no progress in https://github.com/phetsims/scenery/issues/1326 and I don't think we need to keep this issue on our radar (but I wonder if QA searches closed issues when seeing if an issue has already been reported).  Closing.
