### ISSUE TITLE
Current not read in junction between two AC source

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#807]
Discovered in testing https://github.com/phetsims/qa/issues/752

@samreid while testing 1.0.0-rc.2 I noticed that if you try to read the current on the current chart in the junction between two AC sources you get a "null" reading. Seems like there should still be a current read out in this case. Does not block publication, but seems worthy of noting as an issue.

Example:

https://user-images.githubusercontent.com/4051174/145916790-08dd3b50-d407-4c48-8965-9185ce2d853d.mp4

**Comment by samreid** [comment]
I'll triage this for next publication with phet-io.

**Comment by arouinfar** [comment]
@samreid @matthew-blackman thanks for investigating. I agree that we can close this as wont-fix, but I should update the CCK: AC Teacher Tips first.

**Comment by arouinfar** [comment]
Teacher tips updated and uploaded to the site, closing.
