### ISSUE TITLE
AC-specific circuit elements and features should not appear in the DC studio tree

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#824]
AC-specific circuit elements and features should not appear in the DC studio tree

**Comment by samreid** [comment]
I wrote on slack:

> I was going to have the capacitorGroup OPT_OUT of tandem, but tandem is required in PhetioGroup.  Should I skip creating the group altogether, or make tandem optional for PhetioGroup?

It's worked well to have AC and DC share as much code as possible, and I don't want to complicate the type hierarchy unless necessary.  @zepumph can you please advise?

**Comment by samreid** [comment]
Also, @arouinfar can you comment what should be excluded from DC?  Anything other than capacitors, inductors, AC sources and their corresponding controls?

**Comment by zepumph** [comment]
I was going to recommend passing an option through to the Class creating these groups, so that AC can tell it to create and instrument these.

>and I don't want to complicate the type hierarchy unless necessary.

Does this mean would prefer not to do this?

If you want to make PhetioGroup Tandem.OPTIONAL, go for it.

**Comment by samreid** [comment]
> I was going to recommend passing an option through to the Class creating these groups, so that AC can tell it to create and instrument these.

So the type would be `PhetioGroup<Capacitor> | null` ?  I considered creating `ACCircuit extends Circuit` but what if in the future we have a variant of CCK that has capacitors but not inductors?  We have talked about CCK "Intro" and energy-focused CCK variants, so we may need to be able to support arbitrary combinations.

**Comment by samreid** [comment]
The real light bulb is only available on the Lab screen.  Do we need to omit the realLightBulbGroup from the intro screen?

**Comment by zepumph** [comment]
It does not bother me to have PhetioGroup tandem optional. This of course means making if Tandem.OPTIONAL in PhetioDynamicElementContainer. Will you just document the reason to avoid future confusion, something like, "Many PhET-iO instrumented types live in common code used by multiple sims, and may only be instrumented in a subset of their usages."

**Comment by samreid** [comment]
> The real light bulb is only available on the Lab screen. Do we need to omit the realLightBulbGroup from the intro screen?

@arouinfar and I discussed it, the realLightBulb shouldn't appear in the tree in screen 1.  Same with the high voltage battery and high resistance resistor and bulb, they shouldn't be in the intro screen.

> Anything other than capacitors, inductors, AC sources and their corresponding controls?

@arouinfar indicated the charts should be excluded from DC.

**Comment by samreid** [comment]
@zepumph can you please review https://github.com/phetsims/tandem/commit/3750a57bf4f09cab72343b55de4e8e012fd37d72 ?  It was failing with an assertion error before that commit.

**Comment by arouinfar** [comment]
@samreid here are the irrelevant elements that I'm currently seeing in the tree:

AC-Specific elements:
- [ ] `circuitConstructionKitDc.*Screen.model.stopwatch`
- [ ] `circuitConstructionKitDc.*Screen.view.circuitElementEditContainerNode.frequencyControl`
- [ ] `circuitConstructionKitDc.*Screen.view.circuitElementEditContainerNode.phaseShiftControl`

Lab Screen-specific elements:

- [ ] `circuitConstructionKitDc.introScreen.model.addRealBulbsProperty`
- [ ] `circuitConstructionKitDc.introScreen.model.circuit.highResistanceLightBulbGroup`
- [ ] `circuitConstructionKitDc.introScreen.model.circuit.highVoltageBatteryGroup`
- [ ] `circuitConstructionKitDc.introScreen.model.circuit.realLightBulbGroup`
- [ ] `circuitConstructionKitDc.introScreen.model.circuit.seriesAmmeterGroup`
- [ ] `circuitConstructionKitDc.introScreen.model.sourceResistanceProperty`
- [ ] `circuitConstructionKitDc.introScreen.model.wireResistivityProperty`
- [ ] `circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.highResistanceNumberControl`
- [ ] `circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.highVoltageNumberControl`
- [ ] `circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.lightBulbHighResistanceNumberControl`
- [ ] `circuitConstructionKitDc.introScreen.view.circuitNode.highVoltageBatteryNodeGroup`
- [ ] `circuitConstructionKitDc.introScreen.view.circuitNode.seriesAmmeterNodeGroup`

**Comment by zepumph** [comment]
Looks great! Thanks.

**Comment by samreid** [comment]
OK I added guards for "this is only in the AC sim" and "this is only in the lab screen" and updated following the checklist above.  @arouinfar can you please test and spot check?

**Comment by arouinfar** [comment]
@samreid I verified the list in https://github.com/phetsims/circuit-construction-kit-common/issues/824#issuecomment-1024729218 but found a few more Lab-only elements to remove from the Intro Screen:

- [ ] `introScreen.view.circuitNode.highResistanceLightBulbNodeGroup`
- [ ] `introScreen.view.sensorToolbox.seriesAmmeterNodeIcon`
- [ ] `introScreen.view.sensorToolbox.seriesAmmeterToolNode.visibleProperty`

I also realized that these properties still provide important information on the Intro Screen and I should not have asked you to remove them. Please return these to the Intro Screen:
- [ ] `model.sourceResistanceProperty`
- [ ] `model.wireResistivityProperty`

**Comment by samreid** [comment]
I adjusted the five requests in the commit.  @arouinfar can you please review/test?

**Comment by arouinfar** [comment]
Looks good, thanks @samreid

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/772

The clear button (view.circuitElementEditContainerNode.clearButton) should be removed from the studio tree (Confirmed with @arouinfar that this button is only for inductors/capacitors which aren't present in DC).

**Comment by arouinfar** [comment]
This is something that should be cleaned up for publication, but I don't think it will have any ill effects on the client, so I switched the milestone.

**Comment by samreid** [comment]
Today we discussed reverting the "lab" specific features, so those are more unified.  I can revert those commits.

**Comment by samreid** [comment]
Just wanting to clarify the convention before I start on this issue.  In Circuit Construction Kit: DC, the Intro screen should support natural features from the Lab screen?  But none of the features from AC?

**Comment by arouinfar** [comment]
> In Circuit Construction Kit: DC, the Intro screen should support natural features from the Lab screen? But none of the features from AC?

Yes, that seems reasonable @samreid. My takeaway from https://github.com/phetsims/geometric-optics-basics/issues/3 is that we do not need to aggressively prune the tree to remove features that could *safely* be turned on in other screens/flavors of a sim, especially when the differences are largely subtractive in nature. In the future, derivative simulations could potentially be created by clever use of `visibleProperty`, much like CM did when creating Geometric Optics: Basics.

That said, we should not add AC-only features to DC (AC sources, capacitors, inductors, charting tools) and similarly, we shouldn't include DC-only components (high-voltage and high-resistance components) in AC because they have not been tested in an AC environment and go beyond the scope of the learning goals. 

I think it's fine for Lab screen components to make an appearance in the tree of the Intro screen, so long as the feature is fully functional. I see no harm in PhET-iO clients adding series ammeters or high-V batteries to the Intro screen, for example.

**Comment by matthew-blackman** [comment]
The clear button no longer appears in studio in DC mode. @samreid and I confirmed that DC studio does not show any inductors or capacitors.

**Comment by matthew-blackman** [comment]
Cross-linking issue #900 in separate milestone for AC release
