### ISSUE TITLE
currentTypeProperty should use the new enumerations pattern, and UPPERCASE values

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#827]
currentTypeProperty should use the new enumerations pattern, and UPPERCASE values.  See if there are more cases like this.

**Comment by samreid** [comment]
Fixed in the commits.  Should be reviewed/tested.  @arouinfar can you please test each of the features above briefly to make sure there were no regressions?

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid
