### ISSUE TITLE
Bits of ammeter visible in Intro screen play area on startup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#829]
Possibly related to #824.

After pulling all and clearing my cache, there are bits of an ammeter wallpapered to the Intro Screen. Master currently looks like this: 
![image](https://user-images.githubusercontent.com/8419308/151853098-f4e38352-649f-4098-ad0a-532abaa94df0.png)

**Comment by samreid** [comment]
Thanks, it was caused by https://github.com/phetsims/circuit-construction-kit-common/issues/824.  Fixed in the commit and ready for testing.

**Comment by arouinfar** [comment]
Thanks @samreid, looks good in master
