### ISSUE TITLE
Circuit elements still movable when `isMovableProperty` is false

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#830]
Discovered while reviewing #797 

Steps to reproduce:
1. Open sim in Studio.
2. Drag any element out of the carousel.
3. Hold down ctrl to navigate the tree the circuit element's model.
3. Set the element's `isMovableProperty` to false.
4. Drag the circuit element around the play area. It's still movable!

**Comment by samreid** [comment]
In https://github.com/phetsims/circuit-construction-kit-common/issues/797#issuecomment-1018726700 we decided to control CircuitElement movability via the adjacent vertices.  It was an error that `CircuitElement.isMovableProperty` still remained, so I removed it in the commit.  @arouinfar does this seem good to you?

**Comment by arouinfar** [comment]
Thanks for the reminder @samreid. I no longer is any instances of `isMovableProperty` in the tree, so I'll go ahead and close.
