### ISSUE TITLE
When joined, vertices should retain non-default values from either parent.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#833]
In https://github.com/phetsims/circuit-construction-kit-common/issues/797 @kathy-phet said:

> I think the issue can be documented, and noted as existing. If you see a clear pattern for improvement - and its doable - I would recommend it.
> 
> My recommendation would be ...
> Any property that is not the "default" setting should OVERWRITE/TAKE PRECEDENCE. So if there is a label on the existing vertex, it should persist onto the new vertex. Or we should make a hierarchy, e.g. if one vertex is not moveable, that vertex should remain. and so forth.

**Comment by samreid** [comment]
Fixed in the commit and seems to be working correctly. @arouinfar or @kathy-phet would you like to review/test?

**Comment by arouinfar** [comment]
@samreid @kathy-phet I think the behavior in master is fine for the client preview version.

Joining vertices will retain properties appropriately, but cutting a vertex destroys the old one and creates new vertices that all revert to the default behavior. Clearing the `labelTextProperty` seems reasonable in this case, but I wouldn't expect the `draggableProperty` to change necessarily.

**Comment by kathy-phet** [comment]
Yes, this seems a bit problematic regarding blowing away labels when you cut the vertex. But seems OK for client preview. We can discuss various scenarios and behaviors ... and see what might be the best pattern. I assume hitting reset gets you the label back, so that seems good.

**Comment by samreid** [comment]
Based on the remarks, it seems we should move this to the next milestone.

**Comment by arouinfar** [comment]
We reviewed this in the 2/24/22 design meeting and decided that the current behavior is acceptable, but I've added a note in #865 to discuss how vertex properties are handled when combined/split.
