### ISSUE TITLE
Vertex boolean properties should have `is` prefix

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#834]
Discovered in #797 

Vertices have `draggableProperty` and `selectedProperty` which both behave nicely. However, the name is a bit of a departure from the other boolean properties such as `isEditableProperty` and `isCuttableProperty` (to name a few). 

@samreid I think it would be nice to continue with the `is` prefix here too, but it can wait until the full release.

**Comment by samreid** [comment]
This would be good to do before the imminent milestone.

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by arouinfar** [comment]
Looks good, thanks @samreid
