### ISSUE TITLE
Voltage and current readings misaligned in Studio and State Wrappers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#837]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/772, when the sim is launched in studio, the word "voltage" and the voltage reading are shifted to the right. 

**Steps to reproduce**
1. In studio: on either screen make a simple circuit like the one shown below. Close switch.
2. Attach voltage meter.
3. Launch sim. 

**Visuals**
<img width="619" alt="Screen Shot 2022-02-03 at 8 40 57 AM" src="https://user-images.githubusercontent.com/87318828/152353974-e97b80c4-ed89-4f4b-8d0d-817eede31bc9.png">

**Comment by Nancy-Salpepi** [comment]
In both the Studio and State Wrappers, when the switch is open--both the voltage and current readings will be misaligned in the launched/downstream sim. 

Steps:
1. In the intro screen, create a simple circuit with battery, switch and bulb. Leave the switch open.
2. Attach ammeter and voltmeter
3. In studio: Launch sim
4. Close switch--values will move to proper place.
![readingsStudio](https://user-images.githubusercontent.com/87318828/152546578-694962d5-9928-4ea6-bad4-2aee361dba3e.gif)

**Comment by KatieWoe** [comment]
The adjustment to being in the proper place seems to occur when the voltage readout changes.

**Comment by arouinfar** [comment]
This looks pretty serious. 

@samreid I'm going to add this issue to the preview milestone. If it's not feasible to patch, we should at least alert the client about this particular bug.

**Comment by samreid** [comment]
I traced this problem to the surprising fact that the text bounds are not updating right after text set:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/679486/153532637-56234787-a569-432d-92f0-5dd68a199acb.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/679486/153532623-66253504-b0ec-4b51-ae40-3cb7bc4523a8.png">

@jonathanolson is this a known scenery aspect?

**Comment by samreid** [comment]
Can you please test/review this on master using phettest?  Please close if it seems corrected.

**Comment by Nancy-Salpepi** [comment]
Looks good @samreid!
