### ISSUE TITLE
negative ammeter readings not maintained in Studio and State wrappers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#839]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/772

In Studio and State wrappers, the negative sign for current doesn't appear in the downstream/launched sim. This happens on both screens. 

**Steps to reproduce**
In State:
1. Make a simple circuit in the intro screen
2. Attach ammeter
3. Go to PhET-iO menu > Options to select "signed" for ammeter readout
4. Reverse battery in the circuit--the upstream sim will have a negative reading while the downstream sim in still positive

**Visuals**
<img width="520" alt="Screen Shot 2022-02-04 at 8 03 07 AM" src="https://user-images.githubusercontent.com/87318828/152534989-8b780b5b-533b-47c0-b8ae-cd13109926d6.png">

**Comment by arouinfar** [comment]
@samreid I'm tagging this for the preview milestone to make sure we let the client know that this is a known bug. However, I don't think it needs to be fixed until the production version.

**Comment by arouinfar** [comment]
I've documented this as a known issue, so switching the milestone

**Comment by samreid** [comment]
I fixed this by instrumenting the current sense property, closing.
