### ISSUE TITLE
Carousel scrolling occurs after sim is launched in Studio

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#841]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/772

In Studio, if the sim is launched when the carousel is on page 2,3, or 4 the carousel scrolls to that page after launch instead of already being on that page. This happens on both screens.

**Steps to reproduce**
1. In the Studio wrapper go to either screen
2. Navigate to another page of the carousel
3. Launch sim
4. Press the 'reset all' button

**Visuals**
![carousel](https://user-images.githubusercontent.com/87318828/152557145-12900be3-2137-4d34-99c3-8feb9d801bad.gif)

**Comment by arouinfar** [comment]
This is the first (modern) PhET-iO sim with a carousel, and the design pattern hasn't been established yet. This bug is a bit unsightly, but I don't think it's terribly harmful. 

I'm going to tag this for the preview milestone to include a blanket statement that carousel is a bit quirky and subject to change as we establish the design pattern.

**Comment by arouinfar** [comment]
I've documented this as a known issue, so switching the milestone to production.

**Comment by arouinfar** [comment]
Unsurprisingly, this is also present in https://github.com/phetsims/qa/issues/774

@KatieWoe reported in #863 

> **Device**
Dell
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/774
On the lab screen, if you have the real bulb activated in studio and launch the sim, the carousel will be on the last page even if isn't meant to be.
>**Steps to Reproduce**
>1. Go to the lab screen in studio
>2. Turn on the real bulbs
>3. Scroll the carousel back to the top
>4. Launch the sim
>
>**Visuals**
>![wrongpage](https://user-images.githubusercontent.com/41024075/154353240-2f190251-909e-4fbe-bac0-4d10b6ffa7da.gif)

**Comment by samreid** [comment]
In the commit, carousel animation is skipped during setting phet-io state.  It appears to correct this problem.  @arouinfar can you please review in master?

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid.

**Comment by samreid** [comment]
Thanks, closing.
