### ISSUE TITLE
Taking out fuse and putting it back prevents launching sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#843]
**Device**
Dell
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/772. If you take the fuse out of the carousel, and then put it back, a launched sim from studio will no longer load. The console throws an error that says it is impossible to set state. In order to fix this you need to refresh the studio page.

**Steps**
1. Go to the lab screen in studio
2. Drag out the fuse
3. Drag the fuse back to the carousel
4. Launch the sim

**Visuals**
<img width="960" alt="impossibletosetstate" src="https://user-images.githubusercontent.com/41024075/152590640-e0f2f3f6-1683-4cf2-a0fd-cdec49eac6b9.png">
![consoleerror](https://user-images.githubusercontent.com/41024075/152590642-1e2b601e-f828-49b3-a056-f2a0fa484993.gif)

**Comment by KatieWoe** [comment]
Doesn't seem to happen to the state wrapper unless you press the launch button.

**Comment by arouinfar** [comment]
@samreid this looks like a bug that can negatively impact the client's usage. I recommend we try fixing this before sending the client another version, but if that's not feasible it should be documented as a known bug.

**Comment by samreid** [comment]
Fuse.isRepairableProperty was not being disposed.  That was corrected in https://github.com/phetsims/circuit-construction-kit-common/commit/df80074f680e0ac01fbe705e50ddbd0496bc24f7.  This is likely fixed, and ready for testing in next dev version.

**Comment by samreid** [comment]
Can you please test/review this on master using phettest?  Please close if it seems corrected.

**Comment by KatieWoe** [comment]
Looks fixed on master
