### ISSUE TITLE
Carousel's Next/Previous buttons do not stay disabled in Studio

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#844]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/772 in the Studio Wrapper:

If the previous button and next button are disabled, they will be enabled when the sim is launched. 
This happens on both screens. 

**Steps to reproduce**
1. In studio, navigate to the second page of the carousel on either screen
2. Disable the previous button (view.circuitElementToolbox.carousel.previousButton.enabledProperty)
3. Disable the next button (view.circuitElementToolbox.carousel.nextButton.enabledProperty)
4. Launch the sim

**Visuals**
![carouselbuttons](https://user-images.githubusercontent.com/87318828/152592178-22362a81-9eb4-42f8-9d32-542a05ed961f.gif)

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. I think the solution here is that `carousel.nextButton.enabledProperty` and `carousel.previousButton.enabledProperty` should be phetioReadOnly: true. However, that should be handled in a separate issue for the PhET-iO design patterns for carousel. Self-assigning to open an issue in sun.

**Comment by arouinfar** [comment]
Design issue for carousel linked above, closing.

**Comment by KatieWoe** [comment]
This has not been done in the newest dev. Reopening for https://github.com/phetsims/qa/issues/774
<img width="960" alt="notdone" src="https://user-images.githubusercontent.com/41024075/153957387-80424f23-660e-41f9-b6be-117213f8cd91.png">

**Comment by arouinfar** [comment]
Thanks @KatieWoe this issue will be addressed in https://github.com/phetsims/sun/issues/736 where the button's `enabledProperty` will be made read-only.
