### ISSUE TITLE
Value location interferes with ability to select circuit element

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#845]
**Test device**
iPad Air 2
**Operating System**
15.2

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/772

On either screen, when the values checkbox is selected and the voltage is negative, the voltage value appears in the middle of the battery. This makes it difficult to select the battery--especially on the iPad (but also with the trackpad on my mac).  Is it possible to  change the location of the voltage value to below the battery or keep it above the battery like with positive values?

**Steps to reproduce**
1. On the iPad, make a circuit and attach the voltmeter
2. Check the 'values' checkbox
3. Flip the battery--the value moves over the battery instead of above it
4. Tap the screen so the battery is no longer selected.
5. Try to select the battery

**Visuals**

https://user-images.githubusercontent.com/87318828/152841428-aadf70c9-04a8-4128-b935-e801be84bb71.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.14/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.3.0-dev.14 2022-02-01 01:48:26 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1409x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi, this looks like a bug to me. The location of the value display should not depend on the battery's orientation. It's also a bit odd that the value blocks the pickability of the battery itself, but I don't know if that is to be expected or not.

**Comment by Nancy-Salpepi** [comment]
Thanks @arouinfar!
I just went back and looked at the published version of CCK-AC and the value location changes from top to bottom when the battery is flipped. 
![voltagevalue](https://user-images.githubusercontent.com/87318828/152858076-ae593599-8c1c-4e95-b1d3-5ed5015ecbd7.gif)

**Comment by arouinfar** [comment]
Oh, good to know @Nancy-Salpepi!

@samreid since this affects sim usability, I'm going to tag it for the preview milestone. It should either be patched or documented as a known bug.

**Comment by arouinfar** [comment]
@KatieWoe also reported this issue in #847

**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/772.
This does not seem to be as much of an issue in published, as upside down elements are not as fully covered by their values label. In the dev version, if certain elements are upside down (such as by flipping the battery) the values label can cover the entire element and clicking on it does not focus on it so you can't change voltage etc.



**Visuals**
In published:
<img width="959" alt="pubupsidedown" src="https://user-images.githubusercontent.com/41024075/152863382-d4d1c86f-bed5-4d23-aa74-8bad435969a4.png">
In dev:
![values_in_way](https://user-images.githubusercontent.com/41024075/152863407-3f770536-491c-4691-88c6-f18aabd8c1ff.gif)

Noting that this can also make dragging objects more difficult. It is particularly bad with fuses.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.14/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.3.0-dev.14 2022-02-01 01:48:26 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Feb 10 design check-in: For the client preview, making the label non-pickable is sufficient.  For the full version, the labels should be in the correct locations.

**Comment by arouinfar** [comment]
Thanks @samreid. The behavior in master is reasonable for the client preview and is definitely an improvement. 

We can defer addressing the label location until the next milestone.

**Comment by samreid** [comment]
@arouinfar what is the desired location for the label?  The current version shows this behavior:

![Kapture 2022-02-18 at 17 56 44](https://user-images.githubusercontent.com/679486/154779364-395a53f0-6450-4395-8d6d-630bb1e4c830.gif)

I wonder if it ended up that way in part because it prevents some overlap when creating loops?

@arouinfar please advise.

**Comment by arouinfar** [comment]
@samreid the location of the label generally looks good as the component is rotated, but perhaps the label could pop back up to the top when it reaches 180°.

**Comment by samreid** [comment]
This commit prefers to put the label above the circuit element, the rest of the logic is the same:

![Kapture 2022-08-27 at 17 23 19](https://user-images.githubusercontent.com/679486/187051294-ac9a6606-da7e-4625-965a-c39cf8bff0f9.gif)

**Comment by arouinfar** [comment]
Looks great, thanks @samreid!
