### ISSUE TITLE
Going to a non-existent carousel page freezes sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#848]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/772. May be related to https://github.com/phetsims/circuit-construction-kit-common/issues/844. There isn't a reason for doing this that I can think of, but since it causes a crash I'm still documenting.
If you go to the element `circuitConstructionKitDc.introScreen.view.circuitElementToolbox.carousel.previousButton.enabledProperty` and enable the previous button while on the first carousel page, then try to go to a previous page, the whole page freezes with the below console error.
**Visuals**
<img width="344" alt="console" src="https://user-images.githubusercontent.com/41024075/152882662-a9aa0cd5-2aff-4fde-bcb7-4ed6e0fb30de.png">
![frozenstudio](https://user-images.githubusercontent.com/41024075/152882664-3eb8da99-c62d-411d-8442-288ae7acfd5e.gif)

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

The solution here is the same as the solution to #844 -- `carousel.nextButton.enabledProperty` and `carousel.previousButton.enabledProperty` should be phetioReadOnly: true. I'll self-assign to open up the appropriate carousel design issue in sun.

@samreid I do not think there is any reason for the client to be messing with the `enabledProperty` of these buttons, so they are unlikely to run into any issues.

**Comment by arouinfar** [comment]
Design issue for carousel linked above, closing.
