### ISSUE TITLE
Add linked property to ZoomControlPanel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#852]
The zoom state is controlled by `model.zoomProperty`. It would be nice to add a linked property under the corresponding view element `ZoomControlPanel`.
<img width="182" alt="image" src="https://user-images.githubusercontent.com/8419308/153677191-42a81ca2-0ba8-4fec-9ba4-ef3a703cc622.png">

**Comment by samreid** [comment]
Fixed, and it looks like this:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/679486/187051790-58cddba2-222a-40b8-a2c9-b3da1a98891e.png">

There is some complication that there is another competing (cooperating?) enumeration like so:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/679486/187051801-47240c97-b7ee-4b1f-a19b-8c558bdc01ad.png">

@arouinfar please review.

**Comment by arouinfar** [comment]
Thanks @samreid! Looks good in master.
