### ISSUE TITLE
Battery carousel icon doesn't need "right" descriptor

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#853]
The battery in the carousel is `view.circuitElementToolbox.circuitElementTools.rightBatteryToolNode`. The "right" descriptor appears six places in the tree (3 for each screen). 
<img width="201" alt="image" src="https://user-images.githubusercontent.com/8419308/153679654-3354a42a-577d-49bc-8b9a-b8d56abcd75b.png">

This orientation information doesn't add any value to the tree and carries the implication that there could be a paired "left" battery. For comparison purposes, the high-voltage battery looks like this:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/8419308/153680061-8d574377-f308-4532-b840-d5772fa0a30a.png">

@samreid let's remove "right" so it's `batteryToolNode` and `batteryIcon`.

**Comment by samreid** [comment]
It has a "right" descriptor because in an incomplete version of CCK Basics we added batteries facing the opposite way.  In light of https://github.com/phetsims/geometric-optics-basics/issues/3#issuecomment-1050287506 do we still want to do this?

**Comment by arouinfar** [comment]
I'm a bit conflicted. I really do think the "right" descriptor adds a bit of difficulty when scanning the tree for "battery". However, this is mitigated by the Studio select feature. Since there could be a "left" battery in future flavors of CCK, let's leave this as-is so we don't have to introduce API-breaking changes in the future to distinguish the "right" and "left" batteries.
