### ISSUE TITLE
Several elements should be read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#854]
@samreid please set these to phetioReadOnly: true.

- [x] `model.circuit.circuitChangedEmitter`
- [x] `model.circuit.circuitElements.elementAddedEmitter`
- [x] `model.circuit.circuitElements.elementRemovedEmitter`
- [x] `model.circuit.*.archetype.endVertexProperty`
- [x] `model.circuit.*.archetype.startVertexProperty`
- [x] `model.circuit.vertexGroup.archetype.positionProperty`
- [ ] `model.circuit.realLightBulbGroup.archetype.resistanceProperty` (real bulbs don't have user-adjustable reistance)
- [x] `model.meters.ammeter*.currentProperty`
- [x] `model.meters.voltmeter*.voltageProperty`
- [ ] `view.circuitNode.*NodeGroup.archetype.visibleProperty`
- [ ] `view.meterNodes.*.probeTextNode.readoutText.textProperty`
- [x] `view.sensorToolbox.*Label.visibleProperty`
- [x] `view.sensorToolbox.*NodeIcon.probeTextNode.readoutText.textProperty`

**Comment by samreid** [comment]
> model.circuit.realLightBulbGroup.archetype.resistanceProperty (real bulbs don't have user-adjustable reistance)

Right, but giving an API to PhET-iO clients allows them to choose the value, without making it user-adjustable.  Should clients be able to choose that resistance value?

**Comment by samreid** [comment]
All issues addressed or asked about in the preceding comment.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
Thanks @samreid. I verified the checked items in https://github.com/phetsims/circuit-construction-kit-common/issues/854#issue-1133585268, but those related to strings are now moot.

>> `model.circuit.realLightBulbGroup.archetype.resistanceProperty` (real bulbs don't have user-adjustable resistance)
>
> Right, but giving an API to PhET-iO clients allows them to choose the value, without making it user-adjustable. Should clients be able to choose that resistance value?

Excellent point @samreid. It's also now user-adjustable with the Get Value/Set Value functionality within Studio, so we should leave this as-is.

>> view.circuitNode.*NodeGroup.archetype.visibleProperty
>
>For the archetype ones, we do not yet support customizable archetypes. Are these requests for when https://github.com/phetsims/phet-io/issues/1856 is further along?

Those related to the vertices should definitely be read-only. Things can get messy if clients are able to specify `startVertexProperty`, `endVertexProperty`, and `positionProperty`. The behavior in master looks good to me. 

I don't remember the rationale for this particular `visibleProperty`, but we can more review archetypes in more detail in https://github.com/phetsims/phet-io/issues/1856.

>> view.meterNodes.*.probeTextNode.readoutText.textProperty
>
> I don't see those as instrumented any more. Should I resurrect it?

I thought it was weird for clients to be able to edit the readout strings such as this one, which is why I asked for the `textProperty` to be read-only.
<img width="80" alt="image" src="https://user-images.githubusercontent.com/8419308/194955145-3c3100c4-53e4-4190-93ca-b554634772e2.png">

However, I think it may be useful to clients to know what value is being displayed in the meters, since it differs slightly from the underlying `currentProperty` or `voltageProperty` being measured. Conceptually, I think this is analogous to `measuringTapeNode.readoutStringProperty` in GAO.

I still see the `readoutText` in Studio, but I don't see a value in the Element Panel, so don't think it's working as expected.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/8419308/194955758-94c6580a-e276-4085-aa33-4870e6d7a201.png">

**Comment by samreid** [comment]
OK we updated the tandems and marked things as readonly.  @arouinfar ready for review.

**Comment by arouinfar** [comment]
I now see dependencies under the `readoutText`, for example: 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/8419308/206324099-fc3c7365-e119-41ad-8885-975f05b0b4f0.png">

> However, I think it may be useful to clients to know what value is being displayed in the meters, since it differs slightly from the underlying `currentProperty` or `voltageProperty` being measured. Conceptually, I think this is analogous to `measuringTapeNode.readoutStringProperty` in GAO.

The `readoutText` links back to the underlying `currentProperty` so it's not analogous to the GAO example. However, my initial concern was that the `readoutText` was editable and then later lacking useful information in Studio. Those issues have been resolved, so we can close.
