### ISSUE TITLE
Remove instances of over-instrumentation

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#855]
@samreid I found a few cases of over-instrumentation or circuit elements with irrelevant properties instrumented. Please uninstrument the following:

- [x] `model.circuit.wireGroup.archetype.isEditableProperty`
- [x] `model.circuit.wireGroup.archetype.isValueDisplayableProperty`
- [x] `model.circuit.wireGroup.archetype.labelTextProperty`
- [x] `model.circuit.seriesAmmeterGroup.archetype.isEditableProperty`
- [x] `model.circuit.seriesAmmeterGroup.archetype.isValueDisplayableProperty`
- [x]  `model.circuit.seriesAmmeterGroup.archetype.labelTextProperty`
- [x] `view.circuitNode.*lightBulbNodeGroup.archetype.socketNode`
- [x] `view.viewRadioButtonGroup.lifelikeIcon`
- [x] `view.viewRadioButtonGroup.schematicIcon`
- [x] `view.displayOptionsPanel.arrowNode`
- <s>`labScreen.view.advancedAccordionBox.sourceResistanceControl.maxLabel` </s>
- <s>`labScreen.view.advancedAccordionBox.sourceResistanceControl.tinyLabel` </s>
- <s>`labScreen.view.advancedAccordionBox.*Control.slider.thumbNode`</s>
- <s>`labScreen.view.advancedAccordionBox.*Control.slider.trackNode`</s>

**Comment by samreid** [comment]
I opted out of the tandems checked off above.  For the others, I wanted to ask:

* Is uninstrumentation of the archetypes permanently, or only until we implement https://github.com/phetsims/phet-io/issues/1856 ?
* Do we really want to uninstrument the labels?
* The thumb node and track node should remain instrumented for the data stream events, right?

**Comment by arouinfar** [comment]
> Is uninstrumentation of the archetypes permanently, or only until we implement https://github.com/phetsims/phet-io/issues/1856 ?

These requests all look permanent to me. Wires are not editable and have no value or label to display, so I see no reason for them to have `isEditableProperty`, `isValueDisplayableProperty`, or `labelStringProperty`. These properties do not translate to the series ammeter, either.

>  Do we really want to uninstrument the labels?

The "tiny" and "lots" labels do not need to be instrumented in the view. The strings will still be accessible under `general.model.strings` but we do not need to bring any attention to them in the view.

> The thumb node and track node should remain instrumented for the data stream events, right?

This was a mistake on my part. The `thumbNode` and `trackNode` are normal children of a slider and exist throughout PhET-iO sims. I'll cross those off the list above. Thanks for checking first!

**Comment by samreid** [comment]
@matthew-blackman and I looked into this, and we additionally saw `tandem.createTandem( 'tinyLabelText' )` in `SourceResistanceControls`.  (Whatever we decide should apply equally to SourceResistanceControls and WireResistivityControls). But we were skeptical about uninstrumenting these tick mark label scenery nodes, thinking that would make it impossible to use studio autoselect to discover them.  So we wanted to check about that before proceeding.  @arouinfar what do you recommend?

**Comment by arouinfar** [comment]
> But we were skeptical about uninstrumenting these tick mark label scenery nodes, thinking that would make it impossible to use studio autoselect to discover them. 

I think there's a bit of a miscommunication here. Before the move to dynamic strings, the Wire Resistivity slider had children for the `tiny` and `lots` labels. Those no longer exist in the tree, so I don't think there's anything that needs to be done here. The select feature also seems to be working just fine in master.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/8419308/206323200-7d93de70-22af-481a-9647-6b07c7359281.png">

I crossed the items off the list in the original comment, so we can go ahead and close.
