### ISSUE TITLE
Add top-level visibleProperty to sourceResistanceControl and wireResistivityControl 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#856]
The `sourceResistanceControl` and `wireResistivityControl` in the Advanced AccordionBox could both use a top-level `visibleProperty` so the entire slider could be hidden in one go. 

@samreid please create:
- [x] `labScreen.view.advancedAccordionBox.sourceResistanceControl.visibleProperty` 
- [x] `labScreen.view.advancedAccordionBox.wireResistivityControl.visibleProperty`

**Comment by samreid** [comment]
I instrumented and featured the `visibleProperty`.  If it is preferable, I can remove that `phetioFeatured` from the code and move it to the overrides.  Also referring to https://github.com/phetsims/phet-io/issues/1873 which discusses where this metadata should live.

**Comment by arouinfar** [comment]
Thanks @samreid. The behavior looks good in Studio. Since https://github.com/phetsims/phet-io/issues/1873 hasn't been resolved, I'm not sure where we should specify `phetioFeatured: true` or if this issue can be closed, so back to you.

**Comment by samreid** [comment]
It doesn't seem to be causing problems to specify this in the code, so let's leave it as is.  If we decide otherwise in https://github.com/phetsims/phet-io/issues/1873, we can change that easily.
