### ISSUE TITLE
Is the circuit element tool visible property working correctly?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#858]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/774:

In Studio, when a circuit element that there is multiple of, such as a battery, is placed in the play area and then its visible property is set to false (view.circuitElementToolbox.circuitElementTools.rightBatteryToolNode.visibleProperty), it's value will be true when the sim is launched. If that item was not in the play area, its value stays false. 

This seems like a bug to me, but I first wanted to make sure that this was not by design. 

**Steps to reproduce**
1. In either screen, place a circuit element there is multiple of (battery, switch, wire, resistor, fuse, bulb) into the play area 
2. Set its visible property to false--the circuit element disappears from the carousel
3. Launch the sim--the circuit element appears in the carousel and more of that element can be moved to the play area

**Visuals**

https://user-images.githubusercontent.com/87318828/154090172-5b14ec67-e89a-460f-97e2-bf3c295a6edc.mp4

**Comment by Nancy-Salpepi** [comment]
I noticed that if I follow the same steps as above, but with the ammeter (`view.sensorToolbox.ammeterToolNode.visibleProperty`) and voltmeter (`view.sensorToolbox.voltmeterNodeIcon.visibleProperty`) the visibleProperty stays false after launching. 

https://user-images.githubusercontent.com/87318828/154117847-8ec8399e-693a-466a-b636-7764493ef59d.mp4

**Comment by samreid** [comment]
I improved the tandem name for the voltmeter so it is consistent with the rest of the sim.

**Comment by samreid** [comment]
The labels were supposed to auto-hide when you hide a voltmeter or ammeter tool node, I corrected that in the commit.  I also added a TODO since I was surprised to see 2 levels in that hierarchy (last 2 in this list):

<img width="302" alt="image" src="https://user-images.githubusercontent.com/679486/210692925-33734562-d66f-4bcb-8fbb-51133ec24bfc.png">

**Comment by samreid** [comment]
Anyways, I don't think I should work on that tree much more until checking in about the design of that part.  Do we still need `ammeterToolIconWithLabel`?  Should `seriesAmmeterNodeIcon` be nested under `seriesAmmeterToolNode`? Should the labels be top-level in sensorToolbox, and auto-hide?

**Comment by arouinfar** [comment]
I'll review this with @matthew-blackman in #917

**Comment by arouinfar** [comment]
@matthew-blackman and I verified that the labels in the sensor toolbox disappear when hiding the corresponding ToolNode. The "Ammeters" text will disappear if both `seriesAmmeterToolNode` and `ammeterToolNode` are hidden. 

@samreid There isn't a reason to keep the `*IconWithLabel`. Can you remove those?

**Comment by samreid** [comment]
I removed the iconWithLabel and regenerated APIs. Tested in Studio.  Closing.
