### ISSUE TITLE
Add lifelike/schematic icons to lightBulbToolNode and realLightBulbToolNode

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#859]
The lightBulbToolNode (on both screens) and the realLightBulbToolNode (on lab screen) are missing :
  `lifelikeIcon.resistorIcon`
  `lifelikeIcon.resistorIcon.visibleProperty`
  `schematicIcon.resistorIcon`
  `schematicIcon.resistorIcon.visibleProperty`
  
From my slack conversion with @arouinfar, all items in the carousel should have these.

**Comment by samreid** [comment]
It was requested to uninstrument the lifelikeIcon and schematicIcon in https://github.com/phetsims/circuit-construction-kit-common/issues/855, @arouinfar can you please review if anything needs to be done here?

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi @samreid. Based on the current behavior in master, I don't think there's anything we need to do here.
