### ISSUE TITLE
Setting endVertexProperty and startVertexProperty leads to a crash

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#860]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/774. Found with the `endVertexProperty`'s and `startVertexProperty`'s. Haven't yet seen on others, but may happen elsewhere. Most properties I've tried seem to set properly so far.
The `endVertexProperty` and `startVertexProperty` of circuit elements cause a crash when you try to set them.
**Steps to Reproduce**
1. Go to the intro screen in studio
2. Grab a lightbulb and drag it into the play area
3. Go to `circuitConstructionKitDc.introScreen.model.circuit.lightBulbGroup.lightBulb_0.endVertexProperty` and get value
4. Try to set the value you just got.

**Visuals**
![trytoset](https://user-images.githubusercontent.com/41024075/154117994-12bbf52d-a96a-4b9c-950b-98f2998290cc.gif)

**Comment by arouinfar** [comment]
Thanks @KatieWoe. These properties will be made read-only in #854, so I'll go ahead and close.
