### ISSUE TITLE
Screenshot wrapper not working correctly with Win10 + Chrome

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#861]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/774:

When taking a screenshot with the Screenshot wrapper, the blue background is missing along the right side and across the bottom of the screen. 

* I could not reproduce this on Master with Win10 + chrome 
* This couldn't be reproduced with Win + FireFox or Mac + Safari/Chrome
* Nothing came up in the console

**Steps to reproduce**
No need to even add anything into the play area. Just press the Screenshot button. 

**Visuals**
![screenshotCCK](https://user-images.githubusercontent.com/87318828/154157622-11048883-031a-4576-8b7e-581f9f414bad.PNG)

**Comment by Nancy-Salpepi** [comment]
This also occurs in the PhET brand sim using the Screenshot Option in the PhET Menu with Win10 + chrome. 

Screenshots were correct on published sims ( I tried CC- AC, CCK-DC, Density, Build an Atom) and  CCK-DC in master.

**Comment by KatieWoe** [comment]
I was unable to reproduce this on Win 11 + chrome.

**Comment by stemilymill** [comment]
I was unable to reproduce this on win10 chrome

**Comment by Nancy-Salpepi** [comment]
Hum. I guess it is my device then.

**Comment by samreid** [comment]
@Nancy-Salpepi is this still happening on the latest version (on phettest)?

**Comment by Nancy-Salpepi** [comment]
I wasn't able to reproduce on Master. I'm going to go ahead and close.
