### ISSUE TITLE
capacitanceStep is smaller than capacitorNumberDecimalPlaces

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#862]
> When setting the value for the capacitance C of a capacitor, the display on shows two decimal places (like 0.08 F).
> However, clicking on the slider-arrows modifies the capacitance further (without showing the fine-tuning in the display),
> as evidenced by a voltmeter reading for the capacitor terminals.
>  
> It would be good to see more decimal places in the capacitance
> since the slider/arrow-buttons allows this fine-tuning!
>  
> I was trying to set up a virtual demo with two capacitors
> 0.08F and 0.16F (so that C2= 2*C1) connected to a 9-v battery.
>  
> From the visuals below, the displayed values suggest that V1=5.88
> V2=3.12 so that I have achieved V1/V2=1.88 (not 2).
> I would have to tweak the capacitance sliders [in an alternating manner?]
> while looking at voltmeters to fine-tune to the desired capacitances.
>  
> I would rather see more decimal places in the capacitance.
> It would also be nice to allow me to type-in precisely my desired capacitances (within the bounds)
> rather than tune to it with the slider.
>  
> Without these additional decimal places displayed,
> I think it would be difficult to ask to student to setup
> a situation as above (with C2=2*C1) and verify the algebraic results.
>
> ![8652F11CFE7A4A47B77F992844708E99](https://user-images.githubusercontent.com/5090275/154164680-cdcad3b6-aaee-4164-be3d-3d0199f9c318.png)
> ![EB1241EDB35D4D2E884ACE3DBBFA1ECE](https://user-images.githubusercontent.com/5090275/154164692-15651e09-4269-48c8-8688-857444430601.png)

**Comment by arouinfar** [comment]
@oliver-phet this looks like an error on our part. It's going to take some digging to find the paper trail on what the desired behavior should be, but in the meantime please ask the user to use `?capacitorNumberDecimalPlaces=3` to correct things in the published version. This was not intended to be a public-facing query parameter, just something we used in our own testing/model tuning but it works in the published version.

**Comment by arouinfar** [comment]
The capacitance range was determined in https://github.com/phetsims/circuit-construction-kit-common/issues/590, but the query parameters were introduced in https://github.com/phetsims/circuit-construction-kit-common/issues/780#issuecomment-974291874 when we were trying to address a situation with buggy inductors. We ended up keeping the capacitance values as they are and limiting the number of inductors instead. However, we kept the query parameters around, including the incongruent default values with `capacitanceStep=0.001` and `capacitorNumberDecimalPlaces=2`.

This is something we should be able to easily fix in a maintenance release, but there are two ways we could go:

1. Increase the default value of `capacitorNumberDecimalPlace` to 3.
2. Change the default value of `capacitanceStep` to 0.01.

Based on the decisions made in #590 we probably should go with option (2). However, there may have been some other reason for changing `capacitanceStep` to 0.001 that I'm just not remembering. @ariel-phet @samreid do you recall?

**Comment by ariel-phet** [comment]
@arouinfar I agree option (2) sounds like the right solution. I believe that was our intention. We have fine enough control with inductor values to tune in a resonant frequency.

**Comment by arouinfar** [comment]
Thanks @ariel-phet. Unles @samreid has objections, we should proceed with updating the `capacitanceStep` default to 0.01 and publishing a MR of CCK: AC and CCK: AC - VL.

**Comment by arouinfar** [comment]
2/24/22 design meeting. We decided to proceed with option (2) and publish MR of CCK: AC and CCK: AC - VL.  @samreid should also confirm that the slider thumb snaps to 0.01 increments. In Studio, using `capacitanceStep=0.01` seems to behave as desired.

**Comment by samreid** [comment]
I changed the capacitanceStep to 0.01 and made it the slider thumb snap step as well.  @arouinfar can you please verify the behavior on phettest before we create the maintenance releases?  After the behavior is verified do we need any other steps such as QA involvement for this maintenance release?

**Comment by samreid** [comment]
@arouinfar can this be included with the next milestone of CCK (PhET-iO)?  Or does it warrant an earlier separate maintenance release?

**Comment by arouinfar** [comment]
@samreid the PhET-iO milestones are all related to CCK: DC, and it will likely be quite some time before CCK: AC & CCK: AC - VL are republished off of master. Let's proceed with publishing maintenance releases of the AC flavors, as time allows.

**Comment by samreid** [comment]
On Thursday, @jonathanolson reported that he is working on maintenance releases.  He said:

> I'll be working on maintenance release things. Please don't do anything on maintenance branches without talking to me first!

I replied:

> @jonathanolson Can I work on https://github.com/phetsims/circuit-construction-kit-common/issues/862 ?

On hold until we know more.

**Comment by jonathanolson** [comment]
Maintenance complete that was blocking, feel free to move ahead!

**Comment by samreid** [comment]
Today's meeting: @arouinfar @matthew-blackman and me:  If we are publishing AC within a couple of months, that's OK.  But if it would be longer than that, we should cherry-pick that commit.

**Comment by samreid** [comment]
I feel it could be a couple of months before AC is published.  So I'll add this to our team's backlog.

**Comment by samreid** [comment]
Oops, I recall @jonathanolson said another maintenance release is in progress.  On hold until we get the all-clear.

**Comment by samreid** [comment]
@jonathanolson reported the other maintenance release is complete and we can proceed.

**Comment by samreid** [comment]
Build succeeded: Sim = circuit-construction-kit-ac Version = 1.0.11-rc.1 Brands = phet Locales = en

**Comment by samreid** [comment]
RCs are here: 
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.11-rc.1/phet/
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.10-rc.2/phet/

@arouinfar can you please spot check them?

**Comment by arouinfar** [comment]
Thanks @samreid. I spot-checked the rc's and everything looks good.

**Comment by samreid** [comment]
I sent the build production commands over 10 minutes ago.  Not sure why the build server takes so long.

**Comment by samreid** [comment]
Publications complete. @oliver-phet do we need to notify someone that wrote to phethelp?

**Comment by oliver-phet** [comment]
User emailed via phethelp, though the 3 decimal place query parameter is likely still most useful to them.
