### ISSUE TITLE
Carousel may not be on correct page when sim is launched

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#863]
**Device**
Dell
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/774
On the lab screen, if you have the real bulb activated in studio and launch the sim, the carousel will be on the last page even if isn't meant to be.
**Steps to Reproduce**
1. Go to the lab screen in studio
2. Turn on the real bulbs
3. Scroll the carousel back to the top
4. Launch the sim

**Visuals**
![wrongpage](https://user-images.githubusercontent.com/41024075/154353240-2f190251-909e-4fbe-bac0-4d10b6ffa7da.gif)

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I've moved your comments over to https://github.com/phetsims/circuit-construction-kit-common/issues/841. Closing.
