### ISSUE TITLE
Sim zooming and schematic type changes after sim is launched in Studio.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#864]
**Device**
Dell
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/774. Similar to https://github.com/phetsims/circuit-construction-kit-common/issues/841.
If you launch the sim while it is zoomed out (with the zooming buttons) or in schematic mode it will make those changes after launch.

**Visuals**
![scrollin](https://user-images.githubusercontent.com/41024075/154359540-b271c694-7524-49df-bda9-1dda1a7b7370.gif)

**Comment by samreid** [comment]
Fixed, closing.
