### ISSUE TITLE
Should checkboxes and radio buttons have customizable text? 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#870]
We often (but not always) instrument the title text of checkboxes and radio buttons. Should these strings be instrumented?

<img width="149" alt="image" src="https://user-images.githubusercontent.com/8419308/154786604-b82ceef0-8327-417b-a63a-d50074e1b944.png">
<img width="152" alt="image" src="https://user-images.githubusercontent.com/8419308/154786617-18bad9a1-9eb0-4a6d-a131-75e1f6bbb137.png">

**Comment by arouinfar** [comment]
2/24/22 design meeting, we decided to instrument the strings in the screenshot above. Over to @samreid.

**Comment by samreid** [comment]
I added "label" subcomponents for each of the items above.  Ready for review.

**Comment by arouinfar** [comment]
Now that PhET-iO sims contain all of the rosetta strings, this sort of request is no longer necesary. That said, I reviewed the tree in master, and the checkboxes and radio buttons now all contain links to the appropriate `stringProperty`, which is great. Closing.
