### ISSUE TITLE
Support customizable archetypes

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#876]
For https://github.com/phetsims/phet-io/issues/1856

**Comment by samreid** [comment]
Labeling for design meeting to determine priority/timeline

**Comment by arouinfar** [comment]
Design meeting 11/30/22 @arouinfar @samreid @matthew-blackman 

There is some benefit in allowing instructional designers to customize the archetypes, and we would like to include it in this milestone.

Caveats
* Customizing the archetype will not have a retroactive effect on the already existing elements.

**Comment by samreid** [comment]
We discussed this in https://github.com/phetsims/phet-io/issues/1856#issuecomment-1371353323, the main decisions for this release are:

* Do not proceed with the "always create stateful archetypes" patch for this release.
* Add documentation about how to tap into an `elementCreatedEmitter` to customize new elements in a custom wrapper.

**Comment by samreid** [comment]
Here is a line of code that customizes elements as they are created:

```ts
phetioClient.invoke( 
'circuitConstructionKitDc.introScreen.model.circuit.resistorGroup.elementCreatedEmitter', 
'addListener', [
      ( state, phetioID ) => phetioClient.invoke( phetioID + '.isEditableProperty', 'setValue', [ false ] )
]);
```

It can be pasted in the chrome dev tools while running studio.  Or it can be added to a wrapper. Or after running Studio => Test, you can paste it in the launched sim.  All of these cases work as expected.  This seems like a workable solution that is flexible and easy to describe, and already well-supported.  If a client requires a UI for customizing defaults or archetypes in studio, we can add a UI for this, or we can reconsider https://github.com/phetsims/phet-io/issues/1856.

@arouinfar can you please test this, and add a note about this to the sim-specific documentation?  Or show me where I can do so?

**Comment by samreid** [comment]
I made a note of this in https://github.com/phetsims/circuit-construction-kit-common/issues/865, perhaps this issue can be closed and we will continue in https://github.com/phetsims/circuit-construction-kit-common/issues/865? Up to @arouinfar

**Comment by arouinfar** [comment]
Thanks @samreid! I tested it out in the console and it worked well. I copied your comment over into #865 to make it easier to find when writing up the examples doc. I don't think there's anything else to do in this issue, closing.
