### ISSUE TITLE
Figure out updateRenderer() @protected status

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-common#877]
While working on https://github.com/phetsims/chipper/issues/1237, it seems like many of those overrides are not actually protected, but I didn't know how to proceed. Please help me out @samreid

**Comment by samreid** [comment]
I committed the proposed fix, @zepumph would you like to spot check?

**Comment by zepumph** [comment]
Yes perfect, and exactly what I would have done, I just didn't if it was too strict for how you wanted your code. Thanks!
