### ISSUE TITLE
User suggestion: raise voltage to 220V/380V

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#878]
> I am an electrician's assistant teacher, in an institute and I discovered this excellent tool by chance today.
> I wanted to ask you if the voltage can be raised in AC up to 220V single-phase or 380V three-phase and 50 Hz.

**Comment by arouinfar** [comment]
We'd like to eventually make a household/electrician version of CCK that would better serve the user's goals, but it's not currently on the radar. 

On the Lab Screen, there is a Phase Shift control for the AC sources that may be of use. Currently, the range only extends to 180 degrees, but this was a somewhat arbitrary choice. For three-phase voltages, we would need to extend the range to 240 degrees, which should be doable. I'll open a separate issue for that.

![image](https://user-images.githubusercontent.com/8419308/165803298-2be7eacc-c4d2-4c10-86c4-ff213b9a7d2e.png)

**Comment by oliver-phet** [comment]
Thanks, I'll reply to user.
