### ISSUE TITLE
Extend Phase Shift range to 240 degrees

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#879]
In https://github.com/phetsims/circuit-construction-kit-common/issues/878, a user requested the ability to create a [three-phase AC voltage](https://en.wikipedia.org/wiki/Three-phase_electric_power). In general, their goals are better suited to a household/electrician flavor of CCK, but it seems like increasing the range of the Phase Shift to 240 degrees could achieve some of their goals. 

![image](https://user-images.githubusercontent.com/8419308/165803742-372bdf36-49d6-42f2-ab58-6697683956a6.png)

Let's consider this suggestion when republishing CCK:AC with PhET-iO.

**Comment by samreid** [comment]
In today's meeting @arouinfar @matthew-blackman and I agreed this would be good to try for the AC milestone.

**Comment by samreid** [comment]
The phase range is -180 to +180 degrees.  So a 3-phase voltage can be made like: -120, 0, +120.  Can this issue be closed?

**Comment by samreid** [comment]
@matthew-blackman tested this, and was able to make the 3-phase voltage offset using the phases described above.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
> So a 3-phase voltage can be made like: -120, 0, +120.

I forgot about negative phase shifts! 

> @matthew-blackman tested this, and was able to make the 3-phase voltage offset using the phases described above. @arouinfar what do you think?

I don't think there's anything we need to do here, closing.
