### ISSUE TITLE
Publish a new version of CCK DC PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#881]
For an upcoming meeting

**Comment by samreid** [comment]
I published https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.17/phet-io/wrappers/studio/ today.  @arouinfar can you please spot check it for the purposes of the presentation?

**Comment by arouinfar** [comment]
Thanks @samreid I shared dev.17 in today's meeting, and it was well-behaved during my testing before then.
