### ISSUE TITLE
Carousel order is inconsistent on Lab screen of CCK: DC

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#883]
Noticed during #882 

The "grab bag" items generally follow this order in the CCK: DC and CCK: AC flavors:
1. Dollar bill
2. Paper clip
3. Coin
4. Eraser
5. Pencil
6. Hand
7. Dog

However, the Lab screen of CCK: DC (same as CCK: DC - VL) has the pencil last. @samreid let's update the order in the carousel to match the list above.

**Comment by samreid** [comment]
Fixed in DC and DC VL, @arouinfar want to spot test on phettest?

**Comment by arouinfar** [comment]
Looks good, thanks!
