### ISSUE TITLE
Delete `moreWires` and increase number of wires to 50

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#884]
@DianaTavares reported a user issue with the number of wires available by default.

> Hi PhET design team! PhET fellows are taking more PhET simulations to their classes and today they report me some issues:
> there is not more wire to build more circuits:
> ![image](https://user-images.githubusercontent.com/8419308/171286644-9b5d1ccc-5d57-4593-9099-28b5411f7ed0.png)

The recommended solution was to use the `moreWires` query parameter. However, @DianaTavares raised these concerns:

> I start to think that the query parameter can be a problem in this way teachers are using the sims on cellphones. what Amanda said, if they are using the app, they can not put the qps. and if the teacher is sending the file (no the link, because WhatsApp is free in Mexico in most of the cellphone companies), students have to write very specific things in the URL of the file (text that doesn't have a sense for them)  sound a lot of mistakes.

Query parameters are not accessible in the app and are hard to share when sending the .html file. There are two options we can consider: 
1. Add a "More Wires" checkbox to the Options dialog.  (This would likely require changing the query parameter from a flag to a boolean.)
2. Deprecate the query parameter and always include the full 50 wires in the simulation. We originally limited the number of wires due to performance concerns. However, when introducing `moreWires` in #432 the performance was acceptable on iPad and Chromebook.

I think we could go with option (2), but we should discuss as a team, so adding it to the PhET-iO publication milestone.

**Comment by DianaTavares** [comment]
option 2) solve the problem of this issue of more wires, but I think that moving from query parameter to something in the Options dialog can be better In general for all the simulations. I visualize that this can be a recurrent problem with other simulations, like the new math sims that have a lot of query parameters, or Natural selection where starting with a specific bunny population can be useful for some experiments.

**Comment by arouinfar** [comment]
Discussed with @samreid and @kathy-phet and we decided to go with option (2) and delete the `moreWires` query parameter and include 50 wires by default.

**Comment by samreid** [comment]
Fixed.  Clients that continue to use ?moreWires from their bookmarks will not run into problems (query parameter will be safely ignored).  Closing.
