### ISSUE TITLE
Switch readout display message shifting position after clicking on a different element

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#894]
The text that says "The switch is open/the switch is closed" changes position after clicking on a different component.

To reproduce:
- Add a switch to a blank play area
- Click on switch, view text position
- Add another component and click on it
- Click on the switch again, the text will have shifted position

Screenshot after text shift:
![Screen Shot 2022-11-09 at 2 51 47 PM](https://user-images.githubusercontent.com/108756567/200927623-62719c14-1914-49d9-8a71-6ea47f4bd531.png)

**Comment by samreid** [comment]
Fixed, but we also need to see if other components need this same fix.

**Comment by samreid** [comment]
@matthew-blackman said there are no problems on the other components, closing.
