### ISSUE TITLE
Ensure coverage of phet-io instrumentation for elements in the circuitElementControlNode

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#896]
Today while working on #831 @matthew-blackman discovered there was poor coverage of phet-io instrumentation in what we hope to call the `circuitElementControlNode`.  For example, in the resistor and fuse controls, and light bulb. We should add better instrumentation there.

**Comment by samreid** [comment]
All parts of the resistor controls seem well-instrumented:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/679486/204383962-e5afd170-dfa9-4917-b605-b3f2bafccd3b.png">

**Comment by samreid** [comment]
I saw equally good coverage for the fuse and light bulb controls. @matthew-blackman am I checking the right thing?  Does this issue seem ready to fix?

**Comment by matthew-blackman** [comment]
I tested this in studio and the controls all look instrumented for resistors, bulbs and fuses. Closing this issue.
