### ISSUE TITLE
CircuitElementNodeIO is not used nor redefined

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/circuit-construction-kit-common#899]
There is a field called [CircuitElementNodeIO in CircuitElementNode.ts](https://github.com/phetsims/circuit-construction-kit-common/blob/4ce649c263ef9865b0aa507bef894bb93107584f/js/view/CircuitElementNode.ts#L35) that isn't currently being used. Should it be deleted?

**Comment by samreid** [comment]
Thanks, I deleted it.  Closing.
