### ISSUE TITLE
DC-specific circuit elements and features should not appear in the AC studio tree

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#900]
We should not add DC-only features (high-voltage and high-resistance components) to AC because they have not been tested in an AC environment and go beyond the scope of the learning goals.

**Comment by matthew-blackman** [comment]
@samreid and I agree that the way we are guarding against creating circuit nodes for non-existent circuit element groups in CircuitNode.ts is not as robust as it could be. We recommend doing all of the guarding for non-existent component groups in Circuit.ts, and null-checking for those groups in CircuitNode.ts and CircuitElementToolFactory.ts. This will only apply to groups of screen-specific components.

**Comment by samreid** [comment]
Great, nice work! I just factored out one variable.  I regenerated the API files in https://github.com/phetsims/phet-io-sim-specific/commit/a3554143882d156300f6f3fa5c09c69e85e6b836. Everything else seems good. Closing.
