### ISSUE TITLE
'Reset fuse' button is misaligned vertically

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#902]
See screenshot below. It looks like the 'reset fuse' button should be vertically centered, not bottom-justified.

<img width="353" alt="Screen Shot 2022-11-29 at 11 37 45 AM" src="https://user-images.githubusercontent.com/108756567/204588952-99b2e36d-6651-46f4-9d3f-43a0de0ccc43.png">

**Comment by samreid** [comment]
Thanks, I changed align to center, and it seems much better now:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/679486/204908617-6498c2c5-f773-4abb-9f37-be12301df4b0.png">

Not sure how this was working before--I didn't see much other layout code for the trash button, etc.

Can you please spot check the layouts for a few component types and close if all seems well?

**Comment by samreid** [comment]
@matthew-blackman and I improved 2 buttons and want to apply the pattern to the remaining 2 buttons.

@matthew-blackman volunteered to do the other 2 buttons, each labeled with TODOs.

**Comment by matthew-blackman** [comment]
Closing as previous commit applies the sizing fix to all edit buttons
