### ISSUE TITLE
Remove the hand "circuit element"

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#907]
In https://github.com/phetsims/circuit-construction-kit-common/issues/882, we removed the dog for reasons like:
* The dog is more whimsical than pedagogical (hand better demonstrates things).
* The act of hooking up a dog to wires and its bark can be perceived as animal cruelty.
* We don't want to create disruptive or distracting situations in the classroom.
* Dog resistance is not a learning goal.

We have similar questions about the hand.  @arouinfar wrote:

> We should also be sure to discuss the hand, including:
> 
> Does the hand serve a primary learning goal?
> Should the hand be drawn differently?
> Should the hand be hidden behind a query parameter?

@RVieyra added:

> Just a few more considerations:
> 
> If you keep the hand, I propose a "spread hand," with electrons flowing from pinky to thumb. Right now, wrist to finger is more "odd" than problematic.
> If you keep the hand, please keep in mind the potential need for cultural contextualization (skin tone).
> Does the hand have pedagogical value? Any organic material would, but, you might has well replace it with a carrot (or other fruit/vegetable). Carrots are very conductive, as I learned once when feeding sheep next to an electrified fence. ;-)

In my opinion, including the hand is hazardous for users that don't understand the context of the sim, and it should be removed.  Teachers that want to meet a learning goal about the resistivity of humans can use other circuit elements in analogy.

@arouinfar can you please review and advise?

**Comment by samreid** [comment]
I saw this comment: https://www.compadre.org/portal/services/detail.cfm?ID=14739

> High voltage applied to hand and dog
Author: Axel Mellinger
Posted: October 2, 2018 at 2:36PM
The simulation suggests that applying 10,000 V to a hand (resistance 1 MOhm) would only result in a current of 10 mA, which would be painful but not lethal. However, human skin is a highly non-ohmic conductor. At 10,000 V, electric breakdown leads to a skin resistance that is orders of magnitude smaller than 1 MOhm. The same is true for applying 10,000 V to the dog.
> 
> I feel the simulation should be modified so that it does not give users the false impression that applying high voltage to humans and animals is safe.
> 
> Axel Mellinger
Department of Physics
Central Michigan University

I could not agree more, and I think we should remove the hand.

**Comment by matthew-blackman** [comment]
I also agree with Axel. The core of his argument is that "human skin is a highly non-ohmic conductor", which I think is why the sim shows too-low of a current when high voltage is applied to the hand. The fact that a real hand would be non-ohmic is very important (especially because we are including a non-ohmic light bulb), and also relates to the safety issue of showing the real result of applying voltage to the human body.

**Comment by matthew-blackman** [comment]
12/15/22 Design Meeting

We agree that the hand is somewhat problematic, but still find value in the learning goal related to measuring resistivity of biological materials. We suggest removing the hand for now, with an upcoming discussion about how this could be modified
 by updating the artwork or by choosing another object.

We will create a separate issue for this and have continued design discussions about how to move forward.

**Comment by samreid** [comment]
The hand was removed in the commits.  I left in the code for creating the hand in case it is used in a different context.  I'll close this issue and open a new issue about related learning goals.
