### ISSUE TITLE
CCKCConstants should not be modified

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#908]
I found this nasty bit in circuit-construction-kit-dc-main.ts and circuit-construction-kit-dc-vitural-lab-main.ts:

```
CCKCConstants.CAROUSEL_SCALE = CCKCConstants.DC_CAROUSEL_SCALE;
```

Reaching into (what is expected to be) a constants file and changing a value? Please tell me that this is a temporary hack.

**Comment by samreid** [comment]
@matthew-blackman and I finished this, nice work!  Closing.
