### ISSUE TITLE
@ts-expect-error in circuit-construction-kit-dc-main.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-common#909]
This line in circuit-construction-kit-dc-main.ts:

```typescript
if ( !window.circuitConstructionKitTestSuite ) {
```

... was causing CT errors and blocking other devs, so I added a `@ts-expect-error` to unblock.

The TS error was:
> TS2339: Property 'circuitConstructionKitTestSuite' does not exist on type 'Window & typeof globalThis'

Oddly, the same line was not a problem in the other CCK main.ts files.

**Comment by pixelzoom** [comment]
A couple other things:

* Setting a global on `window` is a code smell.  PhET agree to namespace globals.
* There is zero documentation for `circuitConstructionKitTestSuite`, which made fixing it more expensive.

**Comment by pixelzoom** [comment]
The other 2 mains are JavaScript files.  And in those files, WebStorm flags window.circuitConstructionKitTestSuite as “Unresolved variable circuitConstructionKitTestSuite”.  So I'm guessing your best options for resolving this in TypeScript is:

```diff
- // @ts-expect-error
- if ( !window.circuitConstructionKitTestSuite ) {
+ type WindowKey = keyof typeof window;
+ if ( !window[ 'circuitConstructionKitTestSuite' as WindowKey ] ) {
```

**Comment by samreid** [comment]
Fixed, closing.
