### ISSUE TITLE
Consider making non-ohmic bulbs opt-out instead of opt-in

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#910]
In https://github.com/phetsims/circuit-construction-kit-common/issues/903#issuecomment-1341738002 @arouinfar said:

> I think we could instead consider making non-ohmic bulbs opt-out instead of opt-in. It would involve: 
 * Removing "Add Real Bulbs" checkbox from the Advanced AccordionBox.  
 * Replacing `addRealBulbs` query parameter with something like `hideRealBulbs`.
 * Using `hideRealBulbs` should completely remove the icon from the carousel, not just make it grayscale. (Is this doable @samreid @matthew-blackman?)
> 
> This is a bigger decision and should involve the larger design team.

I replied:

> Should this be discussed in a separate issue? It's unclear whether this recommendation was due to the grayed out real bulb in the toolbox or for other reasons. I wanted to clarify that those are independent, as shown in the commit.

**Comment by samreid** [comment]
Before considering making it "opt out", let's consider just leaving the "Real Bulbs" always on (with no query parameters or preferences or advanced settings to remove it).  They are lower in the toolbox and harder to discover. If students discover that they behave differently or mysteriously, I think that's OK.  They are clearly differentiated from the non-ohmic bulbs. If a client or teacher really needs to get rid of "Real Bulbs", that's what PhET-iO is for.

**Comment by arouinfar** [comment]
@samreid thanks for opening this up. I definitely went off on a tangent in #903, but your removal of the grayed-out non-Ohmic bulb icon in https://github.com/phetsims/circuit-construction-kit-common/issues/903#issuecomment-1342071633 is adequate for the current release. 

I don't think this is the time to make changes to the non-Ohmic bulb behavior. As far as I know, we haven't received any user feedback about the UX of the non-Ohmic bulbs, and teachers are generally happy that real bulbs now exist. I'm going to close this as not planned. If we decide to revisit the non-Ohmic bulb flow, we can look back at this issue for alternative ideas.
