### ISSUE TITLE
Replace usages of merge with optionize / combineOptions

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#914]
This is in line with the overall TS sim patterns

**Comment by matthew-blackman** [comment]
@samreid I replaced all instances of merge with the appropriate counterpart and ended up finding some rogue options that were not being used anywhere else. I flagged them both with TODOs if you can take a look @samreid

**Comment by samreid** [comment]
Thanks, the changes look good and I removed the stale options.  I also converted an occurrence of `_.merge`. Closing.
