### ISSUE TITLE
Create CODAP screen for experimenting with features

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#916]
A new screen would give a modular place to explore new features while ensuring that all code patterns are consistent with the common sim structure.

**Comment by samreid** [comment]
Today @arouinfar and @matthew-blackman and I discussed that this should extend LabScreen.  That will help with overall maintainability. Would be good to do today, or at least before RCs are made.

**Comment by matthew-blackman** [comment]
@samreid I removed the duplicate code in CodapScreenView by extending LabScreenView, and did the same with the model for good measure. If all looks good, this issue can be closed.

**Comment by matthew-blackman** [comment]
Note: You will need to add the 'codap' query parameter to see the Codap Screen.

**Comment by samreid** [comment]
Looks good, thanks! Closing.
