### ISSUE TITLE
Review the studio tree

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#917]
We would like to take a close look at the studio tree to make sure it is well-designed.

**Comment by samreid** [comment]
Some notes about trouble in the studio tree in https://github.com/phetsims/circuit-construction-kit-common/issues/858#issuecomment-1371735015, regarding the voltmeter/ammeter panel.

**Comment by samreid** [comment]
For my reference, notes are being taken in:

<details>

https://docs.google.com/document/d/1z8ECC0PIi7gGQ8WRpp3mFwzX9SrXH48EOJW3gSYii90/edit

</details>

**Comment by samreid** [comment]
Are all reported issues tracked elsewhere?  Can this issue be closed?

**Comment by arouinfar** [comment]
Yes, let's close.

**Comment by matthew-blackman** [comment]
fuseRepairButton visibleProperty should not be readonly

**Comment by matthew-blackman** [comment]
@arouinfar FuseRepairButton ready for your review, please confirm and then close if it looks good.

**Comment by arouinfar** [comment]
@matthew-blackman it's a bit more complicated than we thought, so I opened up #956.
