### ISSUE TITLE
14 TODOs in the code

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#919]
This seems a good opportunity to work on the 14 TODOs in the code.  Perhaps avoid the "black box study" ones?

**Comment by zepumph** [comment]
There are 6 TODOs in the cck a11y view. That is a generated file, and so those TODOs are copied out of the source in chipper along with the rest of the contents. They are definitely not blocking CCK and I do not think they are a priority at this time. Please let me know if ignoring them doesn't seem reasonable to you all.

**Comment by samreid** [comment]
All TODOs addressed, or marked as specific to AC or black-box-study. Thanks to @jbphet @matthew-blackman and @jonathanolson and @arouinfar.  Closing.
