### ISSUE TITLE
Where should the "Edit Circuit Component" panel appear?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#92]
It is not shown at all in the design doc.  In black box, it is centered at the bottom of the screen:

![image](https://cloud.githubusercontent.com/assets/679486/15128984/26ee1036-15fc-11e6-900a-4bb18b4ffbf3.png)

We need to know where this will appear in all 3 screens of "Basics".

**Comment by arouinfar** [comment]
@samreid let's leave the edit component panel centered at the bottom of the screen. Screen 3 will be the only screen with editable components, and it will be very similar to the Explore screen of Black Box.

**Comment by samreid** [comment]
We decided to leave the edit component at the bottom of the screen, and it is already there.  Closing.
