### ISSUE TITLE
Dynamic layout does not reflow correctly when isEditableProperty is toggled for placed circuit elements

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#926]
Panel doesn’t re-center in the play area if toggled while the panel is visible.

Test case 1: Create a resistor, set isEditableProperty to false, click on the resistor, while edit panel visible set isEditableProperty to true

Test case 2: Create a resistor, click on resistor, set isEditableProperty to false

Found while working on https://github.com/phetsims/circuit-construction-kit-common/issues/917

**Comment by samreid** [comment]
@matthew-blackman will take a screenshot and add label: help-wanted

**Comment by matthew-blackman** [comment]
Test case 1: Create a resistor, set isEditableProperty to false, click on the resistor, while edit panel visible set isEditableProperty to true

Before: 
<img width="1164" alt="Screen Shot 2023-01-19 at 2 57 53 PM" src="https://user-images.githubusercontent.com/108756567/213546888-1d642f54-4aa9-4fb1-9616-36454bdcbab1.png">

After:
<img width="1164" alt="Screen Shot 2023-01-19 at 2 58 13 PM" src="https://user-images.githubusercontent.com/108756567/213546908-ac06e1bc-2822-489a-879b-3894a28a9eec.png">

**Comment by matthew-blackman** [comment]
Test case 2: Create a resistor, click on resistor, set isEditableProperty to false

Before:
<img width="1164" alt="Screen Shot 2023-01-19 at 2 59 06 PM" src="https://user-images.githubusercontent.com/108756567/213547088-d7f9311e-a081-46ff-a3ab-090ba551f637.png">

After:
<img width="1164" alt="Screen Shot 2023-01-19 at 2 59 19 PM" src="https://user-images.githubusercontent.com/108756567/213547115-46ead39c-07e6-4f3f-9e30-f8b66aeb2440.png">

**Comment by jbphet** [comment]
I added a `link` that updates the position of the `CircuitElementEditContainerNode` using the pre-existing `updatePosition` method, and it seems to work well for keeping the edit box centered.  I regression tested this by opening and closing the edit box for a number of different components, and changed their edit-ability in studio.

Assigning to @samreid and @matthew-blackman so that one of them can review.

**Comment by samreid** [comment]
I tested many different circuit element edit panels, and they all centered properly.  Good fix @jbphet, thanks!
