### ISSUE TITLE
Padding around buttons in CircuitElementContainer are not symmetrical or uniform across different buttons

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#927]
Padding around the panel looks off in general.
Padding off (by different amounts) when contents reduced to single item

<img width="160" alt="Screen Shot 2023-01-13 at 1 49 37 PM" src="https://user-images.githubusercontent.com/108756567/212396448-6083a911-399e-4437-922e-87d69b1d7486.png">

Found while working on https://github.com/phetsims/circuit-construction-kit-common/issues/917

**Comment by AgustinVallejo** [comment]
Will take a look!

**Comment by samreid** [comment]
For some reason, nested HBox instances gave incorrect bounds for those buttons.  So I switched to Node with `excludeInvisibleChildrenFromBounds` and it works very nicely.  @matthew-blackman can you please review and test?

**Comment by matthew-blackman** [comment]
After addressing this, the fuseButton is giving similar sizing issues when it is the only element in the editContainerNode. We will fix this issue for the fuse button by replacing its parent HBox with a Node according to @samreid comment from above:

> For some reason, nested HBox instances gave incorrect bounds for those buttons. So I switched to Node with `excludeInvisibleChildrenFromBounds` and it works very nicely. @matthew-blackman can you please review and test?

We will also discuss with @marlitas and @jonathanolson and make sure that this fix is sufficient.

<img width="115" alt="Screen Shot 2023-02-06 at 1 00 42 PM" src="https://user-images.githubusercontent.com/108756567/217049705-0963ca21-e3e3-41d0-a341-8e9b8b41df64.png">

**Comment by matthew-blackman** [comment]
This issue appears to be fixed by [this commit](https://github.com/phetsims/circuit-construction-kit-common/commit/0f7e071a8b036a6378b58cfc3389b55b70715dc8) from https://github.com/phetsims/circuit-construction-kit-common/issues/956

@samreid and I have tested this by setting all combinations of components in the EditContainerNode to be visible/invisible. All looks good, closing this issue.
