### ISSUE TITLE
sourceResistanceProperty & wireResistivityProperty instrumented range should match slider ranges

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#928]
Including these properties on the Intro screen adds flexibility, but the range is off. Source resistance range is +/- infinity, can we make it 0.0001-10,000? This matches the maximum of the high-R resistor, so the model should be able to handle this. Wire resistivity: range should match slider range

https://github.com/phetsims/circuit-construction-kit-common/issues/917

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
