### ISSUE TITLE
Rename switch `closedProperty` to `isClosedProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#930]
Related to #917 

Switches have a boolean `closedProperty` that indicates whether the switch is open (false) or closed (true). We use "is" as a prefix for such properties elsewhere in the sim, e.g. `isDisposableProperty`. For consistency, we should do the same here.

@samreid can you please rename this Property to `isClosedProperty`?

**Comment by samreid** [comment]
@liammulh and I addressed this in the commit, closing.
