### ISSUE TITLE
Uninstrument switch `isEditableProperty` 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#931]
Related to #917 

Most circuit components are adjustable in some way (e.g. resistance, voltage, current rating). 
![image](https://user-images.githubusercontent.com/8419308/213034711-30202859-f8f8-4a67-ad2f-0b8f94fac199.png)

To prevent users from editing a circuit component, clients can set `isEditableProperty` to `false`, which would hide the slider in the screenshot above.

Switches do not have a tunable Property (like resistance) so `isEditableProperty` doesn't actually do anything. Can we get rid of it @samreid?

**Comment by samreid** [comment]
We would probably add a ternary operator where `isEditableProperty` is instrumented--to use `Tandem.OPT_OUT` for Switch circuit elements.

**Comment by matthew-blackman** [comment]
@samreid ready for review

**Comment by samreid** [comment]
Excellent, nice work @matthew-blackman.  Closing.
