### ISSUE TITLE
`draggingProbesWithBodyProperty` should be read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#932]
Related to #917 

When removing a tool from the toolbox, `draggingProbesWithBodyProperty` is true and its body and probe(s) move together as a unit. Once in the play area, the tool's body and probe(s) move independently and `draggingProbesWithBodyProperty` is false. If you try to set `draggingProbesWithBodyProperty` back to true and then move the tool, its probe(s) will snap back to the default position. 

The model should be in control of `draggingProbesWithBodyProperty`. There isn't any need for clients to be in control of it, so let's make it `phetioReadOnly: true`.

**Comment by samreid** [comment]
@liammulh and I reviewed this issue and wanted to double check: could we just uninstrument `draggingProbesWithBodyProperty` altogether?  We cannot see how phet-io clients would use it, it seems like an implementation detail that could be eliminated.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
Uninstrumenting sounds reasonable to me @samreid @liammulh. I also can't think of a reason why clients should care about `draggingProbesWithBodyProperty`.

**Comment by samreid** [comment]
Uninstrumented, closing.
