### ISSUE TITLE
Uninstrument `seriesAmmeterNodeIcon`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#933]
Related to #917 

The `seriesAmmeterNodeIcon` contains elements related to the appearance of the series ammeter icon in the toolbox. 
![image](https://user-images.githubusercontent.com/8419308/213036878-09c5b587-92c0-41ea-a8ab-1ec1b4403425.png)

This is an unnecessary feature, so let's uninstrument it @samreid.

**Comment by samreid** [comment]
@liammulh and I fixed it in the commits, and regenerated the API files.  Closing.
