### ISSUE TITLE
Voltmeter/Ammeter connections should be instrumented as axon Properties

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#934]
This will allow clients to check how users are making measurements in the circuits.  @arouinfar and I saw that VoltageConnection is being calculated in Circuit.ts.  We could convert those to axon Properties.  Not sure how it is done for Ammeters.  We will also need this when we get to AC, for the charts.

**Comment by arouinfar** [comment]
Related to #917

**Comment by samreid** [comment]
I instrumented the VoltageConnection for the Voltmeter.  It looks like this at the moment:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/679486/216799096-7d108906-00b7-4225-8ed1-ee3e2d88c4f7.png">

**Comment by samreid** [comment]
I made a similar implementation for the Ammeter:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/679486/216799380-947059a7-d0b7-4486-85ff-0975ed2b3744.png">

@arouinfar and @matthew-blackman can you please test and review?  Perhaps a better name for `ammeter.associatedCircuitElement`?

**Comment by samreid** [comment]
Code review from @matthew-blackman would also be good.  AmmeterConnection type is kind of awkward but I wasn't sure how to simplify.

**Comment by arouinfar** [comment]
@samreid these new circuit properties seem nice, but they're a bit quirky. The voltmeter's `*ConnectionProperty` appears to only report vertices and doesn't handle wires that well. Suppose the wire is bounded by vertex 1 (left) and vertex 2 (right). The value of the `*ConnectionProperty` will read vertex 1 for any value to the left of the probe in this picture:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/8419308/216888841-790f1bb7-16d0-4095-a970-5a799c8e721f.png">

Even though the probe appears to be inside the bounds of vertex 2, the value here is still vertex 1. (Probably because the true center point of the probe is outside of vertex 2's bounds.)

On the flip side, the ammeter's `associatedCircuitElementProperty` doesn't recognize vertices, only the elements themselves. 

I don't think this feature is essential to the initial release, and the current behavior is good enough. Though we should make sure `blackConnectionProperty` and `redConnectionProperty` have appropriate documentation.

**Comment by samreid** [comment]
> @samreid these new circuit properties seem nice, but they're a bit quirky. 

I agree completely. These newly instrumented Properties merely expose implementation details used by the simulation for the simulation logic.

> Suppose the wire is bounded by vertex 1 (left) and vertex 2 (right). The value of the *ConnectionProperty will read vertex 1 for any value to the left of the probe in this picture:

Yes, the implementation in the sim is to arbitrarily choose a reference vertex (not necessarily the closest one) and the delta of the resistance up to that point (like a potentiometer). It seems this behavior has been working well in the sim and would be somewhat risky to change this (but we can investigate if desired).

> On the flip side, the ammeter's associatedCircuitElementProperty doesn't recognize vertices, only the elements themselves.

For the circuit computation, we measure currents that flow through circuit elements. It does not make sense to compute the current flowing through a vertex (it should always sum to 0).  So I believe Ammeters just search for circuit elements and ignore vertices.

After discussion, should we move any remaining behavior change requests to a new issue, and close this one?

**Comment by matthew-blackman** [comment]
@samreid and I will schedule a synchronous review to discuss the changes before closing.

**Comment by matthew-blackman** [comment]
```diff
Subject: [PATCH] -
---
Index: js/model/VoltageConnection.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/VoltageConnection.ts b/js/model/VoltageConnection.ts
--- a/js/model/VoltageConnection.ts	(revision 7db38dd42640ba5fac71bc3e280f369dcb097288)
+++ b/js/model/VoltageConnection.ts	(date 1675806200897)
@@ -11,14 +11,15 @@
 import ReferenceIO from '../../../tandem/js/types/ReferenceIO.js';
 import circuitConstructionKitCommon from '../circuitConstructionKitCommon.js';
 import Vertex from './Vertex.js';
+import CircuitElement from './CircuitElement.js';
 
 const VertexReferenceIO = ReferenceIO( Vertex.VertexIO );
 export default class VoltageConnection {
-  public readonly vertex: Vertex;
+  public readonly measuredElement: Vertex | CircuitElement;
   public readonly voltage: number;
 
-  public constructor( vertex: Vertex, voltage: number = vertex.voltageProperty.value ) {
-    this.vertex = vertex;
+  public constructor( measuredElement: Vertex | CircuitElement, voltage: number ) {
+    this.measuredElement = measuredElement;
     this.voltage = voltage;
   }
 
```

**Comment by samreid** [comment]
I implemented so that VoltageConnection indicates a circuit element or vertex.  Would be good to code review and test in the sim.  I saw special handling for Switch, Capacitor and Wire and "metallic" household objects, so those require specific testing.

**Comment by samreid** [comment]
We reviewed this today and agreed the PhET-iO state looks good as `connection`.  @arouinfar will test a bit more.
