### ISSUE TITLE
Control panels do not horizontally align correctly when sensor tool icons removed from sensor toolbox

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#940]
When the voltmeter or ammeter icons are removed from the sensor toolbox via studio, the control panels do not align correctly. See screenshot below:

<img width="264" alt="Screen Shot 2023-01-23 at 9 22 55 AM" src="https://user-images.githubusercontent.com/108756567/214064105-6084029a-696a-4d2f-956a-175b0058c525.png">

Investigating with the scenery inspector, it looks like the 'advanced' options panel is aligning left within a layout component that is larger than the panel itself. See screenshot below:

<img width="1186" alt="Screen Shot 2023-01-23 at 9 25 24 AM" src="https://user-images.githubusercontent.com/108756567/214064409-610c087c-b6d1-43a9-9a60-fb7cff267b2c.png">

**Comment by AgustinVallejo** [comment]
Will look into!

**Comment by matthew-blackman** [comment]
@AgustinVallejo @samreid and I made some progress on this. We found that if titleAlignX is set to 'center' in AdvancedAccordionBox, the panel alignment works but the title text is no longer center aligned. This is not an ideal fix but it is getting us closer to the issue.

Additionally, I found that there is an issue with the panel group width if the titleText string is long. See below:

<img width="894" alt="Screen Shot 2023-01-25 at 1 18 33 PM" src="https://user-images.githubusercontent.com/108756567/214648860-c62bc3da-812d-4174-987c-fff64878c83a.png">

**Comment by jonathanolson** [comment]
This looks like something I could help with, might be related to the layout engine?

**Comment by jonathanolson** [comment]
Should be fixed with the above commits. It seems like code was added that changed the collapsedBox's bounds AFTER we used those bounds for the workaroundBox.

I also patched a case where the rectBounds of the workaroundBox would not have been getting properly updated.

**Comment by samreid** [comment]
Excellent, thanks @jonathanolson!

**Comment by matthew-blackman** [comment]
Things are looking great @jonathanolson thanks for looking into this!

One remaining issue is the width of the advanced accordion box when the title text is long. This is likely a CCK issue that I can look into. See below:

<img width="298" alt="Screen Shot 2023-01-26 at 10 32 14 AM" src="https://user-images.githubusercontent.com/108756567/214877776-3fb654ac-0d7b-41a9-899a-1d3f7bdba3bc.png">

**Comment by samreid** [comment]
Perhaps try to find a way to reduce the maxWidth of that accordion box title/label?

**Comment by marlitas** [comment]
https://github.com/phetsims/sun/issues/803 may be related to this issue.

**Comment by samreid** [comment]
I believe the best long-term solution for this issue may involve a resizable accordion box, as described in https://github.com/phetsims/sun/issues/803.  For this release, it seems a very minor aesthetic issue in a corner case, and perhaps we should consider that, like related issue https://github.com/phetsims/circuit-construction-kit-common/issues/939#issuecomment-1416672382, this should not be a necessary feature for publishing this release.

@arouinfar OK to remove this issue from the milestone?

**Comment by arouinfar** [comment]
> it seems a very minor aesthetic issue in a corner case

I agree. The behavior has improved since originally reported, and the remaining issue really seems more like an edge case tom.

> OK to remove this issue from the milestone?

Yes, untagging it now.

**Comment by samreid** [comment]
In today's meeting, @arouinfar @matthew-blackman and I agreed that this issue can be closed, because it is a minor cosmetic issue for this sim, and cannot be implemented until the accordion box is resizable in https://github.com/phetsims/sun/issues/803.  We suspect another sim will bump the priority of that issue, then we can re-evaluate in other sims as necessary.
