### ISSUE TITLE
Cut button position in the PhET-iO tree should be consistent with other global-use buttons

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#941]
Found during tree review - https://github.com/phetsims/circuit-construction-kit-common/issues/917

The 'cut button' at view.circuitLayerNode.cutButton is at the same level of the tree as the circuit elements, but it is not a circuit element. @arouinfar @samreid  and I agree that we should move it up to the top-level view so it is a sibling of the ResetAllButton & zoom buttons.

Additionally for clarity, we agree to rename cutButton to vertexCutButton so that its role is more clearly conveyed.

**Comment by samreid** [comment]
Looks great, nice work.  Can you please add a code comment on https://github.com/phetsims/circuit-construction-kit-common/commit/e0eb9b03a6128f268838bbfe6e774aa151b3036b since it is out of the ordinary to use an alternate parent tandem?  After that, the issue can be closed.
