### ISSUE TITLE
circuitElementNode.visibleProperty and vertexNode.visible properties should be uninstrumented

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#943]
Discussed in tree review - https://github.com/phetsims/circuit-construction-kit-common/issues/917

@arouinfar @samreid and I agree that circuitElementNode should not have visibleProperty instrumented, as it can lead to problematic states like the following:

<img width="420" alt="Screen Shot 2023-01-24 at 8 30 26 AM" src="https://user-images.githubusercontent.com/108756567/214307577-b8b5bbc4-f7c4-47fb-b8f5-a1ea52a883f3.png">

**Comment by samreid** [comment]
Great work, thanks.  Closing.
