### ISSUE TITLE
When currentTypeRadioButtonGroup is hidden, the panel should get shorter

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#945]
Found in discussing tree - https://github.com/phetsims/circuit-construction-kit-common/issues/917

When view.displayOptionsPanel.currentTypeRadioButtonGroup.visibleProperty is false, the control options panel should reflow and get shorter.

Parent issue - https://github.com/phetsims/phet-io/issues/1757

**Comment by samreid** [comment]
This works very well and the code change is great, closing.
