### ISSUE TITLE
viewRadioButtonGroup icons visibleProperties should be uninstrumented

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#946]
Found in tree review - https://github.com/phetsims/circuit-construction-kit-common/issues/917

@arouinfar @samreid and I agreed that it doesn't make sense to instrument the visibleProperties of the 'lifelike' and 'schematic' radio buttons, since their role is unclear if only one is showing.

We also discussed the possibility of opening a general sun issue for RectangularRadioButtons. After talking to @zepumph we agreed that this is a good option and we will discuss further.

**Comment by matthew-blackman** [comment]
@samreid @arouinfar should we also uninstrument the individual radio button enabledProperties?

**Comment by samreid** [comment]
I did that in a sun issue, labeled for review.  Matching labels on this issue for tracking.

**Comment by samreid** [comment]
I reverted the sun issue based on further discussion.  This issue seems at a stable place.  We are leaving out the visibleProperty for the lifelike/schematic radio buttons because it would be very odd to have a sole battery button below the carousel.
