### ISSUE TITLE
view.zoomButtonGroup individual button properties are overinstrumented

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#947]
Found during tree review discussion - https://github.com/phetsims/circuit-construction-kit-common/issues/917

@arouinfar @samreid  and I agree that view.zoomButtonGroup visibleProperties should be uninstrumented, and individual button enabledProperty is derived and should be read-only. Setting only one of the zoom buttons to be invisible could cause the user to get "stuck" at a zoom level, and the zoom button group already has internal logic to deal with enabled state.

**Comment by samreid** [comment]
This workaround seems reasonable for now.  And I wrote in a note in https://github.com/phetsims/scenery-phet/issues/796 requesting attention after this is addressed in common code.  I do not feel the common code change is a blocking publication issue, so I think this issue can be closed. Anyone feel free to disagree and/or reopen.
