### ISSUE TITLE
advancedAccordionBox - sourceResistanceControl and wireRestivityControl title labels

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#948]
Found in tree review - https://github.com/phetsims/circuit-construction-kit-common/issues/917

@arouinfar @samreid and I agreed that the advancedAccordionBox slider controls do not need to have their slider visibleProperties independently instrumented, as the text should always share the same visible state as its associated slider.

Additionally, advancedAccordionBox sourceResistanceControl and wireResistivityControl should have titleText instrumented.

**Comment by samreid** [comment]
I reviewed the code and tested studio.  Everything seems good.  I observed that instrumenting `circuitConstructionKitDc.labScreen.view.advancedAccordionBox.sourceResistanceControl.maxLabelText.titleText` doesn't really do anything.  It is not customizable like "tiny".  So perhaps I'll try to uninstrument that.

**Comment by samreid** [comment]
On the contrary! There are some strings that need to use PatternStringProperty so their components can be discovered.  And we need to eliminate an extraneous layer of 'titleNode` in the tree.

**Comment by samreid** [comment]
Fixed in the commits.  Some "extreme" tandems sneaked into the api changes.  @matthew-blackman can you please review? If it seems pretty safe, feel free to close.  Also feel free to check the tree changes with @arouinfar as needed.
