### ISSUE TITLE
advancedAccordionBox dynamic layout leaving too much space when sliders hidden

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#949]
advancedAccordionBox has too much padding between titleText and addRealBulbs checkbox if both sourceResistanceControl and wireResistivityControl are hidden. See below:

<img width="242" alt="Screen Shot 2023-01-25 at 8 31 06 AM" src="https://user-images.githubusercontent.com/108756567/214576224-4267952d-d31c-47fc-bded-663e67b7f59f.png">

**Comment by AgustinVallejo** [comment]
Will take a look!

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo the updated padding looks great!
<img width="170" alt="image" src="https://user-images.githubusercontent.com/8419308/214656650-d0198209-ccc7-4464-9aef-4c3780eb7f7e.png">

I notice that "Advanced" is now centered in the AccordionBox. Is that an unintended consequence of https://github.com/phetsims/circuit-construction-kit-common/commit/f7440cea8bc14ddb53672f05ecfdfe62e2a48535 or did I just stumble across in-progress changes related to another issue, such as #940?

**Comment by matthew-blackman** [comment]
@arouinfar @AgustinVallejo the centering of the title is a result of #940. If the vertical padding looks good then this issue can be closed and we can continue there.
