### ISSUE TITLE
What should the conventional current look like?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#95]
In #91 @arouinfar said:

I think a more important question would be to ask what the conventional current looks like. This hasn't been discussed at all beyond deciding that the conventional current should somehow be displayed. (I believe this was a pretty frequent teacher request.)

I can think of a few ways we could show the conventional current
- An arrow showing the direction of the conventional current
- Positive charges flowing out from the positive terminal of the battery to the negative terminal of the battery.

If we use an arrow to represent the conventional current, it could be simultaneously shown with the electron flow. If we use the latter representation, the conventional current and show electrons would need to be mutually exclusive options (radio buttons).

**Comment by samreid** [comment]
If we show the conventional current as moving spheres, we may wish to show a "-" sign on the electrons, to distinguish them.

**Comment by arouinfar** [comment]
> If we show the conventional current as moving spheres, we may wish to show a "-" sign on the electrons, to distinguish them.

Excellent point, @samreid. I agree we'd need to show +/- signs on the spheres to distinguish them, which seems like an added complication for the moving spheres view.

**Comment by samreid** [comment]
In the design doc, @arouinfar said she would create a mock-up for the conventional current.

**Comment by samreid** [comment]
From yesterday's meeting: 

Checkbox with nested radio options (Show current, electrons default)

Instead of an electron, we could show an small red arrow pointing in the direction of the conventional current. These arrows would be animated around the circuit.

Red arrows would be a similar size to the electrons.

Checkbox with nested radio options
Show Current
Electrons
Conventional

Show Current on, Electrons selected by default.

On all screens.

**Comment by arouinfar** [comment]
Thanks @samreid!

Here's a screenshot of what the panel would look like with the default options on.
![image](https://cloud.githubusercontent.com/assets/8419308/23560321/3c9244c6-fff7-11e6-96b6-b1dd969dca68.png)

**Comment by arouinfar** [comment]
@samreid you mentioned that the conventional current is something that you could try out programmatically. Would it be useful to you if I mocked something up first?

**Comment by samreid** [comment]
I'm going to try using our ArrowNode and see how it looks.

**Comment by samreid** [comment]
It's embarrassing, but here's the 1st draft with defaults for everything:

![image](https://cloud.githubusercontent.com/assets/679486/23561509/c99dae10-fffb-11e6-9476-77db211cdc3d.png)

I'll start on the 2nd draft.

**Comment by samreid** [comment]
Should "values" be available in all screens?

**Comment by samreid** [comment]
Whew, 2nd draft is somewhat better:

![image](https://cloud.githubusercontent.com/assets/679486/23561948/b15ba0e4-fffd-11e6-9174-08202f3eccf6.png)

**Comment by samreid** [comment]
@arouinfar do you want icons in the "electrons" vs "conventional" radio buttons?

**Comment by arouinfar** [comment]
@samreid the 2nd draft looks great! I was also wondering if we should add icons to the radio options. Perhaps a small electron and red arrow next to their respective option?

**Comment by samreid** [comment]
On the right hand side, so they don't interfere with the radio button circles?  How to deal with alignment for different languages?  Or should we switch from aqua to the rectangular radio buttons (like we often use for scene selection)?

**Comment by arouinfar** [comment]
@samreid I was proposing icons to the right of the radio button + label, as we typically do. We don't support layout changes for i18n, but even in RTL locales the sequence of radio button - string - icon seems to work.  I'm hesitant to use iconic radio buttons nested under a check box. We also have iconic radio buttons for the real vs. Schematic view of circuit components. 

![screenshot_20170303-110203](https://cloud.githubusercontent.com/assets/8419308/23562739/06e116e0-0001-11e7-907d-ccb87afbaabe.png)

**Comment by arouinfar** [comment]
@samreid I mocked up two versions of the Show Current radio buttons.  The iconic scene-selection style still feels a little strange to me nested under the checkbox, but it does have some advantages: fewer strings & better layout for i18n, shorter panel, avoids labelling current "electrons". What do you think @samreid? 

![image](https://cloud.githubusercontent.com/assets/8419308/23568547/2c87b77a-0018-11e7-9166-9aafd08a3294.png)     ![image](https://cloud.githubusercontent.com/assets/8419308/23568552/328a3224-0018-11e7-9105-79c5e6cbaac0.png)

> Should "values" be available in all screens?

Missed the questions earlier... yes, I think we'll want Values on all three screens.

**Comment by samreid** [comment]
There may be an advantage in using the word "conventional" and "electrons", if they are part of the important vocabulary surrounding the sim.

**Comment by samreid** [comment]
One other thought (not sure if it is a good idea or not):
What about using scene selection style radio buttons with text inside the button and vertically stacked.  This gets rid of the aqua radio buttons (which looks kind of like an electron/icon) and still includes the text and accommodates i18n.  If you think it is worth discussing, can you create a mock-up of it?

**Comment by samreid** [comment]
It seems we will need to hide the arrows when the circuit is not connected.

**Comment by samreid** [comment]
Do you want to gray out the radio buttons when the checkbox is deselected?  On the upside, it would cue that the checkbox controls the radio buttons.  On the downside, it would prevent the user from turning off the display, then changing display types, then turning the display back on (may be useful if the teacher is asking a predictive question).

**Comment by samreid** [comment]
@arouinfar and @ariel-phet here's a rough draft that shows conventional current (when current is non-zero):
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.6/circuit-construction-kit-dc_en.html?screens=1

Let me know if you have any recommendations.

**Comment by arouinfar** [comment]
@samreid I think the conventional current is a great first pass! However, the arrows feel a bit more crowded than the electrons (though I imagine this is probably an illusion). I'm also wondering if there's enough contrast between the arrows and the wires.


> There may be an advantage in using the word "conventional" and "electrons", if they are part of the important vocabulary surrounding the sim.

I think we're concerned that we may get some pushback from teachers if we refer to the current as "electrons". I'll show the latest dev to Mike and get some feedback from him. I also spoke with @kathy-phet a bit about this, and I think she'd prefer to keep the words. I'm leaning towards this option:
![image](https://cloud.githubusercontent.com/assets/8419308/23574128/97120b20-0038-11e7-8803-3960a34c1331.png)


> What about using scene selection style radio buttons with text inside the button and vertically stacked

Here's a mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/23574030/b363cc60-0037-11e7-9a3b-f9269cb62649.png)

Frankly, it feels a bit heavy to me, and I think that i18n would more challenging with this approach.

> It seems we will need to hide the arrows when the circuit is not connected.

Agreed @samreid. This would be a critical difference between the two representations of current. This seems to be working correctly in dev.6.

> Do you want to gray out the radio buttons when the checkbox is deselected? 

Yes, that's generally what we've done with nested options (e.g. Hooke's Law or Charges & Fields). I think that keeping the radio options active while their parent checkbox is off feels buggy. 
![image](https://cloud.githubusercontent.com/assets/8419308/23571047/5233e2da-0024-11e7-9a4b-8f46343f07d5.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/23571067/64ad12ec-0024-11e7-8443-42533ec01113.png)

**Comment by samreid** [comment]
In the above commit, the radio button become enabled/disabled when the checkbox is checked/unchecked.  This issue is mainly complete, I'll create a side issue to determine whether the arrows or arrow density should be changed.
