### ISSUE TITLE
If seriesAmmeterToolNode is alone in the toolbox, the top padding is too small

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#950]
Hiding the voltmeter and non-contact ammeters in the Lab screen causes the series ammeter icon to appear too close to the top of the panel.

<img width="364" alt="Screen Shot 2023-01-25 at 8 35 36 AM" src="https://user-images.githubusercontent.com/108756567/214577285-67810a26-e16e-4e2d-ae50-e3a907d92a01.png">

**Comment by AgustinVallejo** [comment]
Will take a look!

**Comment by matthew-blackman** [comment]
I added a topMargin of 10 above the series ammeter icon, which only becomes visible when all other meter icons are hidden. Let me know how this looks @arouinfar and we can adjust the margin.

<img width="242" alt="Screen Shot 2023-01-30 at 11 59 10 AM" src="https://user-images.githubusercontent.com/108756567/215543538-f79a64c8-9c96-4857-9c10-9ba66d56d5f6.png">

**Comment by matthew-blackman** [comment]
@samreid adding you to assignees for checking if adding the additional HBox with topMargin is an acceptable solution

**Comment by arouinfar** [comment]
The updated padding looks good to me @matthew-blackman, thanks!

**Comment by samreid** [comment]
I reviewed the code changes and everything seems great.  Thanks for documenting it.  Closing.
