### ISSUE TITLE
viewRadioButtonGroup should reflow to top left corner if circuitElementToolbox carousel is hidden

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#952]
circuitElementToolbox (carousel) should be in a VBox with viewRadioButtonGroup for dynamic layout purposes. Lifelike/schematic buttons should float to the top left of the window if the carousel is hidden.

<img width="1029" alt="Screen Shot 2023-01-25 at 8 48 17 AM" src="https://user-images.githubusercontent.com/108756567/214580235-e2c5cd21-ed2a-4e13-922c-f4215ac51542.png">

**Comment by AgustinVallejo** [comment]
We accidentally fixed this one as well when working on https://github.com/phetsims/circuit-construction-kit-common/issues/952

**Comment by samreid** [comment]
Fixed an additional problem in downstream code, all else seems good.  Closing.
