### ISSUE TITLE
Setting pageControl.visibleProperty to false causes circuitElementToolbox to lose alignment with left UI

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#953]
Dynamic layout issue when hiding the dots. The carousel shifts to the left and loses its alignment with the buttons below. 

<img width="303" alt="Screen Shot 2023-01-25 at 8 57 59 AM" src="https://user-images.githubusercontent.com/108756567/214582686-5eb55dd0-39d8-4025-86f8-8017804e2e34.png">

**Comment by AgustinVallejo** [comment]
Will take a look!

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo!

Looks like the solution was to add slightly more left padding to the sim and then shift everything to the left when the pageControl dots were hidden. I like it!

Not sure if your commits need to be reviewed or not, so back to @matthew-blackman @samreid.

**Comment by samreid** [comment]
Now that we fixed the layout of the PageControls to respect the horizontal margin, the horizontal margin of 17 (which used to be for the carousel) is very far. There is a lot of trapped space to the left of the toolbox:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/679486/216211071-017607e8-9edd-4a15-bdb3-4d5bfc5a57b3.png">

Let's reduce that somewhat.

**Comment by samreid** [comment]
I reduced it and it seems much better with and without the page controls:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/679486/216211341-c9345a66-5aa6-4604-bf32-03753750e37c.png">

Closing.
