### ISSUE TITLE
Meter node titleText is pointing to probeText

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#954]
While working on the featured overrides, @arouinfar and I noticed that the meterNodes all have a probeText and a titleText. The titleText string looks like it's pointing to the same dependency as the probeText, so we are unsure if both of these are needed.

**Comment by matthew-blackman** [comment]
@arouinfar ready for you to take a look in studio. All three types of meters are now using the same tandem names for title text and readout text.

**Comment by arouinfar** [comment]
Looks great, thanks @matthew-blackman!
