### ISSUE TITLE
DisplayOptionsPanel.displayOptionsRadioButtonGroup should have a featured enabledProperty

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#955]
While working on the featured overrides, @arouinfar and I noticed that the current type radio button groups in the display options panel do not have an enabledProperty. This should be added in and also featured.

**Comment by matthew-blackman** [comment]
@arouinfar radio button groups all have a featured enabledProperty now. Ready for you to review.

**Comment by arouinfar** [comment]
The Current Type radio buttons look good, but I think you missed the lifelike/schematic group. My understanding is that today's decision applied to both Rectangular and Aqua radio buttons.

**Comment by arouinfar** [comment]
Scratch that, actually. I see no reason for the lifelike/schematic buttons to have `enabledProperty` or `visibleProperty`. Today's decision was about what we are doing at the sun level. Let's leave things alone in CCK, closing.
