### ISSUE TITLE
Visibility of fuseRepairButton and batteryReverseButton gets overridden

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#956]
In https://github.com/phetsims/circuit-construction-kit-common/issues/917#issuecomment-1419514579 we discovered that the `fuseRepairButton.visibleProperty` was read-only and we wanted to make it writable. @matthew-blackman made the change, but it revealed the reason why it was probably read-only in the first place.

The model sets `fuseRepairButton.visibleProperty` every time a fuse is selected/deselected. Setting the `visibleProperty` to false will only hide button until the next time a fuse is selected (assuming `isRepairableProperty: true`). 

The same is also true of `batteryReverseButton.visibleProperty`. Each time a battery with `isReversibleProperty: true` is selected, the model will set `visibleProperty: true`. 

Interestingly, `trashButton.visibleProperty` does not exhibit this same behavior. If a client hides the trash button, it stays hidden. For consistency and convenience, it would be nice if we could do the same with `fuseRepairButton.visibleProperty` and `batteryReverseButton.visibleProperty`. 

Clients could technically use `isRepairableProperty` and `isReversibleProperty` to hide these buttons, but doing it for every single fuse and battery that students create is a real drag. It would be simpler to have global control over the button's visibility.

**Comment by samreid** [comment]
We added a 2nd gate for the fuse, still need to do the batteries.

**Comment by samreid** [comment]
@matthew-blackman and I addressed both cases, thanks for discovering this.  Ready for review, and please close if all is well.

**Comment by arouinfar** [comment]
Thanks, looks good!
