### ISSUE TITLE
Uninstrument `isEditableProperty` for Real Bulbs

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#957]
In https://github.com/phetsims/circuit-construction-kit-common/issues/937, we uninstrumented `isColorCodeVisibleProperty` and `isEditableProperty` for irrelevant resistor types. We should do the same for `isEditableProperty` for Real Bulbs. The property doesn't do anything because Real Bulbs do not have a tunable resistance, so let's uninstrument it.

**Comment by matthew-blackman** [comment]
Working on this!

**Comment by samreid** [comment]
@matthew-blackman pushed a fix that we collaborated on.  @arouinfar can you please review and close if all is well?

**Comment by arouinfar** [comment]
Looks good, thanks!
