### ISSUE TITLE
Units not being translated in sensor display and EditContainerNode number displays

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#961]
@samreid and I found this issue while investigating locale switching. It looks like the units of the sensor measurements and the number display of the EditContainerNode are not translating when the locale is changed.

<img width="1658" alt="Screen Shot 2023-02-13 at 3 59 11 PM" src="https://user-images.githubusercontent.com/108756567/218573213-fe65b7e4-f5b6-42f2-b367-825db4a4e9a0.png">

**Comment by samreid** [comment]
@matthew-blackman and I discovered that the value is correct if you use `?locale=iw` for example. But it doesn't dynamically recompute when locale is changed at runtime.  We are fixing it now....

**Comment by samreid** [comment]
@matthew-blackman and I addressed all cases we discovered.  SeriesAmmeter, Ammeter, Voltmeter and CircuitElementNumberControl units all update correctly under dynamic locale change.
