### ISSUE TITLE
Short circuit animation speed message showing inaccurate percentage value

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#964]
@samreid and I found that the 'Animation speed limit reached!' message has a bug in the 'speed reduced to X% normal' portion. When the current is in the tens of thousands, the animation speed is being reduced correctly but the message is still reading as 'reduced to 100% normal'. See image below:

![Screen Shot 2023-02-14 at 2 49 04 PM](https://user-images.githubusercontent.com/108756567/218844646-583aaa32-bc6d-4f75-a811-d99eb2ec53dd.png)

**Comment by samreid** [comment]
I'll take a look.

**Comment by samreid** [comment]
Fixed, closing.
