### ISSUE TITLE
Meters in Sensor Toolbox are misaligned when Labels is unchecked

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#966]
**Test device**
Dell 

**Operating System**
Win10

**Browser**
FF/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/900, the meters are misaligned when labels are hidden. 

**Steps to reproduce**
1. On either screen, uncheck the Labels checkbox.

**Visuals**
<img width="240" alt="Screenshot 2023-02-15 at 6 23 54 PM" src="https://user-images.githubusercontent.com/87318828/219216343-d1f4b196-737a-42bf-a03b-41c2b86d7898.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.20/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.3.0-dev.20 2023-02-15 16:13:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language: en-US
Window: 1374x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Thanks, I moved it to circuit-construction-kit-common and added it to the milestone.

**Comment by Nancy-Salpepi** [comment]
This looks good in master.

**Comment by samreid** [comment]
Thanks, it seems this issue has been fixed and verified.  Closing.
