### ISSUE TITLE
Launched sim fails to load when voltmeter is used in Studio

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#968]
**Test device**
MacBook Air

**Operating System**
13.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/900, in Studio, when a voltmeter is hooked up to a circuit, the standard PhET-iO wrapper doesn't load. 

**Steps to reproduce**
1. Create a simple circuit in studio on either screen
2. Attach the voltmeter
3. Launch the standard PhET-iO wrapper

**Visual
<img width="751" alt="Screenshot 2023-02-16 at 7 56 24 PM" src="https://user-images.githubusercontent.com/87318828/219523275-4d679dd9-0718-456b-b073-9cde16b0bbf9.png">

<img width="699" alt="Screenshot 2023-02-16 at 7 52 58 PM" src="https://user-images.githubusercontent.com/87318828/219523293-d9610787-d215-4f17-a360-e7aae97f81c1.png">

<img width="699" alt="Screenshot 2023-02-16 at 7 42 34 PM" src="https://user-images.githubusercontent.com/87318828/219523317-8d11a066-ee86-4677-9f36-23a1eb2ed5be.png">

**Comment by samreid** [comment]
Fixed, and ready for testing in master.  Please be aware of related issue https://github.com/phetsims/circuit-construction-kit-common/issues/972

**Comment by Nancy-Salpepi** [comment]
This looks fixed in master.

**Comment by matthew-blackman** [comment]
This issue has been reviewed and tested. Closing.
