### ISSUE TITLE
Dragged Voltmeter resets draggingProbesWithBodyProperty in launched standard wrapper

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#972]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/968 and https://github.com/phetsims/qa/issues/900. Dragged Voltmeter resets draggingProbesWithBodyProperty in launched standard wrapper. The effect is that the probes jump to the sides of the voltmeter body on drag even if they were attached to a circuit.

**Comment by samreid** [comment]
Before starting, I noticed there are many changes to the PhET-iO API files.  I'll update those first.

**Comment by samreid** [comment]
Fixed. @arouinfar and @matthew-blackman is the name `draggingProbesWithBodyProperty` ok?  Please close if acceptable.

**Comment by matthew-blackman** [comment]
Since `draggingProbesWithBodyProperty` is a boolean, @zepumph suggested to add the 'is' prefix to the class attribute as well as the PhET-iO ID.

**Comment by matthew-blackman** [comment]
All variables and PhET-iO ids are now appropriately named. Closing.
