### ISSUE TITLE
'Tap circuit element to edit' is initially missing in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#973]
**Test device**
MacBook Air M1 chip and iPad

**Operating System**
13.1 and iOS 16.3

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/900, in Studio, if I add objects to the play area and then launch the sim, the 'Tap circuit element to edit' message isn't there. It appears after selecting an object or adding another object to the play area. 

**Steps to reproduce**
1. In Studio, add object to play area --Tap message is on the bottom of the screen
2. Press Test button --Tap message isn't there

**Visuals**

https://user-images.githubusercontent.com/87318828/220194037-a9cff05c-fb14-4d6b-ac10-c26070d7bca3.mp4

**Comment by Nancy-Salpepi** [comment]
I am also seeing odd things in the State Wrapper with this. For example:
1. Set State Rate = 0
2. Add a couple of elements to the upstream sim and press Set State Now--the 'Tap circuit' message doesn't appear in the downstream sim
3. Hit Set State Now again --the message appears in the downstream sim
4. Press Reset All in the upstream sim and then press Set State Now -- the elements disappear in the downstream sim, but the the 'Tap circuit' message is still there. 



https://user-images.githubusercontent.com/87318828/220203295-15c45987-425e-480b-875c-42a577545786.mp4

**Comment by matthew-blackman** [comment]
@arouinfar agrees that this is important to fix for the PhET-iO release milestone. @samreid @zepumph and I will work on this.

**Comment by samreid** [comment]
Fixed, @Nancy-Salpepi can you please verify?

**Comment by samreid** [comment]
Thanks, closing.
