### ISSUE TITLE
Highlight behavior is different than in published

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#975]
**Test device**
MacBook Air M1 chip

**Operating System**
13.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/900, in the published versions on CCK, as soon as I grab an item out of the carousel or a meter, the highlight around an object in the play area disappears. In 1.3.0-dev.20, the highlight goes away when I let go of the item I grabbed out of the carousel and the highlight doesn't disappear at all when I add a meter to the play area. 

**Steps to reproduce**
1. Add an element to the play area and click on it
2. Grab another element from the carousel --highlight remains until you let go of that object
3. Click on an object in the play area
4. Add a meter to the play area --highlight remains

**Visuals**

https://user-images.githubusercontent.com/87318828/220205014-a6159fe4-d011-47e6-b24b-4efa0c39b338.mp4

**Comment by matthew-blackman** [comment]
@arouinfar mentioned that this is worth some further investigation. She mentioned that this issue is not itself very serious, but may be a byproduct of a deeper issue and warrants looking into.

**Comment by samreid** [comment]
I'll investigate

**Comment by samreid** [comment]
In the commit, I clear the highlighted selection when the user drags out a circuit element or sensor.  @Nancy-Salpepi can you please review?

**Comment by Nancy-Salpepi** [comment]
The highlighted selection is now cleared when an element or sensor is dragged out. 

In published the highlight is also cleared when:
- I grab another element in the play area that isn't part of the circuit
- when I grab the end of a wire and extend it or grab any vertex and move it around

**Comment by samreid** [comment]
We reviewed the behavior with @arouinfar.  We would like to make it so that dragging a selected CircuitElement | Vertex keeps it selected.  Otherwise, it should deselect on mousedown/touchdown.

We also saw that the production version isn't behaving nicely because dragging a selected circuit element then releasing it deselects it.

@arouinfar also commented this is not essential if it is too complex. (we could just deselect everything when anything moves).

**Comment by matthew-blackman** [comment]
The latest commit appears to give all desired behaviors discussed in the comment above. I have done about 20 minutes of testing across various combinations of selected/deselected objects and wires and found no issues. @arouinfar this is ready for your review.

**Comment by arouinfar** [comment]
Thanks @samreid @matthew-blackman! The highlighting behavior feels nice in master. @samreid are we good to close?

**Comment by samreid** [comment]
Yes, thanks, closing.
