### ISSUE TITLE
Values units for existing elements don't change when locale is switched

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#982]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Chrome/Safari

**Problem description**
For https://github.com/phetsims/qa/issues/908, when I switch locales, the units of existing circuit elements don't change. New Circuit elements added to the play area will display the units for the new locale. 

**Steps to reproduce**
1. On either screen, check Values Checkbox
2. Change locale to 
                     <img width="113" alt="Screenshot 2023-03-02 at 10 03 11 AM" src="https://user-images.githubusercontent.com/87318828/222466315-6054187c-af18-4bec-89c0-d98400e15c20.png">
3. Add elements to the play area
4. Change locale to English and add more elements to the play area

**Visuals**
<img width="533" alt="Screenshot 2023-03-02 at 9 49 23 AM" src="https://user-images.githubusercontent.com/87318828/222466714-9c676491-a6a6-43fe-b74e-cdda096a8101.png">

**Comment by stemilymill** [comment]
This also applies to language direction rtl/ltr. Elements added with any ltr language will keep units to the right of numbers when locale is changed to any rtl and vice versa.

![rtl ltr dynamic locale unit location not change](https://user-images.githubusercontent.com/85511101/222647698-a873e8c0-19dd-405a-af69-661f90fd6ce6.jpg)

**Comment by samreid** [comment]
Code review seems OK. But @arouinfar could you please test readouts for each circuit element type, and switch locales (or use stringTest=dynamic)?

**Comment by arouinfar** [comment]
Tested with `stringTest=dynamic` and with the steps originally reported, and everything looks good!

**Comment by samreid** [comment]
For QA, please show the readout for several different circuit element types, and check if it updates when the locale is changed via the preferences dialog.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3. Closing!!

<img width="680" alt="Screenshot 2023-03-08 at 6 02 02 PM" src="https://user-images.githubusercontent.com/87318828/223872232-9db4056b-27db-4bdb-be5b-1a84ad66f380.png">


<img width="680" alt="Screenshot 2023-03-08 at 6 05 44 PM" src="https://user-images.githubusercontent.com/87318828/223872616-e49d06b5-1597-4111-aaae-c771d7288b98.png">
