### ISSUE TITLE
Update description of `probeConnectionProperty` in examples.md

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#984]
For https://github.com/phetsims/qa/issues/908

In examples.md we state:

> Non-contact ammeters have the following property:
>
>* `probeConnectionProperty` - the `phetioID` of the circuit element in contact with the non-contact ammeter's measurement probe, as well as the value of the current at this location

However, @Nancy-Salpepi and @stemilymill noticed that this property only provides the `phetioID` in Studio, not the current. We inspected the data stream, and it provides the exact same data that is visible in Studio. 

Looks like this was a mistake in the documentation, so I'll fix it.

**Comment by arouinfar** [comment]
Fixed in the above commit. Since the issue relates to the non-contact ammeter, no changes are necessary for the virtual lab flavor.

@matthew-blackman can you review? If all looks good, we can mark this as `ready-to-cherry-pick`.

**Comment by samreid** [comment]
For QA, please check that text like `probeConnectionProperty - the phetioID of the circuit element in contact with the non-contact ammeter's measurement probe` appears in the examples document.

**Comment by Nancy-Salpepi** [comment]
This has been updated in rc.3.
Closing.
