### ISSUE TITLE
Update language in examples.md to refer to 'Get Command'

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#986]
In https://github.com/phetsims/studio/issues/298 we updated the get/set interface in Studio. The examples doc references the "Copy Set Value Code" button which no longer exists, so we should update it.

**Comment by arouinfar** [comment]
Updated in the above commits. The changes happened in the same paragraph as the additions made in #971. However, I made sure not to change any of the text that was added in #971.

**Comment by arouinfar** [comment]
@samreid @matthew-blackman please review, if all looks good, this is ready for cherry-picking.

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/qa/issues/908 in case we use that as the list to cherry-pick.

**Comment by samreid** [comment]
The updates look reasonable to me, thanks!

**Comment by matthew-blackman** [comment]
Looks great @arouinfar

**Comment by samreid** [comment]
For QA, please check that examples.md has text like "The Get Command button will populate the text box ".  One platform only.

**Comment by Nancy-Salpepi** [comment]
I'm confused about this one @samreid . In rc.3 the button in Studio still says 'Copy Set Value Code.'

<img width="680" alt="Screenshot 2023-03-08 at 7 47 16 PM" src="https://user-images.githubusercontent.com/87318828/223886515-84fabd7f-d323-4f6b-ad4a-ef06975561ee.png">

**Comment by Nancy-Salpepi** [comment]
The Examples doc has been updated with 'Get Command.'

**Comment by Nancy-Salpepi** [comment]
In rc.4 the Examples doc has been updated with 'Get Command' and I think the directions are clear on to how to use this button.
Closing.
