### ISSUE TITLE
Virtual Lab: Hiding ammeter icon in toolbox should also hide the 'Ammeter' label

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#987]
Discovered in https://github.com/phetsims/circuit-construction-kit-dc-virtual-lab/issues/20

In cck-dc, the 'Ammeters' label disappears when BOTH types of ammeter icons have been hidden. In cck-dc-virtual-lab, there is only one kind of ammeter icon: `view.sensorToolbox.seriesAmmeterToolNode`. When its `visibleProperty` is false, the 'Ammeter' label in the toolbox should automatically hide. Instead, it looks like this:

![image](https://user-images.githubusercontent.com/8419308/224188230-113ad7af-a208-48bf-a8ff-0b01d545c421.png)

**Comment by samreid** [comment]
I added a fix that addresses the visibility for the ammeter. It seems to work well in DC-VL and DC.  I noticed the voltmeter doesn't center when the ammeters disappear, but that seems also present in DC so is presumably not in scope for this publication.  @arouinfar can you please test in master?

NOTE: If this solution is OK, then after creating SHAs as described in https://github.com/phetsims/circuit-construction-kit-dc-virtual-lab/issues/20 we would probably cherry-pick this into those branches.

**Comment by matthew-blackman** [comment]
This looks like a resurgence of https://github.com/phetsims/circuit-construction-kit-common/issues/925

@arouinfar would like your input as to whether this warrants 30-60 mins of work and a maintenance release on CCK-DC.

**Comment by zepumph** [comment]
We were able to reproduce this in the published CCK DC studio by hiding `circuitConstructionKitDc.introScreen.view.sensorToolbox.noncontactAmmeterToolNode.visibleProperty`.

Let's do a quick MR for this!

**Comment by KatieWoe** [comment]
Looks mostly good. I did notice that, when the ammeter is removed the voltmeter shifts but doesn't center. However, when the voltmeter is removed the ammeter does center. Is this acceptable?
![vgone](https://user-images.githubusercontent.com/41024075/224433307-62bda259-d780-45fd-8962-1db88d7513ac.png)
![gone](https://user-images.githubusercontent.com/41024075/224433308-a481e0ed-ce20-4352-84e8-1d09ab44c7e6.png)
![notgone](https://user-images.githubusercontent.com/41024075/224433309-8e7ca0a9-af1d-433d-8aac-ca20e56f8cd9.png)

**Comment by samreid** [comment]
We observed the same problem in https://github.com/phetsims/circuit-construction-kit-dc-virtual-lab/issues/20#issuecomment-1464200104 and concluded that it was not important enough to delay publication.

**Comment by KatieWoe** [comment]
In that case this is probably done

**Comment by arouinfar** [comment]
Let's continue the discussion of the layout issue in https://github.com/phetsims/circuit-construction-kit-common/issues/925

@KatieWoe confirmed the bug reported here has been addressed, closing.

**Comment by zepumph** [comment]
MR for CCK DC 1.3 has been completed.
