### ISSUE TITLE
The dog was removed?

### ISSUE THREAD

**Issue by PhetHubDogEnjoyer** [phetsims/circuit-construction-kit-common#991]
Why did you remove the dog. "Oh my students are shocking it and its hurting it" It not a real dog. You are teaching children no shocker they are going to play around with the dog as an option.

#Bringbackthedog

**Comment by samreid** [comment]
Removed based on discussion in https://github.com/phetsims/circuit-construction-kit-common/issues/882, thanks for your feedback!  Closing.
