### ISSUE TITLE
PhET-iO Instrumentation for Circuit Construction Kit: AC

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#995]
This week @brent-phet asked me to estimate the effort involved in bringing Circuit Construction Kit: AC to production for PhET-iO. 

The good:
* CCK AC shares a lot of code with DC, which is already production instrumented
* Studio is running and appears to be working correctly
* The state wrapper is mostly working

Known issues or remaining work
* The temporal probe locations are not working correctly in the state. Would probably need to be instrumented. Would also need to use the same way the voltmeter probes know if they are in contact with a conductor.
* Thorough review by designer
* Thorough testing by QA
* There are 45 open issues other than this one. More than likely we will want to address many of them to make sure the simulation is in good shape for production.  Many of those model-related issues such as the ones related to the inductors, capacitors or model are non-trivial and would either need to be punted, get something working like #228 or a huge and unknown development effort to rewrite the model to support those cases.
* As we work on CCK AC, we will undoubtedly want to make improvements for DC. That will require migration rules and could lead to a period where there is an inconsistency in their APIs. Ultimately we would probably republish DC at the same time.

If we want to quickly publish an "ok" version of what's already there without adding new functionality or changing the model, I would recommend a subteam of 1 designer + 3 developers for one iteration.  If we decide to tackle more and more complexity, then it will take longer.  In either case, I feel the next point for this issue is a check-in with the designer to briefly test studio and think about what features are in AC that are not in DC that would need effort for PhET-iO.

**Comment by brent-phet** [comment]
Adding @arouinfar to get design-related overview impacting the total lift.

**Comment by arouinfar** [comment]
> If we want to quickly publish an "ok" version of what's already there without adding new functionality or changing the model, I would recommend a subteam of 1 designer + 3 developers for one iteration. 

I generally agree with @samreid's assessment of the remaining work, and I think one iteration is sufficient to get an "okay" version into QA. However, a full QA cycle (dev, rc, spot check) will take a minimum of one additional iteration. Best case scenario, I think we're looking at 2 iterations, but I can see that slipping into a 3rd.

I would estimate the design lift of CCK: AC to be maybe half of CCK: DC, but still larger than recent PhET-iO retrofits like Acid-Base Solutions and Beer's Law Lab. I would need to allocate ~70% effort into CCK: AC to have the design complete in one iteration. This means I will need to scale back contributions to other simulations. I typically support ~5 sims during any given iteration.

**Comment by brent-phet** [comment]
P.S. - An additional consideration would be the additional lift to publish CCK:AC Virtual Lab simultaneously.

**Comment by brent-phet** [comment]
This information and a link to this issue has been transferred to the request in Monday.com to be considered in scheduling. Closing.
