### ISSUE TITLE
Make it impossible to drop circuit elements into an invisible toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#999]
@kathy-phet said:

> If you HIDE the tool panel from view, but DO NOT make your elements "is disposable false", you can still trash them by dragging them over the now invisible toolbox. If the toolbox is invisible, I think it should NOT be able to trash the elements via that mechanism.

**Comment by samreid** [comment]
I was able to reproduce the problem, and I observed it is also problematic for sensors (voltmeters, etc). I committed a fix that  corrects the problem. There was also related unused code that I removed in the commit, since it was confusing. @kathy-phet how would you like to proceed? Some options:

1. Leave this fix in main for the next release. In that case we could close the issue.
2. Publish maintenance releases for the affected simulations. This could take 1-2 hours and would involve steps like:
  a. Determine the affected simulations (I believe it is just DC and DC-virtual lab, is that correct?)
  b. See if the unused/confusing code is used in the release branches
  c. Request QA test the fix on main
  d. Run the maintenance process on 2 (or more?) release branches to create release candidates
  e. Request QA spot checking for the release candidates
  f. Run the maintenance process to create the production versions
  g. Spot check the production deploys.

**Comment by samreid** [comment]
The affected versions are:

https://phet-io.colorado.edu/sims/circuit-construction-kit-dc-virtual-lab/1.3/
https://phet-io.colorado.edu/sims/circuit-construction-kit-dc/1.3/

AC has not yet been published for PhET-iO. The 1.2 versions and earlier were not published for PhET-iO.

I notified slack dev-public:

> Probably working on maintenance branches today for https://github.com/phetsims/circuit-construction-kit-common/issues/999

**Comment by samreid** [comment]
Out for testing in DC. If this passes QA testing, we can production deploy it and do the same process for DC Virtual Lab.

**Comment by KatieWoe** [comment]
This looks ok to me in the rc.

**Comment by samreid** [comment]
I wrote on slack dev-public:

> I’d like to run a production deploy for this maintenance: https://github.com/phetsims/circuit-construction-kit-common/issues/999. Anything in progress that I need to be aware of?

**Comment by samreid** [comment]
https://phet-io.colorado.edu/sims/circuit-construction-kit-dc/1.3.15/ was published. I'll notify @JacquiHayes and @kathy-phet on slack, then start working on dc-virtual-lab.

**Comment by samreid** [comment]
Deployed: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.13-rc.1/phet/circuit-construction-kit-dc-virtual-lab_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.13-rc.1/phet-io/

**Comment by samreid** [comment]
I opened https://github.com/phetsims/qa/issues/1132 for testing and will notify QA on slack.

**Comment by KatieWoe** [comment]
Looks fixed in cck dc vl rc.

**Comment by samreid** [comment]
Thanks, should I wait for https://github.com/phetsims/qa/issues/1132 to be called before publishing?

**Comment by KatieWoe** [comment]
Yeah. It'll be done today.

**Comment by Nancy-Salpepi** [comment]
looks fixed with mac + safari in CCK DC Virtual Lab 1.3.13-rc.2.

**Comment by samreid** [comment]
Published and confirmed fixed in the published version. However, there is some problem and confusion noted in https://github.com/phetsims/phet-io-wrappers/issues/645.  The fix is in 1.3.13 and I can see it is fixed, but the wrong client sim version is reported. Anyways, let's close this and continue in https://github.com/phetsims/phet-io-wrappers/issues/645
